### ISSUE TITLE
Figure out how to support tenants for accounts

### ISSUE THREAD

**Issue by drmaas** [spinnaker/spinnaker#1028]
Someone here asked how we are going to manage tenants and brought up that we might want to separate tenants from accounts.

[9:52]  
I don’t know what that would look like, and it definitely isn’t going to be mvp, I just wanted to throw it out there

[9:52]  
Tenants apparently are the only way to add quotas and having to redeploy to add tenants may be frustrating for some

Should we tie 1 tenant/account?

**Comment by pravka** [comment]
IMO it should be 1:1 tenant/account (similar to the way you would configure multiple namespaces in the k8s driver). If the need is there to add multiple tenants, they should each be declared in a separate array, i.e.:

```
openstack:
  enabled: ${OS_ENABLED:false}
  accounts:
    - name: openstack-tenant1
      environment: test
      accountType: main
      master: test
      username: ${OS_USERNAME:'username'}
      password: ${OS_PASSWORD:'password'}
      tenantName: tenant1
      domainName: Default
      endpoint: ${OS_AUTH_URL:''}
      regions: ${OS_REGIONS:''}
      insecure: ${OS_INSECURE:false}
    - name: openstack-tenant2
      environment: test
      accountType: main
      master: test
      username: ${OS_USERNAME:'username'}
      password: ${OS_PASSWORD:'password'}
      tenantName: tenant2
      domainName: Default
      endpoint: ${OS_AUTH_URL:''}
      regions: ${OS_REGIONS:''}
      insecure: ${OS_INSECURE:false}
```
