### ISSUE TITLE
/gate redirected to wrong /gate/login URL

### ISSUE THREAD

**Issue by linusgg** [spinnaker/spinnaker#1112]
***Issue Type***

Bug

***Cloud Provider***

AWS

***Environment***

I am running Spinnaker using the Spinnaker Amazon AMI to deploy into AWS.

***Feature Area***

Gate login URL when enabled OAuth

***Description***

I terminate SSL using Apache reverse proxy so port 9000 is only opened locally. 
When I access `https://spinnaker.mydomain.com/gate`, it redirected me to `http://spinnaker.mydomain.com:9000/gate/login` (note it is http and port number 9000 is added) which is really weired. I had to manually ajust the URL to `https://spinnaker.mydomain.com/gate/login` in the browser address bar to be able to see the Google authentication page and login. I wonder how is the URL is generated.

*Steps to Reproduce*
**This is my spinnaker.conf for apache.** 
```
<VirtualHost 127.0.0.1:9000>
  DocumentRoot /opt/deck/html
  ProxyPass "/gate" "http://localhost:8084" retry=0
  ProxyPassReverse "/gate" "http://localhost:8084"
  ProxyPass "/rosco" "http://localhost:8087" retry=0
  ProxyPassReverse "/rosco" "http://localhost:8087"
  <Directory "/opt/deck/html/">
    Require all granted
  </Directory>
</VirtualHost>

<VirtualHost *:443>
  <Proxy *>
    Order deny,allow
    Allow from all
  </Proxy>
  SSLEngine on
  SSLCertificateFile    "/opt/spinnaker/config/ssl/server.crt"
  SSLCertificateKeyFile "/opt/spinnaker/config/ssl/server.key"
  ProxyPass "/" "http://localhost:9000/" retry=0
  ProxyPassReverse "/" "http://localhost:9000/"
  ProxyPreserveHost on
  RequestHeader set X-Forwarded-Proto "https" early
</VirtualHost>
```
**Part of my deck configuration from spinnaker-local.yml is**
```
deck:
      baseUrl: https://spinnaker.mydomain.com
      gateUrl: ${services.deck.baseUrl}/gate
      bakeryUrl: ${services.deck.baseUrl}/rosco
      auth:
        enabled: true
```
**My gate-googleOAuth.yml:**

```
spring:
  oauth2:
    client:
      preEstablishedRedirectUri: https://spinnaker.mydomain.com/gate/login
      useCurrentUri: false
      clientId: 
      clientSecret: 
    userInfoRequirements:
      hd: mydomain.com
```
