### ISSUE TITLE
Provide option to give server group instances floating ip addresses

### ISSUE THREAD

**Issue by drmaas** [spinnaker/spinnaker#1180]
Something like this in heat template for each server resource:

```
  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: {get_attr: [server1, addresses,  { get_param: public_net_id }, 0, port]}
```
