### ISSUE TITLE
Deploy on Kubernetes is not working

### ISSUE THREAD

**Issue by ianrossi** [spinnaker/spinnaker#1358]
I'm not sure if the README here (https://github.com/spinnaker/spinnaker/tree/master/experimental/kubernetes/simple) is up to date, but I can not get it to work on Kubernetes using S3 bucket persistence.

Spinnaker does not create the bucket for you, as the docs say. But I manually created the bucket and the folder within, and Front 50 throws this in the log:
```
2017-01-05 05:34:09.373  INFO 1 --- [0.0-8080-exec-1] com.amazonaws.latency                    : ServiceName=[Amazon S3], AWSErrorCode=[NoSuchKey], StatusCode=[404], ServiceEndpoint=[https://cc-lab4-front50.s3.amazonaws.com], Exception=[com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 18D8793B16F426CA), S3 Extended Request ID: k6BhYZNi0egi+njOwFVX0XmSehDoIvn5Bd5d57Gmg0vFwWFDLoHHiT21XgwDsp35jMZBVysHhhA=], RequestType=[GetObjectRequest], AWSRequestID=[18D8793B16F426CA], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=2, RequestCount=1, Exception=1, HttpClientPoolLeasedCount=0, ClientExecuteTime=[11.129], HttpClientSendRequestTime=[0.138], HttpRequestTime=[10.227], RequestSigningTime=[0.135], CredentialsRequestTime=[0.001], HttpClientReceiveResponseTime=[8.59], 
```
I'm not sure what object it's looking for, whether the folder in the bucket or a file inside the folder, but the bucket and folder both exist.

Here is my spinnaker-local.yml for front50:
```
  front50:
    host: spin-front50.spinnaker
    port: 8080
    baseUrl: ${services.default.protocol}://${services.front50.host}:${services.front50.port}

    # If using storage bucket persistence (gcs or s3), specify the bucket here
    # disable cassandra and enable the storage service below.
    storage_bucket: cc-lab4-front50
    bucket_root: front50

    cassandra:
      enabled: false
    redis:
      enabled: false
    gcs:
      enabled: false # Enable me
      project: # Set me
    s3:
      enabled: true # or me
```

**Comment by ianrossi** [comment]
@lwander

**Comment by lwander** [comment]
Does the machine you are running the deploy-spinnaker-to-kubernetes scripts on have credentials in `~/.aws/credentials` that would allow you to read/write from that bucket?

**Comment by lwander** [comment]
Ok, let's try the following:

  1. Could you restart the `front50` pod, capture the first few minutes of logs, and post those into a gist?
  2. What does `kubectl describe secret aws-config --namespace spinnaker` return?

Thanks

**Comment by Shubham-Sakhuja-Bose** [comment]
Is there any way for this to work without giving spinnaker access to AWS?

**Comment by lwander** [comment]
You can use [minio](https://www.minio.io/) as a object store instead - I don't have any docs on hand about how to configure that, and it's arguably not as safe/persistent as S3 or GCS since you're in charge of managing your minio nodes.

**Comment by dforrest88** [comment]
I setup Spinnaker on Kubernetes yesterday and ran into the same issue. I had to create an s3 bucket  with the same name as what I had in my config for the front50 error to go away.

**Comment by Ian-Rossi-aimtheory** [comment]
@dforrest88 Thanks for this, when I get back around to Spinnaker, I'll give this a shot.

**Comment by lwander** [comment]
Closing since it looks like we have one or two solutions

**Comment by slashk** [comment]
I am still running into this issue.

My `experimental/kubernetes/simple/config/spinnaker-local.yml`  config looks like this ...

```yaml
  front50:
    host: spin-front50.spinnaker
    port: 8080
    baseUrl: ${services.default.protocol}://${services.front50.host}:${services.front50.port}

    # If using storage bucket persistence (gcs or s3), specify the bucket here
    # disable cassandra and enable the storage service below.
    storage_bucket: front50mtbcal # Needs to be a globally unique name. Pick something clever.
    bucket_root: front50

    cassandra:
      enabled: false
    redis:
      enabled: false
    gcs:
      enabled: false # Enable me
      project: # Set me
    s3:
      enabled: true # Or me
```

I have the S3 bucket created ...

```sh
$ aws s3 ls
2017-02-01 13:03:05 elasticbeanstalk-us-west-2-726577782246
2017-03-15 15:12:07 front50demo
2017-03-15 15:39:40 front50mtbcal
``` 

and I am getting this same `NoSuchKey` error ...

```
2017-03-15 23:17:36.925  INFO 1 --- [0.0-8080-exec-5] com.amazonaws.latency                    : ServiceName=[Amazon S3], AWSErrorCode=[NoSuchKey], StatusCode=[404], ServiceEndpoint=[https://front50mtbcal.s3-us-west-2.amazonaws.com], Exception=[com.amazonaws.services.s3.model.AmazonS3Exception: The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 29EC63896823CD95), S3 Extended Request ID: rcyenaehn4txoQd83LXpFgWILkLE2Xe0BvFFkvraQSZBJ/3x4NyjB2stS2cfUGhhOVGyal5VIk4=], RequestType=[GetObjectRequest], AWSRequestID=[29EC63896823CD95], HttpClientPoolPendingCount=0, RetryCapacityConsumed=0, HttpClientPoolAvailableCount=2, RequestCount=1, Exception=1, HttpClientPoolLeasedCount=0, ClientExecuteTime=[54.957], HttpClientSendRequestTime=[0.245], HttpRequestTime=[52.351], RequestSigningTime=[0.315], CredentialsRequestTime=[0.031, 0.006], HttpClientReceiveResponseTime=[45.794],
```

I've attached the fuller log for front50 here.

[front50.log.zip](https://github.com/spinnaker/spinnaker/files/846237/front50.log.zip)
