### ISSUE TITLE
Add node-selector support for kubernetes

### ISSUE THREAD

**Issue by dennismartensson** [spinnaker/spinnaker#1436]
*Title*

Add node-selector support for kubernetes

*Cloud Provider*

Kubernetes

*Environment*

I am running Spinnaker using the GCP.`

*Feature Area*

Pipelines

*Description*

Add node-selector support for kubernetes so we can use the [NodeSelector](https://kubernetes.io/docs/user-guide/node-selection/) to control where the pods are deployed. This can be used to put a pod in the right zone in a multi zone cluster, or to move pods to specific node pools.

*Steps to Reproduce*

Should work similar to the Pod Annotations field but it cant be in the `annotations` need to be inside `spec`as example 

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
```
