### ISSUE TITLE
how to register gate to Eureka?

### ISSUE THREAD

**Issue by a64011144** [spinnaker/spinnaker#1623]
how to register gate to Eureka?

i introduce spring-cloud-netflix's dependencies like this:
compile('org.springframework.cloud:spring-cloud-dependencies:Camden.SR6')
compile('org.springframework.cloud:spring-cloud-starter-eureka:1.2.6.RELEASE')

and @EnableEurekaClient at the gate's Main class, but there's many errors when starting gate, it maybe the dependencies conflicts because spring-cloud-netflix introduces many dependencies.

Please help me.

**Comment by cfieber** [comment]
the spring cloud dependencies are unnecessary, a eureka client is already wired up in the application (conditionally enabled)

you can enable it with:
```
eureka:
  enabled: true

netflix:
  appinfo:
    name: gate
    ... (see https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/appinfo/PropertyBasedInstanceConfigConstants.java)
  discovery:
     serviceUrl: http://my.eureka.server
    ... (see https://github.com/Netflix/eureka/blob/master/eureka-client/src/main/java/com/netflix/discovery/PropertyBasedClientConfigConstants.java)
```
