### ISSUE TITLE
[Gate]: Redirect URL after login is not correct if not terminating SSL at the server

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#1630]
*Title*

[Gate]: Redirect URL after login is not correct if not terminating SSL at the server

*Cloud Provider*

All?

*Environment*

AWS

*Feature Area*

Authentication - Google

*Description*

Related to [#390](https://github.com/spinnaker/gate/pull/390)

The above PR fixed one issue related to this, but there is one more area that is affected.

Backstory:

If terminating SSL at a Load Balancer (ELB), Gate was not sending back the correct `/login` URL. Using `preEstablishedRedirectUri` had no affect on the endpoint `/auth/redirect` would redirect to. Now that the `/login` endpoint is correct, once you've authenticated with Google, the `/auth/redirect` URL is incorrect. Refreshing the page will get you in, but the clean flow from Spinnaker -> Google -> Spinnaker is broken.

**Comment by ttomsu** [comment]
@ethanfrogers Were you able to use the tomcat properties I sent you to get this working? For the record:

```
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
```

**Comment by andrewbackes** [comment]
I was able to recreate this issue. Adding the `server.tomcat` settings you have here fixes it, but introduces a new problem. 

*New Problem:*
After the auth provider bounces you back to:
`https://<my-spinnaker-dns-name>:8084/login?code=<redacted>&state=<redacted>`
gate 302's you to:
`https://<my-spinnaker-dns-name>/auth/redirect?to=https%3A%2F%2F<my-spinnaker-dns-name>%2F%23%2Finfrastructure`
Notice there isn't a port. I tried a few different setups. Interestingly, this setup:
```
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    internalProxies: .*
```
gives a CORS error. The origin`<my-spinnaker-dns-name>` is not accepted by `<my-spinnaker-dns-name>:8084`. I tried adding `<my-spinnaker-dns-name>` to `cors.allowedOriginsPattern` but it didn't seem to have an affect.

**Comment by ttomsu** [comment]
@andrewbackes Your setup may or may not be similar to the original bug. Please contact me in the chat room and we can hash out what the issue is

**Comment by rchench** [comment]
I met the similar issue and I've tested different versions (1.6.1, 1.7.6 and 1.8.0) in both firefox and chrome, using tsl, non-tsl, NodePort and ingress. I was kinds of lost and confused within this journey. And now I concluded as it works from chrome but not firefox.

**Comment by vide** [comment]
I'm seeing a similar problem (using Spinnaker 1.8.0 deployed with Halyard), as I commented here https://github.com/spinnaker/spinnaker/issues/2414#issuecomment-402654521
Basically with _authn_ *enabled* and _authz_ *disabled* it fails the first time and then it works. If I enable authz it won't work no matter how many times you try

**Comment by jordiclariana** [comment]
Hi! I'm a colleague of @vide . We found out how to fix this. This works for us:

```
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
    httpsServerPort: X-Forwarded-Port
```

The proxy has to set `X-Forwarded-Port` header, otherwise you should hardcode the original port.

We figure this out reading Tomcat's documentation, [here](https://tomcat.apache.org/tomcat-8.5-doc/api/org/apache/catalina/valves/RemoteIpValve.html).

**Comment by vide** [comment]
Plus, for some strange reason Halyard didn't start Fiat correctly, so that's why it started to loop. With Fiat started and [this `gate-local.yml`](https://github.com/spinnaker/spinnaker/issues/1630#issuecomment-402712481) now everything works as expected

**Comment by rchench** [comment]
@vide I tried your approach, but it does not resolve my issue.
do you mean put followings into ~/.hal/default/profiles/gate-local.yml and redeploy spinnaker?
```
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
    httpsServerPort: X-Forwarded-Port
```
my case is that SSL terminates at ingress controller (traefik) and I also tried nodePort (SSL terminates at deck and gate), the URL redirect always works for chrome, but does not work for firefox.

**Comment by rchench** [comment]
I opened Firefox web developer and noticed a XML Parsing Error:
```
XML Parsing Error: no root element found
Location: https://spinnaker-sandbox-api.rnd.gic.ericsson.se/auth/user
Line Number 1, Column 1:
```
Maybe this is something related. (Firefox Quantum 61.0.1)
Tried safari and it also works as well.

**Comment by vide** [comment]
@rchench any chance you're using some firefox add-on that breaks the authentication process for you? I had problems with the multi-containers add-on for instance.

**Comment by rchench** [comment]
I don't think so, because I have tested this in several machines (Mac, Windows, Ubuntu) and some of my colleagues. All have the same issue.

**Comment by rchench** [comment]
I just installed Spinnaker 1.9.0 and found this issue is gone.
Also tried 1.8.5 and the issue is still there.

Wondering what changes have merged into 1.9.0 but I am happy to see it is gone and will migrate to 1.9.0 version.

**Comment by wjoel** [comment]
I'm seeing this with nightly releases, and using the fix in https://github.com/spinnaker/spinnaker/issues/1630#issuecomment-402712481 with `.hal/default/profiles/gate-local.yml` solved it. Thanks!

Any reason not to make that part of the default config for gate?

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by spinnakerbot** [comment]
This issue is tagged as 'to-be-closed' and hasn't been updated  in 45 days, so we are closing it. You can always reopen this issue if needed.

**Comment by ngocson2vn** [comment]
The following fix works well:
```
vim ~/.hal/default/profiles/gate-local.yml
###########################################
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
    httpsServerPort: X-Forwarded-Port
###########################################
```

**Comment by ethanfrogers** [comment]
@ttomsu thoughts on adding the above to Gate's `halconfig/gate.yml`? I think this is a common enough problem that it would be good to drop in by default.

**Comment by ttomsu** [comment]
I think that's a good idea.

**Comment by ttomsu** [comment]
@xolantumy I don't see anything that stands out specifically. The `env.API_HOST` looks odd, but I think if that were causing an issue you'd see different behavior. 

I'd try to get a HAR file of one or two of the browser redirects (with 'Preserve Log' checked!) and ping me in the chat room (since GH issues aren't a great place to debug things)

**Comment by vanditboy** [comment]
For those who uses Spinnaker deployment via helm (or directly hal) with istio gateway in version < 1.1.0 :

There is problem with `X-Forwarded-Proto` when terminating SSL on ELB: https://github.com/istio/istio/issues/7964

Workaround is bellow: 

helm value.yaml file changes (or gate-local.yml file):

```
      gate-local.yml: |-
        server:
          tomcat:
            protocolHeader: X-Forwarded-New
            remoteIpHeader: X-Forwarded-For
            internalProxies: .*
            httpsServerPort: X-Forwarded-Port
```
For the virtual file to expose gate externally - keep in mind that domains for gate and deck (dashboard) should be different: 
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: spin-gate
spec:
  hosts:
  - "spinnaker-api.domain.com"
  gateways:
  - spinnaker-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: spin-gate
        port:
          number: 8084
    appendHeaders:
        "X-Forwarded-New": "https"
```

There is an option to use istio filters to replace headers but I didn't try this out.

For istio version >= 1.1.0 there is a possibility to remove and add the headers

**Comment by inge4pres** [comment]
Hi there,

attaching to this issue as it seems related.
I was not able to configure gate/deck behind a reverse proxy and appending a custom URI; the redirection to login service happens correctly, but then the actual login POST does not include the additional URI path.

Spinnaker version: 1.16.0

Configuration bits:
* api and UI custom URL set by hal
 ```
hal config security api edit --override-base-url https://domain.com/spinnaker-api
hal config security ui edit --override-base-url https://domain.com/spinnaker
```
* gate-local.yml as per [previous comment] (https://github.com/spinnaker/spinnaker/issues/1630#issuecomment-402712481)

Logs from the httpd reverse proxy when landing on authentication page:
```
IP - - [11/Sep/2019:11:14:32 +0200] "GET /spinnaker-api/login HTTP/1.1" 200 632 "https://domain.com/spinnaker/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" 

<putting credentials in and clicking login>

IP - - [11/Sep/2019:11:14:41 +0200] "POST /login HTTP/1.1" 404 203 "https://domain/spinnaker-api/login" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
```

The problem I see is that the `POST /login` should have been `POST /spinnaker-api/login`.
Any idea where this is handled or if it configurable?
Thanks for you help

**Comment by xacaxulu** [comment]
+1

**Comment by jasonmcintosh** [comment]
@inge4pres  If I recall right, the /login path is actually hard coded for "logins" and I'm not sure there's a way currently to change it.  That means you can't have "paths" under a single LB with routing rules without some work.  I believe there were a few teams/orgs looking into adding that as an option but not sure if it ever got done.  You MIGHT be able to add an additional rule that listens for /spinnaker-api/login and does a proxy with a rewrite to strip out the /spinnaker-api path and pass that to gate.  I know I can do that with F5 hardware with an iRule :) . Not entirely sure what LB you're using (would guess ALB?) and not sure how well they support that kinda logic.

**Comment by abjrcode** [comment]
Configured the Helm chart as follows:
```yml
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: poc
  namespace: default
spec:
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: spinnaker
    version: 2.0.0-rc3
  values:
    ingress:
      enabled: true
      host: spinnaker.mydomain.io.
      annotations:
        kubernetes.io/ingress.class: "nginx"
        external-dns.alpha.kubernetes.io/hostname: spinnaker.mydomain.io.
    ingressGate:
      enabled: true
      host: spinnaker-api.mydomain.io
      annotations:
        kubernetes.io/ingress.class: "nginx"
        external-dns.alpha.kubernetes.io/hostname: spinnaker-api.mydomain.io.
    halyard:
      additionalScripts:
        create: true
        data:
          config.sh: |-
            $HAL_COMMAND config security ui edit --override-base-url "https://spinnaker.mydomain.io"
            $HAL_COMMAND config security api edit --override-base-url "https://spinnaker-api.mydomain.io"

            $HAL_COMMAND config security authn oauth2 edit \
              --provider github \
              --client-id 3fa1e85bf1431acba9d3 \
              --client-secret 35be5936ce1a20d02237cf108129a4b19dbfe17b \
              --pre-established-redirect-uri "https://spinnaker-api.mydomain.io/login"
            $HAL_COMMAND config security authn oauth2 enable
      additionalProfileConfigMaps:
        data:
          gate-local.yml: |-
            server:
              tomcat:
                protocolHeader: X-Forwarded-Proto
                remoteIpHeader: X-Forwarded-For
                internalProxies: .*
                httpsServerPort: X-Forwarded-Port
```
I have tried numerous combinations without avail. GitHub redirects back to HTTPS endpoint but somehow I end up with "http://spinnaker-api.mydomain.io" which doesn't work because I don't have SSL re-direction (I don't want it).

Also tried with version `1.23.3` of the chart and had the same issue.
