### ISSUE TITLE
Display Kubernetes Downward API resourceFields as environment variables

### ISSUE THREAD

**Issue by micahhausler** [spinnaker/spinnaker#1815]
*Title*

Display Kubernetes Downward API `resourceFieldRef` as environment variables

*Cloud Provider*

Kubernetes

*Feature Area*

Server Group/Run Job configuration

*Description*

When defining environment variables, it would be really nice to be able to expose [Kubernetes resource fields](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-container-fields-as-values-for-environment-variables) as possible environment variables. The possible values are just:

* `requests.cpu`
* `limits.cpu`
* `requests.memory`
* `limits.memory`

along with a specified container name, and divisor. ([API Docs](https://kubernetes.io/docs/resources-reference/v1.6/#resourcefieldselector-v1-core))

This is especially useful for applications that set a max memory size at runtime 
```yaml
apiVersion: extensions/v1beta
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: myapp
        command:
        - "java"
        - "-Xmx$(LIMITS_MEMORY)m"
        - "myapp"
        env:
        - name: LIMITS_MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: nginx
              resource: limits.memory
              divisor: 1Mi
```

I've already worked on Clouddriver support for this and would like to take this on.
