### ISSUE TITLE
Container configurations doesn't get copied from existing server Group while Creating new server group in pipeline

### ISSUE THREAD

**Issue by priteshmehta** [spinnaker/spinnaker#1861]
**Steps:**

*Title* Container configurations doesn't get copied from existing server Group while Creating new server group in pipeline

A descriptive title.

*Cloud Provider * :  Kubernetes 

*Environment*
Installed Spinnaker using latest version halyard (0.30.0-11) on ubuntu 14.04

Versions:
```
version: 1.1.1
timestamp: '2017-07-21 13:37:10'
hostname: null
services:
  echo:
    version: 0.4.0-135
    commit: 515436cd7f046ac8db92963e9812684b79845df8
  clouddriver:
    version: 0.5.0-135
    commit: 2855e9941a97b1c3897ee8378e001ad546d5b715
  deck:
    version: 1.3.0-135
    commit: 1e4261fe8462621e5bd5cf466445598f9b062ebb
  fiat:
    version: 0.3.0-135
    commit: e775f0d8a26b8df1cc59474180844f6115eb9e48
  front50:
    version: 0.4.2-135
    commit: adbdb555f7ad5733005b25c809fdda2d4efe9e63
  gate:
    version: 0.5.0-135
    commit: 935d23f2511f5e1b50c1a267f5a06bd65e1aba44
  igor:
    version: 0.4.0-135
    commit: de3acd99a3e675918ddd9cced629052a7bca6787
  orca:
    version: 0.5.0-135
    commit: d6f3ad00845d539c404d6a7fabcf8511fcb468e7
  rosco:
    version: 0.4.0-135
    commit: 7fe25ac87e9a63e7e5b1c462a1e03763e84a2088
  spinnaker:
    version: 0.7.0-135
    commit: e37c852a1f82c940b4e84bc7d0a701ce41a43f1b
  monitoring-third-party:
    version: 0.2.0-135
    commit: 0d72809835b3eba81343d11f3dabec4cd727c1cd
  monitoring-daemon:
    version: 0.2.0-135
    commit: 0d72809835b3eba81343d11f3dabec4cd727c1cd
dependencies:
  redis:
    version: 2:2.8.4-2
    commit: null
  consul:
    version: 0.7.5
    commit: null
  vault:
    version: 0.7.0
    commit: null
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker 
```

*Feature Area* Pipelines

*Description*
I have kubernetes (1.6) cluster running and applications are running using RC  (ReplicationController) type. When I have installed spinnaker, it was able to populate all the running application and RCs as server groups successfully.

 Then after I tried creating pipeline. While adding new server group in deployment stage, spinnaker shows that existing server group can be used as template. (as showing in screenshot1).  I have selected use as template and hoping the all the container settings (i.e. image name, env, volume mounts, commands etc..)  would get populated automatically but I doesn't. 

*Steps to Reproduce*
1. Open any existing Application showing under Applications tab
2. Click on PIPELINES tab
3. Click on +Create icon to create new pipeline and input pipeline name.
4. Click on Add stage  in order to add new stage
5. Select Type as Deploy and click on Add server group
6. Select existing server group as template so that all settings as shown in screenshot1 should get populated for new server group.

*Actual Result:*
	Spinnaker failed to populate Container configurations. Please refer highlighted area in below screenshot2

*Additional Details*

Additional information such as screenshots and exception logs.
![screenshot1](https://user-images.githubusercontent.com/20135657/28559107-b3df16aa-7147-11e7-9fce-2392f0e89ae1.png)
![screenshot2](https://user-images.githubusercontent.com/20135657/28559108-b3e6850c-7147-11e7-9dac-87fc25098173.png)
