### ISSUE TITLE
[Gate] - redirect for gate is not using its configured override 

### ISSUE THREAD

**Issue by jeffbean** [spinnaker/spinnaker#1934]
Gate redirect configuration not using override config

I am running Spinnaker using the `localdebian` install on GCP with an nginx proxy doing the SSL termination in front on the instance. 

Gate URL overrides are not being respective. This results in all the redirect Auth flows broken if you configure Gate to have a different base path as Deck.

*Steps to Reproduce*
https://www.spinnaker.io/setup/quickstart/faq/#i-want-to-expose-localdebian-spinnaker-on-a-public-ip-address-but-it-always-binds-to-locahost

*Additional Details*

My investigations led me to see that gate is using the deckBase URL and not its own configured gateBaseURL for doing redirects. 

https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/controllers/AuthController.groovy#L52

I'm not sure if this is a deliberate decision but I fixed this with a nginx rewrite in the time being. 

```
"location /auth": {
        "rewrite": "^(/auth)(.*)$ https://spinnaker.mydomain.com/gate/auth/$2 last"
} 
```

Maybe fixes: #1630 #996

**Comment by ethanfrogers** [comment]
@jeffbean just as confirmation, this is the behavior we saw as well. Worked around it with a similar rewrite.

**Comment by brantburnett** [comment]
In my case, I'm using the [NGINX Ingress Controller](https://github.com/kubernetes/ingress-nginx) on a Kubernetes cluster.  I was able to work around the bug with these Ingress definitions:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spin-ingress
  namespace: spinnaker
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: spinnaker.host.name.here
    http:
      paths:
      - path: /*
        backend:
          serviceName: spin-deck
          servicePort: 9000
      - path: /gate/*
        backend:
          serviceName: spin-gate
          servicePort: 8084
---
# Addresses issue https://github.com/spinnaker/spinnaker/issues/1934
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spin-auth-ingress
  namespace: spinnaker
  annotations:
    ingress.kubernetes.io/rewrite-target: /auth/
spec:
  rules:
  - host: spinnaker.host.name.here
    http:
      paths:
      - path: /auth/*
        backend:
          serviceName: spin-gate
          servicePort: 8084
```
