### ISSUE TITLE
Can not use feign to communicate with gate when registering gate to springcloud eureka

### ISSUE THREAD

**Issue by a64011144** [spinnaker/spinnaker#1938]
*Title*

Can not use feign to communicate with gate when registering gate to springcloud eureka

*Cloud Provider*

k8s 1.6.7

*Environment*

Use haylard to deploy spinnaker in single Ubuntu-14.04 machine.
hal version bom: 1.1.0
  gate:
    version: 0.5.0-72
    commit: 935d23f2511f5e1b50c1a267f5a06bd65e1aba44

Eureka info:
Use org.springframework.cloud:spring-cloud-starter-eureka-server:1.3.1.RELEASE to start local Eureka server.

As halyard does not provide ways to config gate's eureka configurations, so i edited gate.yml as followings:
eureka:
  enabled: true
netflix:
  appinfo:
    name: gate
    validateInstanceId: false
  discovery:
     serviceUrl: 
       defaultZone: http://localhost:8012/eureka/

*Feature Area*

Gate Eureka

*Description*

The actual problems i see are as followings:
1.when starting eureka and gate, access Eureka server: http://localhost:8012/
![image](https://user-images.githubusercontent.com/14847104/30008441-52ce2b96-9152-11e7-8a2f-e637f3a7730f.png)
As @cfieber told me in https://github.com/spinnaker/spinnaker/issues/1623 Am i doing sth wrong? Does gate not support Spring Eureka server but just Netflix Eureka server(https://github.com/Netflix/eureka/wiki/Configuring-Eureka#configuring-eureka-server)?

2.As 1st problem occured, i continue to use @FeignClient('gate') to communicate with gate in my other SpringBoot's application. As you have expected, the result is just stacktrace as followings:
![image](https://user-images.githubusercontent.com/14847104/30008622-d20afdd4-9153-11e7-8a50-b0b1b59ec465.png)

*Steps to Reproduce*

1. start all spinnaker components.
2. use spring initializer (https://start.spring.io/) to generate app, import spring-cloud-starter-eureka-server dependency, then start this Spring Eureka Server.
3. config gate.yml as followings:
eureka:
  enabled: true
netflix:
  appinfo:
    name: gate
    validateInstanceId: false
  discovery:
     serviceUrl: 
       defaultZone: http://localhost:8012/eureka/
4. restart gate and access http://localhost:8012 to see if gate registers itself successfully.
5. use any other SpringBoot's app, in its Main add @EnableFeignClients, then write any Service and add @FeignClient('gate')

*Additional Details*

None.

**Comment by a64011144** [comment]
the format is not so good... so i pasted eureka's config in gate.yml as a picture:
![image](https://user-images.githubusercontent.com/14847104/30008899-4013ed3e-9156-11e7-9bc1-a36907a417e0.png)

**Comment by cfieber** [comment]
You should be able to see the raw discovery record if you hit your eureka server `http://localhost:8012/eureka/apps` - from the looks of that error it is missing some values that the UI template is expecting

You probably need some additional info in the `netflix.appinfo` section.

Here is an example of what we use:

```
netflix:
  enabled: true
  appinfo:
    name: gate
    version: 1.0
    statusPageUrlPath: /health
    healthCheckUrlPath: /health
    vipAddress: spinnaker-api-main.netflix.net,gate-main.netflix.net
    secureVipAddress: spinnaker-api-main.netflix.net,gate-main.netflix.net
    port: 7001
    port.enabled: true
    securePort: 7103
    securePort.enabled: true
```

I don't know exactly what `@feignclient('gate')` is supplying as an annotation parameter - for the eureka use case that is (or should be) the vipAddress not the appname but I'm not exactly sure since I've never used it.
