### ISSUE TITLE
Authentication with Google Oauth stopped working at some point

### ISSUE THREAD

**Issue by ryan-mf** [spinnaker/spinnaker#2029]
*Title*

Authentication with Google Oauth stopped working at some point.

*Cloud Provider*

GCP and Kubernetes

*Environment*

Spinnaker running on a GCE instance

*Feature Area*

Authentication

*Description*

We have Gate configured to require Google Oauth in order to login to Spinnaker, and we just realized that broke at some point and we're all logged in as anonymous. It could have been a long time ago, but nobody noticed until today. We've tried re-running /opt/spinnaker/bin/reconfigure_spinnaker.sh, but that didn't help.

**Did something change in the Spinnaker code at some point that required a different configuration in Spinnaker to enable/enforce Google Oauth?**

*Steps to Reproduce*

1. Configure /opt/spinnaker/config/gate-local.yml per previous documented instructions:
```
spring:
  oauth2:
    client:
      clientId: <snip>
      clientSecret: <snip>
    userInfoRequirements:
      hd: /(domain1\.com|domain2\.com)/
```
2. Update Spinnaker with:
```
/opt/spinnaker/bin/reconfigure_spinnaker.sh
```
3. Restart Spinnaker with "restart spinnaker".
4. Observe that Google Oauth isn't requested as expected when logging into Spinnaker. Instead users are given access anonymously.
