### ISSUE TITLE
Support Taints/Tolerations in k8s

### ISSUE THREAD

**Issue by tony612** [spinnaker/spinnaker#2123]
This is a feature request.

*Cloud Provider*

Kubernetes

*Environment*

I'm running Spinnaker on AWS to deploy to k8s.

*Feature Area*

Pipeline/Deployment

*Description*

I hope [taints/tolerations](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/) can be supported in Spinnaker, which is useful for scheduling.

**Comment by lwander** [comment]
Are you more interested in tainting nodes during a pipeline, adding tolerations to pods deployed by spinnaker, or both?

**Comment by tony612** [comment]
@lwander The later. :)

**Comment by lwander** [comment]
Makes sense to me - this'll be supported out of the box by the V2 provider

**Comment by tony612** [comment]
Will toleration be support by V1 provider?

**Comment by lwander** [comment]
It definitely can be - if you (or anyone else) wants to add the feature I'll be happy to help. I personally don't have the time in the coming weeks to add it.

**Comment by ethanfrogers** [comment]
@tony612 let us know here if you start working on it. if not, i'd be happy to add it. :)

**Comment by tony612** [comment]
@ethanfrogers You can work on that first. I'm not familiar with Groovy/Java 😂

**Comment by benjaminws** [comment]
Suddenly find myself needing this.

**Comment by ethanfrogers** [comment]
i'm working on a couple of v1 provider improvements this week. i'll try to get this one done.

**Comment by chris-lee-parsable** [comment]
Where is the documentation for this? I can't find anything about it.

**Comment by mau21mau** [comment]
> this has been added and will land in 1.8!

Ok so how do we use it. I've added to the kubernetes section on the .hal/default/service-settings/gate.yml to be like this:

```
kubernetes:
  nodeSelector:
    cloud.google.com/gke-nodepool: tools-preemptive
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "sheetgo-services"
    effect: "NoSchedule"
  podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: 'true'
```

But it hasn't been added to the pod. Only the `nodeSelector` works. This is what I have describing the pod:

```
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  spin-gate-files-463744424:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  spin-gate-files-463744424
    Optional:    false
  kube-api-access-qqvv4:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              cloud.google.com/gke-nodepool=tools-preemptive
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
```

**Comment by mau21mau** [comment]
I've soved this manually by patching the deployments. First I created a patch-deployments.yaml file:

```
spec:
  template:
    spec:
      tolerations:
      - key: "role"
        operator: "Equal"
        value: "key-of-my-services"
        effect: "NoSchedule"
```

Then run a command to apply this patch to all deployments from the namespace `spinnaker`:

```
kubectl get deployments.apps -n spinnaker | awk '{print $1}' | xargs kubectl patch deployment -n spinnaker --patch-file patch-deployments.yaml
```
