### ISSUE TITLE
clouddriver/halyard - deprecated requiredGroupMembership

### ISSUE THREAD

**Issue by johnrengelman** [spinnaker/spinnaker#2195]
Clouddriver: v1.748.1
Halyard: 84bb86c2

## Problem
Set `requiredGroupPermissions` on an account using the `--required-group-membership` flag in Halyard:
```
hal config provider openstack account add test --required-group-membership auth-group
```

This configures `clouddriver.yaml` to have the `requiredGroupMembership:` block under the account:
```
openstack:
  accounts:
      - name: ost-tgt-pe-prod
         requiredGroupMembership:
         - 'auth-gropu'
         providerVersion: V1
```

This causes Clouddriver to startup with a deprecation message saying that `requiredGroupMembership` is deprecated and to use `permissions` instead.

Additionally, checking the account permissions by hitting `http://gate/auth/user`, shows all the accounts as existing in `allowedAccounts` even though the logged in user is not a member of the `auth-group` as specified in `requiredGroupMembership`.

So, even though the setting is only `deprecated`, it's appearing to not have any affect.
