### ISSUE TITLE
Kubernetes V2 relationships are sometimes singleton null lists

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2215]
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/groovy/com/netflix/spinnaker/clouddriver/kubernetes/v2/caching/agent/KubernetesCacheDataConverter.java#L236-L246

**Comment by wjoel** [comment]
This can be reproduced with the following StatefulSet:
```yaml
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: halyard-stateful
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halyard-stateful
  template:
    metadata:
      labels:
        app: halyard-stateful
    spec:
      serviceAccountName: halyard-admin
      containers:
      - name: halyard
        image: gcr.io/spinnaker-marketplace/halyard:nightly
        ports:
        - name: service
          containerPort: 8084
        - name: dashboard
          containerPort: 9000
        volumeMounts:
        - mountPath: /root
          name: halyard-stateful
  volumeClaimTemplates:
  - metadata:
      name: halyard-stateful
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 100Mi
```
