### ISSUE TITLE
Preconfigured Webhooks - Configurable Parameters

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#2224]
*Title*

Preconfigured Webhooks - Configurable Parameters

*Cloud Provider*

Any

*Environment*

N/A

*Feature Area*

Pipelines - Preconfigured Webhooks

*Description*

(I've just discovered Preconfigured Webhook stages, omg).

When setting up Preconfigured Webhook stages, it would be _super_ powerful if the admin, or person building the stage,  could expose explicit parameters that could then be utilized in the payload or elsewhere. These parameters could then be rendered in Deck, allowing users to configure them as necessary. This would be similar to how Jenkins jobs are rendered. If the job takes any parameters, they are exposed in the stage configuration.

For example, the config of a Preconfigured Webhook stage may look like this:

```
- label: Ping Bucket
   description: Ping a Requestbin Bucket
   type: requestBinPing
   enabled: true
   url: <my-request-bin-url>
   method: POST
   userDefinedParams:
      - name: MESSAGE
         type: string #default string
         defaultValue: i love tacos #default empty
   payload: |
     {
       "text": "${userDefinedParams.MESSAGE}"
      }
   waitForCompletion: false
```

When the stage `Ping Bucket` is chosen in a pipeline, the parameters are exposed to the user for configuration.

I'm totally down to do the work if this is something that others think would be useful. We already have a couple of ideas of things that we'd use it for!
