### ISSUE TITLE
Configuration for indexing kinds per namespace

### ISSUE THREAD

**Issue by danielpeach** [spinnaker/spinnaker#2283]
Ideally there would be defaults that each namespace could override.

e.g., in the following config, Spinnaker would index pods and replicaSets for `kube-system`, and
deployments, pods, and replicaSets for `spinnaker`.

```
index:
  defaultKinds:
   - pod
   - replicaSet
  namespaces:
    - name: spinnaker
      kinds:
       - deployment
       - pod
       - replicaSet
    - name: kube-system
```
