### ISSUE TITLE
Support for binding Persistent Volume and Persistent Volume Claims

### ISSUE THREAD

**Issue by imosquera** [spinnaker/spinnaker#2306]
*Title*
Support for binding Persistent Volume and Persistent Volume Claims

*Feature Area*
Kubernetes V2

*Description*
Currently there is only support for containers, configMaps and secrets.  There should be support for Persistent Volumes and Persistent Volume Claims as well

**Comment by marfenij** [comment]
@lwander sorry if this is incorrect topic, but I can't find any better 

but I can't use secrets via k8s V2 manifest 
my version `release-1.7.x-latest-unvalidated`

sample manifest:
```
apiVersion: v1
kind: Secret
metadata:
  name: db-access
  namespace: default
type: Opaque
data:
  connection: SOMEBASE64DATA==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
  labels:
    app: api
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      tier: frontend
  template:
    metadata:
      name: api
      labels:
        app: api
        tier: frontend
    spec:      
      containers:
      - name: api
        image: gcr.io/gcp-project/api
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__DbConnection
          valueFrom:
            secretKeyRef:
              name: db-access
              key: connection
```

so problem is:
spin apply version to secret name like `db-access-v000` and deploy
but do not rename reference in pod template, so it leaves unchanged and I got error, cause pod can't resolve secret by `db-access` name
