### ISSUE TITLE
Halyard: Add redis_exporter sidecar to Halyard-deployed redis

### ISSUE THREAD

**Issue by spinnaker-release** [spinnaker/spinnaker#2417]
_Migrated from https://github.com/spinnaker/halyard/issues/734_

__Opened by__: @ttomsu _(2017-10-18 18:47:16)_ https://github.com/oliver006/redis_exporter

Adding this as a sidecar to each Redis will allow Prometheus to scrape metrics for monitoring

Sample config:

```
- name: redis-exporter
        image: oliver006/redis_exporter:v0.10.7
        ports:
        - name: sidecar
          containerPort: 9121
        resources:
          limits:
            cpu: "0.1"
```
