### ISSUE TITLE
Halyard: Null pointer error when parsing kubernetes config

### ISSUE THREAD

**Issue by spinnaker-release** [spinnaker/spinnaker#2418]
_Migrated from https://github.com/spinnaker/halyard/issues/748_

__Opened by__: @rbwsam _(2017-11-07 18:28:35)_ ```
$ hal -v
0.35.0-20171002192634
```

When attempting to deploy to a Kubernetes environment I receive a null pointer exception that appears to be related to parsing my Kubernetes config file:

```
$ hal deploy apply
+ Get current deployment
  Success
- Apply deployment
  Failure
Problems in Global:
! ERROR Unexpected exception: java.lang.NullPointerException:
  Cannot get property 'user' on null object

- Failed to deploy Spinnaker.
```

```
java.lang.NullPointerException: Cannot get property 'user' on null object
	at org.codehaus.groovy.runtime.NullObject.getProperty(NullObject.java:60) ~[groovy-all-2.4.11.jar:2.4.11]
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174) ~[groovy-all-2.4.11.jar:2.4.11]
	at org.codehaus.groovy.runtime.callsite.NullCallSite.getProperty(NullCallSite.java:47) ~[groovy-all-2.4.11.jar:2.4.11]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296) ~[groovy-all-2.4.11.jar:2.4.11]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesConfigParser.withKubeConfig(KubernetesConfigParser.groovy:77) ~[clouddriver-kubernetes-1.669.0.jar:1.669.0]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesConfigParser$withKubeConfig.callStatic(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.kubernetes.security.KubernetesConfigParser.parse(KubernetesConfigParser.groovy:33) ~[clouddriver-kubernetes-1.669.0.jar:1.669.0]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.KubernetesProviderUtils.getClient(KubernetesProviderUtils.java:127) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at com.netflix.spinnaker.halyard.deploy.spinnaker.v1.service.distributed.kubernetes.KubernetesDistributedService.getRunningServiceDetails(KubernetesDistributedService.java:554) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deploy(DistributedDeployer.java:172) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at com.netflix.spinnaker.halyard.deploy.deployment.v1.DistributedDeployer.deploy(DistributedDeployer.java:55) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at com.netflix.spinnaker.halyard.deploy.services.v1.DeployService.deploy(DeployService.java:205) ~[halyard-deploy-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at com.netflix.spinnaker.halyard.controllers.v1.DeploymentController.lambda$deploy$16(DeploymentController.java:205) ~[halyard-web-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at com.netflix.spinnaker.halyard.core.DaemonResponse$StaticRequestBuilder.build(DaemonResponse.java:125) ~[halyard-core-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at com.netflix.spinnaker.halyard.core.tasks.v1.TaskRepository.lambda$submitTask$1(TaskRepository.java:48) ~[halyard-core-0.35.0-20171002192634.jar:0.35.0-20171002192634]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
```
My Kubernetes config file:


```yaml
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    server: <redacted>
    certificate-authority-data: <redacted>
users:
- name: <redacted>
  user:
    auth-provider:
      name: oidc
      config:
        client-id: <redacted>
        client-secret: <redacted>
        extra-scopes: groups
        id-token: <redacted>
        idp-issuer-url: <redacted>
        refresh-token: <redacted>
contexts:
- context:
    cluster: local
    user: <redacted>
```

__Comments__:

---

@lwander _(2017-11-06 13:12:19)_: The current kubeconfig you've provided likely won't work with the v1 kubernetes provider - the client library we're using (and migrating off-of) has some severe limitations, in particular, auth-provider isn't supported at all AFAIK. The next iteration of the provider uses the k8s built java provider in order to help us get around these problems. 

Halyard is "correctly" letting you know that the spinnaker will fail to load these credentials as-is. 

---

@rbwsam _(2017-11-07 18:28:35)_: @lwander Thank you very much for that info!
