### ISSUE TITLE
Allow free-form docker repos from UI

### ISSUE THREAD

**Issue by u2mejc** [spinnaker/spinnaker#2481]
*Allow free text docker repos*

Presently Spinnaker requires a static list of repos, likely due to Docker Hub not supporting listing repositories. This causes a need to update the config, that we keep in version control, simply because of a new image repo need. With the popularity of Docker hub / cloud and other repos that still don't list, I'd propose this issue be alleviated by allowing free-form text entry here so that you don't have to maintain a "white list" of repos you can use, nor have to run third part software like https://github.com/skuid/dewey

*Cloud Provider*
- all

*Environment*
- Pulling images from DockerHub, etc
- Spinnaker 1.6

*Feature Area*
- UI

*Description*

_see above_

*Steps to Reproduce*

- Configure a pipeline
- Select the Automated Trigger, Docker Repository type
- Note that four fields are required (Registry Name, Organization, Image, Tag), instead of a single field: `index.docker.io/library/busybox:1` or `gcr.io/google-containers/busybox:latest`

New or alternative repositories do not auto-populate and require a change to the config to show up in the pipeline UI.

*Additional Details*

Snippet from my hal config:
```yaml
    dockerRegistry:
      enabled: true
      accounts:
      - name: dockerhub
        requiredGroupMembership: []
        providerVersion: V1
        address: https://index.docker.io
        username: ********
        password: ********
        email: fake.email@spinnaker.io
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories:
        - library/busybox
```
