### ISSUE TITLE
! ERROR Network default not found via any configured google account(Shared VPC)

### ISSUE THREAD

**Issue by jawlitkp** [spinnaker/spinnaker#2512]
Hello,

I am trying to install spinnaker on google cloud platform and we are using shared VPC. when I tried to add google account I am getting below error. 

- Add the spinnaker-gce-account account
  Failure
Problems in default.provider.google:
! ERROR Network default not found via any configured google
  account.
- Failed to add account spinnaker-gce-account for provider
  google.

**Comment by nfirvine** [comment]
I was able to fix by changing this section in `.hal/config`: 
```
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
...
        network: <some actual network>
```
