### ISSUE TITLE
Pipeline template config modal does not render objects properly.

### ISSUE THREAD

**Issue by danielpeach** [spinnaker/spinnaker#2514]
Seeing some bugs in rendering objects as yaml in pipeline template configure modal. When you load the modal initially, it usually renders fine, but after clicking configure, it’ll render as [object Object]

Reported by @robzienert

**Comment by sbwsg** [comment]
I can get `[object Object]` a couple of different ways:
1. When a variable of type object has defaultValue defined in a template, that defaultValue appears in the ObjectInput field of the initial modal as [object Object].
2. When a pipeline is configured from template and the template uses an object variable in a yaml string e.g.
```yaml
variables:
- name: foo
  type: object
  defaultValue:
    foo: bar
  description: Test object variable.
stages:
- id: wait
  type: wait
  config:
    waitTime: 5
    obj: "{{ foo }}"
```
I end up in with pipeline JSON that has `obj: "object Object"` in the stage config.
