### ISSUE TITLE
Pipeline Templates: imageDescription key/val pair is parsed incorrectly 

### ISSUE THREAD

**Issue by prondeau** [spinnaker/spinnaker#2515]
*Title*

Pipeline Templates: imageDescription key/val pair is parsed incorrectly

*Cloud Provider*

Kubernetes

*Environment*

I am running Spinnaker v1.6.0, using roer for pipeline-templates and deploying to GKE.

*Feature Area*

Pipeline-templates

*Description*

I want to dynamically set the `imageDescription` of a deployment based on the environment. I am trying to achieve this by setting the `imageDescription` field (`config.clusters.containers.imageDescription`) equal to a pipeline parameter. However, after creating the template and trying to run a pipeline I see in the pipeline-template json there has been some strange escaping of quotes in the value, resulting in a pipeline execution error. The strange thing is other keys/values are being parsed properly. In the following example, I try setting the `imageDescription` and the `imageName` to the same parameter. Only the `imageName` is evaluated by SPEL.

Here is a snippet of a pipeline-template:
https://gist.github.com/prondeau/25c11cc2f6236723e900dd9366c90020

And here is the rendered pipeline JSON snippet:
https://gist.github.com/prondeau/a58f7864d6475a67ba23b14585d96d72#file-pipeline-config-json-L20

As you can see on line 20 of the JSON, the `imageDescription` value is being escaped, while on line 21, the `imageName` is not escaped. This results in Spinnaker not evaluating `imageDescription` by SPEL during execution. The error I see while trying to run this pipeline is:

> No such property: fromContext for class: java.lang.String, Failed to evaluate [imageDescription] No converter found capable of converting from type [java.util.LinkedHashMap] to type [java.lang.String] - EL1001E: Type conversion problem, cannot convert from java.util.LinkedHashMap to java.lang.String

And this is the relevant pipeline execution JSON snippet:
```
"containers":[{"args":[],"commands":[],"envVars":[],"imageDescription":"\"${ parameters.foo }\"","imagePullPolicy":"IFNOTPRESENT","limits":{},"name":{"fromContext":true,"stageId":"findImage"},"ports":[],"requests":{},"volumeMounts":[]}
```

Here we can see that the value of `imageDescription` is a string that was not evaluated, while the `name` was evaluated as expected.

**Comment by lwander** [comment]
@jtk54 can you take a look at this?

**Comment by jtk54** [comment]
I was able to coerce the `imageDescription` parameter to be a string by removing the escape strings and using single quotes surrounding the object when declaring the parameter: 

```yaml
# config.yml
parameters:
  - name: imageDescription
    default: '{"fromContext": "true", "stageId": "findImage"}'
...
```

and then reference the parameter object directly instead of using `#readJson()`:
```yml
# template.yml
config:
    clusters:
    - imageDescription: "${ parameters.imageDescription }"
      name: "${ parameters.imageDescription }"
```

The result of the hydrated pipeline had the correct `Map` type: 

```json
clusters": [
          {
            "imageDescription": {
              "fromContext": true,
              "stageId": "findImage"
            },
            "name": {
              "fromContext": true,
              "stageId": "findImage"
            }
          }
        ],
```

Try this out and let me know if that solves the issue.

**Comment by lwander** [comment]
Interesting thing is that the rendered pipeline's parameters are objects rather than strings, which means no `#readJson()` is required

**Comment by prondeau** [comment]
Okay, great! So I was able to get it to work with the solution you've outlined. I realized the source of my problem. I have a `container-spec` module, and there I had set:
```
config:
  clusters:
    containers:
      imageDescription: "{{ imageDescription|json }}"
```
After removing the pipe to json I got the correct results. However, I came upon another error. If I define imageDescription in different ways for different containers, this may break functionality. As an example, here is a module I am using: 
```
# module.yaml
config:
  clusters:
    containers:
      imageDescription: "{{ imageDescription }}"
```
If in the first scenario I have the following:
```
# template1.yaml
source://spinnaker/module
parameters:
- name: imageDescription
   default:  '{"fromContext": "true", "stageId": "findImage"}'
...
variables:
  imageDescription: "${ parameters.imageDescription }"
```
And in another I have:
```
# template2.yaml
source://spinnaker/module
variables:
  imageDescription:
    account: gcr-io
    imageId: gcr.io/endpoints-release/endpoints-runtime:1.13
    registry: gcr.io
    repository: endpoints-release/endpoints-runtime
    tag: 1.13
```
The preceding pipeline-template fails with a parsing error. However, I can get around this error by passing a JSON string as the imageDescription in `template2.yaml` like so:
```
# template2-modified.yaml
source://spinnaker/module
imageDescription: '{ "account": "gcr-io-public", "imageId": "gcr.io/endpoints-release/endpoints-runtime:1.13", "registry": "gcr.io", "repository": "endpoints-release/endpoints-runtime", "tag": "1.13" }'
```

I'm not sure if this actually constitutes a bug, but I wanted to write this up in case others come across similar behaviour. Thanks for all of your help debugging though.
