### ISSUE TITLE
deployedServerGroups behavior unpredictable in branching pipelines

### ISSUE THREAD

**Issue by JukkaForsgren** [spinnaker/spinnaker#2538]
*Title*

deployedServerGroups behavior unpredictable in branching pipelines.

*Cloud Provider*

AWS, but probably relevant with all cloud providers.

*Environment*

Spinnaker 1.6.0 running on GKE. Roer version 0.10.0

*Feature Area*

Pipelines

*Description*

deployedServerGroups array seems to act unpredictably in pipelines that have branching and parallel deployment stages in those branches. According to Pipeline Expressions Guide, the array should contain a "reference to the server group that was created by the last deploy stage". In reality it seems that each deploy stage adds a new element to the array, but this behavior doesn't seem to be logical or deterministic when multiple parallel deployments are done in different branches of pipeline. It becomes impossible to know with confidence which array index refers to what deployment stage when you try to access them later in the pipeline.

*Steps to Reproduce*

Create pipeline that first bakes an AMI or finds an existing image. Then branch into two or more parallel deploy stages and after each of those, add manualJudgment stage and try to print out the servergroup that was deployed by the previous deployment stage in the same branch. I use manualJudgment stage to print this:

```
- config:
    failPipeline: true
    instructions: "${deployedServerGroups[X]['serverGroup']}"
    judgmentInputs: []
    notifications: []
  dependsOn:
  - deploy_to_design
  id: manualJudgment1
  inheritanceControl: {}
  inject: {}
  name: Manual Judgment
  type: manualJudgment
```
Replace index X above with what you think should give the previous servergroup in the same branch.

*Suggested improvement*

It would be much better if there was a helper function like #deployedServerGroup that you could use to reference a specific deployment stage with name (or id), and get the correct servergroup name that was deployed there. This would take out the guesswork.
