### ISSUE TITLE
Ldap authentication configuration

### ISSUE THREAD

**Issue by dbazhal** [spinnaker/spinnaker#2570]
*Title*

There are no sufficient parameters to configure spinnaker authn using ldap.

*Cloud Provider*

Kubernetes

*Environment*

I am running spinnaker using halyard and private kubernetes cluster.

*Feature Area*

Authentication - LDAP

*Description*

I am using gate-local.yml like this:
```yaml
ldap:
  enabled: true
  url: ldap://my.ldap.tld:389/DC=org,DC=com
  userDnPattern: sAMAccountName={0}
  userSearchBase: OU=users
  userSearchFilter: (&(ObjectClass=user)(sAMAccountName={0}))
  managerDn: CN=sys,OU=users,DC=org,DC=com
  managerPassword: pewpew
  groupSearchBase: CN=group,OU=my,OU=groups
  groupSearchFilter: (&(uniqueMember={0})(ObjectClass=groupOfUniqueNames))
  groupRoleAttribute: cn
```
and expect all parameters map into LdapAuthenticationProviderConfigurer, but some of them dont - like groupSearchFilter/groupRoleAttribute, and that makes me unable to use ldap authentication if there is any custom ldap/ad groups configuration(for example if I am using not "groupOfUniqueNames" group type and "uniqueMember" group membership attribute, but "group" and "member"). And I cant debug errors like "object not found" other way than using tcpdump to track exact requests to ldap, it would be much easier to have such info in spin-gate output during failing login attempts.
Also I would be glad to have possibility to configure all that params using halyard config.

*Steps to Reproduce*

None, soz

*Additional Details*

None

**Comment by clanesf** [comment]
@dbazhal - 

I think the issue here may be that you need to put (sAMAAccountName={0}) into the userSearchFilter all by itself and not specify a userDnPattern.

Here is my configuration for LDAP that works (with some things blocked out)

```
ldap:
  enabled: true
  url: ldap://ldap.org.local/dc=org,dc=local
  managerDn: CN=User,DC=ORG,DC=LOCAL 
  managerPassword:  
  userSearchBase:
  userSearchFilter: (sAMAccountName={0})

```

That's all that's there.  

We are currently using it only for Authentication and not Authorization, but it works. Good luck. 

You can always try joining the #auth slack channel as well.

**Comment by dbazhal** [comment]
Unm. I'm not sure that we understood each other. What I'm trying to say is two things:
1) Hal config does not cover much of authn/authz functionality(so I, as user, got to google lot of things and then write them down to gate-local.yaml / fiat-local.yaml). And it hurts pretty much because docs do not cover it too.
2) There is no such thing as groupSearchFilter for Gate at all: https ://github.com/spinnaker/gate/blob/8ab12cd0b11d7e5a771d7db0dcd64eb380d0cc99/gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy#L61 despite LdapAuthenticationProviderConfigurer gives you ability to set that parameter(https://docs.spring.io/spring-security/site/docs/4.2.4.BUILD-SNAPSHOT/apidocs/org/springframework/security/config/annotation/authentication/configurers/ldap/LdapAuthenticationProviderConfigurer.html)

In addition, the configuration I have given is completely working. Except that groupSearchFilter

**Comment by clanesf** [comment]
@dbazhal - I'm sorry, I must have misunderstood. I was thinking you were having trouble getting it to work at all. 

As the groupSearchFilter has more to do with Authorization than Authentication, I haven't gotten there yet.

**Comment by chz8494** [comment]
@dbazhal Hitting exactly this problem, have you found out a solution for group search?

**Comment by dbazhal** [comment]
@chz8494 nope, there is no. spinnaker/gate should be patched to support group filters

**Comment by chz8494** [comment]
@dbazhal I figured it out myself. The guide on their website was for openldap. If you use windows AD, then you need to filter based on "member" and use useDNpattern cn=.

**Comment by rakheshn** [comment]
@dbazhal : Could you help with this ldap setup for me?
 I have AD ldap setup and same configured in cloulddriver-local.yml as below:
Whenever I add "requiredGroupMembership" and/or "permissions", that managed AWS account disappears from the spinnaker UI (ex: not able to list the account while creating server group)
------------------------------------------
my clouddriver-local.yml

requiredGroupMembership: [
  "AD group 1"
  ]

permissions: {
  WRITE: ["AD group 1"]
  }
---------------------------
my fiat-local.yml

auth:
  groupMembership:
    service: ldap
    ldap:
      url: ldap://XXXXXXXX:389/dc=int,dc=aaaaaaa,dc=com
      managerDn: CN= ,OU=,OU=,OU=,DC=int,DC=,DC=
      managerPassword: XXXXXXXXXXXXXXXXXXXXX
      userDnPattern: uid={0},OU=XXXX
      groupSearchBase: OU=aa,OU=bb,OU=cc,OU=dd
      groupSearchFilter: (uniqueMember={0})
      groupRoleAttributes: cn

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by spinnakerbot** [comment]
This issue is tagged as 'to-be-closed' and hasn't been updated  in 45 days, so we are closing it. You can always reopen this issue if needed.

**Comment by atyutyunnik** [comment]
> @dbazhal I figured it out myself. The guide on their website was for openldap. If you use windows AD, then you need to filter based on "member" and use useDNpattern cn=.

How exactly (redacted) does your record look like?

**Comment by icoolchn** [comment]
> @dbazhal我自己想通了。他们网站上的指南是openldap。如果您使用Windows AD，则需要根据“member”进行过滤并使用useDNpattern cn =。
Hey,If you use Windows AD is successful, can provide reference case

**Comment by xxbandy** [comment]
@icoolchn  you can try it .
```
ldap:
  enabled: true
  url: ldap://ldap:389
  managerDn: CN=administrator,CN=Users,dc=xxx,dc=com
  managerPassword: passwd
  #userSearchBase: dc=xxx,dc=com
  userSearchBase: ou=xxx,dc=xxx,dc=com
  userSearchFilter: (sAMAccountName={0})
```
