### ISSUE TITLE
Support reference to certs in kubeconfig for Spinnaker deployed to Kubernetes by Halyard

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2580]
E.g

```yaml
- name: example
  user:
    client-certificate: cc.crt
    client-key: ck.key
```

should work.

Tricky thing is mounting those & rewriting the key & cert to point at the mounted files.
