### ISSUE TITLE
GCE: SAML + Required Membership not working

### ISSUE THREAD

**Issue by sweetib** [spinnaker/spinnaker#2621]
**Title**

SAML along with required membership is not working in new version of spinnaker setup.

**Cloud Provider**
GCP

**Environment**
GCE
OS: Ubuntu Xenial 16.04
Version of Spinnaker sub-services used:

```
spinnaker                        0.83.0                  
spinnaker-clouddriver            1.758.0
spinnaker-deck                   2.1168.0
spinnaker-echo                   1.542.0
spinnaker-fiat                   0.36.0
spinnaker-front50                1.120.0
spinnaker-gate                   4.17.1
spinnaker-igor                   1.87.5
spinnaker-orca                   5.9.1
spinnaker-rosco                  0.102.0
```

**Feature Area**
Spinnaker Gate and Clouddriver and Fiat

**Description**
All the configs in old version for enabling SAML was done under gate and required membership was added under clouddriver config. We haven't done any additional config under fiat as such. And Fiat was disabled in old setup. We are not using halyard for configuration as of now. after updating our spinnaker setup to above mentioned version we started getting errors in our pipelines.

**Error in Pipeline Execution**

```
2018-03-11 17:53:51.066  WARN 1323 --- [nio-7002-exec-1] .n.s.c.s.DefaultAllowedAccountsValidator : sweeti@gmail.com is not authorized (account: deploy-production, description: BasicGoogleDeployDescription, allowedAccounts: [], requiredGroups: [deployment team], json: null)
```
What should be the value added to `allowedAccounts` and which `json` needs to be provide why are they being forwarded as null? And `sweeti@gmail.com` is part of `DEPLOYMENT TEAM` group. 

sample of our clouddriver config is 
```
google:
  accounts:
    - name: deploy-production
      project: production
      jsonPath: /opt/spinnaker/config/production.json
      regions:
        - asia-east1
        - asia-southeast1
      requiredGroupMembership:
        - DEPLOYMENT TEAM
      consul:
        enabled: false
```

sample of gate-local.yml
```
server:
  address: 0.0.0.0

saml:
  enabled: true
  metadataUrl: file:/opt/spinnaker/config/xyzMetadata.xml
  keyStore: file:/opt/spinnaker/config/saml.jks
  keyStorePassword: **************
  keyStoreAliasName: saml
  issuerId: io-spinnaker.xyz
  redirectHostname: spinnaker.xyz.com/gate

auth:
  groupMembership:
    service: google
    google:
      credentialPath: /opt/spinnaker/config/spinnaker-groups.json
      adminUsername: xyz@gmail.com
      domain: xyz.co.id
```

Version of sub services used in old setup
```
spinnaker                           0.82.0  
spinnaker-clouddriver               1.670.1 
spinnaker-deck                      2.1135.0
spinnaker-echo                      1.142.0 
spinnaker-fiat                      0.30.1  
spinnaker-front50                   1.104.0 
spinnaker-gate                      3.54.0  
spinnaker-igor                      1.74.0  
spinnaker-monitoring-daemon         0.5.0   
spinnaker-monitoring-third-party    0.5.0   
spinnaker-orca                      3.4.21  
spinnaker-rosco                     0.97.0
```

We even tried enabling Fiat but after that we started getting errors in Front50  as below:
```
2018-03-11 08:13:52.998  INFO 27816 --- [ofit-/pipelines] c.n.s.echo.services.Front50Service       : <--- HTTP 401 http://0.0.0.0:8080/pipelines?restricted=false (296ms)
2018-03-11 08:13:53.005 ERROR 27816 --- [  Retrofit-Idle] c.n.s.e.pipelinetriggers.PipelineCache   : Error fetching pipelines from Front50: 401
```
Even though service account configured in spinnaker has full access to GCS location used by Front50. Due to this we were not able to get the pipelines or task details on UI.

Not sure what exactly we are missing. Any kind of help will be appreciated. 
Is it possible to have Oauth with Required membership? Is it supported. Or is there a better way to achieve this?
