### ISSUE TITLE
Triggers not executing when `targetSize` is 1

### ISSUE THREAD

**Issue by ericfrancis** [spinnaker/spinnaker#2633]
**Title**

Triggers not executing when `targetSize` is 1

**Cloud Provider**

Kubernetes v1

**Environment**

I am running spinnaker 1.6.0 deployed from halyard.

**Feature Area**

Triggers

**Description**

I am expecting that when a new image is pushed to my docker registry, a pipeline should be executed.

**Steps to Reproduce**

```
    definition:
      account: "{{ cluster }}"
      application: "{{ application }}"
      cloudProvider: kubernetes
      loadBalancers: ["{{ application }}"]
      maxRemainingAsgs: 5
      namespace: "{{ namespace }}"
      region: "{{ namespace }}"
      scaleDown: true
      strategy: "redblack"
      targetSize: "{{ targetSize }}"
```

**Additional Details**

Using `roer` to publish my pipelines.

![screen shot 2018-04-05 at 5 25 50 pm](https://user-images.githubusercontent.com/1517115/38395083-d12180dc-38f6-11e8-8b5b-bb251e75735c.png)
