### ISSUE TITLE
Artifacts from templates in v2 Deploy Manifest stage are null when viewing configuration in Deck

### ISSUE THREAD

**Issue by dchw** [spinnaker/spinnaker#2654]
**Environment**

Spinnaker 1.6.1 deployed with Halyard 0.43.0-20180327030510 into a Kubernetes Cluster.

**Description**

The v2 Deploy Manifest stage does not show artifacts correctly when they are populated via a pipeline template. In the JS console while viewing the stage, the following error is logged repeatedly:

```
TypeError: can't convert undefined to object
Stack trace:
summarizeExpectedArtifact/<@https://spinnaker.imaginelearning.com/app.js:16871:16
fn@https://spinnaker.imaginelearning.com/vendor.bundle.js line 55 > Function:4:176
n@https://spinnaker.imaginelearning.com/vendor.bundle.js:55:66515
u/<@https://spinnaker.imaginelearning.com/vendor.bundle.js:55:65841
$digest@https://spinnaker.imaginelearning.com/vendor.bundle.js:55:73963
$apply@https://spinnaker.imaginelearning.com/vendor.bundle.js:55:75595
u@https://spinnaker.imaginelearning.com/vendor.bundle.js:55:50972
b@https://spinnaker.imaginelearning.com/vendor.bundle.js:55:53576
We/</w.onload@https://spinnaker.imaginelearning.com/vendor.bundle.js:55:53982
 undefined angular.js:14525
```

It should be noted that the same stage when built by hand in the UI does not have the same issues.

**Steps to Reproduce**

Given this template:
```yaml
schema: "1"
id: v2-fail-template
metadata:
  name: Deploy Some Manifests
  description: Deploys some manifests into a cluster
  scopes: [ global ]
variables:
  - name: dockerRepo
    description: The docker image repository to use
    type: string
  - name: appName
    description: The application name
    type: string
configuration:
  expectedArtifacts:
    - matchArtifact:
        kind: docker
        name: index.docker.io/{{dockerRepo}}
        type: docker/image
      defaultArtifact:
        kind: custom
      useDefaultArtifact: false
      usePriorExecution: false
      id: dockerImageArtifact
    - matchArtifact:
        kind: github
        name: "{{appName}}/test.yaml"
        type: github/file
      defaultArtifact:
        kind: default.github
        reference: https://api.github.com/repos/Org/repo/folder/test.yaml
        type: github/file
        version: master
      useDefaultArtifact: true
      usePriorExecution: false
      id: testManifestArtifact
stages:
  - id: deployTest
    type: deployManifest
    name: Deploy Manifests
    config:
      account: v2-nonprod
      cloudProvider: kubernetes
      manifest: null
      manifestArtifactAccount: BuildBot
      manifestArtifactId: testManifestArtifact
      moniker:
        app: "{{appName}}"
        cluster: test
      relationships:
        loadBalancers: []
        securityGroups: []
      requiredArtifactIds: [ dockerImageArtifact ]
      source: artifact
      versioned: null
```

And this config:
```yaml
schema: "1"
pipeline:
  application: TestApp
  name: Deploy
  template:
    source: spinnaker://v2-fail-template
  variables:
    appName: testApp
    dockerRepo: org/testApp
configuration:
  description: Deploys TestApp manifests
  inherit:
    - expectedArtifacts
```

The manifest stage will not render properly. Note that the YAML isn't perfect; it has been hand-sanitized to remove company details and may require a little tweaking.

**Additional Details**
 Here are some screenshots of the affected parts of the UI in the v2 Deploy Manifest stage config:

<img width="606" alt="screen shot 2018-04-12 at 9 13 07 am" src="https://user-images.githubusercontent.com/1056816/38707915-bf60b08c-3e70-11e8-825f-cfd573da1235.png">

<img width="739" alt="screen shot 2018-04-12 at 4 54 08 pm" src="https://user-images.githubusercontent.com/1056816/38708164-288aa8fa-3e72-11e8-8fb8-2be83f8a1a71.png">
