### ISSUE TITLE
azureTenantId in oauth2 not set 

### ISSUE THREAD

**Issue by craigedmunds** [spinnaker/spinnaker#2695]
I'm having what appears to be the same issue described [here](https://github.com/spinnaker/spinnaker/issues/2519), however the solution described there, creating  ~/.hal/default/profiles/gate-azureOAuth.yaml with 

```
security:
  oauth2:
    client:
      accessTokenUri: https://login.microsoftonline.com/our-id/oauth2/token
      userAuthorizationUri: https://login.microsoftonline.com/our-id/oauth2/authorize

```
And running hal deploy apply doesn't work.

I've failed to track down either where azureTenantId should be set, or any way to control it either via a file on disk, or through the hal cli.

Am I going mad?
