### ISSUE TITLE
Kubernetes Manifest Deploy stage hangs indefinitely if k8s Job fails

### ISSUE THREAD

**Issue by ssakhuja57** [spinnaker/spinnaker#2696]
*Title*

Kubernetes Manifest Deploy stage hangs indefinitely if k8s Job fails

*Cloud Provider*

Kubernetes

*Environment*

Using halyard to deploy to GKE, version bom is:

```
version: master-latest-unvalidated
timestamp: '2018-04-23 06:28:19'
services:
  echo:
    version: 0.9.0-20180421022808
    commit: 6d1dcde0e8700b30112013660b991e8f13f16bcb
  clouddriver:
    version: 3.0.0-20180422022807
    commit: d723a9b241a8e644b3648a78efe0f922ddb7e34b
  deck:
    version: 2.2.0-20180423022807
    commit: 5a89f7289168b89d685b3afff0f8a9243c7316f1
  fiat:
    version: 0.6.0-20180420022807
    commit: d4b09d3d00927ee2eefee1bdabcc8373e330600b
  front50:
    version: 0.10.0-20180420022807
    commit: 3dc7259e9dbf1d9c54d190cd2220780bbb1312a5
  gate:
    version: 0.11.0-20180421022808
    commit: 2829ff641cf1edceede28fe3e723007fd3a72657
  igor:
    version: 0.10.0-20180420022807
    commit: 3db44785aff1b05a9d7d60d073855295ad3efe83
  kayenta:
    version: 0.1.0-20180421022808
    commit: 660b789a0c0f10791f1d09ae942c09963a8dc0ac
  orca:
    version: 0.11.0-20180421022808
    commit: e307e44a70966129f074597249082430adf0d4fd
  rosco:
    version: 0.6.0-20180420022807
    commit: 044e163153205ee6b124220880bc0c130a5615b3
  spinnaker:
    version: 0.18.0-20180421022808
    commit: 6cf3ae5d1c88109f004ebb2552ba670962f1c735
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.6.0-20180415022806
    commit: cd2679bfcf205f39d664adac08de7045970d33eb
  monitoring-daemon:
    version: 0.6.0-20180415022806
    commit: cd2679bfcf205f39d664adac08de7045970d33eb
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker
```

*Feature Area*

Pipelines

*Description*

Expected: Deploy Manifest stage should fail if deploying a k8s Job whose Pod fails and has a backoffLimit of 0.

Actual: Deploy Manifest stage hangs indefinitely.

*Additional Details*

![screen shot 2018-04-24 at 11 23 41 am](https://user-images.githubusercontent.com/6405307/39197997-f4d69776-47b3-11e8-80d8-5002bc3b7cc1.png)

Job YAML with status:
```
{
  "kind": "Job",
  "apiVersion": "batch/v1",
  "metadata": {
    "name": "example-service-int-test",
    "namespace": "dev",
    "selfLink": "/apis/batch/v1/namespaces/dev/jobs/example-service-int-test",
    "uid": "ed9466f6-47d1-11e8-aedd-42010af002fb",
    "resourceVersion": "692514",
    "creationTimestamp": "2018-04-24T15:12:39Z",
    "labels": {
      "controller-uid": "ed9466f6-47d1-11e8-aedd-42010af002fb",
      "job-name": "example-service-int-test"
    },
    "annotations": {
      "artifact.spinnaker.io/location": "\"dev\"",
      "artifact.spinnaker.io/name": "\"example-service-int-test\"",
      "artifact.spinnaker.io/type": "\"kubernetes/job\"",
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadata\":{\"annotations\":{\"artifact.spinnaker.io/location\":\"\\\"dev\\\"\",\"artifact.spinnaker.io/name\":\"\\\"example-service-int-test\\\"\",\"artifact.spinnaker.io/type\":\"\\\"kubernetes/job\\\"\",\"moniker.spinnaker.io/application\":\"\\\"blast\\\"\",\"moniker.spinnaker.io/cluster\":\"\\\"dev\\\"\"},\"name\":\"example-service-int-test\",\"namespace\":\"dev\"},\"spec\":{\"backoffLimit\":0,\"template\":{\"spec\":{\"containers\":[{\"command\":[\"/bin/bash\",\"-c\",\"curl example-services\"],\"image\":\"centos:7\",\"name\":\"client\"}],\"restartPolicy\":\"Never\"}}}}\n",
      "moniker.spinnaker.io/application": "\"blast\"",
      "moniker.spinnaker.io/cluster": "\"dev\""
    }
  },
  "spec": {
    "parallelism": 1,
    "completions": 1,
    "backoffLimit": 0,
    "selector": {
      "matchLabels": {
        "controller-uid": "ed9466f6-47d1-11e8-aedd-42010af002fb"
      }
    },
    "template": {
      "metadata": {
        "creationTimestamp": null,
        "labels": {
          "controller-uid": "ed9466f6-47d1-11e8-aedd-42010af002fb",
          "job-name": "example-service-int-test"
        }
      },
      "spec": {
        "containers": [
          {
            "name": "client",
            "image": "centos:7",
            "command": [
              "/bin/bash",
              "-c",
              "curl example-services"
            ],
            "resources": {},
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Never",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "securityContext": {},
        "schedulerName": "default-scheduler"
      }
    }
  },
  "status": {
    "conditions": [
      {
        "type": "Failed",
        "status": "True",
        "lastProbeTime": "2018-04-24T15:12:40Z",
        "lastTransitionTime": "2018-04-24T15:12:40Z",
        "reason": "BackoffLimitExceeded",
        "message": "Job has reach the specified backoff limit"
      }
    ],
    "startTime": "2018-04-24T15:12:39Z",
    "failed": 1
  }
}
```
