### ISSUE TITLE
Kubernetes V2 - env.configMapKeyRef not binding ConfigMaps

### ISSUE THREAD

**Issue by ethanfrogers** [spinnaker/spinnaker#2712]
*Title*

Kubernetes V2 - env.configMapKeyRef not binding ConfigMaps

*Cloud Provider*

Kubernetes

*Feature Area*

Artifacts/Kubernetes V2

*Description*

Given the following manifest, the `configMapKeyRef` should be replaced with the versioned `ConfigMap` that is deployed. When the `ConfigMap` is deployed (`v001`) the `env.configMapKeyRef.name` should also be replaced.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  foo: bar
```

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        env:
           - name: MY_KEY
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: foo
        ports:
        - containerPort: 80
```
