### ISSUE TITLE
Manifest status flashes on and off in v2 deploy execution tab

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#2743]
![image](https://user-images.githubusercontent.com/4874941/39626798-73d5c6c2-4f71-11e8-9b96-85e256e303f6.png)

The events & manifest status keep appearing & reappearing when viewing the pipeline.

**Comment by lwander** [comment]
Using an intentionally bad manifest (to keep the stage running & show failed checks) the issues persists at HEAD

```yaml
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: nginx
    name: nginx-deployment
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containers:
          - image: 'nginx:.9'
            name: nginx
            ports:
              - containerPort: 80
```
