### ISSUE TITLE
Deploying Spinnaker with halyard to k8s with kube v2 provider and SSL enabled for gate fails because k8s readinessProbe fails

### ISSUE THREAD

**Issue by davidxia** [spinnaker/spinnaker#2765]
### Issue Summary:

Deploying Spinnaker with halyard to k8s with kube v2 provider and SSL enabled for gate fails because k8s readinessProbe fails.

### Cloud Provider(s):

Kube V2

### Environment:

Distributed on k8s

### Feature Area: 

halyard, gate

### Description:

The [built in TLS support](https://www.spinnaker.io/setup/security/authentication/ssl/) doesn't seem to work when I use an untrusted CA to sign the server cert for gate. I'm using halyard to deploy spinnaker to k8s.

My spin-gate deployment can't reach running because the [readinessProbe created by halyard](https://github.com/spinnaker/halyard/blob/4db8515854df9666edc17ddc0f287e083ebdc947/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java#L74) is `wget --spider -q https://localhost:8084/health` as constructed when hal is configured to enable SSL.

I see the gate container is a busybox image. I think the version of wget in that image doesn't support the `--no-check-certificate` switch.

I expect to see the readinessProbe succeed for the gate pod and the pod to reach running.

### Steps to Reproduce:

* configure halyard to deploy spinnaker to k8s
* [follow the steps here](https://www.spinnaker.io/setup/security/authentication/ssl/) with an untrusted CA

### Additional Details:

Gate's deployment spec is

```
$ kubectl --context gke_operation-covfefe-1_us-central1_production-us-central1 -n spinnaker get deployment spin-gate -o yaml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{"moniker.spinnaker.io/application":"\"spin\"","moniker.spinnaker.io/cluster":"\"gate\""},"labels":{"app":"spin","cluster":"spin-gate"},"name":"spin-gate","namespace":"spinnaker"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"spin","cluster":"spin-gate"}},"template":{"metadata":{"annotations":{},"labels":{"app":"spin","cluster":"spin-gate"}},"spec":{"containers":[{"env":[],"image":"gcr.io/spinnaker-marketplace/gate:1.0.0-20180509105900","name":"gate","ports":[{"containerPort":8084}],"readinessProbe":{"exec":{"command":["wget","--spider","-q","https://localhost:8084/health"]}},"resources":{"limits":{},"requests":{}},"volumeMounts":[{"mountPath":"/opt/spinnaker/config","name":"spin-gate-files-1264499492"},{"mountPath":"/home/halyard/.hal/k8s-spinnaker/staging/dependencies","name":"spin-gate-files-1285758024"}]}],"volumes":[{"name":"spin-gate-files-1285758024","secret":{"secretName":"spin-gate-files-1285758024"}},{"name":"spin-gate-files-1264499492","secret":{"secretName":"spin-gate-files-1264499492"}}]}}}}
    moniker.spinnaker.io/application: '"spin"'
    moniker.spinnaker.io/cluster: '"gate"'
  creationTimestamp: 2018-05-09T20:49:25Z
  generation: 1
  labels:
    app: spin
    cluster: spin-gate
  name: spin-gate
  namespace: spinnaker
  resourceVersion: "47287631"
  selfLink: /apis/extensions/v1beta1/namespaces/spinnaker/deployments/spin-gate
  uid: 75b62e0c-53ca-11e8-b65d-42010a8000b5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-gate
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spin
        cluster: spin-gate
    spec:
      containers:
      - image: gcr.io/spinnaker-marketplace/gate:1.0.0-20180509105900
        imagePullPolicy: IfNotPresent
        name: gate
        ports:
        - containerPort: 8084
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - wget
            - --spider
            - -q
            - https://localhost:8084/health
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/spinnaker/config
          name: spin-gate-files-1264499492
        - mountPath: /home/halyard/.hal/k8s-spinnaker/staging/dependencies
          name: spin-gate-files-1285758024
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: spin-gate-files-1285758024
        secret:
          defaultMode: 420
          secretName: spin-gate-files-1285758024
      - name: spin-gate-files-1264499492
        secret:
          defaultMode: 420
          secretName: spin-gate-files-1264499492
status:
  conditions:
  - lastTransitionTime: 2018-05-09T20:49:25Z
    lastUpdateTime: 2018-05-09T20:49:25Z
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: 2018-05-09T20:49:25Z
    lastUpdateTime: 2018-05-09T20:49:25Z
    message: ReplicaSet "spin-gate-7f5d9796dd" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```

Running the readinessProbe inside the gate pod returns an error if you're using a cert signed by an untrusted CA.

```
$ kubectl --context gke_operation-covfefe-1_us-central1_production-us-central1 --namespace spinnaker exec -it spin-gate-7f5d9796dd-h2t85 -- /bin/bash

bash-4.4$ wget
BusyBox v1.27.2 (2017-12-12 10:41:50 GMT) multi-call binary.

Usage: wget [-c|--continue] [--spider] [-q|--quiet] [-O|--output-document FILE]
	[--header 'header: value'] [-Y|--proxy on/off] [-P DIR]
	[-S|--server-response] [-U|--user-agent AGENT] [-T SEC] URL...

Retrieve files via HTTP or FTP

	--spider	Only check URL existence: $? is 0 if exists
	-c		Continue retrieval of aborted transfer
	-q		Quiet
	-P DIR		Save to DIR (default .)
	-S    		Show server response
	-T SEC		Network read timeout is SEC seconds
	-O FILE		Save to FILE ('-' for stdout)
	-U STR		Use STR for User-Agent header
	-Y on/off	Use proxy

bash-4.4$ wget --spider -q https://localhost:8084/health
wget: TLS error from peer (alert code 40): handshake failure
wget: error getting response: Connection reset by peer

bash-4.4$ echo $?
1
```

Port forwarding shows that if you disable server cert validation, the health check command works.

```
kubectl --context gke_operation-covfefe-1_us-central1_production-us-central1 -n spinnaker port-forward spin-gate-7f5d9796dd-h2t85 8084


nc localhost 8084 -vz
localhost [127.0.0.1] 8084 open

curl https://localhost:8084/health -v

*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8084 failed: Connection refused
*   Trying fe80::1...
* TCP_NODELAY set
* Connection failed
* connect to fe80::1 port 8084 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8084 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* stopped the pause stream!
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.

curl https://localhost:8084/health -vk

*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8084 failed: Connection refused
*   Trying fe80::1...
* TCP_NODELAY set
* Connection failed
* connect to fe80::1 port 8084 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8084 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=NY; L=New York; O=Spotify; OU=warpspeed; CN=localhost; emailAddress=warpspeed@spotify.com
*  start date: May  5 02:39:54 2018 GMT
*  expire date: May  5 02:39:54 2019 GMT
*  issuer: C=US; ST=NY; L=New York; O=Spotify; OU=warpspeed; CN=spinnaker.spotify.net; emailAddress=warpspeed@spotify.com
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /health HTTP/1.1
> Host: localhost:8084
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 200
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT, PATCH
< Access-Control-Max-Age: 3600
< Access-Control-Allow-Headers: x-requested-with, content-type, authorization, X-RateLimit-App
< Access-Control-Expose-Headers: X-AUTH-REDIRECT-URL
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-Frame-Options: DENY
< X-Application-Context: gate:test,local:8084
< Content-Type: application/vnd.spring-boot.actuator.v1+json;charset=UTF-8
< Content-Length: 15
< Date: Wed, 09 May 2018 21:03:14 GMT
<
* Connection #0 to host localhost left intact
{"status":"UP"}


wget --spider https://localhost:8084/health

Spider mode enabled. Check if remote file exists.
--2018-05-09 17:04:17--  https://localhost:8084/health
Resolving localhost (localhost)... ::1, fe80::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8084... failed: Connection refused.
Connecting to localhost (localhost)|fe80::1|:8084... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8084... connected.
ERROR: cannot verify localhost's certificate, issued by ‘emailAddress=warpspeed@spotify.com,CN=spinnaker.spotify.net,OU=warpspeed,O=Spotify,L=New York,ST=NY,C=US’:
  Unable to locally verify the issuer's authority.
To connect to localhost insecurely, use `--no-check-certificate'.
```

Here's the version of halyard, spinnaker components, and my hal config.

```
halyard@guc3-halyard-d-ccw5:~$ hal -v
1.1.0-20180425074556

halyard@guc3-halyard-d-ccw5:~$ hal version bom master-latest-unvalidated
+ Get BOM for master-latest-unvalidated
  Success
version: master-latest-unvalidated
timestamp: '2018-05-09 18:38:27'
services:
  echo:
    version: 1.0.0-20180509022808
    commit: 68aa8e113e508fe8fa996ec2ed66b982b74f9c02
  clouddriver:
    version: 3.2.0-20180509143818
    commit: 10bbce9edb0049a11409f4b5736a893042613708
  deck:
    version: 2.3.0-20180509143818
    commit: 18f40953e599ad6c5cff0e10d194f0c1cd6fd264
  fiat:
    version: 0.7.0-20180509022808
    commit: 3167d188d020f91d464083f9f2e3efff1695c01c
  front50:
    version: 0.11.0-20180504022808
    commit: 98746b2dddae7435eae34fda45c2dd3e8c1ad643
  gate:
    version: 1.0.0-20180509105900
    commit: 2823dedff807ba96fb18efa2020b31c6309e29ca
  igor:
    version: 0.10.0-20180424022807
    commit: c9619f5af65f36b62002ecc27ed6f0251fa04e27
  kayenta:
    version: 0.2.0-20180502022807
    commit: 555960141f4711b6d26dd0dc9e32cba7f7dfde2f
  orca:
    version: 0.12.0-20180509133827
    commit: 22f6ae34769af54b4a45f8ea157ddc2b984406ae
  rosco:
    version: 0.7.0-20180508022808
    commit: c4aad5b239bba4b9951688fca272c676afb5da96
  spinnaker:
    version: 0.20.0-20180508022808
    commit: 1a6e8f1ff6376a120b4e3c707056b469fd6f26a7
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.6.1-20180426022808
    commit: acdda56147dcefe514be46733249767a4223381f
  monitoring-daemon:
    version: 0.6.1-20180426022808
    commit: acdda56147dcefe514be46733249767a4223381f
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker


halyard@guc3-halyard-d-ccw5:~$ cat ~/.hal/config

currentDeployment: k8s-spinnaker
deploymentConfigurations:
- name: k8s-spinnaker
  version: master-latest-unvalidated
  providers:
    kubernetes:
      enabled: true
      accounts:
      - name: gke_operation-covfefe-1_europe-west1_production-europe-west1
        providerVersion: V2
        context: gke_operation-covfefe-1_europe-west1_production-europe-west1
        configureImagePullSecrets: true
        kubeconfigFile: /home/halyard/.kube/config
        omitNamespaces:
        - default
        - kube-system
        - kube-public
        - spinnaker
        omitKinds:
        - controllerrevision
        - clusterrole
        - clusterrolebinding
        - networkpolicy
        - persistentvolume
        - persistentvolumeclaim
        - role
        - rolebinding
      - name: gke_operation-covfefe-1_us-central1_production-us-central1
        providerVersion: V2
        context: gke_operation-covfefe-1_us-central1_production-us-central1
        configureImagePullSecrets: true
        kubeconfigFile: /home/halyard/.kube/config
        omitNamespaces:
        - default
        - kube-system
        - kube-public
        - spinnaker
        omitKinds:
        - controllerrevision
        - clusterrole
        - clusterrolebinding
        - networkpolicy
        - persistentvolume
        - persistentvolumeclaim
        - role
        - rolebinding
      - name: gke_operation-covfefe-1_asia-east1_production-asia-east1
        providerVersion: V2
        context: gke_operation-covfefe-1_asia-east1_production-asia-east1
        configureImagePullSecrets: true
        kubeconfigFile: /home/halyard/.kube/config
        omitNamespaces:
        - default
        - kube-system
        - kube-public
        - spinnaker
        omitKinds:
        - controllerrevision
        - clusterrole
        - clusterrolebinding
        - networkpolicy
        - persistentvolume
        - persistentvolumeclaim
        - role
        - rolebinding
      - name: gke_operation-covfefe-1_europe-west1_testing-europe-west1
        providerVersion: V2
        context: gke_operation-covfefe-1_europe-west1_testing-europe-west1
        configureImagePullSecrets: true
        kubeconfigFile: /home/halyard/.kube/config
        omitNamespaces:
        - default
        - kube-system
        - kube-public
        - spinnaker
        omitKinds:
        - controllerrevision
        - clusterrole
        - clusterrolebinding
        - networkpolicy
        - persistentvolume
        - persistentvolumeclaim
        - role
        - rolebinding
      - name: gke_operation-covfefe-1_us-central1_testing-us-central1
        providerVersion: V2
        context: gke_operation-covfefe-1_us-central1_testing-us-central1
        configureImagePullSecrets: true
        kubeconfigFile: /home/halyard/.kube/config
        omitNamespaces:
        - default
        - kube-system
        - kube-public
        - spinnaker
        omitKinds:
        - controllerrevision
        - clusterrole
        - clusterrolebinding
        - networkpolicy
        - persistentvolume
        - persistentvolumeclaim
        - role
        - rolebinding
      - name: gke_operation-covfefe-1_asia-east1_testing-asia-east1
        providerVersion: V2
        context: gke_operation-covfefe-1_asia-east1_testing-asia-east1
        configureImagePullSecrets: true
        kubeconfigFile: /home/halyard/.kube/config
        omitNamespaces:
        - default
        - kube-system
        - kube-public
        - spinnaker
        omitKinds:
        - controllerrevision
        - clusterrole
        - clusterrolebinding
        - networkpolicy
        - persistentvolume
        - persistentvolumeclaim
        - role
        - rolebinding
      primaryAccount: gke_operation-covfefe-1_europe-west1_production-europe-west1
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: gke_operation-covfefe-1_us-central1_production-us-central1
    location: spinnaker
    gitConfig:
      upstreamUser: spinnaker
  persistentStorage:
    persistentStoreType: gcs
    gcs:
      jsonPath: /etc/gcloud/xpn-tugboat-1.json
      project: xpn-tugboat-1
      bucket: spotify-production-spinnaker
      rootFolder: front50
      bucketLocation: eu
    redis: {}
  features:
    artifacts: true
  security:
    apiSecurity:
      ssl:
        enabled: true
        keyAlias: spinnaker
        keyStore: /home/halyard/keystore.jks
        keyStoreType: jks
        keyStorePassword: '123456'
        trustStore: /home/halyard/keystore.jks
        trustStoreType: jks
        trustStorePassword: '123456'
      overrideBaseUrl: https://test.net
    uiSecurity:
      ssl:
        enabled: true
        sslCertificateFile: /home/halyard/server.crt
        sslCertificateKeyFile: /home/halyard/server.key
        sslCertificatePassphrase: '123456'
      overrideBaseUrl: https://test.net
  timezone: America/New_York
```

cc @lwander
