### ISSUE TITLE
kube v2 provider fails to deploy kube Service with message`timeout`

### ISSUE THREAD

**Issue by nfirvine** [spinnaker/spinnaker#2772]
### Issue Summary:

Attempting to deploy a k8s Service always results in a failed stage at 25 seconds, with the message `timeout`

### Cloud Provider(s):

GCE + GKE

### Environment:

Spinnaker 1.7.3 on GKE deploying to a different GKE

### Steps to Reproduce:

Attempt to deploy a Service manifest: 
```
- apiVersion: v1
  kind: Service
  metadata:
    name: svcrepro
    namespace: default
  spec:
    ports:
      - name: prom
        port: 9090
        protocol: TCP
        targetPort: 9090
    selector:
      app: prom
      component: prom
    type: ClusterIP
```

Stages fails at 25 seconds.

The resource is in fact deployed.

I've witnessed similar behaviour with statefulsets.

### Additional Details:

(Update: removed irrelevant logs)

I don't believe this to be a problem with CPU bottlenecking as in https://github.com/spinnaker/spinnaker/issues/2494, as we have plenty of overhead.
