### ISSUE TITLE
Allow sensitive values to be used in preconfigured webhooks without showing up in the execution context

### ISSUE THREAD

**Issue by willgorman** [spinnaker/spinnaker#2787]
### Issue Summary:

Preconfigured webhooks may contain sensitive values (like credentials to authenticate with the webhook endpoint) with an expectation of privacy since those values are not displayed in Deck when adding the stage to a pipeline.  However, as mentioned [here](https://github.com/spinnaker/orca/pull/1329#issue-119663993) those values still are available in the execution context.  

### Feature Area: 

Webhook stages

### Description:

It would be helpful to be able to keep the values from the preconfigured webhook stage that aren't needed in Deck from being returned.   This could be the default behavior, but in cases where the values aren't sensitive it can be valuable to still have them available for troubleshooting.   Another option would be to allow the preconfigured stage to declare what values are sensitive:

```yaml
      customHeaders:
        X-Api-Key:
          - <newrelic-api-key>
        Content-Type:
          - application/json
      # Proposed change
      sensitiveHeaders:
        - X-Api-Key
      sensitivePayload: true
```
(I'm assuming that only headers or the payload would be expected to contain sensitive data)

### Additional details:

Relates to https://github.com/spinnaker/orca/pull/1329
