### ISSUE TITLE
Kubernetes V2 Manifests: Escape Java Variables

### ISSUE THREAD

**Issue by rossedman** [spinnaker/spinnaker#2829]
### Issue Summary:
When committing config maps for Elasticsearch/Filebeats or other Java based applications, Spinnaker will try to inject the variables, causing pipeline failures. How could we escape variables that are not meant for Spinnaker?

### Cloud Provider(s):
Azure/GKE

### Environment:
Spinnaker Distributed, On GKE, Deploying To Azure + GKE

### Feature Area: 
Templating/Expressions

### Steps to Reproduce:

Create a config map like this:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false
    processors:
      - add_cloud_metadata:
    cloud.id: ${ELASTIC_CLOUD_ID}
    cloud.auth: ${ELASTIC_CLOUD_AUTH}
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
      protocol: https
```

Attempt to deploy through "Deploy Manifest" stage. It will fail as its trying to write `${path.config}` and other variables.

### Additional Details:
