### ISSUE TITLE
Cannot use Enterprise github authn with halyard

### ISSUE THREAD

**Issue by awalker125** [spinnaker/spinnaker#2856]
### Issue Summary:
I'm trying to use the BYO oauth2 to use enterprise github as authn provider. I cannot get it to enable using the documentation. Creating gate-local.yml doesnt seem to help with halyard.

#2664 seems to be similar

### Cloud Provider(s):
k8s

### Environment:
k8s/aws

### Feature Area: 
halyard
gate

### Description:
I've tried enabling the github provider but then overriding the uris in gate-local.yml but it continues to use github.com

**Comment by awalker125** [comment]
I opened a pull request where I implemented a basic egithub provider. This works for me https://github.com/spinnaker/halyard/pull/956

**Comment by bfarrell** [comment]
I hadnt seen the other issue before, but I was successful getting our enterprise github in our environment.  

These were the steps I took

Run the following commands:
```
hal config security authn oauth2 edit --client-id <github client id> --client-secret <githuh client secret> --provider github
```
```
hal config security authn oauth2 enable
```
Then you will need to manually overwrite the URIs to point to github.example.com instead of the public github.  In order to accomplish that, do the following:

In your .hal directory, cd into the profile you are using.  This is likely default.  Then cd into the profiles dir.
eg ~/.hal/default/profiles
Create a gate-local.yml wih the following info
```
security:
  oauth2:
    enabled: true
    client:
      accessTokenUri: https://github.example.com/login/oauth/access_token
      userAuthorizationUri: https://github.example.com/login/oauth/authorize
    resource:
      userInfoUri: https://github.example.com/api/v3/user
```
Then setup the group auth
```
hal config security authz github edit --accessToken <github token> --organization c<github-org> --baseUrl https://github.example.com/api/v3
```
```
hal config security authz edit --type github
```
```
hal config security authz enable
```

**Comment by awalker125** [comment]
@bfarrell thanks. I did try the gate-local.yml but in the example it was

````
spring:
  oauth2:
    enabled: true
    client:
      accessTokenUri: https://github.example.com/login/oauth/access_token
      userAuthorizationUri: https://github.example.com/login/oauth/authorize
    resource:
      userInfoUri: https://github.example.com/api/v3/user
```

I'll give that a go later on.
