### ISSUE TITLE
Support for AWS EKS container service

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#2871]
### Issue Summary

Now that the AWS EKS container service is out in GA (two US regions only, but still) - it'd be awesome to get support for it in Spinnaker - as it's not a completely standard Kubernetes (regarding authentication).

### Description

Expectation is that Spinnaker can connect to an EKS cluster as it could connect to any Kubernetes cluster.

### Additional Details:

AWS EKS requires at least these things to work:
* new enough kubectl (1.10.X?) - CloudDriver's is new enough? (looks like it)
* Heptio Authenticator installation (to where? Halyard + CloudDriver?)
* anything else...?

See this: https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html and this: https://aws.amazon.com/blogs/aws/amazon-eks-now-generally-available/

**Comment by lwander** [comment]
Maybe @edwinavalos or @ethanfrogers have some experience w/ this.

**Comment by iniinikoski** [comment]
Unfortunately I don't know enough on the Heptio Authenticator part yet - but this looks like a good description page: https://github.com/heptio/authenticator#how-does-it-work. Hopefully this does not get too tricky...

**Comment by jasonmcintosh** [comment]
SO kubectl as of 1.10 supports external authentication mechanisms.  Heptio is one implementation of those that generates a token based upon IAM credentials.  For this to work, it takes an external auth block to call the authenticator to generate the kube token.

**Comment by jasonmcintosh** [comment]
I tested this locally and was able to do deploys & such running halyard 1.20 and spinnaker 1.7.6 with no issues :)  Note, you HAVE to use the v2 provider not the v1 provider.  V1 seems to parse the config file where-as v2 appears to just call kubectl commands.

**Comment by jasonmcintosh** [comment]
@ethanfrogers @iniinikoski I'd suggest if there isn't a task already changing this to "Add support for kubectl external auth mechanisms for users."  IN THEORY the primary changes should be to clouddriver (and maybe halyard).

**Comment by lwander** [comment]
> "Add support for kubectl external auth mechanisms for users."

Could you file a new issue for that? Totally agree we need to support it.

**Comment by jasonmcintosh** [comment]
@lwander It DOES work on local based spinnaker - my theory is it would break though on distributed deploys as I don't think the docker image includes references in the user block for external applications.  Want me to submit an issue anyways or try and confirm that behavior (though looking at code base for the docker image, pretty sure my theory is accurate)?

**Comment by DanRoeSparks** [comment]
@jasonmcintosh We're currently running a local spinnaker, but when running hal deploy apply we're erroring on the account creation step - clouddriver is unable to auth to EKS and fails at that point. It sounds like you've managed to get past this - could you help me get a clue?

**Comment by jasonmcintosh** [comment]
Yep, it works that way.  Ideally we could use role based logins to EKS for this, but until then, that's a workaround.  Just prefer the role due to credential rotation & compliance rules.

**Comment by jicowan** [comment]
@DanRoeSparks Did you create a service account for Spinnaker and then extract the secret/token to configure Spinnaker to access the k8s API?  What permissions did you assign to the RBAC role you created for the service account?  Was that the only step you had to do to get Spinnaker to work with EKS?

**Comment by DanRoeSparks** [comment]
@jicowan 
This is the role binding yaml:
```apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: spinnaker-robot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: spinnaker-robot
  namespace: default
```

and this is the service account yaml:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker-robot
```

here's the relevant part of the kubeconfig:
```
users:
- name: aws
  user:
    token: <token string>
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: heptio-authenticator-aws
      args:
        - "token"
        - "-i"
        - "<cluster-name>"
      env:
        - name: AWS_PROFILE
          value: development
```

and here's the auth configmap we needed to get ELBs created properly:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<account number>:role/<cluster-name>-worker
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
```

The last thing we had to do was to make sure we had the correct tags on the subnets that we already had - they also needed the `kubernetes.io/cluster/<cluster-name>:shared` tags so instances inside them could be attached to their load balancer.

I think that's everything. It might be worth noting that 1.8.0 is now out (as of yesterday, iirc) and is supposed to include support for external auth, so you might not need to mess around with tokens now. 

I'm part-way through creating some Puppet types/providers for hal, and I'm just about to push on with the k8s config, so if I run into anything useful I'll let you know.
