### ISSUE TITLE
Spinnaker does not create an application entry for hyphenated deployments

### ISSUE THREAD

**Issue by louisvernon** [spinnaker/spinnaker#2887]
### Issue Summary:
Spinnaker treats Kubernetes deployments differently if the name is hyphenated versus unhyphenated. If hyphenated it does not appear to create an application entry automatically. 

This may not be considered an issue as Spinnaker does not support hyphenated application names outside of the Kubernetes v2 provider.

### Cloud Provider(s):

GCP/GKE

### Environment:

Spinnaker 1.7.4 running on a GKE 1.9.7 cluster (added using the v1 provider). Spinnaker is deploying using v2 provider to a different GKE 1.9.7 cluster.

### Feature Area: 

Kubernetes V2 provider.

### Description:

While making a reproducer for #2877 I noticed that Spinnaker does not create an application entry automatically for deployments with hyphens in their name.

### Steps to Reproduce:

spinnakerbug:
```
kind: Deployment
metadata:
  name: spinnakerbug
  labels:
    app: spinnakerbug
```
`kubectl apply -f spinnakerbug.yaml`

![image](https://user-images.githubusercontent.com/552230/41179080-aa31d1a4-6b26-11e8-86ac-99ace1abfaf3.png)

spinnaker-bug:
```
kind: Deployment
metadata:
  name: spinnaker-bug
  labels:
    app: spinnakerbug
```
`kubectl apply -f spinnaker-bug.yaml`

![image](https://user-images.githubusercontent.com/552230/41179271-696470ea-6b27-11e8-8e36-0087767309bc.png)
