### ISSUE TITLE
Kubernetes v2 deploy manifest timeout

### ISSUE THREAD

**Issue by stevegszabo** [spinnaker/spinnaker#2903]
I was able to install spinnaker using v2 manifest, pods are running however when I try to deploy a trivial service manifest as a test it hangs at: Wait For Manifest To Stabilize. The service is deployed correctly  so spinnaker is able to manage the namespace.

hal config version edit --version 1.7.6
hal deploy apply

```
    kubernetes:
      enabled: true
      accounts:
      - name: dev-kube
        requiredGroupMembership: []
        providerVersion: V2
        permissions: {}
        dockerRegistries: []
        context: devctx
        configureImagePullSecrets: true
        namespaces:
        - spinnaker
        omitNamespaces: []
        kinds:
        - spinnaker
        omitKinds: []
        customResources: []
        kubeconfigFile: /home/spinnaker/.hal/kube-config.yml
        oauthScopes: []
        oAuthScopes: []
      primaryAccount: dev-kube
```

**Comment by lwander** [comment]
What are the most recent events for the resource you're trying to deploy?

**Comment by stevegszabo** [comment]
I was using a service manifest which I deployed previously outside of spinnaker in the same namespace. I should mention that I don't have any clusters listed under the infrastructure tab. I tried adding a server group but that task failed for the same reason - Wait For Manifest To Stabilize

**Comment by stevegszabo** [comment]
I also noticed there are not options listed for Expected Artifact, I should be able to provide a bitbucket repo to pull the manifest?

**Comment by stevegszabo** [comment]
I configured a docker reg:

```
    dockerRegistry:
      enabled: true
      accounts:
      - name: nexus-docker-registry
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        address: https://aaaaa.com:9999
        username: aaaaaaa
        password: aaaaaaa
        email: fake.email@spinnaker.io
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories: []
      primaryAccount: nexus-docker-registry

```

**Comment by stevegszabo** [comment]
I didn't configure this section which could explain why the artifacts drop down is empty:

```
  artifacts:
    gcs:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []

```
