### ISSUE TITLE
Support password command for Docker registry authentication

### ISSUE THREAD

**Issue by edwinavalos** [spinnaker/spinnaker#2941]
Proposing a solution that should take care of authenticating to ECR based registries (and any other registries with odd authentication methods)

Configuration example

```
dockerRegistry:
  ...
  passwordCommand: "aws --profile ecracccount ecr get-authorization-token --registry-ids 123456789"
  passwordCommandInterval: <time in ms>
```

Decision points:
* We want to support any registry that might have a weird method of getting a docker password
* We didn't want to introduce AWS dependencies into the docker provider
* Password will be read into memory
  - Need to test for possible race conditions (if previous credentials get expired if we refresh during a deployment)

Implementation:
Use an agent similar to CleanupAlarmAgent in clouddriver-aws and iterate over the docker accounts. If there is a passwordCommand specified we run that command on the given millisecond interval. This also needs to be run during the instantiation of a docker account, so I need to confirm that the agent implemented this way accomplishes that.

Looking for discussion on why this might not work, or for any improvements to the overall idea. Thanks!
