### ISSUE TITLE
Spin-cli - Gitlab Oauth requires https redirect urls

### ISSUE THREAD

**Issue by kskewes** [spinnaker/spinnaker#2995]
### Issue Summary:
Gitlab won't start OAUTH process when configured without an HTTPS redirect URL. 

### Cloud Provider(s):
- Gitlab hosted (OAUTH provider)

### Environment:
- Spinnaker 1.8.0 installed via halyard into distributed kubernetes v2
- Nginx TLS termination for Gate and Deck external URL's. 
- Gitlab OAuth configured in Gate and working. 
- spin-cli running on my Ubuntu 16.04 laptop, not in kubernetes.
- Chrome browser.  

### Feature Area: 
Pipeline Templates with `spin-cli`

### Description:
Configuring spin-cli to use hosted Gitlab (gitlab.com) for OAUTH provider. 
Hosted Gitlab requires that OAUTH applications have an https enabled callback/redirect URL.
`spin-cli` currently starts an HTTP endpoint at `localhost:8085`.

### Steps to Reproduce:

1. Clone spin-cli repo. 
2. Modify `command/meta.go` - change Spinnaker Gate URL from localhost to my external gate url: https://github.com/spinnaker/spin/blob/0f250bc99bdd05641e32fdbab85d95d01c667b3e/command/meta.go#L76
3. Leave the OAUTH redirecturl as http://localhost:8085 here: https://github.com/spinnaker/spin/blob/0f250bc99bdd05641e32fdbab85d95d01c667b3e/command/meta.go#L248
4. Add a new Gitlab.com 'application' in my username,  (this is the second one, as already 1 for Gate with Gates external URL), this creates client id and client secret, set callback url to `http://localhost:8085`, set scopes to `read_user` (this gives username if doing any restriction like doing in Gate)
5. Set Gitlab oauth URL's and scope in `.spin/config`
```
  oauth2:                                                                                             
    # The following is an example for Google's OAuth2 endpoints.                                      
    # The values for these are specific to your OAuth2 provider.                                      
    authUrl: https://gitlab.com/oauth/authorize                                                       
    tokenUrl: https://gitlab.com/oauth/token                                                          
                                                                                                      
    # See https://www.spinnaker.io/setup/security/authentication/oauth/providers/                     
    # to see examples for acquiring clientId/clientSecret.                                            
    clientId: <redacted>                        
    clientSecret: <redacted>                   
    scopes:                                                                                           
      - read_user     
```  
6. `go build -v` && `./spin application list`
7. Run the `navigate to` link in a browser. 
Receive from Gitlab.com `The redirect URI included is not valid.`
**stuck**

**Verify HTTPS requirement:**
8. Change the Gitlab.com Oauth application redirect URL to `https://localhost:8085`. 
9. Manually change browser URL to `...redirect_uri=https%3A%2F%2Flocalhost%3A8085` 
10. Gitlab presents "Authorize App" screen. (good!)
11. Browser redirects to https://localhost:8085 but complains:
```
This site can’t provide a secure connection
localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```
12. Try paste the authorization code from browser localhost URL into `./spin application list`
```
Paste authorization code:
<code here>
OAuth2 Authentication failed.
oauth2: cannot fetch token: 401 Unauthorized
Response: {"error":"invalid_client","error_description":"Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method."}
```

### Additional Details:
- Gitlab Oauth details: https://docs.gitlab.com/ce/api/oauth2.html

**Comment by jtk54** [comment]
I was able to reproduce this on a private gitlab instance. Working on providing a flag to `spin` to listen over SSL.

**Comment by jtk54** [comment]
Update here -- got the flow working almost all the way through. Hitting a problem with self-signed certs. I suspect we'd want to have support for self-signed certs in this flow, so I'm working through this now.

**Comment by jtk54** [comment]
Added support for self-signed certs with `SkipInsecureVerify` and got most of the way there. Apparently there is a bug in Gitlab's oauth2 provider code that makes in incompatible with the golang/oauth2 library: https://gitlab.com/gitlab-org/gitlab-ce/issues/46214. I pinged that bug for workarounds as it blocks this feature in `spin`.

**Comment by kskewes** [comment]
Thanks very much. 
I wonder how Gate is handling this as I'm using GitLab oauth configured as provider type other. Might be some clues although different language.

**Comment by jtk54** [comment]
Seems to be related to the [golang oauth2 extension library](https://github.com/golang/oauth2) specifically. I'm not sure how much flexibility exists in the library to make accommodations. I can inspect what Gate does, but I suspect it's just delegating to Spring security packages that may have different options available than the golang libs.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by kskewes** [comment]
There has been an update on the [Gitlab issue](https://gitlab.com/gitlab-org/gitlab-ce/issues/46214#note_99944922)

```
For Go's oauth2 you want to use oauth2.RegisterBrokenAuthHeaderProvider.
You just need to call it at initialisation with oauth2.RegisterBrokenAuthHeaderProvider("https://gitlab-url/").
```

I thought I tried this when we were troubleshooting Gitlab before. Will have another go.

**Comment by kskewes** [comment]
Woohoo, it works.

At [client.go L265](https://github.com/spinnaker/spin/blob/master/cmd/gateclient/client.go#L265) add:
```
oauth2.RegisterBrokenAuthHeaderProvider("https://gitlab.com")
```
Build, run.

Gitlab callback url: `http://localhost:8085`
`~/.spin/config` used:
```
gate:
  endpoint: https://spinnaker-api.example.com
auth:
  enabled: true
  oauth2:
    tokenUrl: https://gitlab.com/oauth/token
    authUrl: https://gitlab.com/oauth/authorize
    clientId: redacted1
    clientSecret: redacted2
    scopes:
    - read_user
```

Perhaps we could use a `config` variable that takes a site url to register, eg:
```
  oauth2:
    tokenUrl: https://gitlab.com/oauth/token
    authUrl: https://gitlab.com/oauth/authorize
    registerBrokenAuthHeaderProvider: https://gitlab.com
```

This way the Spin project doesn't have to maintain a list of these like other projects (Dex?) do.
