### ISSUE TITLE
Using ${"${var}"} to escape a VAR in a manifest appears to be broken in spinnaker 1.8.0

### ISSUE THREAD

**Issue by sharkannon** [spinnaker/spinnaker#3028]
### Issue Summary:
Trying to use the proposed solution from https://github.com/spinnaker/spinnaker/issues/2809 in Spinnaker 1.8.0, the manifest tries to deploy but gets stuck on "Deploy Manifest".

### Cloud Provider(s):
Google Cloud
Kubernetes 0.10.4
Spinnaker 1.8

### Environment:
Using Spinnaker to deploy in GCP on Kubernetes

### Feature Area: 
v2 Manifest Deploy

### Steps to Reproduce:
Create Manifest with ${ "${variable}" } in it and try to read it from git and execute.

![screen shot 2018-07-10 at 11 33 16](https://user-images.githubusercontent.com/704223/42530109-2af6fb1c-8435-11e8-8849-db1f3885bed6.png)

**Comment by lancespeelmon** [comment]
FYI had same results here... To work around the issue I just had to remove all the `${var}` references from the manifest. :(

**Comment by sharkannon** [comment]
FYI, depending on what you are doing with your template, removing the {} from your variables works... it’s just not pretty and can cause issues depending on the language you have in your manifest.

**Comment by rosepan** [comment]
I am having the same issue when deploy kafka helm chart using Spinnaker 1.8.0. Wondering what's the solution available other than updating the manifests? 

The kafka helm chart contains a large number of manifests including .sh files and yaml files. Updating the manifest files in kafka helm chart requires a lot modifications. 

Also when kafka helm chart is upgraded to a newer version, the same procedure will be repeated again.  Appreciate any tips.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by willgorman** [comment]
@spinnakerbot remove-label stale

We're seeing this as well on Spinnaker 1.8.3.  Are there any workarounds?  I'd also be up for taking a shot at fixing.  I'm not sure what the change was that originally fixed this in https://github.com/spinnaker/spinnaker/issues/2809.  Maybe I'm overlooking something but I don't see a link to any commits related to that.  @lwander @jeyrschabu can either of you point me at that?

**Comment by rosepan** [comment]
The workaround I am using is to update the ${ENV_VAR} to #{'$'}{ENV_VAR} in the manifest before running the bake (manifest) stage. Then inside Spinnaker orca service, revert #{'$'}{ENV_VAR} in the manifest back to ${ENV_VAR} after the evaluation so the manifest can be deployed via Deploy (Manifest) stage.

Here is the change in the method transformString() in orca/orca-core/src/main/java/com/netflix/spinnaker/orca/pipeline/expressions/ExpressionTransform.java

===============
  private Object transformString(Object source,
...
    // remove the escape delimiter. #{'$'} to $
    if (isDollarSignEscapedExpression(source)) {
      log.info("after reverting: the source is: \n" + source.toString().replace("#{'$'}", "$"));
      return source.toString().replace("#{'$'}", "$");
    } else {
      return source;
    }
}

  private boolean isDollarSignEscapedExpression(Object obj) {
    return (obj instanceof String && obj.toString().contains("#{'$'}"));
  } 
====================

The Deploy (manifest) stage seems working fine. I can see the Kubernetes resources created in the Kubernetes cluster.

However, at the end of Spinnaker deploy (manifest) stage, the console output shows there is a warning saying something like "Cannot evaluate {env_var} ....". Note the missing '$' sign in the expression. It seems the manifest is evaluated again by ExpressionTransform.transformString() after the Deploy stage. Not sure why the manifest is evaluated twice. But it seems it's a warning and does no harm, so I ignore this warning currently. It's better to be fixed.

Please share any other solutions you have.

**Comment by willgorman** [comment]
After doing some more testing, it looks like this might only be an issue for manifests provided as artifacts.

If I deploy the following as text from a deploy manifest stage:
```yaml
apiVersion: v1
data:
  foo: '${"${bar}"}'
kind: ConfigMap
metadata:
  name: expressionless
```
It works, but with a warning:

![image](https://user-images.githubusercontent.com/49793/47672094-1554ab00-db7f-11e8-8f53-bd8a3f42c68d.png)
![image](https://user-images.githubusercontent.com/49793/47672127-2ef5f280-db7f-11e8-9f3b-f33dcc74e611.png)

The same manifest but consumed as an artifact from Github produces this:

![image](https://user-images.githubusercontent.com/49793/47672935-361e0000-db81-11e8-857e-5e653fcc0355.png)

I wonder if the  outer expression is getting evaluated when the artifact is pulled out down so `${"${bar}"} -> "${bar}"` and that's what the deploy manifest stage is failing to evaluate?

**Comment by pratiktest** [comment]
@spinnakerbot remove-label stale
Im on spinnaker 1.11.2.  I have this annotation templated and escaped in my manifest file as follows 
```io.xxxxx/hosts: "${'${data.host}'}:8080/admin/actuator/prometheus"```. My manifest is only deployed if change in manifest causes the trigger to deploy the manifest. If i use my manifest  as a default artifact by specifying the github file location url (I often do this as i want to trigger pipeline on any change and not just if my deployment manifest changes) deployment of my manifest hangs

**Comment by pratiktest** [comment]
Sorry i was not putting the default manifest correctly, hence i was getting the error. I verified that spinnaker 1.11.2 the escaping works fine in text and as a artifact

**Comment by xxmaestroxx** [comment]
Is there no other solution then "escaping" environment variables again?

That would lead us in the direction, that we have to fork all helm charts (like keycloak, postgres, neo4j, ...) which contains environement variables and have the need to escape the environment variables.

Is that real the solution?
Is there something other available? Like changing the SPeL character from $ to @ maybe? So that spinnaker SPel is not using the same character like the environment variables.

Moreover the escaping breaks for us the default helm installation. So we are manipulating the helm charts in that manner, that they are just working with spinnaker not with plain helm.

**Comment by ezimanyi** [comment]
I believe this has been fixed in 1.9 in spinnaker/orca#2341, so closing this.

**Comment by maggieneterval** [comment]
Just wanted to highlight that a workaround to this issue was released with Spinnaker 1.13. More details available in the PR here: https://github.com/spinnaker/spinnaker/issues/3028

**Comment by anoopwebs** [comment]
@maggieneterval I have updated Spinnaker version to 1.13.1 and tried to deploy a config map for statsD exporter mapping like below (manifest source -Text)
```
apiVersion: v1
data:
  exporter_mapping.yml: |-
    mappings:
    - match: ctr.error.*.*
      name: ctr_errors_count
      labels:
        command: ${1}
        message: ${2}
    - match: ctr.usage.*.*
      name: ctr_usage_count
      labels:
        command: ${1}
kind: ConfigMap
metadata:
  labels:
    name: statsd-exporter-mapping
  name: statsd-exporter-mapping
```
but this config map is getting deployed as 
```
exporter_mapping.yml:
mappings:
- match: ctr.error.*.*
  name: ctr_errors_count
  labels:
    command: 1
    message: 2
- match: ctr.usage.*.*
  name: ctr_usage_count
  labels:
    command: 1
```

I tried wrapping with another ${} but then it gets deployed as 
```
exporter_mapping.yml:
mappings:
- match: ctr.error.*.*
  name: ctr_errors_count
  labels:
    command: ${${1}}
    message: ${${2}}
- match: ctr.usage.*.*
  name: ctr_usage_count
  labels:
    command: ${${1}}
```

What I can do to get this config map deployed with expected data like 
```
exporter_mapping.yml:
mappings:
- match: ctr.error.*.*
  name: ctr_errors_count
  labels:
    command: ${1}
    message: ${2}
- match: ctr.usage.*.*
  name: ctr_usage_count
  labels:
    command: ${1}
```

**Comment by anoopwebs** [comment]
Thanks @maggieneterval, for the quick reply. 

Tried `${“${1}”}` and it get deployed as it is. Generated configmap as follows 
```
exporter_mapping.yml:
mappings:
- match: ctr.error.*.*
  name: ctr_errors_count
  labels:
    command: ${“${1}”}
    message: ${“${2}”}
- match: ctr.usage.*.*
  name: ctr_usage_count
  labels:
    command: ${“${1}”} 
```

When I tried `${"${1}"}` instead`${“${1}”}` (" instead “) then I got 
```
exporter_mapping.yml:
mappings:
- match: ctr.error.*.*
  name: ctr_errors_count
  labels:
    command: 1
    message: 2
- match: ctr.usage.*.*
  name: ctr_usage_count
  labels:
    command: 1
```
