### ISSUE TITLE
Spinnaker UI not loading with local git setup as environment

### ISSUE THREAD

**Issue by apraovjr** [spinnaker/spinnaker#3036]
Here, I followed the steps from this link and in step 3 Choose environment i have done local git source code (planning to contribute to spinnaker for azure)
https://www.spinnaker.io/setup/install/

After `hal deploy apply`, the spinnaker UI deck loads on `localhost:9000` but in console, i see this error

`Failed to load http://localhost:8084/webhooks/preconfigured: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost:9000' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute`

I followed some links online which suggested to add in gate.yml file.

`cors:
  allowedOriginsPattern: http://localhost:9000`

It still doesnt work. Any help would be appreciated as this is blocking me to work with local setup

**Comment by danielpeach** [comment]
Please provide some more information so that someone could reproduce this:

- Which version of halyard are you running?
- What does your halconfig (`~/.hal/config`) look like? If you paste your halconfig in here, please remember to omit any secrets.

**Comment by apraovjr** [comment]
@danielpeach 
The version is 1.3.1-20180620105301

`currentDeployment: default
deploymentConfigurations:
- name: default
  version: 1.8.1
  providers:
    appengine:
      enabled: false
      accounts: []
    aws:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
    azure:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      clusters: []
    dockerRegistry:
      enabled: true
      accounts:
      - name: my-docker-registry
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        address: https://index.docker.io
        username: appugr8
        password: omitted
        email: fake.email@spinnaker.io
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories: []
      primaryAccount: my-docker-registry
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        useInternalIp: false
    kubernetes:
      enabled: true
      accounts:
      - name: my-k8s-account
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        dockerRegistries:
        - accountName: my-docker-registry
          namespaces: []
        context: AKSClusterSpin
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /Users/aprao/.kube/config
        oauthScopes: []
        oAuthScopes: []
      primaryAccount: my-k8s-account
    openstack:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
    oracle:
      enabled: false
      accounts: []
  deploymentEnvironment:
    size: SMALL
    type: LocalGit
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    customSizing: {}
    gitConfig:
      upstreamUser: spinnaker
      originUser: apraovjr
  persistentStorage:
    persistentStoreType: azs
    azs:
      storageAccountName: spinnakerstoragev1
      storageAccountKey: omitted
      storageContainerName: spinnaker
    gcs:
      rootFolder: front50
    redis: {}
    s3:
      rootFolder: front50
    oracle: {}
  features:
    auth: false
    fiat: false
    chaos: false
    entityTags: false
    jobs: false
  metricStores:
    datadog:
      enabled: false
    prometheus:
      enabled: false
      add_source_metalabels: true
    stackdriver:
      enabled: false
    period: 30
    enabled: false
  notifications:
    slack:
      enabled: false
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: false
      masters: []
    travis:
      enabled: false
      masters: []
  security:
    apiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://localhost:8084
    uiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://localhost:9000
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: false
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: false
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
      enabled: false
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    gitlab:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []
  pubsub:
    google:
      enabled: false
      subscriptions: []
  canary:
    enabled: false
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: false
      accounts: []
    - name: datadog
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    reduxLoggerEnabled: true
    defaultJudge: NetflixACAJudge-v1.0
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true`

**Comment by sbwsg** [comment]
There seems to be some incorrect behaviour in the response coming from Gate but I'm not able to reproduce it yet.  In my LocalGit deployment the browser requests `localhost:8084/webhooks/preconfigured` with an `Origin: http://localhost:9000` header and then Gate responds with an `Access-Control-Allow-Origin: http://localhost:9000` header.  I can only get Gate to return `Access-Control-Allow-Origin: *` if I omit the Origin header completely.

Can you confirm the following:

1. What is the output of `curl -v -H Origin:http://localhost:9000 http://localhost:8084/webhooks/preconfigured`?
2. In your browser, open up the network panel and browse to localhost:9000.  Find the requests that fire to `/webhooks/preconfigured`.  Can you copy and paste the Request and Response headers that are sent and received for that GET request into this issue or into a gist?

Thanks!

**Comment by apraovjr** [comment]
Here is output for the 1 
```
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8084 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8084 (#0)
> GET /webhooks/preconfigured HTTP/1.1
> Host: localhost:8084
> User-Agent: curl/7.54.0
> Accept: */*
> Origin:http://localhost:9000
> 
< HTTP/1.1 200 
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: http://localhost:9000
< Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT, PATCH
< Access-Control-Max-Age: 3600
< Access-Control-Allow-Headers: x-requested-with, content-type, authorization, X-RateLimit-App
< Access-Control-Expose-Headers: X-AUTH-REDIRECT-URL
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: DENY
< X-Application-Context: gate:test,local:8084
< X-SPINNAKER-REQUEST-ID: f5a78fa4-f3ee-4381-9d56-89c79183e5fc
< Content-Type: application/json;charset=UTF-8
< Content-Length: 2
< Date: Fri, 13 Jul 2018 18:37:14 GMT
< 
* Connection #0 to host localhost left intact
```

Output for 2 request and response respectively
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Host: localhost:8084
Origin: http://localhost:9000
Pragma: no-cache
Referer: http://localhost:9000/
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
X-RateLimit-App: deck
```

Response headers
```
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: x-requested-with, content-type, authorization, X-RateLimit-App
Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT, PATCH
Access-Control-Allow-Origin: http://localhost:9000
Access-Control-Expose-Headers: X-AUTH-REDIRECT-URL
Access-Control-Max-Age: 3600
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Length: 2
Content-Type: application/json;charset=UTF-8
Date: Fri, 13 Jul 2018 18:38:04 GMT
Expires: 0
Pragma: no-cache
X-Application-Context: gate:test,local:8084
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-SPINNAKER-REQUEST-ID: 1bbd47f6-0853-473c-b585-a0ffaa27eb62
X-XSS-Protection: 1; mode=block
```

**Comment by sbwsg** [comment]
Hm.  I'm a little confused - the error specifically calls out `"The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'."` but we can see that the Access-Control-Allow-Origin header is not '*' in the response but is set to `http://localhost:9000`.  It also seems that even though the error posted is about the preflight OPTIONS request that the browser is receiving the subsequent GET request without issue.

Can you provide a screenshot of the errors you see in the console as well as the list of network requests that are being made (including their http method)?  Something like this:

<img width="741" alt="screen shot 2018-07-13 at 3 18 54 pm" src="https://user-images.githubusercontent.com/34253460/42709941-2e0d2c0e-86b0-11e8-9123-41fdc7f1e6f6.png">

Also, feel free to reach out to me on slack, (join here: https://join.spinnaker.io my username is `@sbws`) since this is a dev issue it might simply be quicker to iterate on the problem in chat.

**Comment by apraovjr** [comment]
@sbwsg Actually i dont get that error once i did this, 
hal config security ui edit --override-base-url http://<deck-loadbalancer-dns-entry>:9000 hal config security api edit --override-base-url http://<gate-loadbalancer-dns-entry

where url was localhost plus this command
echo "host: localhost" | tee \ ~/.hal/default/service-settings/gate.yml \ ~/.hal/default/service-settings/deck.yml

and hal deploy appply

But i get this error when i want to enable canary coniguration for new application created

Request URL: http://localhost:8084/v2/canaryConfig
Request Method: GET

error
```
"Bad Request"failureCause
"retrofit.RetrofitError: 400 
message:"400 "
status:400
timestamp:1531510409138
url:"http://localhost:8090/canaryConfig
```

**Comment by sbwsg** [comment]
OK, since this issue is resolved with those hal commands I'm going to close it.  Canary Analysis is a separate topic and requires some configuration.  The best place to get started is here: https://www.spinnaker.io/setup/canary/ and then work through the guides and docs starting here: https://www.spinnaker.io/guides/user/canary/

Judging from the hal config you posted previously it looks like you haven't enabled canary.  The setup guide I've linked to above should walk you through that process.

If you have further questions about setting up Canary Analysis then both the forum https://community.spinnaker.io and slack are good resources.  If you encounter what appear to be bugs or issues in the way Spinnaker is operating then feel free to create further Github issues!

**Comment by apraovjr** [comment]
@sbwsg should i open new issue for canary ?

**Comment by sbwsg** [comment]
It's difficult to say without knowing more - have you followed the setup guide already?  https://www.spinnaker.io/setup/canary/

Paste the result of `hal config -q` into this issue with any sensitive information removed.

**Comment by apraovjr** [comment]
@sbwsg yes followed it. Its local git setup running on machine.

```
name: default
version: 1.8.1
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: true
    accounts:
    - name: my-docker-registry
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      address: https://index.docker.io
      username: appugr8
      password: 
      email: fake.email@spinnaker.io
      cacheIntervalSeconds: 30
      clientTimeoutMillis: 60000
      cacheThreads: 1
      paginateSize: 100
      sortTagsByDate: false
      trackDigests: false
      insecureRegistry: false
      repositories: []
    primaryAccount: my-docker-registry
  google:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: true
    accounts:
    - name: my-k8s-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      dockerRegistries:
      - accountName: my-docker-registry
        namespaces: []
      context: AKSClusterSpin
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /Users/aprao/.kube/config
      oauthScopes: []
      oAuthScopes: []
    primaryAccount: my-k8s-account
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: LocalGit
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  gitConfig:
    upstreamUser: spinnaker
    originUser: apraovjr
persistentStorage:
  persistentStoreType: azs
  azs:
    storageAccountName: spinnakerstoragev1
    storageAccountKey: 
    storageContainerName: spinnaker
  gcs:
    rootFolder: front50
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
metricStores:
  datadog:
    enabled: false
  prometheus:
    enabled: true
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: true
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
    overrideBaseUrl: http://localhost:8084
  uiSecurity:
    ssl:
      enabled: false
    overrideBaseUrl: http://localhost:9000
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: true
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: true
    accounts:
    - name: aprao-prometheus
      endpoint:
        baseUrl: http://localhost:9090/
      supportedTypes:
      - METRICS_STORE
  - name: datadog
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultMetricsAccount: aprao-prometheus
  defaultStorageAccount: spinnakerstoragev1
  defaultJudge: NetflixACAJudge-v1.0
  defaultMetricsStore: prometheus
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true
```
