### ISSUE TITLE
Specifying `env` options via Halyard ServiceSettings causes Redis to crashloop

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#3067]
### Issue Summary:
Specifying the `env` [service setting](https://www.spinnaker.io/reference/halyard/custom/#custom-service-settings) for Redis causes it to crash loop in kubernetes 

### Cloud Provider(s):
K8s- v2 provider

### Description:
Without an override, it appears to launch the Redis Deployment object with:

```
spec:
      containers:
      - env:
        - name: MASTER
          value: "true"
        image: gcr.io/kubernetes-spinnaker/redis-cluster:v2
```

This MASTER env var is not included when you specify your own `env` vars, and it probably should be.
