### ISSUE TITLE
Spinnaker > 1.6 can't deregister k8s instance from loadbalancer if container spec contains "securityContext"

### ISSUE THREAD

**Issue by mdirkse** [spinnaker/spinnaker#3082]
### Issue Summary:
We've been having this weird issue for a while that stopped us upgrading to any version beyond 1.6.1. We use the k8s v1 provider and after the upgrade every pipeline would hang a the "Wait for Cluster Disable" task. I had no idea what was going on (went through a fair bit of Clouddriver and Orca code, even down the wrong rabbit hole: #2990) until I noticed that, when disabling the servergroup, Clouddriver was correctly disabling the Replicaset ( i.e. setting `"service.spinnaker.io/enabled": "false"`) but not the actual pods in it (the `load-balancer-etc` label was still still set to `true`). Further investigation showed that an attempt to deregister the instance from the load balancer via the UI also failed, but this time with an actual error:
```
Orchestration failed: DeregisterKubernetesAtomicOperation | KubernetesOperationException: [Toggle Pod Labels to false for test-tst-app-v001-vqs85 in default for account spinnaker-test failed: Pod "test-tst-app-v001-vqs85" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
{"Volumes":[{"Name":"default-token-tr5fj","HostPath":null,"EmptyDir":null,"GCEPersistentDisk":null,"AWSElasticBlockStore":null,"GitRepo":null,"Secret":{"SecretName":"default-token-tr5fj","Items":null,"DefaultMode":420,"Optional":null},"NFS":null,"ISCSI":null,"Glusterfs":null,"PersistentVolumeClaim":null,"RBD":null,"Quobyte":null,"FlexVolume":null,"Cinder":null,"CephFS":null,"Flocker":null,"DownwardAPI":null,"FC":null,"AzureFile":null,"ConfigMap":null,"VsphereVolume":null,"AzureDisk":null,"PhotonPersistentDisk":null,"Projected":null,"PortworxVolume":null,"ScaleIO":null,"StorageOS":null}],"InitContainers":null,"Containers":[{"Name":"test","Image":"library/redis:4.0.10-alpine","Command":null,"Args":null,"WorkingDir":"","Ports":null,"EnvFrom":null,"Env":null,"Resources":{"Limits":null,"Requests":null},"VolumeMounts":[{"Name":"default-token-tr5fj","ReadOnly":true,"MountPath":"/var/run/secrets/kubernetes.io/serviceaccount","SubPath":"","MountPropagation":null}],"VolumeDevices":null,"LivenessProbe":null,"ReadinessProbe":null,"Lifecycle":null,"TerminationMessagePath":"/dev/termination-log","TerminationMessagePolicy":"File","ImagePullPolicy":"IfNotPresent","SecurityContext":{"Capabilities":null,"Privileged":null,"SELinuxOptions":null,"RunAsUser":100,"RunAsGroup":null,"RunAsNonRoot":true,"ReadOnlyRootFilesystem":null,"AllowPrivilegeEscalation":

A: null},"Stdin":false,"StdinOnce":false,"TTY":false}],"RestartPolicy":"Always","TerminationGracePeriodSeconds":30,"ActiveDeadlineSeconds":null,"DNSPolicy":"ClusterFirst","NodeSelector":null,"ServiceAccountName":"default","AutomountServiceAccountToken":null,"NodeName":"minikube","SecurityContext":{"HostNetwork":false,"HostPID":false,"HostIPC":false,"ShareProcessNamespace":null,"SELinuxOptions":null,"RunAsUser":null,"RunAsGroup":null,"RunAsNonRoot":null,"SupplementalGroups":null,"FSGroup":null},"ImagePullSecrets":null,"Hostname":"","Subdomain":"","Affinity":null,"SchedulerName":"default-scheduler","Tolerations":[{"Key":"node.kubernetes.io/not-ready","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300},{"Key":"node.kubernetes.io/unreachable","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300}],"HostAliases":null,"PriorityClassName":"","Priority":null,"DNSConfig":null}

B: false},"Stdin":false,"StdinOnce":false,"TTY":false}],"RestartPolicy":"Always","TerminationGracePeriodSeconds":30,"ActiveDeadlineSeconds":null,"DNSPolicy":"ClusterFirst","NodeSelector":null,"ServiceAccountName":"default","AutomountServiceAccountToken":null,"NodeName":"minikube","SecurityContext":{"HostNetwork":false,"HostPID":false,"HostIPC":false,"ShareProcessNamespace":null,"SELinuxOptions":null,"RunAsUser":null,"RunAsGroup":null,"RunAsNonRoot":null,"SupplementalGroups":null,"FSGroup":null},"ImagePullSecrets":null,"Hostname":"","Subdomain":"","Affinity":null,"SchedulerName":"default-scheduler","Tolerations":[{"Key":"node.kubernetes.io/not-ready","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300},{"Key":"node.kubernetes.io/unreachable","Operator":"Exists","Value":"","Effect":"NoExecute","TolerationSeconds":300}],"HostAliases":null,"PriorityClassName":"","Priority":null,"DNSConfig":null}
]
```

Turns out that, if you have a `securityContext` set in you pod spec (as we do), Spinnaker can't update it because the fabric8 client lib version doesn't know how to handle that, tries to post an empty update upon which the k8s api server balks. So Clouddriver can never update the labels on any pods, which means it can never deregister instances from the load balancer which in turn means that, for versions > 1.6.1, k8s clusters can never be disable (and pipelines always timeout). Apparently, until 1.6.1 the status of the pods wasn't considered when waiting for the cluster to disable. 

### Cloud Provider(s):
Kubernetes v1

### Feature Area: 
Clouddriver

### Steps to Reproduce:
-  Install [minikube](https://github.com/kubernetes/minikube) and start the local cluster.
- Create a directory called `config` (or whatever) and create the following files in it:
`clouddriver.yml` ->
```yaml
dockerRegistry:
  enabled: true
  accounts:
  - name: gcr-spinnaker
    providerVersion: V1
    address: https://eu.gcr.io
    email: fake.email@spinnaker.io
    repositories:
    - spinnaker-marketplace
  primaryAccount: gcr-spinnaker
kubernetes:
  enabled: true
  accounts:
  - name: spinnaker-test
    providerVersion: V1
    dockerRegistries:
    - accountName: gcr-spinnaker
    namespaces:
    - default
    kubeconfigFile: /opt/spinnaker/config/kubeconfig
    context: minikube
  primaryAccount: spinnaker-test
```
`kubeconfig` ->
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /opt/spinnaker/config/ca.crt
    server: https://<INSERT YOUR MINIKUBE IP AND PORT HERE>/
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /opt/spinnaker/config/client.crt
    client-key: /opt/spinnaker/config/client.key
```
- copy the `ca.crt`, `client.crt` and `client.key` files from the `${HOME}/.minikube` directory into your `config` directory. You now have the necessary config in place to run Clouddriver with a single k8s account that points to your minikube instance.
- Start Redis (Clouddriver needs it): `docker run -d --net=host`
- Finally, run clouddriver with the config you've just assembled (and make sure to start it from your `config` directory):
```
docker run -ti --net=host -v "$(pwd):/opt/spinnaker/config" gcr.io/spinnaker-marketplace/clouddriver:3.4.0-20180724145924
```
- Then create a ReplicaSet by doing `kubectl apply -f` with the following yaml:
```yaml
apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  annotations:
    service.spinnaker.io/enabled: "true"
  labels:
    app: test
    cluster: test-tst-app
    detail: app
    test-tst-app-v001: "true"
    load-balancer-test-lb: "true"
    replication-controller: test-tst-app-v001
    stack: tst
    version: "1"
  name: test-tst-app-v001
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
      cluster: test-tst-app
      detail: app
      test-tst-app-v001: "true"
      replication-controller: test-tst-app-v001
      stack: tst
      version: "1"
  template:
    metadata:
      labels:
        app: test
        cluster: test-tst-app
        detail: app
        test-tst-app-v001: "true"
        load-balancer-test-lb: "true"
        replication-controller: test-tst-app-v001
        stack: tst
        version: "1"
    spec:
      containers:
      - image: library/redis:4.0.10-alpine
        imagePullPolicy: IfNotPresent
        name: test
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 100
```
- Then create a loadbalancer by running the following command: 
```bash
curl -X POST -H "Content-Type: application/json" -d  '[ {  "upsertLoadBalancer": { "name": "test-lb",  "ports": [ { "name": "http", "port": 80, "targetPort": 8080, "protocol": "TCP" } ], "account":  "spinnaker-test" } } ]' localhost:7002/kubernetes/ops
```

You can now try to deregister the instance from the loadbalancer by running the following:
```bash
curl -X POST -H "Content-Type: application/json" -d '[ { "deregisterInstancesFromLoadBalancer": { "loadBalancerNames": ["test-lb"], "instanceIds": ["test-tst-app-v001-<YOUR POD ID HERE>"], "namespace": "default", "credentials": "spinnaker-test" }} ]' localhost:7002/kubernetes/ops
```
The Clouddriver logs will show the exception and the `load-balancer` labels will not be modified.

If you repeat the same steps, but leave out the `securityContext` from the ReplicaSet yaml, everything works as intended.
