### ISSUE TITLE
clouddriver fails to start after deploy

### ISSUE THREAD

**Issue by usrleon** [spinnaker/spinnaker#3127]
### Issue Summary:
After deployment clouddriver starts with error:
`2018-08-03 22:57:43.744  WARN 30385 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'searchController': Unsatisfied dependency expressed through field 'searchProviders'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'catsSearchProvider' defined in com.netflix.spinnaker.clouddriver.cache.CacheConfig: Unsatisfied dependency expressed through method 'catsSearchProvider' parameter 2; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.List<com.netflix.spinnaker.clouddriver.cache.SearchableProvider>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
`
more in attached log
[clouddriver.log](https://github.com/spinnaker/spinnaker/files/2258992/clouddriver.log)

### Cloud Provider(s):
AWS
### Environment:
Debian local installation
Ubuntu 14.04
halyard 1.5.0-20180713143726
spinnaker 1.8.4
### Steps to Reproduce:
Deploy using manual https://www.spinnaker.io/setup/install/deploy/
### Additional Details:

---

**Comment by lwander** [comment]
These kinds of bean/spring issues arise from misconfiguration -- w/o knowing your configuration, is it possible you haven't run `hal config provider aws enable`?

**Comment by thecodejunkie** [comment]
I'm seeing this exact same issue of a new deployment of 1.9.3 to GCP, with the Kubernetes (Manifest Based) provider. I followed the steps provided at https://www.spinnaker.io/setup/install/deploy/ and the deploy ran without problems

However I do see the exact same problem in the log for the clouddriver pod.

@sbwsg this is related to our discussions in #3285 but I've since followed your recommendation of using a GCP VM to host Halyard and deploy it from there, instead of the marketplace

**Comment by thecodejunkie** [comment]
I've tried deploying it to both `europe-west1-b` and `europe-north1-a` and cloud driver fails with the same error in both regions. I also tried 1.9.2 with (in `europe-west1-b`) with the same error

**Comment by thecodejunkie** [comment]
@usrleon did you ever find a solution to this problem?

**Comment by thecodejunkie** [comment]
@sbwsg here's a censored copy of `hal deploy -q`

```
name: default
version: 1.9.3
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: false
    accounts: []
  google:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: false
    accounts:
    - name: my-k8s-v2-account
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: gke_my-project_europe-north1-a_spinnaker
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /home/my-name/.kube/config
      oauthScopes: []
      oAuthScopes: []
    primaryAccount: my-k8s-v2-account
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
  accountName: my-k8s-v2-account
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  gitConfig:
    upstreamUser: spinnaker
  haServices:
    clouddriver:
      enabled: false
    echo:
      enabled: false
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: /home/my-name/my-project-a7df1d806191.json
    project: my-project
    bucket: spin-8d8301c3-b009-4a62-ab82-bad1946027bf
    rootFolder: front50
    bucketLocation: eu
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
  artifacts: true
metricStores:
  datadog:
    enabled: false
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
  wercker:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
      ldap:
        roleProviderType: LDAP
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true
```
