### ISSUE TITLE
K8S-V2: Scale and Deploy stage run infinitely when deploying 0 pods

### ISSUE THREAD

**Issue by e96wic** [spinnaker/spinnaker#3148]
### Issue Summary:

When scaling down a deployment to 0 replicas or when deploying a k8s-deployment with 0 replicas, the respective stages run infinitely. They don't seem to notice when the action is finished. In both cases the k8s-instances were correctly modified.

### Cloud Provider(s):

Kubernetes

### Environment:

Kubernetes

### Feature Area: 

Kubernetes / Pipelines / Deploy Manifest and Scale manifest Stage

**Comment by lwander** [comment]
Can you share the `status` section of the `kubectl get deploy -o yaml <resource>` for the deployment that never finishes scaling?

**Comment by e96wic** [comment]
Before and after:

It looks like kubernetes does not update the 'lastTransitionTime' when scaling down a deployment. Only the 'observedGeneration' is updated.

```
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-08-09T15:05:31Z
    lastUpdateTime: 2018-08-09T15:05:31Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 40
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1


status:
  conditions:
  - lastTransitionTime: 2018-08-09T15:05:31Z
    lastUpdateTime: 2018-08-09T15:05:31Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 41
```
