### ISSUE TITLE
Unable to use GitHub Teams authorization

### ISSUE THREAD

**Issue by evenh** [spinnaker/spinnaker#3154]
### Issue Summary:

When trying to perform the [GitHub Teams configuration](https://www.spinnaker.io/setup/security/authorization/github-teams/), it fails with an exception in Halyard.

### Cloud Provider(s):

GKE

### Environment:

Using V2 Kubernetes provider

```
hal 1.6.0-20180806143444
spinnaker 1.8.5

k8s:
  Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.7", GitCommit:"dd5e1a2978fd0b97d9b78e1564398aeea7e7fe92", GitTreeState:"clean", BuildDate:"2018-04-19T00:05:56Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.5-gke.3", GitCommit:"6265b9797fc8680c8395abeab12c1e3bad14069a", GitTreeState:"clean", BuildDate:"2018-07-19T23:02:51Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}
```

### Feature Area: 

Halyard/authorization

### Description:

When I'm trying to configure GitHub Teams authorization as per the docs, I get the the following output:

```
➜  5-spinnaker git:(master) ✗ hal config security authz github edit \
    --accessToken $TOKEN \
    --organization $ORG \
    --baseUrl=https://api.github.com
+ Get current deployment
  Success
- Get github group membership settings
  Failure
Problems in Global:
! ERROR Unexpected exception: java.lang.RuntimeException: It
  shouldn't be possible to have multiple
  com.netflix.spinnaker.halyard.config.model.v1.security.RoleProvider nodes. This
  is a bug.

- Failed to get github method.
```

### Steps to Reproduce:

1. Follow the documentation for setting up a personal access token
2. Export ORG and TOKEN variables
3. Execute command from description

**Comment by allen-servedio** [comment]
I have also hit this issue and have not found a work around at this time. Does anyone have any thoughts on what is causing this?

**Comment by allen-servedio** [comment]
@evenh - I have posted https://community.spinnaker.io/t/unable-to-use-github-teams-authorization/592 to try to get us some help. This is a blocker for me.

**Comment by allen-servedio** [comment]
@evenh - okay, I have a work around now. You have to manually modify your ~/.hal/config file with the following (look for the `<something here>` type of comments to see where to put your ids and secrets:

```
authn:
  oauth2:
    enabled: true
    client:
      clientId: <client id here>
      clientSecret: <client secret here>
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      scope: user:email
    resource:
      userInfoUri: https://api.github.com/user
    userInfoMapping:
      email: email
      firstName: ''
      lastName: name
      username: login
    provider: GITHUB
  saml:
    enabled: false
  ldap:
    enabled: false
  x509:
    enabled: false
  iap:
    enabled: false
  enabled: true
authz:
  groupMembership:
    service: GITHUB
    google:
      roleProviderType: GOOGLE
    github:
      roleProviderType: GITHUB
      baseUrl: https://api.github.com
      accessToken: <access token here>
      organization: <organization here>
    file:
      roleProviderType: FILE
    ldap:
      roleProviderType: LDAP
  enabled: true      
```

You can see the result here: `cat ~/.hal/default/staging/gate.yml`

This is still a bug in Halyard, but at least we have a work around now.

**Comment by evenh** [comment]
Thanks @allen-servedio. I have replicated your workaround and I don't get warnings anymore. However, if I understand correctly it still doesn't work the way I expect it to. I can log in a member of my organization, but I can also log in as a random GitHub user who doesn't have any organization membership (nor a team membership). I see the following in Fiat logs:

```
2018-08-14 20:17:46.127  INFO 1 --- [cutionAction-21] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced 2 non-anonymous user roles.
2018-08-14 20:17:46.127  INFO 1 --- [cutionAction-21] tsSchedulerConfig$LoggingInstrumentation : [] Fiat:UserRoleSyncer completed in 1s
2018-08-14 20:27:46.137  INFO 1 --- [cutionAction-22] c.n.s.fiat.roles.UserRolesSyncer         : [] Synced anonymous user role.
2018-08-14 20:27:46.138  INFO 1 --- [cutionAction-22] c.n.s.f.r.github.client.GitHubClient     : [] ---&gt; HTTP GET https://api.github.com/orgs/my-org/members/outside-user
2018-08-14 20:27:46.871  INFO 1 --- [cutionAction-22] c.n.s.f.r.github.client.GitHubClient     : [] &lt;--- HTTP 404 https://api.github.com/orgs/my-org/members/outside-user (732ms)
2018-08-14 20:27:46.873  INFO 1 --- [cutionAction-22] c.n.s.f.r.github.client.GitHubClient     : [] ---&gt; HTTP GET https://api.github.com/orgs/my-org/members/evenh
2018-08-14 20:27:47.017  INFO 1 --- [cutionAction-22] c.n.s.f.r.github.client.GitHubClient     : [] &lt;--- HTTP 204 https://api.github.com/orgs/my-org/members/evenh (143ms)
2018-08-14 20:27:47.019  INFO 1 --- [cutionAction-22] c.n.s.f.r.github.client.GitHubClient     : [] ---&gt; HTTP GET https://api.github.com/orgs/my-org/teams?page=1&amp;per_page=100
2018-08-14 20:27:47.167  INFO 1 --- [cutionAction-22] c.n.s.f.r.github.client.GitHubClient     : [] &lt;--- HTTP 200 https://api.github.com/orgs/my-org/teams?page=1&amp;per_page=100 (148ms)
```

**Comment by allen-servedio** [comment]
@evenh - so I have not tried that yet... Based on the log sample that you are showing, does someone outside of your organization basically get a bunch of 404's or can they access everything? Ideally I'd like to limit it to a github team, but I have not delved into that to see if it is possible.

Basically, other than making sure that Github can verify them, are you able to further restrict access?

**Comment by evenh** [comment]
Logged in as the other user, I can see everything. From the documentation:

> Fiat’s authorization model is a whitelist that is open by default. In other words, when a resource does not define who is allowed to access it, it is considered unrestricted.
>
> With Fiat, you can…
>
> - Restrict access to specific accounts.
> - Restrict access to specific applications.
> - Run pipelines using automated triggers against access-controlled applications.
> - Use and periodically update user roles from a backing role provider.

I think the logs is demonstrating the periodical update. I have not had a chance to try to manually restrict anything yet but I'd like to figure out if/how I can lock down the whole instance to GitHub users that are not part of an organization/team.

**Comment by allen-servedio** [comment]
Okay, if I dig down into that, I'll post back what I do. If you can also do that, it would help me out. Thanks for letting me know what you found.

**Comment by pagottoo** [comment]
Same problem here... 

- Spinnaker on K8S...
- hal version list -> 1.9.2, via container on K8S...
- Github App oAuth configured, including organization restriction, and any user can view all on my spinnaker...

**Comment by stewchen** [comment]
Hi all, merged the fix for this issue. Will comment back when it's released

**Comment by max-rocket-internet** [comment]
@stewchen correct me if I'm wrong but that PR was about LDAP but this issue is about Github?

**Comment by stewchen** [comment]
Correct, the new ldap role provider had a name collision bug with the github role provider, which introduced this issue a few weeks ago.

**Comment by stewchen** [comment]
The fix should be released - please update to the latest halyard version.

**Comment by atlix** [comment]
Hi all!
Got the same issue after installing fresh vesrion of Spinnaker via halyard in K8s v1.12.0 (don't know what version of hal cause hal --version return Unknown, installed it via curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh).
Configured OAuth, made organization restriction, but any user can see everything after authorize via github. 

```
    authn:
      oauth2:
        enabled: true
        client:
          clientId: *******
          clientSecret: *******
          accessTokenUri: https://github.com/login/oauth/access_token
          userAuthorizationUri: https://github.com/login/oauth/authorize
          scope: user:email
          preEstablishedRedirectUri: https://*******
          useCurrentUri: false
        resource:
          userInfoUri: https://api.github.com/user
        userInfoMapping:
          email: email
          firstName: ''
          lastName: name
          username: login
        provider: GITHUB
...
      enabled: true
    authz:
      groupMembership:
        service: GITHUB
...
        github:
          roleProviderType: GITHUB
          baseUrl: https://api.github.com
          accessToken: *******
          organization: *******
...
      enabled: true
```

What should i do? :) Create another issue? I've try 1.10.5 and 1.11 versions of Spinnaker
