### ISSUE TITLE
kayenta-pod can't start

### ISSUE THREAD

**Issue by RockyFu267** [spinnaker/spinnaker#3161]
Issue Summary:
I have a problem when starting kayenta-pod.

 Cloud Provider(s):
aliyun and Private environment

Environment:
kubernetes

Description:
I work in china,our company can't use gcs or aws. So I used minio instead of S3.
The error log of kayenta-pod looks like:

2018-08-10 03:31:10.690  INFO 1 --- [    scheduler-5] c.n.k.o.controllers.PipelineController   : Health indicators are still reporting DOWN; not starting orca queue processing yet: DOWN {redisHealth=UP {}, canaryConfigIndexingAgent=DOWN {existingByApplicationIndexCount=0, expectedByApplicationIndexCount=1, cyclesInitiated=73, cyclesCompleted=73}, diskSpace=UP {total=105553780736, free=81575895040, threshold=10485760}}

But my orca -pod is running，It is healthy.

Additional Details:
The hal-config file is as follows:
```
deploymentConfigurations:
- name: default
  version: 1.8.3
  providers:
    appengine:
      enabled: false
      accounts: []
    aws:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
    azure:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      clusters: []
    dockerRegistry:
      enabled: false
      accounts: []
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        useInternalIp: false
    kubernetes:
      enabled: true
      accounts:
      - name: my-k8s-v2-account
        requiredGroupMembership: []
        providerVersion: V2
        permissions: {}
        dockerRegistries: []
        context: kubernetes-admin@kubernetes
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /root/.kube/config
        oauthScopes: []
        oAuthScopes: []
      primaryAccount: my-k8s-v2-account
    openstack:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
    oracle:
      enabled: false
      accounts: []
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: my-k8s-v2-account
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    customSizing: {}
    gitConfig:
      upstreamUser: spinnaker
  persistentStorage:
    persistentStoreType: s3
    azs: {}
    gcs:
      rootFolder: front50
    redis: {}
    s3:
      bucket: spin-29b8cfa0-409d-410a-8c6e-4622ef2ea0ff
      rootFolder: front50
      endpoint: http://minio-service.spinnaker:9000
      accessKeyId: test001
      secretAccessKey: testtest
    oracle: {}
  features:
    auth: false
    fiat: false
    chaos: false
    entityTags: false
    jobs: false
    artifacts: true
  metricStores:
    datadog:
      enabled: false
    prometheus:
      enabled: true
      push_gateway: http://10.88.10.48:30009
      add_source_metalabels: true
    stackdriver:
      enabled: false
    period: 30
    enabled: true
  notifications:
    slack:
      enabled: false
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: true
      masters:
      - name: my-jenkins-master
        address: http://10.88.10.48:8999
        username: rockyfu
        password: xxxxxxx
    travis:
      enabled: false
      masters: []
  security:
    apiSecurity:
      ssl:
        enabled: false
    uiSecurity:
      ssl:
        enabled: false
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: false
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: false
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
      enabled: false
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    gitlab:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []
  pubsub:
    google:
      enabled: false
      subscriptions: []
  canary:
    enabled: true
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: true
      accounts:
      - name: prometheus
        endpoint:
          baseUrl: http://10.88.10.48:30009
        supportedTypes:
        - METRICS_STORE
    - name: datadog
      enabled: false
      accounts: []
    - name: aws
      enabled: true
      accounts:
      - name: test001
        bucket: spin-29b8cfa0-409d-410a-8c6e-4622ef2ea0ff
        rootFolder: kayenta
        endpoint: http://minio-service.spinnaker:9000
        secretAccessKey: testtest
        supportedTypes:
        - CONFIGURATION_STORE
        - OBJECT_STORE
      s3Enabled: true
    reduxLoggerEnabled: true
    defaultMetricsAccount: prometheus
    defaultStorageAccount: test001
    defaultJudge: NetflixACAJudge-v1.0
    defaultMetricsStore: prometheus
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true


```
