### ISSUE TITLE
Kubernetes V2: Helm bake should substitute ImagePullSecrets for private registries

### ISSUE THREAD

**Issue by ksegun** [spinnaker/spinnaker#3202]
### Issue Summary:
Helm bake should substitute ImagePullSecrets for private registries

### Cloud Provider(s):
kubernetes v2

### Environment:
I am running spinnaker version 1.9.0 Kubernetes on GKE

### Description:
I created a helm chart that generates ImagePullSecrets (see https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#creating-image-pull-secrets). The generated ImagePullSecret is created with a version, however, the image pull secret is not updated in the generated template and pod deploy fails because the image cannot be pulled for the private registry

### Steps to Reproduce:
Create a Helm chart and add ImagePullSecrets support following https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#creating-image-pull-secrets)

[Chart files](https://gist.github.com/ksegun/f82a460f572e976d5840884a3a30ba0f)

Created secret is named secret release-registrykey-v000, generated deployment has release-registrykey

**Comment by lwander** [comment]
You need to tell Spinnaker not to version the configuration:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
  annotations:
    'strategy.spinnaker.io/versioned': 'false' # <-- this is the important part
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
```

https://www.spinnaker.io/reference/providers/kubernetes-v2/#strategy
