### ISSUE TITLE
Termination hooks are not executed when resizing server group to 0 (AWS)

### ISSUE THREAD

**Issue by costimuraru** [spinnaker/spinnaker#3229]
### Issue Summary:
Termination hooks are not executed when resizing server group to 0 (AWS)

### Cloud Provider(s):
AWS

### Environment:
Spinnaker deployed in AWS, trying to deploy in AWS.

### Feature Area: 
CloudDriver

### Description:
We're using Spinnaker to deploy on AWS. We have setup a termination lifecycle hook (shutdown hook), so that when Spinnaker creates a server group (an Auto Scaling Group) it attaches this hook to it.
Whenever the ASG decides to kill an instance, it will first call this termination hook, before shutting down the node. The hook is received by a process running on the AWS instance, with the whole purpose of performing cleanup and upload data before shutting down.

This works great with Spinnaker when trying to resize from let's say 10 to 1 instance. The 9 termination hooks will be triggered just fine.
The problem occurs, when we try to resize to 0 instances. In this case, Spinnaker has an optimization: if the Auto Scale Group is not attached to any load balancers, it will just terminate the instances itself (from CloudDriver): https://github.com/spinnaker/clouddriver/blob/80c2c369bf5fa4ec98c6ad3956b05c6995c11116/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/deploy/ops/ResizeAsgAtomicOperation.groovy#L93
This is problematic because the shutdown hook(s) don't get executed and the server is not able to perform the cleanup/upload the data before shutting down.

### Steps to Reproduce:
1) Enable termination hooks in Spinnaker for AWS.
2) Deploy a server group in AWS using spinnaker. Don't attach it to any load balancers.
3) Once the nodes are up, resize the Server Group to 0.

Actual Result: The shutdown hook doesn't get executed because the instance is killed automatically by Spinnaker.

Desired Result: If Spinnaker (CloudDriver) detects that the server group is attached to a load balancer OR has termination hooks, then skip the termination optimization when resizing to 0 instances.

### Additional Details:

CloudDriver config for adding shutdown hooks:
```
    - name: adev-aws
      accountId: "<>"
      regions:
        - name: us-east-1
      lifecycleHooks:
        - defaultResult: 'CONTINUE'
          heartbeatTimeout: 7200
          lifecycleTransition: 'autoscaling:EC2_INSTANCE_TERMINATING'
          notificationTargetARN: 'arn:aws:sns:{{region}}:{{accountId}}:spinnaker-shutdowns-pending'
          roleARN: 'arn:aws:iam::{{accountId}}:role/spinnakerasg'
```
