### ISSUE TITLE
Dropdown list of elements in pipeline template UI

### ISSUE THREAD

**Issue by benjaminws** [spinnaker/spinnaker#3231]
### Issue Summary:

It would be useful to have the ability to specify a list of elements in a pipeline template variable, and have those elements be selectable in the pipeline template configuration UI modal.

An example template configuration might look like this:

```
variables:
  - name: region
    label: Region to deploy to
    type: selectableList
    description: The region to deploy to
    elements:
        - us-east-1
        - us-west-2
        - eu-central-1
```

The UI would be a typical html select, with the elements defined in the configuration as the values. 

It might look like this:

![image](https://user-images.githubusercontent.com/121679/44494407-951f4000-a639-11e8-80fa-089142eccc7d.png)

![image](https://user-images.githubusercontent.com/121679/44494394-889ae780-a639-11e8-9239-eeac657355fe.png)

Ultimately the selected element would be accesible in the template as `region`.

### Cloud Provider(s):

N/A

### Environment:

N/A

### Feature Area: 

Pipeline
