### ISSUE TITLE
[Halyard] Feature Request: Expose service port for monitoring sidecar container

### ISSUE THREAD

**Issue by jfillo** [spinnaker/spinnaker#3249]
### Feature Area: 

Halyard deploying Spinnaker using Kubernetes v2 provider

### Feature Request:

The monitoring sidecar container (if it exists) should have its port exposed in the service resource definition.

By including these in the service definition, those people using Kube-Prometheus can create a single ServiceMonitor like:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mon-spinnaker
  labels:
    team: infra
spec:
  selector:
    matchLabels:
      app: spin
  endpoints:
  - port: monitoring
    targetPort: 8008
    path: /prometheus_metrics
```
to pipe their metrics to Prometheus

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 52 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by jfillo** [comment]
@spinnakerbot remove-label stale

Still would like to see this done. Though yy PR hasn't had much traction in a while.

**Comment by kskewes** [comment]
Me too.
We could use `matchLabels` value of `app.kubernetes.io/part-of=spinnaker` instead of `app: spin` going forward to migrate to the recently published Kubernetes common labels scheme.
This label is already being added to objects.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by costimuraru** [comment]
Could we get this integrated?

Right now, we're working around it, by adding the Prometheus pod annotations on each service, but it looks kinda ugh:

```yaml
      clouddriver-local.yml: |-
        kubernetes:
          podAnnotations:
            iam.amazonaws.com/role: {{ terraform.helm.spinnaker.iam_role }}
            prometheus.io/scrape: "true"
            prometheus.io/path: "/prometheus_metrics"
            prometheus.io/port: "8008"

      rosco-local.yml: |-
        kubernetes:
          podAnnotations:
            iam.amazonaws.com/role: {{ terraform.helm.spinnaker.iam_role }}
            prometheus.io/scrape: "true"
            prometheus.io/path: "/prometheus_metrics"
            prometheus.io/port: "8008"

      gate-local.yml: |-
        kubernetes:
          podAnnotations:
            iam.amazonaws.com/role: {{ terraform.helm.spinnaker.iam_role }}
            prometheus.io/scrape: "true"
            prometheus.io/path: "/prometheus_metrics"
            prometheus.io/port: "8008"
...
```
