### ISSUE TITLE
halyard LDAP config doesn't support all possible properties gate LDAP config offers

### ISSUE THREAD

**Issue by jfillo** [spinnaker/spinnaker#3268]
### Issue Summary:
Taken from this exchange in Slack: https://spinnakerteam.slack.com/archives/C99CEV2MA/p1535034864000100

Gate LDAP configuration allows for the following properties to be defined:
```
ldap.enabled
ldap.url
ldap.managerDn
ldap.managerPassword
ldap.groupSearchBase
ldap.userDnPattern
ldap.userSearchBase
ldap.userSearchFilter
```
https://github.com/spinnaker/gate/blob/master/gate-web/src/main/groovy/com/netflix/spinnaker/gate/security/ldap/LdapSsoConfig.groovy#L135

However, Halyard only allows the following properties:
```
ldap.enabled
ldap.url
ldap.userDnPattern
ldap.userSearchBase
ldap.userSearchFilter
```
https://github.com/spinnaker/halyard/blob/master/halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/LdapConfig.java#L28

So for 
```
ldap.managerDn
ldap.managerPassword
ldap.groupSearchBase
```
the only way to ensure gate has access to these properties is to specify them manually set them in:
**gate-local.yml**
```yml
ldap:
  managerDn: xxx
  managerPassword: xxx
  groupSearchBase: xxx
```

Halyard should be correct to allow for the setting of these values and the documentation at https://www.spinnaker.io/setup/security/authentication/ldap/ should be updated to indicate these fields can be set

### Cloud Provider(s):
Any

### Environment:
Tested using halyard to deploy spinnaker to a k8s v2 provider account

### Feature Area: 
Halyard

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 51 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by jfillo** [comment]
@spinnakerbot remove-label stale

Definitely should still be done. If the prefered way of installing/configuring Spinnaker is via Halyard I think it should be *required* to ensure this type of parity.

**Comment by atlaskerr** [comment]
As a first-timer setting up LDAP, its really confusing that halyard doesn't have flags to do authenticated bind to and LDAP server. I spent a lot of time learning halyard thinking I was doing something wrong.

I would love to see a full LDAP config in halyard!

**Comment by wuzhihui1123** [comment]
**i have the same problem , this is my install script**

![image](https://user-images.githubusercontent.com/4246626/49564152-872dca80-f95d-11e8-83fa-f1cb0ebe2e05.png)

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by madamczyk-tbscg** [comment]
Same here, +1

**Comment by jlact** [comment]
Just spent longer than needed trying to work around the fact authn doesn't support manager creds while authz does. This really needs addressing as it's very misleading. The gate-local.yml workaround works fine, but shouldn't be required.

**Comment by hsmith90** [comment]
The docs should definitely reflect that, while there are flags for the mangerDn and password, as well as the searchBase & filter, they aren't actually working yet. They don't update the config files in the actual `gate` deployment. This is VERY misleading, and the docs should be updated to reflect that you need to use the `gate-local.yml` workaround until these flags are fully implemented.

**Comment by hsmith90** [comment]
For anyone needing explicit instructions for the `gate-local.yml` workaround:

1. `hal config security authn ldap enable`
2. Create `.hal/default/profiles/gate-local.yml`
3. Fill it as follows:

```
ldap:
    enabled: true
    url: ldaps://my.ldap-domain.com:636/DC=ldap-domain,DC=com
    userSearchBase: OU=Users,OU=ArbitraryOU
    userSearchFilter: (&(objectClass=user)(sAMAccountName={0}))
    managerDn: CN=svc_spinnaker,OU=service accounts,DC=ldap-domain,DC=com
    managerPassword: Sup3rSecure!
```

Make sure your `.hal/config` only contains the following for the authn ldap portion:
```
    authn:
      ldap:
        enabled: true
      enabled: true 
```

Note that this solution is required if:
1. Your users are in multiple branches/OUs
2. The CN/uid is not the username they usually use (in my company's case, we use sAMAccountName for the username, and CN for the user's full name)

Many thanks to Sergii on the Spinnaker Slack #auth channel for helping me figure this out.
