### ISSUE TITLE
Unknown user error occurred with kubernetes RBAC.

### ISSUE THREAD

**Issue by katsew** [spinnaker/spinnaker#3270]
### Issue Summary:

When I deployed Deployment manifest via kubernetes cloud provider v2, I scale replicas from UI, then the following error occurred.

```
Failed to scale deployment/xxxxxxxxxx from xxx: Error from server (Forbidden): 
deployments.extensions "xxxxxxxxxx" is forbidden: User 
"system:serviceaccount:spinnaker:spinnaker-service-account" cannot get 
deployments.extensions/scale in the namespace "xxxxxx": Unknown user 
"system:serviceaccount:spinnaker:spinnaker-service-account"
```

### Cloud Provider(s):
kubernetes v2

### Environment:

Spinnaker: v1.9.0

GKE
master: 1.10.6-gke.1
nodepool: 1.10.6-gke.1

### Steps to Reproduce:

1. Create a GKE cluster with RBAC enabled.
1. Create a service account (described in [here](https://www.spinnaker.io/setup/install/providers/kubernetes-v2/#optional-configure-kubernetes-roles-rbac) )
2. Create a pipeline that deploys manifest
3. Execute pipeline and create Deployment
4. Select ServerGroupManagerAction for Deployment and click on `Scale`
5. Increment number of replicas, then submit

### Additional Details:

We can scale replicas by using `kubectl`, but not from Spinnaker UI.

Update: 

I tried to deploy manifest of ConfigMap, but the same error occurred.
I don't know it's relevant to this issue, but here is the manifest that I failed to deploy.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: foo
  namespace: dev
  labels:
    app: test
data:
  TEST: "yes"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bar
  namespace: dev
  labels:
    app: test
data:
  TEST: "no"
```
