### ISSUE TITLE
Halyard AWS defaults causes unexpected IndexOutOfRangeException

### ISSUE THREAD

**Issue by perek** [spinnaker/spinnaker#3280]
### Issue Summary:
Previously providers could specify empty regions and set the default in another key

### Cloud Provider(s):
AWS

### Environment:
GCP

### Feature Area: 
Halyard Deck Deployment

### Description:
This commit breaks configs which previously worked:https://github.com/spinnaker/halyard/commit/8376dfa069a00a2ae51dbc9b64a49f90c5b0637c#diff-9ed4a568a1ad414eaeecbcd163cddbceR157

It blindly assumes that key 0 is set which causes a back indexOutOfRange exception in deploy apply which is hard to debug

### Steps to Reproduce:
config like this breaks:
```
aws:
      enabled: true
      accounts:
      - name: spinnaker-test
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        accountId: 'ID'
        regions:[]
```

I fixed for now by setting a region:
```
aws:
      enabled: true
      accounts:
      - name: spinnaker-test
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        accountId: 'ID'
        regions:
        - us-west-2
```

### Additional Details:

A fix could be to check for an empty key as this field is not required for proper operation
