### ISSUE TITLE
Support "traffic.spinnaker.io/load-balancers" annotation in manifest

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#3377]
This will inform spinnaker which:

1. load balancers (typically services) to attach to a resource during a deployment, and
2. labels to add/remove during enable/disable

The format will likely be

```yaml
annotations:
  traffic.spinnaker.io/load-balancers: ["service my-service", "service, my-canary-service"]
...
```

@danielpeach fyi
