### ISSUE TITLE
Can’t add a Google Kubernetes cluster to Spinnaker 

### ISSUE THREAD

**Issue by alex25555** [spinnaker/spinnaker#3384]
### Issue Summary:
We have a Spinnaker Google Kubernetes deployment to which we would like to add a Google Kubernetes Cluster to. I'm following the steps listed in the following doc to add a K8 cluster.  

https://www.spinnaker.io/setup/quickstart/halyard-gke-deploy-rbac/

However, Hal attempts to deploy a Spinnaker installation where as we want to add a Google Kubernetes cluster to use with Spinnaker. 

During which time, `hal deploy connect` fails with the following.  It appears that the hal configurations are incorrect. 

I would really appreciate help with this. Thank you 

K8 account for Spinnaker 'k8s-spinnaker-test7-account'
K8 account for cluster to be managed by Spinnaker 'spin-deploy7-account'

hal deploy connect
+ Get current deployment
  Success
- Connect to Spinnaker deployment.
  Failure
Problems in Global:
! ERROR No instances running in latest server group for service
  spin-deck in namespace spinnaker
- Failed to generate connection script.

Hal configuration file:
```
currentDeployment: default
deploymentConfigurations:
- name: default
  version: 1.9.4
  providers:
    appengine:
      enabled: false
      accounts: []
    aws:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
    azure:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      clusters: []
    dockerRegistry:
      enabled: true
      accounts:
      - name: local-docker-registry1
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        address: https://xxxxxx
        email: fake.email@spinnaker.io
        cacheIntervalSeconds: 300
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories: []
      primaryAccount: local-docker-registry1
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        useInternalIp: false
    kubernetes:
      enabled: true
      accounts:
      - name: k8s-spinnaker-test7-account
        requiredGroupMembership: []
        providerVersion: V2
        permissions: {}
        dockerRegistries: []
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        oauthScopes: []
        oAuthScopes: []
      - name: spin-deploy7-account
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        dockerRegistries:
        - accountName: local-docker-registry1
          namespaces: []
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        oauthScopes: []
        oAuthScopes: []
    openstack:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
    oracle:
      enabled: false
      accounts: []
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: spin-deploy7-account
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    customSizing: {}
    gitConfig:
      upstreamUser: spinnaker
    haServices:
      clouddriver:
        enabled: false
      echo:
        enabled: false
  persistentStorage:
    persistentStoreType: gcs
    azs: {}
    gcs:
      rootFolder: front50
      bucketLocation: us
    redis: {}
    s3:
      rootFolder: front50
    oracle: {}
  features:
    auth: false
    fiat: false
    chaos: false
    entityTags: false
    jobs: false
    artifacts: true
  metricStores:
    datadog:
      enabled: false
    prometheus:
      enabled: false
      add_source_metalabels: true
    stackdriver:
      enabled: false
    period: 30
    enabled: false
  notifications:
    slack:
      enabled: false
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: false
      masters: []
    travis:
      enabled: false
      masters: []
   wercker:
      enabled: false
      masters: []
  security:
    apiSecurity:
      ssl:
        enabled: false
    uiSecurity:
      ssl:
        enabled: false
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: false
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: false
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
        ldap:
          roleProviderType: LDAP
      enabled: false
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    gitlab:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []
  pubsub:
    google:
      enabled: false
      subscriptions: []
  canary:
    enabled: false
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: false
      accounts: []
    - name: datadog
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    reduxLoggerEnabled: true
    defaultJudge: NetflixACAJudge-v1.0
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true
```

### Cloud Provider(s):
Google Cloud Platform
