### ISSUE TITLE
Kubernetes custom resources that have the same kind as a built-in resource are not cached

### ISSUE THREAD

**Issue by willgorman** [spinnaker/spinnaker#3387]
### Issue Summary:

When a CRD has the same `kind` as a built-in resource type, `KubernetesUnregisteredCustomResourceCachingAgent` appears to cache resources of the built-in resource type instead of the custom resource.  

### Cloud Provider(s):

Kubernetes V2

### Feature Area: 

Deploy Manifest

### Description:

In our Kubernetes cluster we are using Calico network policies.  When we attempt to deploy a manifest containing a Calico network policy, the stage times out while waiting for the manifest to stablize.  An example of the manifest:

```yaml
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: log-then-deny
spec:
  selector: all()
  order: 1100
  egress:
  - action: log
  - action: deny
  ingress:
  - action: log
  - action: deny
```

When we look at the keys in the cache, we don't see anything for the `KubernetesUnregisteredCustomResourceCachingAgent` that appears related to these policies.  However, we do see keys that indicate that `networkpolicies.networking.k8s.io` network policies are being cached by the custom resource caching agent.    It seems like the custom resource caching agent might need to also use the group in addition to the kind for finding resources.  In the case of the Calico policies, that part of the CRD looks like

```
  group: crd.projectcalico.org
  names:
    kind: NetworkPolicy
    listKind: NetworkPolicyList
    plural: networkpolicies
    singular: networkpolicy
```
The resources can be loaded by kubectl with `kubectl get networkpolicies.crd.projectcalico.org`

---

**Comment by lwander** [comment]
What happens if you set the kind in the manifest to `networkpolicies.networking.k8s.io`?

**Comment by lwander** [comment]
Whoops, typo on my end, I meant `networkpolicies.crd.projectcalico.org`. I'm wondering if we need to scope kinds by their full group & kind for CRDs to be disambiguated.

**Comment by willgorman** [comment]
With `networkpolicies.crd.projectcalico.org` the same thing happens but with `Unsupported Kubernetes object kind 'networkpolicies.crd.projectcalico.org', unable to continue.` as the error.  I'm going to try getting `KubernetesUnregisteredCustomResourceCachingAgent` to include the group in addition to the kind.

**Comment by lwander** [comment]
I think this will be kind-of hairy, most lookups are just a namespace, kind and name pair. If we can overload kind to include the group in all but the manifest for all codepaths this should be fixable.

**Comment by willgorman** [comment]
@lwander With https://github.com/cerner/clouddriver/commit/68b4a784aa31f596f4c18693f80a37d54c521fac the calico network policy gets cached and the wait for manifest to stabilize task completes.  Based on your comment though, it sounds like this probably doesn't do everything that needs to be done.    Is there anything else you can think of that I should test with this change?

**Comment by lwander** [comment]
I'm surprised that works since at a few points the kind in the manifest (NetworkPolicy) is used to lookup the cached kind (networkpolicies.crd.projectcalico.org). Are you able to load that manifest using the /manifest controller in clouddriver?

**Comment by tillig** [comment]
I may be running into something related. I'll explain what I see here and if it doesn't sound like the same thing, I'd be happy to open a separate/new issue. (In which case, sorry for derailing things here.)

Using Spinnaker 1.9.5 deployed via Halyard.

I'm deploying apps that involve Istio entities. Istio has [a lot of custom resource definitions](https://raw.githubusercontent.com/istio/istio/release-1.0/install/kubernetes/helm/istio/templates/crds.yaml). I'm trying to deploy a `DestinationRule` defined as such:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: destinationrules.networking.istio.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: istio-pilot
spec:
  group: networking.istio.io
  names:
    kind: DestinationRule
    listKind: DestinationRuleList
    plural: destinationrules
    singular: destinationrule
    categories:
    - istio-io
    - networking-istio-io
  scope: Namespaced
  version: v1alpha3
```

My manifest works fine via `kubectl apply` and it also _usually_ works when using the "Deploy (Manifest)" step in Spinnaker.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: calculator
  namespace: calculator
  labels:
    app: calculator
spec:
  host: calculator
  subsets:
  - name: canary
    labels:
      track: canary
  - name: production
    labels:
      track: production
```

What I've found is that, at some point (I can't exactly determine when) I start getting the following message when this manifest gets deployed:

`Unsupported Kubernetes object kind 'DestinationRule', unable to continue.`

I tried the thing above and switched to `destinationrules.networking.istio.io` but that just gave the same error.

`Unsupported Kubernetes object kind 'destinationrules.networking.istio.io', unable to continue.`

I tried forcing a config refresh via `http://localhost:7002/config-refresh` and I see in the logs that the `DestinationRule` is found...

```
spin-clouddriver-67885cf9b5-z8pg5 clouddriver 2018-10-08 19:24:18.276  INFO 1 --- [ecutionAction-4] s.c.k.v.c.a.KubernetesCacheDataConverter : MYACCOUNTNAME/KubernetesUnregisteredCustomResourceCachingAgent[1/1]: grouping DestinationRule has 3 entries and 4 relationships
```

...but it _still_ won't deploy.

**Killing the Clouddriver pod and forcing it to redeploy itself works.** This is the only thing I can figure out so far that allows my manifest to be deployed again. Works great for... a little less than 10 minutes. Then it forgets what a `DestinationRule` is again and requires the Clouddriver pod to be killed.

Is this related or should I file a new issue?
