### ISSUE TITLE
The application tab displays `No matches found for ''`

### ISSUE THREAD

**Issue by wadadli** [spinnaker/spinnaker#3431]
### Issue Summary:
The application tab displays `No matches found for ''`

### Cloud Provider(s):
Kubernetes

### Environment:
Vanilla.  I just deployed to GKE following the instructions on the website.
Both GKE clusters are v1.10.6-gke.2 

### Feature Area: 
Deck

### Description:
After a fresh spinnaker deploy, spinnaker lists all of the applications that exist in the cluster and the account (cluster) they are on.  If `hal deploy connect` is ended or the page is refreshed, all applications disappear and `No matches found for ''` is displayed, old applications that were once clicked on are still displayed under the  `Recently viewed` heading, but clicking them leads to this message:

```
Application Not Found

Please check your URL - we can't find any data for spinnaker.
```

### Steps to Reproduce:
Deploy Spinnaker v1.9.5 using hal and the instructions on the main website, add a gcs bucket as an artefact store, end a `hal deploy connect` session or refresh the page.

### Additional Details:
```
kubernetes:
    enabled: true
    accounts:
    - name: prod-k8s-gke
      environment: prod
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: cota_prod
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces:
      - default
      - kube-system
      omitNamespaces: []
      kinds:
      - prod
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /home/michael/.kube/config
      oauthScopes: []
      oAuthScopes: []
    - name: infra-k8s-gke
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: cota_infra
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces:
      - default
      - kube-system
      - spinnaker
      omitNamespaces: []
      kinds:
      - infra
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /home/michael/.kube/config
      oauthScopes: []
      oAuthScopes: []
    primaryAccount: prod-k8s-gke
```
