### ISSUE TITLE
Add trigger won't populate the Subscription Name popup

### ISSUE THREAD

**Issue by tsantos** [spinnaker/spinnaker#3444]
### Issue Summary:

My goal is to add a trigger to a pipeline that triggers based on changes to Google Container Registry. The "Subscription Name" popup never populates with entries. The "System Type" popup shows an item called "google' but nothing in "Subscription Name".

I've been following the directions on the page: https://www.spinnaker.io/setup/triggers/google/

### Cloud Provider(s):

Google Cloud Platform

### Environment:

Spinnaker 1.9.5 running with v2 provider in a Google Kubernetes Engine cluster. Halyard 1.11.

### Feature Area: 

Pipelines

### Description:

As per the process described in the docs above, I expect to see "my-google-pubsub" in the Subscription Name popup. I do not see any items in the Subscription Name popup.

### Steps to Reproduce:

1. Follow the instructions for GCR (and creds and editiing) on this page: https://www.spinnaker.io/setup/triggers/google/

2. Run `hal deploy apply`.

3. Go to a pipeline and select "Add Trigger".

4. In "Type" select "Pub/Sub"

5. In "Pub/Sub System Type" select "google"

6. Go to "Subscription Name" and there are no subscriptions to select from

#### Here are the artifacts that I think are pertinent to the issue:

1. This is the section for pubsub in my .hal/config file:

```
  pubsub:
    enabled: true
    google:
      enabled: true
      subscriptions:
      - name: my-google-pubsub
        project: my-project
        subscriptionName: acme-gcr
        jsonPath: /home/someone/.gcp/pubsub-account.json
        ackDeadlineSeconds: 10
        messageFormat: GCR
```

2. The keys in pubsub-account.json match the ones associated with my spinnaker-pubsub-account.

3. This is what the GUI shows when I try to find a subscription:
![image](https://user-images.githubusercontent.com/79223/46827985-dd600200-cd4e-11e8-9649-7db51cb33215.png)

4. My service account has Pub/Sub subscriber:
```
$ gcloud projects add-iam-policy-binding $PROJECT --role roles/pubsub.subscriber --member serviceAccount:$SA_EMAIL
members:
  - serviceAccount:spinnaker-pubsub-account@my-project.iam.gserviceaccount.com
  role: roles/pubsub.subscriber
```

5. The subscription exists:
```
$ gcloud pubsub subscriptions list
---
ackDeadlineSeconds: 10
messageRetentionDuration: 604800s
name: projects/my-project/subscriptions/acme-gcr
pushConfig: {}
topic: projects/my-project/topics/gcr
```
