### ISSUE TITLE
Error Fetching Clouddriver-3-4-5-20180927041608 While Deploying to GKE

### ISSUE THREAD

**Issue by sbwsg** [spinnaker/spinnaker#3446]
### Issue Summary:

From @anup13kumar:

Im trying to set up spinnaker in gcp kubernetes cluster [distributed] google compute engine but while running sudo hal deploy apply I'm getting below error:

```
Apply deployment
Failure
Problems in Global:
! ERROR Failed to create instance template for
projects/marketplace-spinnaker-release/global/images/spinnaker-clouddriver-3-4-5-20180927041608:
404 Not Found
{
"code" : 404,
"errors" : [ {
"domain" : "global",
"message" : "The resource
'projects/marketplace-spinnaker-release/global/images/spinnaker-clouddriver-3-4-5-20180927041608'
was not found",
"reason" : "notFound"
} ],
"message" : "The resource
'projects/marketplace-spinnaker-release/global/images/spinnaker-clouddriver-3-4-5-20180927041608'
was not found"
}

Failed to deploy Spinnaker.
```

**Comment by sbwsg** [comment]
@anup13kumar

Can you provide a sanitized copy of your hal config? Run `hal config -q --no-validate` and remove any sensitive information before posting here.

Further, can you describe in a bit more detail the following things:

1. Where are you running Halyard?  A GCE VM?  A k8s Pod?
2. What version of Halyard are you running?

**Comment by sbwsg** [comment]
Also, can you confirm whether the issue is still happening?  I've just deployed Spinnaker 1.9.5, which uses clouddriver-3-4-5, and did not experience any problems.

Please provide the complete log output from `hal deploy apply --debug`.

**Comment by anup13kumar** [comment]
Hello @sbwsg ,

Thanks for immediate response..
Info:
1.GCP : cloud provider
2.GCS : storage
3.Enviornment : distrubuted (GCP kubernetes cluster)

Here i am giving details as requested:

Further, can you describe in a bit more detail the following things:
Where are you running Halyard? A GCE VM? A k8s Pod?: -->**_EC2 instance , Ubuntu 16.04_** 
What version of Halyard are you running? -->**_1.8.0_**

**********************************************************************************
hal config -q --no-validate
name: default
version: 1.9.5
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: false
    accounts: []
  google:
    enabled: true
    accounts:
    - name: workshop3
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      project: workshop3-cici
      jsonPath: /home/ubuntu/.gcp/gcs-account-wks3.json
      alphaListed: false
      imageProjects: []
      consul:
        enabled: false
        agentEndpoint: localhost
        agentPort: 8500
        datacenters: []
    primaryAccount: workshop3
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: false
    accounts: []
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
  accountName: workshop3
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  gitConfig:
    upstreamUser: spinnaker
  haServices:
    clouddriver:
      enabled: false
    echo:
      enabled: false
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: /home/ubuntu/.gcp/gcs-account-wks3.json
    project: workshop3-cici
    bucket: spin-wks3
    rootFolder: front50
    bucketLocation: us
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
metricStores:
  datadog:
    enabled: false
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
  wercker:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
      ldap:
        roleProviderType: LDAP
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true

**************************************************************************************
[apply debug log.txt](https://github.com/spinnaker/spinnaker/files/2473787/apply.debug.log.txt)

Please help me in this 

Thanks,
Anup

**Comment by sbwsg** [comment]
Great, thanks, just adding a comment to wrap the hal config in backticks so it gets indented nicely:

hal config -q --no-validate
```
name: default
version: 1.9.5
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: false
    accounts: []
  google:
    enabled: true
    accounts:
    - name: workshop3
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      project: workshop3-cici
      jsonPath: /home/ubuntu/.gcp/gcs-account-wks3.json
      alphaListed: false
      imageProjects: []
      consul:
        enabled: false
        agentEndpoint: localhost
        agentPort: 8500
        datacenters: []
    primaryAccount: workshop3
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: false
    accounts: []
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
  accountName: workshop3
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  gitConfig:
    upstreamUser: spinnaker
  haServices:
    clouddriver:
      enabled: false
    echo:
      enabled: false
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: /home/ubuntu/.gcp/gcs-account-wks3.json
    project: workshop3-cici
    bucket: spin-wks3
    rootFolder: front50
    bucketLocation: us
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
metricStores:
  datadog:
    enabled: false
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
  wercker:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
      ldap:
        roleProviderType: LDAP
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true
```
