### ISSUE TITLE
Ace editor often unusable in release candidate

### ISSUE THREAD

**Issue by lwander** [spinnaker/spinnaker#3452]
When pasting in yaml, and attempting to make edits, the editor behaves unpredictably (often adding duplicate characters, ignoring keystrokes, etc...)

Here is what I see in the chrome console:
```
webpack:///./node_modules/angular/angular.js?:14525 Error loading YAML from string apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: frontend
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: 'nginx:1.15.4'
          name: nginx
          ports:
            - containerPort: 80

----:  YAMLException
(anonymous) @ webpack:///./node_modules/angular/angular.js?:14525
webpack:///./app/scripts/modules/kubernetes/src/v2/manifest/yaml/YamlEditor.tsx?:31 Uncaught TypeError: Cannot read property 'column' of undefined
    at Object.YamlEditor.handleChange [as onChange] (webpack:///./app/scripts/modules/kubernetes/src/v2/manifest/yaml/YamlEditor.tsx?:31)
    at ReactAce.onChange (webpack:///./node_modules/react-ace/lib/ace.js?:267)
    at Editor.EventEmitter._signal (webpack:///./node_modules/brace/index.js?:3865)
    at Editor.onDocumentChange (webpack:///./node_modules/brace/index.js?:13292)
    at EditSession.EventEmitter._signal (webpack:///./node_modules/brace/index.js?:3865)
    at EditSession.onChange (webpack:///./node_modules/brace/index.js?:9805)
    at Document.EventEmitter._signal (webpack:///./node_modules/brace/index.js?:3865)
    at Document.applyDelta (webpack:///./node_modules/brace/index.js?:7955)
    at Document.remove (webpack:///./node_modules/brace/index.js?:7865)
    at EditSession.remove (webpack:///./node_modules/brace/index.js?:10325)
```

**Comment by danielpeach** [comment]
Can you give a more clear example? I can copy + paste the yaml in the error you've given without a problem.

**Comment by lwander** [comment]
It doesn't happen immediately, it's usually after a minute or so of editing have happened that I start to see problems.

**Comment by mbasc** [comment]
in case related symptoms - we've been seeing some editor issues related to copy and paste, and with dashes. both are avoidable (using artifacts), but in case it helps on repro.

pasted data not updated:
if you ctrl-a in the editor then ctrl-v to paste yaml from the clipboard, the save button does not show up. if you modify another field on the page like comments, the save button shows up, but pasted changes are not applied - any changes prior to your ctrl-v will persist though.

'---':
adding '---' on a new line, the coursor will jump to '--HERE-'. if you then return and start typing, it cascades down as if insert is off, eg:

    ---
    helloworld-
    helloworl-
    hellowor-
    hellowo-
    hello-
    hell-
    hel-
    he-
    h-
    -

**Comment by lwander** [comment]
I can pretty reliably cause the editor to break now by just copy-pasting anything into the stage config for the manifest editor. This doesn't happen when submitting an ad-hoc action on the clusters tab.

**Comment by lwander** [comment]
Seems now the editor disappears when pasting more than manifest into the pipeline editor. Try the following:

```yaml
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    tier: frontend
  annotations:
    traffic.spinnaker.io/load-balancers: '["service my-service"]'
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/google_samples/gb-frontend:v3
```
