### ISSUE TITLE
kubernetes provider support kubernetes  "Endpoints" object

### ISSUE THREAD

**Issue by kevincai** [spinnaker/spinnaker#3525]
### Issue Summary:
given a kubernetes yaml to create an object with 'Kind: Endpoints", spinnaker rejected with `Unsupported Kubernetes object kind 'Endpoints', unable to continue.`

### Cloud Provider(s):
Kubernetes V2

### Environment:
Running spinnnaker 1.10.1 on Kubernetes, and manage deployments on the same kubernetes cluster.

### Feature Area: 
Pipelines

### Description:
Expect spinnaker can create Kubernetes `Endpoints` object successful.

### Steps to Reproduce:

Following config as example, put into spinnaker Deploy stage
```yaml
---
apiVersion: v1
kind: Endpoints
metadata:
  name: redis-master
  namespace: default
subsets:
- addresses:
  - ip: 172.20.217.206
  ports:
  - port: 6379
    protocol: TCP
```

**Comment by elvis-cai** [comment]
same on 1.11.0 
Exception ( Monitor Deploy )
Unsupported Kubernetes object kind 'Endpoints', unable to continue.

**Comment by atanner27** [comment]
We are also facing this same issue

**Comment by lwander** [comment]
Placing 

```yaml
...
name: my-k8s-v2-account
customResources:
  - kubernetesKind: endpoint
...
```

into your account config for the account that needs to deploy endpoint objects is a workaround.
