### ISSUE TITLE
1.10.x broke login using oauth (or authz, not sure which)

### ISSUE THREAD

**Issue by thecodejunkie** [spinnaker/spinnaker#3530]
### Issue Summary:
After upgrading to 1.10.0 or 1.10.1 I am no longer able to sign into Spinnaker using OAuth

### Cloud Provider(s):
Google Cloud

### Environment:
1.10.0 and 1.10.1

### Feature Area: 
Gate

### Description:
I have a Spinnaker 1.9.3 (also tested that it still works in 1.9.5) server up and running that is configured to do Authentication against a GitHub Enterprise setup (using OAuth) and that as Authorization setup so that is it restricted to a single team. The server is public facing, i.e it has overridden the base URLs and and accessible on a domain name.

After upgrading to either 1.10.0 or 1.10.1 I an no longer able to sign in. I just end up with the following error message

```
{
  "error": "Internal Server Error",
  "exception": "com.netflix.spinnaker.gate.services.commands.ServerErrorException",
  "message": "Internal Server Error",
  "status": 500,
  "timestamp": 1540911193735
}
```

Reverting back to 1.9.3 or 1.9.5 removes the problem and I am able to sign in again. It seems something was broken between the 1.9.x and 1.10.x code bases

### Additional Details:
The way I've configured auth against our GitHub Enterprise is by doing the following

```
CLIENT_ID=<clientId>
CLIENT_SECRET=<clientSecret>
PROVIDER=github

hal config security authn oauth2 edit \
  --client-id $CLIENT_ID \
  --client-secret $CLIENT_SECRET \
  --provider $PROVIDER
```

1. `cd` into `~/.hal/default/profiles``
2. Run `vim gate-local.yaml` and enter

```
security:
  oauth2:
    enabled: true
    client:
      accessTokenUri: https://<<url to our github enerprise>>/login/oauth/access_token
      userAuthorizationUri: https://<<url to our github enerprise>>/login/oauth/authorize
    resource:
      userInfoUri: https://<<url to our github enerprise>>/api/v3/user
```

And also enabled it

```
hal config security authn oauth2 enable
```
