### ISSUE TITLE
Stage 'Bake (Manifest)' ignores namespace

### ISSUE THREAD

**Issue by nitrogear** [spinnaker/spinnaker#3532]
### Issue Summary:
Stage 'Bake (Manifest)' ignores namespace

### Cloud Provider(s):
AWS, Kubenetes

### Environment:
Spinnaker 1.9.5

### Feature Area: 
Bakery

### Description:
Stage 'Bake (Manifest)' generates YAML for service and deployment using wrong namespace, it ignores value 'namespace' and helm package always is deployed to namespace 'spinnaker'

### Steps to Reproduce:
https://www.spinnaker.io/guides/user/kubernetes-v2/deploy-helm/
1. Create a new pipeline, configure expected artifact (helm package on s3/http)
2. Create 'Bake (Manifest)' stage, configure it to prepare manifest from artifact and deploy it to any namespace and produce base64 artifact
3. Create 'Deploy (Manifest)' stage and configure it to use previously created artifact

### Additional Details:
Bake stage looks as follows:
```
{
  "expectedArtifacts": [
    {
      "defaultArtifact": {},
      "id": "94a35f0f-3549-49a0-ba6b-142d935447a8",
      "matchArtifact": {
        "kind": "base64",
        "name": "assetservice-testing",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": false
    }
  ],
  "inputArtifacts": [
    {
      "account": "http-account",
      "id": "db0bb34b-ce9f-48d1-983a-5e396b610bc1"
    },
    {
      "account": "http-account",
      "id": "029352fb-c695-49d3-b05e-c6d9850964b1"
    }
  ],
  "name": "Bake (Manifest)",
  "namespace": "testing",
  "outputName": "assetservice-testing",
  "overrides": {},
  "templateRenderer": "HELM2",
  "type": "bakeManifest"
}
```

Example of generates service (from Deploy Status of failed pipeline)
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    artifact.spinnaker.io/location: spinnaker
    artifact.spinnaker.io/name: assets-service
    artifact.spinnaker.io/type: kubernetes/service
    moniker.spinnaker.io/application: assetservice
    moniker.spinnaker.io/cluster: service assets-service
  labels:
    app: assets-service
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: assetservice
    chart: assets-service-2018.43.6-af29aaf
    heritage: Tiller
    release: assetservice-testing
  name: assets-service
  namespace: spinnaker
spec:
  ports:
    - name: assets-service
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: assets-service
    release: assetservice-testing
  type: ClusterIP
```
