### ISSUE TITLE
Not able to set security oauth properties using Halyard

### ISSUE THREAD

**Issue by thecodejunkie** [spinnaker/spinnaker#3542]
### Issue Summary:
Unable to set OAuth2 related properties using Halyard 1.12. I have a suspicion that the values are set but not displayed correctly  

### Cloud Provider(s):
Google Cloud

### Environment:
Installed on a Google Cloud VM

### Feature Area: 
Halyard 1.12.0-20181024113436

### Description:
I've been using a `gate-local.yml` file to specify the properties below, however I thought I'd get rid of that file and configure them using `hal config security authn oauth2 edit` instead. However when I try to set any of the values, HAL tell me 

```
+ Get current deployment
  Success
+ Get authentication settings
  Success
+ Edit oauth2 authentication settings
  Success
+ Successfully edited oauth2 method.
```

But when I check `hal config` they still have their default values (I've removed values that aren't relevant to the bug report)

```
security:
  authn:
    oauth2:
      client:
        accessTokenUri: https://github.com/login/oauth/access_token
        userAuthorizationUri: https://github.com/login/oauth/authorize
      resource:
        userInfoUri: https://api.github.com/user
```

That said, I have a suspicion that the values are set but just not displayed correctly. The reason I suspect this is that even if I've configured them in `~/.hal/default/profiles/gate-local.yaml` and run `hal config` then they're still left at their default values, but if I apply them to my Spinnaker then it functions as expected.

I have not tried to remove my `gate-local.yaml` file, apply the values using `hal config security authn oauth2 edit` and deploy the configuration. I do not want to break my Spinnaker instance.

### Steps to Reproduce:
Run `hal config security authn oauth2 edit` with any of the following properties and provide a URL

- `--access-token-uri`
- `--user-authorization-uri `
- `--user-info-uri`

Check `hal config` and notice that the properties still have their default values
  
### Additional Details:
I can set others values just fine, like `--client-secret` and `--client-id` and their values are displayed correct by `hal config`
