### ISSUE TITLE
Defining Baseline + Canary Server Groups throws a JavaScript error

### ISSUE THREAD

**Issue by thecodejunkie** [spinnaker/spinnaker#3546]
### Issue Summary:
Clicking the `Create baseline / canary pair` button, while defining a new `Canary Analysis` stage, throws a JavaScript error. This makes is impossible to setup automated canary analysis.

### Cloud Provider(s):
Google Cloud (running 

### Environment:
Spinnaker 1.10.1

### Feature Area: 
Canary / Kayenta

### Description:
When I click the `Create baseline / canary pair` button, on a `Canary Analysis` stage, I end up with a JavaScript error which makes it impossible to proceed with the canary configuration.

```
Uncaught (in promise) Error: No "serverGroup.commandBuilder" service found for provider "undefined"
    at ProviderServiceDelegate.getDelegate (providerService.delegate.ts:21)
    at ServerGroupCommandBuilderService.getDelegate (serverGroupCommandBuilder.service.ts:145)
    at ServerGroupCommandBuilderService.buildNewServerGroupCommandForPipeline (serverGroupCommandBuilder.service.ts:166)
    at KayentaStageController.<anonymous> (lib.js:7789)
    at tryCatch (runtime.js:65)
    at Generator.invoke [as _invoke] (runtime.js:303)
    at Generator.prototype.(/anonymous function) [as next] (https://[REDACTED]/vendors~app.js?b04b558c6a2ea3e9b2e4:136770:21)
    at fulfilled (lib.js:7424)
```

I've verified this in my Spinnaker setup and in a Spinnaker setup that was created by following the https://cloud.google.com/solutions/automated-canary-analysis-kubernetes-engine-spinnaker guide (it ends up creating a 1.10.1 instance, but the material seems to be written for 1.9.x).

The last change to this feature seems to have been for 1.10.0 https://github.com/spinnaker/deck/pull/5747 which was created by @danielpeach and reviewed by @sbwsg 

### Steps to Reproduce:
1. Configure Kayenta support on your Spinnaker
2. Create a new pipeline
3. Add a `Canary Analysis` stage to your pipeline
4. Click the `Create baseline / canary pair` button under the `Baseline + Canary Server Groups` heading
5. Check the browse console for the error

### Additional Details:
1. This does not affect 1.9.5 since it appears that functionality was not in the 1.9.x code base
2. I've tried it on both Chrome (Stable + Dev channel) as well as on the latest stable FireFox release.

Please let me know if there is any additional information that I can provide. I've currently downgraded my Spinnaker to 1.9.5 because Deck + Canary seem to be a bitch sketchy in 1.10.x at the moment, but I am happy to bump the version if I can help with more testing

For the sake of completion, here is my canary configs

```
  canary:
    enabled: true
    serviceIntegrations:
    - name: google
      enabled: true
      accounts:
      - name: my-google-account
        project: [REDACTED]
        jsonPath: [REDACTED]
        bucket: [REDACTED]
        rootFolder: kayenta
        supportedTypes:
        - CONFIGURATION_STORE
        - METRICS_STORE
        - OBJECT_STORE
      gcsEnabled: true
      stackdriverEnabled: true
    - name: prometheus
      enabled: false
      accounts: []
    - name: datadog
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    reduxLoggerEnabled: true
    defaultJudge: NetflixACAJudge-v1.0
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true
```
