### ISSUE TITLE
Cannot create new server group because of JavaScript evaluation logic in Deck

### ISSUE THREAD

**Issue by MichaelMarkieta** [spinnaker/spinnaker#3559]
### Issue Summary:
Evaluating an undefined property throws an error. Cannot create new server group.

https://github.com/spinnaker/deck/blob/c046a1f43889c0ec5b475cb906aa4ae6cb5ca5f3/app/scripts/modules/kubernetes/src/cluster/configure/CommandBuilder.js#L41

`defaults.accounts` throws an error because `defaults === {}`

### Cloud Provider(s):
GCP + GKE

### Environment:
```
hal 1.12.0-20181024113436
spinnaker 1.10.1
```

### Feature Area: 
Deck

### Description:
```
hal 1.12.0-20181024113436
spinnaker 1.10.1
```

### Additional Details:
```
TypeError: Cannot read property 'account' of null
    at Object.buildNewClusterCommand (CommandBuilder.js:41)
    at Object.buildNewServerGroupCommand (CommandBuilder.js:11)
    at ServerGroupCommandBuilderService.buildNewServerGroupCommand (serverGroupCommandBuilder.service.ts:158)
    at allClusters.controller.js:108
    at processQueue (angular.js:16832)
    at angular.js:16876
    at Scope.$digest (angular.js:17971)
    at angular.js:18200
    at completeOutstandingRequest (angular.js:6274)
    at angular.js:6554 "Possibly unhandled rejection: {}"
```

**Comment by MichaelMarkieta** [comment]
```
KubernetesProviderSettings.defaults = {
    account: "my-k8s-account"
    instanceLinkTemplate: "{{host}}/api/v1/proxy/namespaces/{{namespace}}/pods/{{name}}"
    internalDNSNameTemplate: "{{name}}.{{namespace}}.svc.cluster.local"
    namespace: "default"
    proxy: "localhost:8001"
}
```

**Comment by sbwsg** [comment]
Thanks for the issue report.  It would be really helpful to know the specific actions you took in the UI that triggered this error.  Did it happen when you clicked the "Create Server Group" button in the Clusters view?  Or ran a pipeline to create a server group?

Could you also provide the sanitized output from `hal config -q --no-validate` if you're using Halyard to configure your Spinnaker deployment?

**Comment by MichaelMarkieta** [comment]
As a user, when I click on the "Create new server group" nothing happens. When I check the chrome console I am able to see the error.

As a user, I am able to create a Load Balancer. There doesn't seem to be an issue on that page in the UI.

```
name: default
version: 1.10.1
providers:
  appengine:
    enabled: false
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: true
    accounts:
    - name: my-docker-registry
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      address: https://gcr.io
      username: _json_key
      email: fake.email@spinnaker.io
      cacheIntervalSeconds: 30
      clientTimeoutMillis: 60000
      cacheThreads: 1
      paginateSize: 100
      sortTagsByDate: false
      trackDigests: false
      insecureRegistry: false
      repositories: []
      passwordFile: /home/admin/gcr-account.json
    primaryAccount: my-docker-registry
  google:
    enabled: true
    accounts:
    - name: my-gce-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      project: ***
      jsonPath: /home/admin/gce-account.json
      alphaListed: false
      imageProjects: []
      consul:
        enabled: false
        agentEndpoint: localhost
        agentPort: 8500
        datacenters: []
    primaryAccount: my-gce-account
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: true
    accounts:
    - name: my-k8s-account
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      dockerRegistries:
      - accountName: my-docker-registry
        namespaces: []
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /home/admin/.kube/config
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: false
    primaryAccount: my-k8s-account
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: oci.json
      baseImages: []
deploymentEnvironment:
  size: SMALL
  type: Distributed
  accountName: my-k8s-account
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  sidecars: {}
  gitConfig:
    upstreamUser: spinnaker
  haServices:
    clouddriver:
      enabled: false
      disableClouddriverRoDeck: false
    echo:
      enabled: false
persistentStorage:
  persistentStoreType: gcs
  azs: {}
  gcs:
    jsonPath: /home/admin/gcs-account.json
    project: ***
    bucket: ***
    rootFolder: front50
    bucketLocation: northamerica-northeast1
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
metricStores:
  datadog:
    enabled: false
    tags: []
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
  wercker:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
      ldap:
        roleProviderType: LDAP
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  oracle:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  enabled: false
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: signalfx
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true
```
