### ISSUE TITLE
! ERROR Failed to connect to appengine Admin API: 403 Forbidden

### ISSUE THREAD

**Issue by timini** [spinnaker/spinnaker#3569]
I have spinnaker installed on GCE using the deployment manager template here: https://github.com/GoogleCloudPlatform/spinnaker-deploymentmanager

I believe this installation method should setup halyard to use the compute engine default service account.

Once installation is complete I am trying to add appengine provider to my spinnaker machine, by following the instructions here https://www.spinnaker.io/setup/install/providers/appengine/

When i try and add the appengine account to hal i get the following error:
```
tr@spinnaker-spinnaker-2vkw:~$ hal config provider appengine account add staging-appengine --project=staging-omix-platform
+ Get current deployment
  Success
- Add the staging-appengine account
  Failure
Problems in default.provider.appengine.staging-appengine:
! ERROR Failed to connect to appengine Admin API: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Request had insufficient authentication scopes.",
    "reason" : "forbidden"
  } ],
  "message" : "Request had insufficient authentication scopes.",
  "status" : "PERMISSION_DENIED"
}.

- Failed to add account staging-appengine for provider
  appengine.
```
the service account for the compute engine instance runnign spinnaker (and hal) has the App engine Admin IAM role:
```
tr@spinnaker-spinnaker-2vkw:~$ gcloud config list
[core]
account = 420217292057-compute@developer.gserviceaccount.com
disable_usage_reporting = True
project = staging-omix-platform

Your active configuration is: [default]
```
![image](https://user-images.githubusercontent.com/247302/47964239-aec40700-e02e-11e8-9f8c-b28510495376.png)

**Comment by sbwsg** [comment]
I've moved this issue from the docs repo to spinnaker/spinnaker since it has to do with a configuration or other technical issue with the template.

**Comment by sbwsg** [comment]
I'm a bit confused.  I've just run through the steps outlined in https://github.com/GoogleCloudPlatform/spinnaker-deploymentmanager and I receive a VM that does *not* have Halyard installed.

Did you perform some work to install Halyard after the template was deployed?

Can you please provide the output from `hal config -q --no-validate`, with any sensitive information removed?

It would also be helpful if you could describe in a bit more detail all of the steps you went through to setup your VM.

**Comment by timini** [comment]
Thats correct, I setup my VM just using the intallation steps described on the deployment manager link. Once complete i sshed to the spinnaker compute engine VM and installed HAL on the VM using:
```
curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/debian/InstallHalyard.sh
sudo bash InstallHalyard.sh
hal config version edit --version $(hal version latest -q)
hal config provider appengine enable
```
This is the details of my hal config:
```
timrichardson@spinnaker-spinnaker-2vkw:~$ hal config -q --no-validate
OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
   7504
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

name: default
version: 1.10.1
providers:
  appengine:
    enabled: true
    accounts: []
  aws:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
    defaultKeyPairTemplate: '{{name}}-keypair'
    defaultRegions:
    - name: us-west-2
    defaults:
      iamRole: BaseIAMRole
  ecs:
    enabled: false
    accounts: []
  azure:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: azure-linux.json
      baseImages: []
  dcos:
    enabled: false
    accounts: []
    clusters: []
  dockerRegistry:
    enabled: false
    accounts: []
  google:
    enabled: false
    accounts:
    - name: staging-omix
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      project: staging-omix-platform
      alphaListed: false
      imageProjects: []
      consul:
        enabled: false
        agentEndpoint: localhost
        agentPort: 8500
        datacenters: []
    primaryAccount: staging-omix
    bakeryDefaults:
      templateFile: gce.json
      baseImages: []
      zone: us-central1-f
      network: default
      useInternalIp: false
  kubernetes:
    enabled: false
    accounts: []
  openstack:
    enabled: false
    accounts: []
    bakeryDefaults:
      baseImages: []
  oracle:
    enabled: false
    accounts: []
    bakeryDefaults:
      templateFile: oci.json
      baseImages: []
deploymentEnvironment:
  size: SMALL
  type: LocalDebian
  updateVersions: true
  consul:
    enabled: false
  vault:
    enabled: false
  customSizing: {}
  sidecars: {}
  gitConfig:
    upstreamUser: spinnaker
  haServices:
    clouddriver:
      enabled: false
      disableClouddriverRoDeck: false
    echo:
      enabled: false
persistentStorage:
  azs: {}
  gcs:
    rootFolder: front50
  redis: {}
  s3:
    rootFolder: front50
  oracle: {}
features:
  auth: false
  fiat: false
  chaos: false
  entityTags: false
  jobs: false
metricStores:
  datadog:
    enabled: false
    tags: []
  prometheus:
    enabled: false
    add_source_metalabels: true
  stackdriver:
    enabled: false
  period: 30
  enabled: false
notifications:
  slack:
    enabled: false
timezone: America/Los_Angeles
ci:
  jenkins:
    enabled: false
    masters: []
  travis:
    enabled: false
    masters: []
  wercker:
    enabled: false
    masters: []
security:
  apiSecurity:
    ssl:
      enabled: false
  uiSecurity:
    ssl:
      enabled: false
  authn:
    oauth2:
      enabled: false
      client: {}
      resource: {}
      userInfoMapping: {}
    saml:
      enabled: false
    ldap:
      enabled: false
    x509:
      enabled: false
    iap:
      enabled: false
    enabled: false
  authz:
    groupMembership:
      service: EXTERNAL
      google:
        roleProviderType: GOOGLE
      github:
        roleProviderType: GITHUB
      file:
        roleProviderType: FILE
      ldap:
        roleProviderType: LDAP
    enabled: false
artifacts:
  bitbucket:
    enabled: false
    accounts: []
  gcs:
    enabled: false
    accounts: []
  oracle:
    enabled: false
    accounts: []
  github:
    enabled: false
    accounts: []
  gitlab:
    enabled: false
    accounts: []
  http:
    enabled: false
    accounts: []
  s3:
    enabled: false
    accounts: []
pubsub:
  enabled: false
  google:
    enabled: false
    subscriptions: []
canary:
  enabled: false
  serviceIntegrations:
  - name: google
    enabled: false
    accounts: []
    gcsEnabled: false
    stackdriverEnabled: false
  - name: prometheus
    enabled: false
    accounts: []
  - name: datadog
    enabled: false
    accounts: []
  - name: signalfx
    enabled: false
    accounts: []
  - name: aws
    enabled: false
    accounts: []
    s3Enabled: false
  reduxLoggerEnabled: true
  defaultJudge: NetflixACAJudge-v1.0
  stagesEnabled: true
  templatesEnabled: true
  showAllConfigsEnabled: true
```
