### ISSUE TITLE
Manifest based deployments for services

### ISSUE THREAD

**Issue by okundzich** [spinnaker/spinnaker#3592]
### Issue Summary:
In create service stage add ability to take configuration from manifest/artifact.

### Cloud Provider(s):
CF

### Environment:
CF 2.0 and greater

### Feature Area: 
Deck and clouddriver

### Description:
In create service stage add an artifact based configuration of service. This will a manifest to deploy service with. It will translate to `cf create service` arguments.

**Comment by stuart-pollock** [comment]
Sample manifest: 
``` yml
---
service: service
service_plan: service-plan
tags:
- tag1
parameters: |
  { "service_param_key": "service_param_value" }
```
