### ISSUE TITLE
Link to PCF Apps Manager and PCF Metrics from SG details

### ISSUE THREAD

**Issue by okundzich** [spinnaker/spinnaker#3664]
### Issue Summary:
Provide a link to application in PCF AppsManager and Metrics from SG details screen. We want to specifically link to application (guid) in there, not just main screen.

### Cloud Provider(s):
CF

### Environment:
PCF 2.0+

### Feature Area: 
CF

![screen shot 2018-11-28 at 2 53 41 pm](https://user-images.githubusercontent.com/26604045/49178320-7659d500-f31d-11e8-9957-b5cc10e093b0.png)

**Comment by okundzich** [comment]
@spinnakerbot add-label provider/cf

**Comment by Jammy-Louie** [comment]
current ui
![screen shot 2018-12-06 at 10 30 53 am](https://user-images.githubusercontent.com/8474965/49593677-2218ab80-f942-11e8-8f43-0245de750877.png)

**Comment by okundzich** [comment]
Need to add this to official docs.

**Comment by Jammy-Louie** [comment]
when specifying an apps manager uri, it must be specified under the cloud foundry account settings

```yml
cloudfoundry:
   enabled: true
   accounts:
   - name: <ACCOUNT_NAME>
      user: '<ACCOUNT_USER>'
      password: '<ACCOUNT_PASSWORD>'
     api: <CF_API_URI>
     appsManagerUri:<APPS_MANAGER_URI>
     metricsUri: <METRICS_URI>
```
