### ISSUE TITLE
Minio x509 Cert Error - Self Signed Cert

### ISSUE THREAD

**Issue by mitchellmaler** [spinnaker/spinnaker#3686]
Our Minio has a self signed cert. How do I provide front50 with our internal ca?

**Comment by abergmeier** [comment]
My proposal would be to:
- Configure a `initContainer` which runs:
```
mkdir -p /var/run/java &&\
cp /etc/ssl/certs/java/cacerts /var/run/java/cacerts &&\
keytool -import -trustcacerts -keystore /var/run/java/cacerts -storepass changeit -noprompt -file /usr/share/ca-certificates/myca/ca.crt
```

- Create a `~/.hal/default/service-settings/front50.yml` with:
```
kubernetes:
  volumes:
  - id: myca
    mountPath: /usr/share/ca-certificates/myca
```
- Configure an `emptyDir`, which mounts to `/var/run/java` (no idea how)
- Create a _Secret_ named `myca`, which contains your `ca.crt`
- Pass `-Djavax.net.ssl.trustStore=/var/run/java/cacerts` when starting Java (no idea how)

That might do the trick. Is that what you had in mind @ethanfrogers?

**Comment by ethanfrogers** [comment]
@mitchellmaler @abergmeier +1 on the above. I could probably be further simplified by storing the trust/key store as a binary Secret in Kubernetes and mounting that into Front50. This approach just overwrites the default Java stores with your custom one so it's likely not as elegant as it could be but it allows you to use custom CAs in places where Spinnaker doesn't yet support them.

* Import your certificate into the default Java trust/key store. @abergmeier example above should suffice. Paths will probably differ if you're on OSX or Linux. A quick Google should tell you the default path.

* Create a Kubernetes Secret from the keystore.
```
$ kubectl create secret generic -n spinnaker internal-trust-store --from-file {path-to-cacerts}
```

* Configure the Secret as a volume mount in `~/.hal/default/service-settings/front50.yml`

```
kubernetes:
  volumes:
  - id: internal-trust-store
    mountPath: /etc/ssl/certs/java
    type: secret
```
