### ISSUE TITLE
Configure SQL through halyard (Orca)

### ISSUE THREAD

**Issue by ricklagerweij** [spinnaker/spinnaker#3702]
### Issue Summary:
Make it possible to configure SQL through halyard.

### Cloud Provider(s):
Any

### Environment:
Kubernetes 1.13.0
Halyard 1.12
Spinnaker 1.10.5

### Feature Area: 
Orca

### Description:
You can manually configure Spinnaker to use SQL and migrate Redis data to SQL with the orca-local.yml and migration guide on the website, this should be standard through halyard.

### Steps to Reproduce:
N/A.

### Additional Details:
Currently it's not possible to configure SQL through hal. A default config file:

```
sql:
  enabled: true
  connectionPool:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/orca
    user: orca_service
    password: password
    connectionTimeout: 5000
    maxLifetime: 30000
    # MariaDB-specific:
    maxPoolSize: 50
```
