### ISSUE TITLE
Halyard deploy fails if kuberentes annotations have regex

### ISSUE THREAD

**Issue by jareksm** [spinnaker/spinnaker#3736]
### Issue Summary:
Halyard deploy fails if kuberentes annotations have regex

### Cloud Provider(s):
kubernetes v2

### Feature Area: 
Add annotations to pods

### Description:
Generates following error:

```
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Problems in Global:
! ERROR Unexpected exception: while scanning a double-quoted scalar
 in 'string', line 38, column 65:
     ... louddriver/multiline.pattern" : "^[[:space:]]+(at|\.{3})\b|^Caus ... 
                                         ^
found unknown escape character .(46)
 in 'string', line 38, column 84:
     ... e.pattern" : "^[[:space:]]+(at|\.{3})\b|^Caused by:", 
```

### Steps to Reproduce:
Create following file .hal/default/service-settings/clouddriver.yml
```
kubernetes:
  podAnnotations:
    prometheus.io.path: /prometheus_metrics
    prometheus.io.port: "8008"
    prometheus.io.scrape: "true"
    co.elastic.logs.clouddriver/exclude_lines: ^$
    co.elastic.logs.clouddriver/multiline.match: after
    co.elastic.logs.clouddriver/multiline.negate: "false"
    co.elastic.logs.clouddriver/multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
    co.elastic.logs.monitoring-daemon/exclude_lines: ^$
    co.elastic.logs.monitoring-daemon/multiline.match: after
    co.elastic.logs.monitoring-daemon/multiline.negate: "false"
    co.elastic.logs.monitoring-daemon/multiline.pattern: '^[[:space:]]+|^Traceback|^ValueError:'
```

### Additional Details:

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

* An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 
* Before you open an issue, please [check if a similar issue already exists](https://github.com/spinnaker/spinnaker/issues) or has been closed before.
* Make sure you have read through the [Spinnaker FAQ](https://www.spinnaker.io/community/faqs/) and [Halyard FAQ](https://www.spinnaker.io/setup/quickstart/faq/) to provide as much information as possible.

Descriptions:

* Issue Summary: A brief description of what you're seeing.
* Cloud Provider: AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc. Please assign a label from the right so your issue can be properly sorted.
* Environment: As much information about your Spinnaker environment and configuration that might be relevant to the issue. For example: "I am running Spinnaker using the Amazon images to deploy into AWS and GCP."
* Feature Area: Notifications, Pipelines, UI, Jenkins, etc. Please assign a label from the right so your issue can be properly sorted.
* Description: The behavior you expect to see, and the actual behavior.
* Steps to reproduce: Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.
* Additional Details: Additional information such as screenshots and exception logs.
