### ISSUE TITLE
Volumes settings fail to bind values

### ISSUE THREAD

**Issue by abergmeier** [spinnaker/spinnaker#3745]
### Issue Summary:
When specifying a _service-setting_ for clouddriver:
```
kubernetes:
  volumes:
  - name: company-ca
    secret:
      secretName: sec-company-ca
  - name: issuing-ca
    secret:
      secretName: sec-issuing-ca
```

when deploying, it generates **one** volume entry:
```
      volumes:
      - name: spin-clouddriver-files-1317527464
        secret: {secretName: spin-clouddriver-files-1317527464}
      - name: spin-clouddriver-files-1786010206
        secret: {secretName: spin-clouddriver-files-1786010206}
      - name: ''
        secret: {secretName: ''}
```

which leads to error:

```
The Deployment "spin-clouddriver" is invalid: 
* spec.template.spec.volumes[2].secret.secretName: Required value
* spec.template.spec.volumes[2].name: Required value
```

### Cloud Provider(s):
Kubernetes
