### ISSUE TITLE
stuck on loading screen - 502 on gate url - gke with .app domain

### ISSUE THREAD

**Issue by jonbcampos-alto** [spinnaker/spinnaker#3789]
### Issue Summary:
I used the stable/helm install and seem to have a lot setup. However I always seem to get stuck with just a loading Spinnaker screen and there are browser console failures for a variety of javascript files. 

### Cloud Provider(s):
GKE / Google Cloud

### Environment:
GKE

### Feature Area: 
install?

### Description:
Install with https://github.com/helm/charts/tree/master/stable/spinnaker
Include a custom url (mine is using Load Balancer SSL terminations for a .app domain)
I've added authorization with the following commands:

```
enable_gcs_artifacts.sh: |
        # this sets up the gcs connection
        $HAL_COMMAND config artifact gcs account add gcs-alto-builds --json-path /opt/gcs/key.json
        $HAL_COMMAND config artifact gcs enable

      enable_pubsub_triggers.sh: |
        # adds pubsub connection
        $HAL_COMMAND config pubsub google enable
        $HAL_COMMAND config pubsub google subscription add gcr-triggers \
          --subscription-name gcr-triggers \
          --json-path /opt/gcs/key.json \
          --project alto-builds \
          --message-format GCR

      configure_spinnaker_settings.sh: |
        # add authentication
        source /opt/halyard/additionalConfigMaps/config.src

        $HAL_COMMAND config security ui edit --override-base-url "$DECK_URL"
        $HAL_COMMAND config security api edit --override-base-url "$GATE_URL"

        CLIENT_ID=$( cat $CLIENT_ID_FILE )
        CLIENT_SECRET=$( cat $CLIENT_SECRET_FILE )

        $HAL_COMMAND config security authn oauth2 edit \
          --client-id "$CLIENT_ID" \
          --client-secret "$CLIENT_SECRET" \
          --provider $PROVIDER \
          --user-info-requirements hd=$FQDN_HD

        $HAL_COMMAND config security authn oauth2 enable

        $HAL_COMMAND config security authn oauth2 edit --pre-established-redirect-uri https://$GATE_URL/login

        $HAL_COMMAND deploy apply
```

I get an error that the javascript on the loading screen fails.
<img width="986" alt="screen shot 2018-12-27 at 5 56 15 pm" src="https://user-images.githubusercontent.com/43216158/50497944-0a44bc80-0a02-11e9-9d2b-41b5745e5d99.png">

**Comment by jonbcampos-alto** [comment]
I went through this morning and rebuilt the entire setup. Through multiple steps things seemed to be working. Where things fall apart is when adding SSL and authentication. I am running on a .app domain so I have to add SSL or I can't access the url. 

At this point I am getting the same error as before though. Same issue being stuck at the loading screen. I am assuming that I obviously messed something up.

Below is basically the entire script that I ran to get to this point (excluding sensitive data)

```bash
#!/usr/bin/env bash

echo "set service account"
CONTEXT=$(kubectl config current-context)

# This service account uses the ClusterAdmin role -- this is not necessary,
# more restrictive roles can by applied.
kubectl apply --context $CONTEXT \
    -f https://spinnaker.io/downloads/kubernetes/service-account.yml

TOKEN=$(kubectl get secret --context $CONTEXT \
   $(kubectl get serviceaccount spinnaker-service-account \
       --context $CONTEXT \
       -n spinnaker \
       -o jsonpath='{.secrets[0].name}') \
   -n spinnaker \
   -o jsonpath='{.data.token}' | base64 --decode)

kubectl config set-credentials ${CONTEXT}-token-user --token $TOKEN

kubectl config set-context $CONTEXT --user ${CONTEXT}-token-user

echo "done creating service account"

---

#!/usr/bin/env bash

echo "create provider account"
CONTEXT=$(kubectl config current-context)
ACCOUNT=spinnaker-k8s-v2-account

hal config provider kubernetes account add $ACCOUNT \
    --provider-version v2 \
    --context $CONTEXT

hal config features edit --artifacts true

hal deploy apply

echo "done creating provider account"

---

#!/usr/bin/env bash

echo "create artifact account"
ARTIFACT_ACCOUNT_NAME=spinnaker-artifact-account
SERVICE_ACCOUNT_DEST=~/.gcp/gcs-account.json

hal config artifact gcs account add $ARTIFACT_ACCOUNT_NAME \
    --json-path $SERVICE_ACCOUNT_DEST

hal config artifact gcs enable

echo "done creating artifact account"

---

#!/usr/bin/env bash

echo "add environment"
CONTEXT=$(kubectl config current-context)
ACCOUNT=spinnaker-k8s-v2-account

hal config deploy edit --type distributed --account-name $ACCOUNT

echo "done adding environment"

---

#!/usr/bin/env bash

echo "start editing storage settings"
SERVICE_ACCOUNT_NAME=spinnaker-account
SERVICE_ACCOUNT_DEST=~/.gcp/gcs-account.json
PROJECT=$(gcloud info --format='value(config.project)')
# see https://cloud.google.com/storage/docs/bucket-locations
BUCKET_LOCATION=us

hal config storage gcs edit --project $PROJECT \
    --bucket-location $BUCKET_LOCATION \
    --json-path $SERVICE_ACCOUNT_DEST

hal config storage edit --type gcs

echo "done editing storage settings"

---

#!/usr/bin/env bash

echo "download service account"
SERVICE_ACCOUNT_NAME=spinnaker-account
SERVICE_ACCOUNT_DEST=~/.gcp/gcs-account.json

gcloud iam service-accounts create \
    $SERVICE_ACCOUNT_NAME \
    --display-name $SERVICE_ACCOUNT_NAME

SA_EMAIL=$(gcloud iam service-accounts list \
    --filter="displayName:$SERVICE_ACCOUNT_NAME" \
    --format='value(email)')

PROJECT=$(gcloud info --format='value(config.project)')

gcloud projects add-iam-policy-binding $PROJECT \
    --role roles/storage.admin --member serviceAccount:$SA_EMAIL

mkdir -p $(dirname $SERVICE_ACCOUNT_DEST)

gcloud iam service-accounts keys create $SERVICE_ACCOUNT_DEST \
    --iam-account $SA_EMAIL

echo "done downloading service account"

---

#!/usr/bin/env bash

echo "enable pubsub triggers"
SERVICE_ACCOUNT_DEST=~/.gcp/gcs-account.json
PROJECT=$(gcloud info --format='value(config.project)')

hal config pubsub google enable
hal config pubsub google subscription add gcr-triggers \
    --subscription-name gcr-triggers \
    --json-path $SERVICE_ACCOUNT_DEST \
    --project $PROJECT \
    --message-format GCR

echo "done enabling pubsub triggers"

---

#!/usr/bin/env bash

echo "start override urls"
GATE_URL=https://api.spinnaker.mysite.app
DECK_URL=https://spinnaker.mysite.app

hal config security ui edit --override-base-url $DECK_URL
hal config security api edit --override-base-url $GATE_URL

hal deploy apply

echo "done override urls"

---

#!/usr/bin/env bash

echo "start enabling ssl"

echo "for gate"
KEYSTORE_PATH=./certs/keystore.jks # /path/to/keystore.jks

hal config security api ssl edit \
  --key-alias spinnaker \
  --keystore $KEYSTORE_PATH \
  --keystore-password \
  --keystore-type jks \
  --truststore $KEYSTORE_PATH \
  --truststore-password \
  --truststore-type jks

hal config security api ssl enable

echo "for deck"
SERVER_CERT=./certs/server.crt   # /path/to/server.crt
SERVER_KEY=./certs/server.key    # /path/to/server.key

hal config security ui ssl edit \
  --ssl-certificate-file $SERVER_CERT \
  --ssl-certificate-key-file $SERVER_KEY \
  --ssl-certificate-passphrase

hal config security ui ssl enable

echo "done enabling ssl"

---

#!/usr/bin/env bash

echo "start enabling oauth"
PROVIDER=google
FQDN_HD=mysite.com
CLIENT_ID=client id
CLIENT_SECRET=client secret

hal config security authn oauth2 edit \
  --client-id $CLIENT_ID \
  --client-secret $CLIENT_SECRET \
  --provider $PROVIDER \
  --user-info-requirements hd=$FQDN_HD

hal config security authn oauth2 enable

echo "done enabling oauth"
```

When I leave SSL turned on I get a *Bad Request* even though I am running through HTTPS via the Load Balancer / Kubernetes / Cert-Manager. So then I turn off SSL with the following:

```bash
hal config security api ssl disable
hal config security ui ssl disable
```
And that returns me to being able to access Spinnaker, just without being able to load those Javascript files.

Thoughts?

**Comment by jonbcampos-alto** [comment]
hal -v
unknown

hal version list
You are on version "1.11.2", and the following are available

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-gke.5", GitCommit:"9aba9c1237d9d2347bef28652b93b1cba3aca6d8", GitTreeState:"clean", BuildDate:"2018-12-11T02:36:50Z", GoVersion:"go1.10.3b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by jonbcampos-alto** [comment]
I've gotten everything to work... except for serving spinnaker through a custom url. The issue seems to be with a custom ingress and the gate services (which just give 503s). Here is my ingress:

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: spinnaker-ip
  labels:
    app: spinnaker-spinnaker
    release: spinnaker
  name: spinnaker-deck-ingress
  namespace: spinnaker
spec:
  rules:
  - host: spinnaker.mysite.app
    http:
      paths:
      - backend:
          serviceName: spin-deck
          servicePort: 80
        path: /
  tls:
  - hosts:
    - spinnaker.mysite.app
    secretName: deck-tls
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gate-spinnaker-ip
  labels:
    app: spinnaker-spinnaker
    release: spinnaker
  name: spinnaker-gate-ingress
  namespace: spinnaker
spec:
  rules:
  - host: api-spinnaker.mysite.app
    http:
      paths:
      - backend:
          serviceName: spin-gate
          servicePort: 80
        path: /
  tls:
  - hosts:
    - api-spinnaker.mysite.app
    secretName: gate-tls
```
