### ISSUE TITLE
Error when enabling Pipeline Cleanup from documentation

### ISSUE THREAD

**Issue by rwillard** [spinnaker/spinnaker#3833]
### Issue Summary:
When I enabled Pipeline Cleanup from https://www.spinnaker.io/setup/productionize/caching/configure-redis-usage/#configure-pipeline-cleanup instructions, new orca wouldn't come up healthy with this error
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'oldPipelineCleanupPollingNotificationAgent' defined in URL [jar:file:/opt/orca/lib/orca-core.jar!/com/netflix/spinnaker/orca/notifications/scheduling/OldPipelineCleanupPollingNotificationAgent.class]: Unsatisfied dependency expressed through constructor parameter 4; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: ""
```
I was able to resolve this by specifying out the values that were listed as Default.
```
pollers:
  oldPipelineCleanup:
    enabled: true       # This enables old pipline cleanup.

    intervalMs: 3600000        # (Default 3,600,000, or 1 hour) How many milliseconds between pipeline cleanup runs

    thresholdDays: 30      # (Default 30) How old a pipeline must be to be deleted.

    minimumPipelineExecutions: 5 # (Default 5) How many executions to keep around.

tasks:
  daysOfExecutionHistory: 180  # How many days to keep old task executions around
```

### Cloud Provider(s):
GKE, Kubernetes V2, Spinnaker version  1.11.4 & 1.10.5

### Feature Area: 
Orca

### Steps to Reproduce:
Add
```
pollers:
  oldPipelineCleanup:
    enabled: true       # This enables old pipline cleanup.

    intervalMs:         # (Default 3,600,000, or 1 hour) How many milliseconds
                        # between pipeline cleanup runs.

    thresholdDays:      # (Default 30) How old a pipeline must be to be deleted.

    minimumPipelineExecutions: # (Default 5) How many executions to keep around.

tasks:
  daysOfExecutionHistory: 180  # How many days to keep old task executions
                               # around.
```
as `~/.hal/$DEPLOYMENT/profiles/orca-local.yml` specified from https://www.spinnaker.io/setup/productionize/caching/configure-redis-usage/#configure-pipeline-cleanup

Note that setting these to their default values resolves the error and Orca comes up healthy.
