### ISSUE TITLE
Bake (Manifest) Overrides string interpolation

### ISSUE THREAD

**Issue by nmnellis** [spinnaker/spinnaker#3845]
### Issue Summary:
Bake (Manifest) Overrides 

### Cloud Provider(s):
GCP GKE

### Environment:
Running Spinnaker in GKE to deploy prometheus helm chart

### Feature Area: 
V2 Kubernetes 

### Description:
Im trying to override a property in Bake (Manifest) but part of the property needs to be interpolated as a string, rather than yaml.
`alertmanagerFiles.alertmanager.yml.<property_name>`
should be interpolated as `alertmanagerFiles."alertmanager.yml".name`

this is how its being interpolated, even if i try to quote the string like above
```yaml
data:
  "alertmanager: |
    yml":
      receivers:
```
It should look like
```yaml
data:
  alertmanager.yml:
      receivers:
```

### Steps to Reproduce:
Create overrides key in the Bake (Manifest) stage that contains a string with a period within `some.property.file"myfile.txt".property`
