### ISSUE TITLE
Didn't create image pull secret and config it in pod yaml file automatically

### ISSUE THREAD

**Issue by WakeupTsai** [spinnaker/spinnaker#3850]
### Issue Summary:
I already added the docker registry account and set it to the dockerRegistries of kubernetes provider. But still can not see spinnaker creating the image pull secret for each namespace.  And the imagePullSecrets doesn't appear in [pod yaml](https://www.spinnaker.io/reference/providers/kubernetes/#server-group), either.  Did I do anything wrong?

### Environment:
Spinnaker 1.11.0

### Cloud Provider(s):
Kubernetes (v2)
dockerRegistry (v1)

### Additional Details:
Here is the config
```
dockerRegistry:
  enabled: true
  accounts:
  - name: gcr-account
    requiredGroupMembership: []
    providerVersion: V1
    permissions: {}
    address: https://gcr.io
    username: _json_key
    email: fake.email@spinnaker.io
    cacheIntervalSeconds: 30
    clientTimeoutMillis: 60000
    cacheThreads: 1
    paginateSize: 100
    sortTagsByDate: false
    trackDigests: false
    insecureRegistry: false
    repositories: []
    passwordFile: /home/user/gcr-account.json
  primaryAccount: gcr-account
kubernetes:
  enabled: true
  accounts:
  - name: staging
    requiredGroupMembership: []
    providerVersion: V2
    permissions: {}
    dockerRegistries:
    - accountName: gcr-account
      namespaces: []
    context: kops.stg.info
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces: []
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /home/user/.kube/config
    checkPermissionsOnStartup: true
    oauthScopes: []
    oAuthScopes: []
    onlySpinnakerManaged: false
  primaryAccount: staging
```
