### ISSUE TITLE
Monitoring-daemon request/limit taken from main service in customsizing

### ISSUE THREAD

**Issue by ricklagerweij** [spinnaker/spinnaker#3853]
### Issue Summary:
When specifying limit or requests for microservices within hal config the monitoring daemon will use the same request as the main service, for example clouddriver gate etc.

### Cloud Provider(s):
Kubernetes V2

### Environment:
Spinnaker 1.11.6
Kubernetes 1.13.0
Halyard 1.13.0

### Feature Area: 
Monitoring-daemon (kayenta)

### Steps to Reproduce:
* Add requests/limits to the hal config
```
      spin-front50:
        requests:
          cpu: 250m
          memory: 2Gi
        limits:
          cpu: 500m
          memory: 4Gi
```
* hal deploy apply
* the added monitoring-daemon pod will have the same limit and requests as front50.
### Additional Details:

---
