### ISSUE TITLE
Unable to select Account on pipeline stage for Kubernetes V2

### ISSUE THREAD

**Issue by popopanda** [spinnaker/spinnaker#3872]
### Issue Summary:
Spinnaker web ui returns when choosing an account for deploy types
```
Uncaught TypeError: Cannot read property 'includes' of null
    at ManifestSelector.isExpression (ManifestSelector.tsx:224)
    at ManifestSelector.handleAccountChange (ManifestSelector.tsx:183)
    at onChange (AccountSelectField.tsx:121)
    at Object.<anonymous> (react-dom.production.min.js:14)
    at ma (react-dom.production.min.js:15)
    at react-dom.production.min.js:15
    at za (react-dom.production.min.js:17)
    at Da (react-dom.production.min.js:18)
    at Fa (react-dom.production.min.js:18)
    at Ba (react-dom.production.min.js:18)
```

### Cloud Provider(s):
Kubernetes V2 - Manifest

### Environment:
I have 2 kubernetes cluster managed through 2 contexts: `ops-eks-cluster` and `dev-eks-cluster`
I installed Spinnaker via Halyard on `ops-eks-cluster`, and added the `dev-eks-cluster` as another account in the halyard configuration and deployed spinnaker to `ops-eks-cluster`.

Spinnaker is installed via the distributed installation on kubernetes - eks on AWS. 

### Description:
On the web ui, I run into uncaught TypeError when I try to add a stage to a pipeline to any applications that involves selecting Account.

I should be able to select any accounts without errors

### Steps to Reproduce:
Selecting the stage type as: Patch or Scale, in the Manifest section if I try to change the account, I get a `Uncaught TypeError: Cannot read property 'includes' of null` error.

If I use the stage type as Deploy, I can choose any accounts without running into any errors

### Additional Details:
Halyard config:
```
  kubernetes:
    enabled: true
    accounts:
    - name: ops-k8s-v2-account
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: ops-eks-cluster
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /Users/myuser/.kube/config-ops
      checkPermissionsOnStartup: true
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: false
    - name: dev-k8s-v2-account
      requiredGroupMembership: []
      providerVersion: V2
      permissions: {}
      dockerRegistries: []
      context: dev-eks-cluster
      configureImagePullSecrets: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces: []
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      kubeconfigFile: /Users/myuser/.kube/config-dev
      checkPermissionsOnStartup: true
      oauthScopes: []
      oAuthScopes: []
      onlySpinnakerManaged: false
    primaryAccount: ops-k8s-v2-account
```
![image](https://user-images.githubusercontent.com/15364875/51561797-05c2c680-1e3d-11e9-9e0c-f167bc2d14ba.png)
