### ISSUE TITLE
Kubernetes Events are missing after v1.10.13

### ISSUE THREAD

**Issue by beyond-code-github** [spinnaker/spinnaker#3928]
### Issue Summary:
There appears to have been a regression starting with v1.11.x whereby Kubernetes events are not shown for running infrastructure.

### Cloud Provider(s):
Kubernetes V2

### Environment:
Distributed deployment running on Kubernetes 1.10.11 deployed to AWS (non-EKS cluster, created via KOPS)

### Feature Area: 
Deck, Clouddriver, applications/infrastructure

### Description:
When running Spinnaker 1.10.13, I see Kubernetes events correctly in the UI.
When running Spinnaker 1.11.6, with no other changes, I do not see Kubernetes events in the UI.
When running Spinnaker 1.12.1, with no other changes, I do not see Kubernetes events in the UI.

Inspecting network traffic in Chrome dev tools indicates that the API is returning ```events: []``` so likely this is not an issue in Deck

### Steps to Reproduce:
```
hal config version edit --version 1.10.13
hal deploy apply
```
Perform a deployment, scale a replica set or other activity that would produce k8s events
From the infrastructure tab, select a pod. View events in the right hand pane.
```
hal config version edit --version 1.11.6
hal deploy apply
```
View the same deployment/pod as before. There are no events in the right hand pane.

No exceptions were observed in the cloud driver logs. 

Running the following from a shell to the cloud driver pod executes succesfully and returns as expected:

```kubectl --kubeconfig=/home/pete.smith/.hal/default/staging/dependencies/1342040884-config --context=my-context --namespace=default -o json get apiService,clusterRole,clusterRoleBinding,configMap,controllerRevision,customResourceDefinition,cronJob,daemonSet,deployment,event,horizontalpodautoscaler,ingress,job,mutatingWebhookConfiguration,namespace,networkPolicy,persistentVolume,persistentVolumeClaim,pod,podSecurityPolicy,podDisruptionBudget,replicaSet,role,roleBinding,secret,service,serviceAccount,statefulSet,storageClass,validatingWebhookConfiguration```

### Additional Details:
Events in 1.10.13:
![image](https://user-images.githubusercontent.com/795965/52218793-48e85500-2893-11e9-845d-0eeb37a3de09.png)

Lack of events in 1.11.6
![image](https://user-images.githubusercontent.com/795965/52218806-50a7f980-2893-11e9-8a4d-b053f882b4b2.png)

BOM for 1.10.13 (Events present):
```
echo:
    version: 2.1.3-20181217212321
    commit: a568cf94060a2a64cd77654fed8db18a86fb5f6d
  clouddriver:
    version: 4.0.8-20190130152235
    commit: 3ca7359d12e4019d75a481e989272fba188b2cbd
  deck:
    version: 2.5.8-20190115073329
    commit: c9abb38e596b3274f20a03699b5f8832856d58a6
  fiat:
    version: 1.2.0-20181115151924
    commit: 83a7ef2d23466cc8807b656d05faaecd4f462f94
  front50:
    version: 0.13.1-20181217212321
    commit: 98b4ab9dd11b6234b833b6cba77873829094cb1f
  gate:
    version: 1.2.1-20181108172516
    commit: a8bb9987eee8032515adb344ec457de574059938
  igor:
    version: 0.13.0-20181003100130
    commit: a4fd89756144d4b0722dc43ee679b9ae51a75171
  kayenta:
    version: 0.4.1-20190105115745
    commit: 96906173682961698683a0aef5d09aaa385d4760
  orca:
    version: 1.1.6-20190115073329
    commit: 769f4e50a77b852de3574a4327d7748d02a03ee2
  rosco:
    version: 0.8.0-20181003100130
    commit: 2f1a4f856b04971fe0fa04c7d402ee8f03827f61
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.9.3-20181121042809
    commit: 4a87d20a443f5e3927667b5f11ece8ee44869c25
  monitoring-daemon:
    version: 0.9.3-20181121042809
    commit: 4a87d20a443f5e3927667b5f11ece8ee44869c25
```

BOM for 1.11.6 (Events not present):

```
version: 1.11.6
timestamp: '2019-01-14 18:22:07'
services:
  echo:
    version: 2.2.3-20190104153242
    commit: 22a704dc9dcfcea2566b62e231d95982bd387745
  clouddriver:
    version: 4.2.3-20190111151755
    commit: 05376e984fa88074fafca3dbc03644b79f2c4d99
  deck:
    version: 2.6.3-20190114132151
    commit: eefd997d58f00d21c7203dc433652c59dcc10e5a
  fiat:
    version: 1.3.0-20181207134351
    commit: 2e4c3bbfcae27f37fe15d591adee0479d40fe841
  front50:
    version: 0.14.0-20181207134351
    commit: 94ad9540f6b079155ae7a7b36d4dc78635c87943
  gate:
    version: 1.4.0-20181217192627
    commit: b83dea9f35024f18592f1741dcb62b3a7b82c086
  igor:
    version: 1.0.0-20181207134351
    commit: 0b3a637e199ee1ac030a7a7fe7bf44139a41668a
  kayenta:
    version: 0.5.1-20190104141519
    commit: 8a49a32291fc139d4772fdf45efd832c28b7d171
  orca:
    version: 2.2.0-20190111140043
    commit: 999b5009ec20b56593eb8876d52d9324f92c3294
  rosco:
    version: 0.8.2-20181221095200
    commit: 0e336fcba0a56dcd93f4692c4cc798b9b887fc7f
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.10.2-20190114132151
    commit: 4b7e19ec916878f296cfc476d2e70ce5edfa3e5c
  monitoring-daemon:
    version: 0.10.2-20190114132151
    commit: 4b7e19ec916878f296cfc476d2e70ce5edfa3e5c
```
