### ISSUE TITLE
GCS Artifacts - Unmatched expected artifact

### ISSUE THREAD

**Issue by Buli-0** [spinnaker/spinnaker#3937]
### Issue Summary:
No matter how I configure artifacts, I'm getting "Unmatched expected artifact" message.

### Cloud Provider(s):
GCP

### Environment:
Spinnaker is deployed on k8s. I'm using shared VPC. Spinnaker in version 1.11.6 at the begining, now it is 1.12.1. I'm using nginx ingress controller.

### Feature Area: 
Artifacts on GCS

### Description:
From start I was sticking to the official halyard spinnaker guide. 

I'm using buckets in the same exact project, my service account is a project owner for now so no rights problems for sure. Front50 is able to store it's files on a bucket that was generated during installation (and it uses the very same service account).

Similarly I cannot produce any artifact in any stage as well. For me it was looking like auth error but I didn't saw any such thing on container logs. Only clouddriver replicated this message regarding unmatched artifact in his container logs.

For now my artifacts config looks like this:
```
artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: true
      accounts:
      - name: spinnaker
        jsonPath: <path to json>

```

Artifact feature is enabled:
```
features:
    auth: false
    fiat: false
    chaos: false
    entityTags: false
    jobs: false
    artifacts: true
```

the error I'm getting (no matter of bucket I'm picking):
```
"canceled": true,
  "canceledBy": "system",
  "cancellationReason": "Failed on startup: Unmatched expected artifact ExpectedArtifact(matchArtifact=Artifact(type=gcs/object, customKind=false, name=gs://<the-bucket-name>/file.yml, version=null, location=null, reference=null, metadata=null, artifactAccount=null, provenance=null, uuid=null), usePriorArtifact=false, useDefaultArtifact=false, defaultArtifact=Artifact(type=null, customKind=true, name=null, version=null, location=null, reference=null, metadata=null, artifactAccount=null, provenance=null, uuid=null), id=a1b81b17-32b5-4d28-8ad7-5c5523dc7ffc, boundArtifact=null) could not be resolved.",
```

as for the declaration in the deck:
![image](https://user-images.githubusercontent.com/47368406/52303908-a236ae00-2991-11e9-9007-b5a5bcc2e3ba.png)

json declaration (generated by gui):
```
 "appConfig": {},
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "customKind": true,
        "id": "3f2cb81c-d3e7-4edd-8ab1-3ef56c802704"
      },
      "id": "a1b81b17-32b5-4d28-8ad7-5c5523dc7ffc",
      "matchArtifact": {
        "id": "8561080f-a466-4ba4-922b-aac5564e5f57",
        "name": "gs://<bucket/path/to/file.yaml>",
        "type": "gcs/object"
      },
      "useDefaultArtifact": false,
      "usePriorArtifact": false
    }
  ],
  "keepWaitingPipelines": false,
  "lastModifiedBy": "problematic@dude.com",
  "limitConcurrent": true,
  "stages": [],
  "triggers": [],
  "updateTs": "1549397325217"
}
```
