### ISSUE TITLE
WaitForUpInstanceTask stuck on red/black strategy without load balancer on google cloud

### ISSUE THREAD

**Issue by diasjorge** [spinnaker/spinnaker#3940]
### Issue Summary:
When deploying a server group without a load balancer using the red/black strategy the pipeline gets stuck on WaitForUpInstancesTask.

The current server group has no associated load balancer. 
Task Completion is checked for Consider only Google health

### Cloud Provider(s):

Google cloud

### Environment:

Spinnaker deployed with Hal on GKE.
```
version: 1.12.1
timestamp: '2019-01-31 08:06:24'
services:
  echo:
    version: 2.3.0-20190123160119
    commit: 57a9319f2887a5c66a4804489df995fda8b3b145
  clouddriver:
    version: 4.3.1-20190130095322
    commit: 97bd18aed07ca661d6ad2bc17ff1eaca9c6c4e84
  deck:
    version: 2.7.1-20190131030608
    commit: eb7c725ec4c7c3a34d10593d4dc46cf01c75fe87
  fiat:
    version: 1.3.2-20190128153726
    commit: daf21b24330a5f22866601559aa0f7ac99590274
  front50:
    version: 0.15.0-20190123161040
    commit: 89d91040b3c92f232c9e495aeab6b57b26844cfb
  gate:
    version: 1.5.0-20190123161040
    commit: e52a6c6d66a1a24cfd122e0d534a2bd22e34baa1
  igor:
    version: 1.1.0-20190123161040
    commit: 807cff8b19d2bebf466ec57e0b57c8bdab61d64f
  kayenta:
    version: 0.6.0-20190123160119
    commit: a0b2b231a21b9a6c48ec23ada8911a07dfae4662
  orca:
    version: 2.3.0-20190128134206
    commit: d637f935a2dac8cf4564317b7358e79f978a1437
  rosco:
    version: 0.9.0-20190123170846
    commit: 42f81a2501de6d40676d47661579a6106b5c3e8a
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.11.1-20190129180006
    commit: dffecbe35d84e80aaa225cf9a55e75739f8be793
  monitoring-daemon:
    version: 0.11.1-20190129180006
    commit: dffecbe35d84e80aaa225cf9a55e75739f8be793
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker
```

### Feature Area: 
Pipelines
Orca

### Description:
The deployment of the server group is stuck and stays on the first step "Resize Server Group: ".

### Steps to Reproduce:
Create a deployment stage without attaching to a load balancer.
Check Consider only Google health

### Additional Details:

This is what I see keeps appearing in the logs
```
2019-02-06 13:12:34.262  INFO 1 --- [    handlers-17] c.n.s.o.c.t.i.WaitForUpInstancesTask     : [user@example.com] app-sandbox-worker-v003: Calculating target desired size from snapshot (1) and server group (1)
2019-02-06 13:12:34.262  INFO 1 --- [    handlers-17] c.n.s.o.c.t.i.WaitForUpInstancesTask     : [user@example.com] app-sandbox-worker-v003: Target desired size is 1
2019-02-06 13:12:34.263  INFO 1 --- [    handlers-17] c.n.s.o.c.t.i.WaitForUpInstancesTask     : [user@example.com] app-sandbox-worker-v003: Instances up check - healthy: 0, target: 1
```
