### ISSUE TITLE
Hal Config generate does not apply config changes

### ISSUE THREAD

**Issue by seanpeters86** [spinnaker/spinnaker#3947]
### Issue Summary:
When running halyard locally and trying to generate config files the config shown in `hal config` and `/.hal/config` do not match what gets generated to `/.hal/default/staging`. 

### Cloud Provider(s):
- N/A

### Environment:
Local, hal version set to 1.12.1.

```
$ hal --version
1.15.0-20190206103304
```

### Feature Area: 
Halyard

### Description:
After starting up halyard locally and making a few config changes (specifically to haServices), I wanted to see how the yml files change. After running the commands in the documentation successfully, I can see the output via `$ hal config --no-validate`

```
  haServices:
    clouddriver:
      enabled: true
      redisMasterEndpoint: test-master
      redisSlaveEndpoint: test-slave
      redisSlaveDeckEndpoint: test-deck
      disableClouddriverRoDeck: false
    echo:
      enabled: true
```

Afterwards I run:

```
$ hal config generate --no-validate
+ Get current deployment
  Success
- Generate config
^ Generate config
* Generate config
_ Generate config
- Generate config
^ Generate config
* Generate config
_ Generate config
- Generate config
^ Generate config
* Generate config
_ Generate config
+ Generate config
  Success
+ Successfully generated config.
Wrote configuration to /.hal/default/staging
```

Afterwards the files in the staging folder have no changes related to HA.

### Steps to Reproduce:
1. `hal config deploy ha clouddriver enable`
2. `hal config deploy ha echo enable`
3. `hal config generate --no-validate`
