### ISSUE TITLE
Feature proposal: discover artifact account from artifact reference

### ISSUE THREAD

**Issue by xavileon** [spinnaker/spinnaker#3957]
### Issue Summary:

There are pipeline stage in orca that need to fetch artifacts using clouddriver artifacts feature (e.g. deploy kubernetes manifest, deploy cloud formation stage). Right now, the `artifactAccount` in the `Artifact` object is a required field to pick the correct credentials configured in cloud driver. Thus, the user needs to know where a given artifact was stored to choose the correct artifact account (usually configured by spinnaker operators and the details not necessary known to users).

This can be confusing to users that are configuring one of these stages and are presented with different artifact account options. Picking the wrong account would result in a not found error, and would lead the user to try other accounts until one works, which may not be a good UX.

### Cloud Provider(s):
N/A

### Feature Area: 
UI, COUDDRIVER

### Description (solution sketch):

The idea would be to discover the artifact account of an artifact from the artifact reference using regex (similar to how igor decorates generated artifacts with metadata).

Assume we have the following `current` config in clouddriver:
```
  artifacts:
    http:
      enabled: true
      accounts:
      - name: account-one
        username: user1
        password: pass1
      - name: account-two
        username: user2
        password: pass2
```

The idea would be to have extend it with something like:
```
  artifacts:
    http:
      enabled: true
      accounts:
      - name: account-one
        username: user1
        password: pass1
        identifier: *account-one.my-storage-provider.com*
      - name: account-two
        username: user2
        password: pass2
        identifier: *account-two.my-storage-provider.com*
```

This way, every time an artifact is fetched in clouddriver, it doesn't need to have an artifact account to match the credentials. It can match the artifact reference (usually a URL) to the identifier regex of each account, the first matcher being the account selected.

### Steps to Reproduce:

For example,

- Configure two or more artifact accounts of the same kind (http, s3, etc).
- Push a kubernetes manifest file to one of the configured accounts.
- Create a pipeline with a deploy manifest stage
- Add a new expected artifact with the kind of the configured accounts
- The user will be presented with two artifact accounts, but only one will work.

The solution proposed here would remove the confusion by not presenting any artifact account and having it automatically selected by clouddriver.
