### ISSUE TITLE
halyard dependencies services not pulling from custom docker registry on local BOM

### ISSUE THREAD

**Issue by schefs** [spinnaker/spinnaker#3967]
### Issue Summary:
halyard dependencies services not pulling from custom docker registry using custom local BOM

### Cloud Provider(s):
kubernetes

### Environment:
air-gaped 

### Feature Area: 
halyard

### Description:
trying to deploy spinnaker on kubernetes in a air-gaped environment using local bom files for each service.
all services images are pulled from the internal docker registry set in the main BOM file
all services are using correctly the internal registry except redis which is defined in the dependencies section in the yml and trying to pull from gcr.io . 

### Steps to Reproduce:

deploy from local bom using this file:

```
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: <my-registry>/spinnaker-marketplace
  gitPrefix: https://github.com/spinnaker
  googleImageProject: marketplace-spinnaker-release
dependencies:
  consul:
    version: local:0.7.5
  redis:
    version: local:2:2.8.4-2
  vault:
    version: local:0.7.0
services:
  clouddriver:
    commit: f6836b774769e1d6d11f35ab7bc3319634806247
    version: local:4.2.5-20190128101926
  deck:
    commit: e4352428e5908dedcfcf6947e8e407825a79bed0
    version: local:2.6.5-20190128135214
  defaultArtifact: {}
  echo:
    commit: 22a704dc9dcfcea2566b62e231d95982bd387745
    version: local:.2.3-20190104153242
  fiat:
    commit: 71ce64586a6d6fa202dc7e6cc2b3063276357a04
    version: local:1.3.1-20190126042507
  front50:
    commit: 129b40767f7586ae7c7dbc1d213b73be9d12b5af
    version: local:0.14.1-20190128101926
  gate:
    commit: b83dea9f35024f18592f1741dcb62b3a7b82c086
    version: local:1.4.0-20181217192627
  igor:
    commit: 0b3a637e199ee1ac030a7a7fe7bf44139a41668a
    version: local:1.0.0-20181207134351
  kayenta:
    commit: 8a49a32291fc139d4772fdf45efd832c28b7d171
    version: local:0.5.1-20190104141519
  monitoring-daemon:
    commit: 4b7e19ec916878f296cfc476d2e70ce5edfa3e5c
    version: local:0.10.2-20190114132151
  monitoring-third-party:
    commit: 4b7e19ec916878f296cfc476d2e70ce5edfa3e5c
    version: local:0.10.2-20190114132151
  orca:
    commit: 352222d11c295eb83226759524de495a18aee4e9
    version: local:2.2.1-20190123222535
  rosco:
    commit: 0e336fcba0a56dcd93f4692c4cc798b9b887fc7f
    version: local:0.8.2-20181221095200
timestamp: '2019-01-28 18:52:30'
version: 1.11.8

```

**Comment by louisjimenez** [comment]
@spinnakerbot add-label component/halyard

**Comment by papanito** [comment]
Did you run `hal config version edit --version local:1.11.8`?
I try to do the same as you but with slightly different result: #4062

**Comment by schefs** [comment]
> Did you run `hal config version edit --version local:1.11.8`?
> I try to do the same as you but with slightly different result: #4062

yes i did. all images are pulled from custom repository except redis. the only difference in my observation is that its not defined as a main service like all other deck,gate, etc... its in a "dependency" section in the yml file.
20 days passed and still I was not able to fix this issue and I can't run spinnaker in my on-premise air-gapped environment.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by schefs** [comment]
@spinnakerbot remove-label stale

still experiencing the same issue with halyard 1.19.0 deploying spinnaker 1.13.4 (latest for both) and redis deployment is not pulling from the internal repository.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by jdoshi1** [comment]
I'm facing the same issue. It looks like the redis image `gcr.io/kubernetes-spinnaker/redis-cluster:v2`  is hardcoded in the halyard repo - https://github.com/spinnaker/halyard/search?q=redis-cluster%3Av2&unscoped_q=redis-cluster%3Av2
@schefs did you find any work arounds?

**Comment by schefs** [comment]
@spinnakerbot remove-label stale
@jdoshi1 sadly I didn't find any solution for months and just gave up on using spinnaker. 
Not because its a "buggy product" . I'm sure you can find a "temporary bandage fix" for this one in your environment. I gave up only because the lack of support here and on other platforms like slack. Plus its seems like not many people have encountered air-gaped on-premise problems (not many out there I guess) so with the lack of support I'm not willing to take the changes that I'll have production deployments are at risk and will not not get the appropriate response from spinnaker developers.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by amitbitcse** [comment]
@schefs The local BOM only references private registry for the Spinnaker services and not the dependent services like redis. If you want to pull image of redis from your own private registry, create a file `~/.hal/$DEPLOYMENT/service-settings/redis.yml` with below content where $DEPLOYMENT is typically default.

`artifactId: <my-registry>/gcr.io/kubernetes-spinnaker/redis-cluster:v2`

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by spinnakerbot** [comment]
This issue is tagged as 'to-be-closed' and hasn't been updated  in 45 days, so we are closing it. You can always reopen this issue if needed.

**Comment by fherbert** [comment]
@schefs you can use the kustomize field in the SpinnakerService resource to override the redis-cluster image:
```
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  ...
  kustomize:
    redis:
      deployment:
        patchesStrategicMerge:
          - |
            spec:
              template:
                spec:
                  containers:
                  - name: redis
                    image: <my-registry>/redis-cluster:v2
```
