### ISSUE TITLE
Why not use HTTPGetAction instead of ExecAction or TCPSocketAction for components deployed to k8s?

### ISSUE THREAD

**Issue by davidxia** [spinnaker/spinnaker#4022]
### Issue Summary:

Why not use HTTPGetAction instead of ExecAction or TCPSocketAction for components deployed to k8s?

### Cloud Provider(s):

kubernetes, GKE

### Environment:

deploy spinnaker with kube v2 provider to GKE with halyard

### Feature Area (if this issue is UI/UX related, please tag @spinnaker/ui-ux-team):

halyard

### Description:

I deploy Spinnaker with halyard to K8s. I noticed all the components' readinessProbes' [handlers](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes) are either ExecActions or TCPSocketActions. With the exception of redis, I think all of them can be [HTTPGetActions](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#httpgetaction-v1-core). This would simplify the readinessProbes to not need `wget` or, in the case of TCPSocketActions, would be a more complete probe by checking the HTTP status code.

Am I missing something? Is there a reason they're all exec's and tcp's?

| component  | current handler | proposed handler |
| ------------- | ------------- | -------------------- |
| clouddriver  | exec  | http |
| deck  | tcp  | http |
| echo | exec | http |
| front50 | exec | http |
| gate | exec | http |
| orca | exec | http |
| rosco | exec | http |
| redis | tcp | tcp |

### Steps to Reproduce:

Deploy Spinnaker with Halyard to k8s with all the defaults.

### Additional Details:

Here are the k8s Pod YAMLs applied by halyard.

```yaml
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-clouddriver-5559d44484-mp8q9
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/clouddriver:4.3.1-20190130095322
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: clouddriver
      ports:
      - containerPort: 7002
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:7002/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "20"
          memory: 5000Mi
        requests:
          cpu: "20"
          memory: 5000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-clouddriver-files-1952526246
      - mountPath: /home/halyard/.hal/k8s-spinnaker/staging/dependencies
        name: spin-clouddriver-files-1757773194
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-9vq9
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 720
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-clouddriver-files-1952526246
      secret:
        defaultMode: 420
        secretName: spin-clouddriver-files-1952526246
    - name: spin-clouddriver-files-1757773194
      secret:
        defaultMode: 420
        secretName: spin-clouddriver-files-1757773194
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-deck-5d78c99957-dkrqg
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: AUTH_ENABLED
        value: "false"
      - name: FIAT_ENABLED
        value: "false"
      image: gcr.io/spinnaker-marketplace/deck:2.7.1-20190131030608
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: deck
      ports:
      - containerPort: 9000
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 9000
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 30Mi
        requests:
          cpu: 200m
          memory: 30Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-deck-files-453000897
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d497067b-5wm3
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-deck-files-453000897
      secret:
        defaultMode: 420
        secretName: spin-deck-files-453000897
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-echo-6dcc588fb9-7k26t
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/echo:2.3.0-20190123160119
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: echo
      ports:
      - containerPort: 8089
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8089/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 3000Mi
        requests:
          cpu: 200m
          memory: 3000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-echo-files-320389460
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-j0j5
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-echo-files-320389460
      secret:
        defaultMode: 420
        secretName: spin-echo-files-320389460
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-front50-66c9cd68d8-kb972
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      image: gcr.io/spinnaker-marketplace/front50:0.15.0-20190123161040
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: front50
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8080/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 3000Mi
        requests:
          cpu: 200m
          memory: 3000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-front50-files-1204564507
      - mountPath: /home/halyard/.hal/k8s-spinnaker/staging/dependencies
        name: spin-front50-files-686274265
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-k1t4
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-front50-files-1204564507
      secret:
        defaultMode: 420
        secretName: spin-front50-files-1204564507
    - name: spin-front50-files-686274265
      secret:
        defaultMode: 420
        secretName: spin-front50-files-686274265
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-gate-846c5dbb9c-hgft4
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/gate:1.5.0-20190123161040
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: gate
      ports:
      - containerPort: 8084
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8084/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 1800Mi
        requests:
          cpu: 200m
          memory: 1800Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-gate-files-1410509960
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-j0j5
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-gate-files-1410509960
      secret:
        defaultMode: 420
        secretName: spin-gate-files-1410509960
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-orca-85f7bb6585-8bt5l
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/orca:2.3.0-20190128134206
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command:
            - bash
            - /opt/spinnaker/scripts/shutdown.sh
      name: orca
      ports:
      - containerPort: 8083
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8083/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 600m
          memory: 3000Mi
        requests:
          cpu: 600m
          memory: 3000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-orca-files-399748092
      - mountPath: /opt/spinnaker/scripts
        name: spin-orca-files-795629369
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d497067b-nzz1
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-orca-files-399748092
      secret:
        defaultMode: 420
        secretName: spin-orca-files-399748092
    - name: spin-orca-files-795629369
      secret:
        defaultMode: 420
        secretName: spin-orca-files-795629369
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-redis-55fd76957f-2xdr5
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: MASTER
        value: "true"
      image: gcr.io/kubernetes-spinnaker/redis-cluster:v2
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: redis
      ports:
      - containerPort: 6379
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 6379
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 600m
          memory: 450Mi
        requests:
          cpu: 400m
          memory: 300Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-971e980a-718n
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-rosco-6bb7fddd59-tfflj
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/rosco:0.9.0-20190123170846
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: rosco
      ports:
      - containerPort: 8087
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8087/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 2000Mi
        requests:
          cpu: 200m
          memory: 2000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-rosco-files-1223233175
      - mountPath: /opt/rosco/config/packer
        name: spin-rosco-files-1649034632
      - mountPath: /opt/rosco/config/packer/scripts
        name: spin-rosco-files-2090299775
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-j0j5
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-rosco-files-2090299775
      secret:
        defaultMode: 420
        secretName: spin-rosco-files-2090299775
    - name: spin-rosco-files-1223233175
      secret:
        defaultMode: 420
        secretName: spin-rosco-files-1223233175
    - name: spin-rosco-files-1649034632
      secret:
        defaultMode: 420
        secretName: spin-rosco-files-1649034632
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
```
