### ISSUE TITLE
Support enabling livenessProbes for Spinnaker components deployed to K8s

### ISSUE THREAD

**Issue by davidxia** [spinnaker/spinnaker#4023]
### Issue Summary:

Is there a way to enable livenessProbes for Spinnaker components deployed to K8s?

### Cloud Provider(s):

kubernetes, GKE

### Environment:

deploy spinnaker 1.12.1 with kube v2 provider to GKE 1.10.11-gke.1 with halyard 1.2.0-20180509113540

### Feature Area (if this issue is UI/UX related, please tag @spinnaker/ui-ux-team):

halyard

### Description:

I checked the docs for halyard [here](https://www.spinnaker.io/reference/halyard/commands/) and [searched halyard PRs for "liveness"](https://github.com/spinnaker/halyard/pulls?utf8=%E2%9C%93&q=is%3Apr+liveness+). I wasn't able to find any mention of support for K8s livenessProbes.

Is there a way to enable livenessProbes for Spinnaker components deployed to K8s? If not, is there any interest in supporting them?

#### Use case

Our Spinnaker instance deployed to GKE has one Pod per component. We only have one pipeline which simply applies a base64 artifact of multiple K8s YAMLs to various GKE clusters. One day after running fine for a week, every pipeline execution failed one after the other with the following error in the UI.

![image](https://user-images.githubusercontent.com/480621/53290264-4b8dea00-376f-11e9-9b10-c2836715facf.png)

Clouddriver Pod seemed unhealthy:

```
$ kubectl -it exec spin-clouddriver-5559d44484-mp8q9  /bin/bash -n spinnaker-test
$ wget http://localhost:7002/health
--2019-02-22 14:32:30--  http://localhost:7002/health
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:7002...
```

We saw a bunch of hanging wget from the readinessProbe:

```
$ ps -ef
PID   USER     TIME  COMMAND
    1 spinnake  2d21 /usr/lib/jvm/java-1.8-openjdk/bin/java -Djava.security.egd=file:/dev/./urandom -Dspring.config.location=/opt/spinnaker/config/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForH
21724 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
45146 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
73909 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
110854spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
153746spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
188385spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
214686spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
239825spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
266463spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
292188spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
314909spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
341368spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
365488spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
388704spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
417709spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
456478spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
490946spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
519033spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
550694spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
584750spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
617622spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
656575spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
686816spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
694199spinnake  0:00 /bin/bash
706661spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=inferno -o json get BackendConfig
706662spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=creator-x -o json get BackendConf
706664spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=research-platform -o json get Bac
706666spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=sonalytic -o json get BackendConf
706668spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=web-platform -o json get BackendC
706680spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_europe-west1_europe-west1-s41l --namespace=debrepo -o json get BackendCo
706694spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=lexikon -o json get BackendConfig
706719spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=cloudability -o json get BackendC
706732spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=essence -o json get BackendConfig
707158spinnake  0:00 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_us-central1_us-central1-b04t --namespace=k8s-itgc -o json get BackendCon
707209spinnake  0:00 ps -ef
3149702 spinnake  0:05 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_us-central1_us-central1-b04t --namespace=default -o json get namespace
3150325 spinnake  0:04 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_production-asia-east1 --namespace=default -o json get custo
3150945 spinnake  0:00 [kubectl]
3151074 spinnake  0:05 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=default -o json get namespace
3151310 spinnake  0:04 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_europe-west1_production-europe-west1 --namespace=default -o json get c
3151350 spinnake  0:00 [kubectl]
3152215 spinnake  0:04 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_asia-east1-k33l --namespace=default -o json get namespace
3158564 spinnake  0:04 kubectl --kubeconfig=/home/halyard/.hal/k8s-spinnaker/staging/dependencies/1167586265-config --context=gke_gke-xpn-1_asia-east1_production-asia-east1 --namespace=default -o json get custo
3587477 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3621286 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3648166 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3679248 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3708648 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3737769 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3765940 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3791635 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3816116 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3852108 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3884710 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3911102 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3940979 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3967962 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
3998680 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
4036199 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
4077934 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
4102261 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
4128607 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
4161052 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
4187130 spinnake  0:00 wget --no-check-certificate --spider -q http://localhost:7002/health
```

Our hypothesis is that if clouddriver had a livenessProbe, it would fail when clouddriver gets into this state. The Pod would be restarted, and our Spinnaker instance would be happy again.

### Steps to Reproduce:

Deploy Spinnaker with Halyard to K8s with all the defaults.

### Additional Details:

Here are the K8s Pod YAMLs created by the Deployments as applied by halyard. Note there are no `livenessProbe`s.

```yaml
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-clouddriver-5559d44484-mp8q9
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/clouddriver:4.3.1-20190130095322
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: clouddriver
      ports:
      - containerPort: 7002
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:7002/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: "20"
          memory: 5000Mi
        requests:
          cpu: "20"
          memory: 5000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-clouddriver-files-1952526246
      - mountPath: /home/halyard/.hal/k8s-spinnaker/staging/dependencies
        name: spin-clouddriver-files-1757773194
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-9vq9
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 720
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-clouddriver-files-1952526246
      secret:
        defaultMode: 420
        secretName: spin-clouddriver-files-1952526246
    - name: spin-clouddriver-files-1757773194
      secret:
        defaultMode: 420
        secretName: spin-clouddriver-files-1757773194
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-deck-5d78c99957-dkrqg
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: AUTH_ENABLED
        value: "false"
      - name: FIAT_ENABLED
        value: "false"
      image: gcr.io/spinnaker-marketplace/deck:2.7.1-20190131030608
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: deck
      ports:
      - containerPort: 9000
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 9000
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 30Mi
        requests:
          cpu: 200m
          memory: 30Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-deck-files-453000897
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d497067b-5wm3
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-deck-files-453000897
      secret:
        defaultMode: 420
        secretName: spin-deck-files-453000897
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-echo-6dcc588fb9-7k26t
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/echo:2.3.0-20190123160119
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: echo
      ports:
      - containerPort: 8089
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8089/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 3000Mi
        requests:
          cpu: 200m
          memory: 3000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-echo-files-320389460
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-j0j5
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-echo-files-320389460
      secret:
        defaultMode: 420
        secretName: spin-echo-files-320389460
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-front50-66c9cd68d8-kb972
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      image: gcr.io/spinnaker-marketplace/front50:0.15.0-20190123161040
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: front50
      ports:
      - containerPort: 8080
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8080/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 3000Mi
        requests:
          cpu: 200m
          memory: 3000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-front50-files-1204564507
      - mountPath: /home/halyard/.hal/k8s-spinnaker/staging/dependencies
        name: spin-front50-files-686274265
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-k1t4
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-front50-files-1204564507
      secret:
        defaultMode: 420
        secretName: spin-front50-files-1204564507
    - name: spin-front50-files-686274265
      secret:
        defaultMode: 420
        secretName: spin-front50-files-686274265
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-gate-846c5dbb9c-hgft4
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/gate:1.5.0-20190123161040
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: gate
      ports:
      - containerPort: 8084
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8084/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 1800Mi
        requests:
          cpu: 200m
          memory: 1800Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-gate-files-1410509960
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-j0j5
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-gate-files-1410509960
      secret:
        defaultMode: 420
        secretName: spin-gate-files-1410509960
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-orca-85f7bb6585-8bt5l
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/orca:2.3.0-20190128134206
      imagePullPolicy: IfNotPresent
      lifecycle:
        preStop:
          exec:
            command:
            - bash
            - /opt/spinnaker/scripts/shutdown.sh
      name: orca
      ports:
      - containerPort: 8083
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8083/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 600m
          memory: 3000Mi
        requests:
          cpu: 600m
          memory: 3000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-orca-files-399748092
      - mountPath: /opt/spinnaker/scripts
        name: spin-orca-files-795629369
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d497067b-nzz1
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-orca-files-399748092
      secret:
        defaultMode: 420
        secretName: spin-orca-files-399748092
    - name: spin-orca-files-795629369
      secret:
        defaultMode: 420
        secretName: spin-orca-files-795629369
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-redis-55fd76957f-2xdr5
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: MASTER
        value: "true"
      image: gcr.io/kubernetes-spinnaker/redis-cluster:v2
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: redis
      ports:
      - containerPort: 6379
        protocol: TCP
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 6379
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 600m
          memory: 450Mi
        requests:
          cpu: 400m
          memory: 300Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-971e980a-718n
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
---
- apiVersion: v1
  kind: Pod
  metadata:
    name: spin-rosco-6bb7fddd59-tfflj
    namespace: spinnaker-test
  spec:
    containers:
    - env:
      - name: JAVA_OPTS
        value: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
      - name: SPRING_PROFILES_ACTIVE
        value: local
      image: gcr.io/spinnaker-marketplace/rosco:0.9.0-20190123170846
      imagePullPolicy: IfNotPresent
      lifecycle: {}
      name: rosco
      ports:
      - containerPort: 8087
        protocol: TCP
      readinessProbe:
        exec:
          command:
          - wget
          - --no-check-certificate
          - --spider
          - -q
          - http://localhost:8087/health
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 200m
          memory: 2000Mi
        requests:
          cpu: 200m
          memory: 2000Mi
      securityContext:
        allowPrivilegeEscalation: false
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /opt/spinnaker/config
        name: spin-rosco-files-1223233175
      - mountPath: /opt/rosco/config/packer
        name: spin-rosco-files-1649034632
      - mountPath: /opt/rosco/config/packer/scripts
        name: spin-rosco-files-2090299775
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-w2lt5
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: gke-production-us-ce-terraform-201812-d63606d6-j0j5
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 60
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: spin-rosco-files-2090299775
      secret:
        defaultMode: 420
        secretName: spin-rosco-files-2090299775
    - name: spin-rosco-files-1223233175
      secret:
        defaultMode: 420
        secretName: spin-rosco-files-1223233175
    - name: spin-rosco-files-1649034632
      secret:
        defaultMode: 420
        secretName: spin-rosco-files-1649034632
    - name: default-token-w2lt5
      secret:
        defaultMode: 420
        secretName: default-token-w2lt5
```
