### ISSUE TITLE
Halyard deploy custom bom fails with `metadata.labels: Invalid value: "local:1.12.4"`

### ISSUE THREAD

**Issue by papanito** [spinnaker/spinnaker#4062]
### Issue Summary:

When deploying a custom bom from local filesystem this fails with

```bash
The Deployment "spin-clouddriver" is invalid:                                                                      
* metadata.labels: Invalid value: "local:1.12.4": a valid label must be an empty                                   
  string or consist of alphanumeric characters, '-', '_' or '.', and must start                                    
  and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or                                      
  '12345', regex used for validation is                                                                            
  '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')                                                                   
* spec.template.labels: Invalid value: "local:1.12.4": a valid label must be an                                    
  empty string or consist of alphanumeric characters, '-', '_' or '.', and must                                    
  start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',                                    
  or '12345', regex used for validation is                                                                         
  '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')                                                                                                                   
````

### Cloud Provider(s):

N/A

### Environment:

Running on-premise (air-gaped)

### Feature Area (if this issue is UI/UX related, please tag @spinnaker/ui-ux-team):

halyard

### Description:

When deploying a custom bom from local filesystem it seems that the version `local:1.12.4` is used as label when not expected.

```bash
spinnaker@spinnaker-spinnaker-halyard-0:/workdir$ hal config version edit --version local:1.12.4                   
+ Get current deployment                                                                                           
  Success                                                                                                          
+ Edit Spinnaker version                                                                                           
  Success                                                                                                          
Problems in halconfig:                                                                                             
- WARNING There is a newer version of Halyard available (1.16.0),                                                  
  please update when possible                                                                                      
? Run 'sudo apt-get update && sudo apt-get install                                                                 
  spinnaker-halyard -y' to upgrade                                                                                 
                                                                                                                   
+ Spinnaker has been configured to update/install version                                                          
  "local:1.12.4". Deploy this version of Spinnaker with `hal deploy apply`.                                        
spinnaker@spinnaker-spinnaker-halyard-0:/workdir$ hal deploy apply                                                 
+ Get current deployment                                                                                           
  Success                                                                                                          
+ Prep deployment                                                                                                  
  Success                                                                                                          
Problems in default.provider.dockerRegistry.sc-proxy:                                                              
- WARNING Your docker registry has no repositories specified, and                                                  
  the registry's catalog is empty. Spinnaker will not be able to deploy any images                                 
  until some are pushed to this registry.                                                                          
? Manually specify some repositories for this docker registry to                                                   
  index.                                                                                                           
                                                                                                                   
Problems in halconfig:                                                                                             
- WARNING There is a newer version of Halyard available (1.16.0),                                                  
  please update when possible                                                                                      
? Run 'sudo apt-get update && sudo apt-get install                                                                 
  spinnaker-halyard -y' to upgrade                                                                                 
                                                                                                                   
Problems in default.security:                                                                                      
- WARNING Your UI or API domain does not have override base URLs                                                   
  set even though your Spinnaker deployment is a Distributed deployment on a                                       
  remote cloud provider. As a result, you will need to open SSH tunnels against                                    
  that deployment to access Spinnaker.                                                                             
? We recommend that you instead configure an authentication                                                        
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker                                         
  securely, and then register the intended Domain and IP addresses that your                                       
  publicly facing services will be using.                                                                          
                                                                                                                   
Problems in default.provider.dockerRegistry.sc-private:                                                            
- WARNING Your docker registry has no repositories specified, and                                                  
  the registry's catalog is empty. Spinnaker will not be able to deploy any images                                 
  until some are pushed to this registry.                                                                          
? Manually specify some repositories for this docker registry to                                                   
  index.                                                                                                           
                                                                                                                   
+ Preparation complete... deploying Spinnaker                                                                      
+ Get current deployment                                                                                           
  Success                                                                                                          
- Apply deployment                                                                                                 
  Failure                                                                                                          
Problems in Global:                                                                                                
! ERROR Failed to deploy manifest:                                                                                 
apiVersion: apps/v1beta2                                                                                           
kind: Deployment                                                                                                   
metadata:                                                                                                          
  name: spin-clouddriver                                                                                           
  namespace: spinnaker                                                                                             
annotations: {moniker.spinnaker.io/application: '"spin"',                                                          
  moniker.spinnaker.io/cluster: '"clouddriver"'}                                                                   
labels: {app: spin, cluster: spin-clouddriver, app.kubernetes.io/name:                                             
  clouddriver,                                                                                                     
app.kubernetes.io/managed-by: halyard, app.kubernetes.io/part-of: spinnaker,                                       
  app.kubernetes.io/version: 'local:1.12.4'}                                                                       
spec:                                                                                                              
  replicas: 1                                                                                                      
  selector:                                                                                                        
    matchLabels: {app: spin, cluster: spin-clouddriver}                                                            
  template:                                                                                                        
    metadata:                                                                                                      
      annotations: {}                                                                                              
labels: {app: spin, cluster: spin-clouddriver, app.kubernetes.io/name:                                             
  clouddriver,                                                                                                     
    app.kubernetes.io/managed-by: halyard, app.kubernetes.io/part-of: spinnaker,                                   
        app.kubernetes.io/version: 'local:1.12.4'}                                                                 
    spec:                                                                                                          
      containers:                                                                                                  
      - name: clouddriver                                                                                          
image:                                                                                                             
  nexus.intra:5000/spinnaker-marketplace/clouddriver:4.3.4-20190301030607                                    
        ports:                                                                                                     
        - {containerPort: 7002}                                                                                    
        readinessProbe:                                                                                            
          exec:                                                                                                    
            command: [wget, --spider, -q, 'http://localhost:7002/health']                                          
        volumeMounts:                                                                                              
     - {name: spin-clouddriver-files-41059968, mountPath: /opt/spinnaker/config}                                   
        lifecycle: {}                                                                                              
        env:                                                                                                       
- {name: JAVA_OPTS, value: '-XX:+UnlockExperimentalVMOptions                                                       
  -XX:+UseCGroupMemoryLimitForHeap                                                                                 
            -XX:MaxRAMFraction=2'}                                                                                 
        - {name: SPRING_PROFILES_ACTIVE, value: local}                                                             
        resources:                                                                                                 
          requests: {}                                                                                             
          limits: {}                                                                                               
      terminationGracePeriodSeconds: 720                                                                           
      volumes:                                                                                                     
      - name: spin-clouddriver-files-41059968                                                                      
        secret: {secretName: spin-clouddriver-files-41059968}                                                      
                                                                                                                   
The Deployment "spin-clouddriver" is invalid:                                                                      
* metadata.labels: Invalid value: "local:1.12.4": a valid label must be an empty                                   
  string or consist of alphanumeric characters, '-', '_' or '.', and must start                                    
  and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or                                      
  '12345', regex used for validation is                                                                            
  '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')                                                                   
* spec.template.labels: Invalid value: "local:1.12.4": a valid label must be an                                    
  empty string or consist of alphanumeric characters, '-', '_' or '.', and must                                    
  start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',                                    
  or '12345', regex used for validation is                                                                         
  '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')            
```

### Steps to Reproduce:

1. Add bom as `additionalConfigMap`
1. Map the bom

    ```bash
    mkdir -p ~/.hal/.boms/bom
    ln -s /opt/halyard/additionalConfigMaps/bom_1.12.4.yml ~/.hal/.boms/bom/1.12.4.yml
    ```

1. Set version and apply config

    ```bash
    hal config version edit --version local:1.12.4
    hal deploy apply
    ```

**Expected**

Images are pulled from internal nexus repo, but 

### Additional Details:

#### values.yml

The `values.yml` contains the config map for the `bom`

```yml

halyard:
  spinnakerVersion: 1.11.6
  image:
    repository: ci-tools.sc.intra:5000/spinnaker-marketplace/halyard
    tag: stable
    env: 
    - name: "JAVA_OPTS"
      value: -Dhttps.proxyHost=webproxy.sc.intra -Dhttps.proxyPort=9090 -Dhttp.proxyHost=webproxy.sc.intra -Dhttp.proxyPort=9090 -DnonProxyHosts=.sc.intra,*.sc.intra,localhost,127.0.0.1,0,1,2,3,4,5,6,7,8,9 -Djavax.net.debug=all
  # Provide a config map with Hal commands that will be run the core config (storage)
  # The config map should contain a script in the config.sh key
  additionalConfig:
    enabled: false
    configMapName: my-halyard-config
    configMapKey: config.sh
  persistence:
    enabled: false
  additionalConfigMaps:
    create: true
    data:
      # https://storage.googleapis.com/halconfig/bom
      bom_1.12.4.yml: |
        version: 1.12.4
        timestamp: '2019-03-01 08:06:24'
        services:
          echo:
            version: 2.3.1-20190214121429
            commit: 5db9d437ca7f2fa374dcada17f77bbbb2965bd67
          clouddriver:
            version: 4.3.4-20190301030607
            commit: b5539c47aad309e24428abb8f8303aff45323b43
          deck:
            version: 2.7.4-20190228030607
            commit: dccdd730886a6beb0388e3622581d8da1ed8edbb
          fiat:
            version: 1.3.2-20190128153726
            commit: daf21b24330a5f22866601559aa0f7ac99590274
          front50:
            version: 0.15.2-20190222161456
            commit: 3105e86b8c084ad6ad78507e3a5e5a427f290b99
          gate:
            version: 1.5.2-20190301030607
            commit: b238ab993ab25381ce907260879548ed74a4953f
          igor:
            version: 1.1.1-20190213190226
            commit: 63d06a5c5d55f07443dd60a81035b35cf96238e7
          kayenta:
            version: 0.6.1-20190221030610
            commit: 81d906bf8307143f40fe88f8554baa318de25ef1
          orca:
            version: 2.3.1-20190220030610
            commit: bad45e78566449117b678a3317552cf53d0dd14e
          rosco:
            version: 0.9.0-20190123170846
            commit: 42f81a2501de6d40676d47661579a6106b5c3e8a
          defaultArtifact: {}
          monitoring-third-party:
            version: 0.11.2-20190222030609
            commit: 232c84a8a87cecbc17f157dd180643a8b2e6067a
          monitoring-daemon:
            version: 0.11.2-20190222030609
            commit: 232c84a8a87cecbc17f157dd180643a8b2e6067a
        dependencies:
          redis:
            version: 2:2.8.4-2
          consul:
            version: 0.7.5
          vault:
            version: 0.7.0
        artifactSources:
          debianRepository: https://nexus.intra/repository/spinnaker-releases/
          dockerRegistry: nexus.intra:5000/spinnaker-marketplace
          googleImageProject: marketplace-spinnaker-release
          gitPrefix: https://scm.intra/scm/SPIN/repos
```

**Comment by papanito** [comment]
It appeared that although specified to use `stable` the image that was pulled was `1.10.1-20180912131447`. 
Specifying `1.16.0` explicitly forced k8s to pull the latest stable version
```yaml
  image:
    repository: ci-tools.sc.intra:5000/spinnaker-marketplace/halyard
    tag: stable
```
I suspect this is an issue from our internal docker repo. 
Thus, this issue is fixed with `1.16.0`

**Comment by rushins** [comment]
i got issue when using Minio storage file added 
echo "spinnaker.s3.versioning: false" > ~/.hal/default/profiles/front50-local.yml

hal deploy apply error
-------
 Invalid value: "spinnaker.s3.versioning:": a
  valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g.
  'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is
  '[-._a-zA-Z0-9]+'), metadata=ListMeta(resourceVersion=null, selfLink=null,
  additionalProperties={}), reason=Invalid, status=Failure,
  additionalProperties={}).
-----------

any idea how to fix.

**Comment by jdoshi1** [comment]
@papanito While using custom bom, do you need to add the custom halconfigs for each service under .boms dir? ex: ~/.hal/.boms/<service>.yml ? Is there a way to use default if nothing is provided?

**Comment by papanito** [comment]
For services you need to add configs under `additionalServiceSettings`

```
  ## Define custom settings for Spinnaker services. Read more for details:
  ## https://www.spinnaker.io/reference/halyard/custom/#custom-service-settings
  ## You can use it to add annotations for pods, override the image, etc.
  ### We need to ount `cacerts` to the follwoing containers so that they can connect to the external services
  ### 
  ### - `clouddriver`
  ### - `igor` (for jenkins connection)
  ### - `fiat` (for ldap)
  additionalServiceSettings:
    igor.yml:
      kubernetes:
        volumes:
        - id: sc-cacerts
          mountPath: /etc/ssl/certs/java
          type: secret
```
