### ISSUE TITLE
Kubernets v2 provider: deployKubernetesManifest.deployKubernetesManifest.Certificate.notValidKind

### ISSUE THREAD

**Issue by ealebed** [spinnaker/spinnaker#4080]
### Issue Summary:
I can't deploy manifest in kubernetes cluster via spinnaker (version 1.12.4), get error:
```
deployKubernetesManifest.deployKubernetesManifest.Certificate.notValidKind
```
In version 1.10.13 it deployed without any problems
### Cloud Provider(s):

kubernetes v2

### Environment:

Spinnaker 1.12.4 deployed by halyard onto kubernetes

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

kubernetes v2, artifacts

### Description:
I try to deploy cert-manager in my kubernetes cluster - [manifest](https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/cert-manager.yaml)

Of course, I add to my kubernetes account configuration 
```
        customResources:
        - kubernetesKind: Certificate
          versioned: false
        - kubernetesKind: Challenge
          versioned: false
        - kubernetesKind: ClusterIssuer
          versioned: false
        - kubernetesKind: Issuer
          versioned: false
        - kubernetesKind: Order
          versioned: false
```

In spinnaker version 1.10.13  I didn't have any problems with deploy this manifest. But after update to spinnaker version 1.12.14 I get error:

```
deployKubernetesManifest.deployKubernetesManifest.Certificate.notValidKind
```

### Steps to Reproduce:

Try to deploy to kubernetes cluster [manifest](https://raw.githubusercontent.com/jetstack/cert-manager/release-0.6/deploy/manifests/cert-manager.yaml) from spinnaker version 1.12.4
