### ISSUE TITLE
deploy apply fails with "Cannot get property 'user' on null object"

### ISSUE THREAD

**Issue by papanito** [spinnaker/spinnaker#4103]
### Issue Summary:

`hal deploy apply` fails with ` Cannot get property 'user' on null object` on kubernetes cluster

### Cloud Provider(s):

Kubernetes

### Environment:

CentOS 7
air-gapped

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

hal

### Steps to Reproduce:

1. Spin-up spinnaker-hal container
    
   ```bash
   helm install stable/spinnaker --name=spinnaker --namespace=spinnaker -f values.yml
   ```
1. Update `spinnaker-spinnaker-halyard` ,add an `env` and redeploy container

   ```yaml
   ...
   containers:
   - image: ci-tools.sc.intra:5000/spinnaker-marketplace/halyard:1.16.0
     imagePullPolicy: IfNotPresent
     name: halyard
     env:
     - name: JAVA_OPTS
       value: -Dhttps.proxyHost=proxy.intra -Dhttps.proxyPort=8080 -Dhttp.proxyHost=proxy.intra -Dhttp.proxyPort=8080 -DnonProxyHosts=.intra,*.intra,localhost,127.0.0.1
     ports:
     ...
   ```
1. Add docker registries

   ```bash
   hal config provider docker-registry enable
   hal config provider docker-registry account add docker-proxy --address https://nexus.intra:5000 --insecure-registry true
   ```

1. Add kubernetes account

   ```bash
  hal config provider kubernetes enable
  hal config provider kubernetes account add k8sdev --docker-registries=docker-proxy --context dev
   ```
1. Apply deployment

   ```bash
   hal deploy apply
  ```

Current error:

```bash
spinnaker@spinnaker-spinnaker-halyard-0:/workdir$ hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Problems in default.provider.dockerRegistry.sc-proxy:
- WARNING Your docker registry has no repositories specified, and
  the registry's catalog is empty. Spinnaker will not be able to deploy any images
  until some are pushed to this registry.
? Manually specify some repositories for this docker registry to
  index.

Problems in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
_ Apply deployment
...
  Failure
Problems in Global:
! ERROR Unexpected exception: java.lang.NullPointerException:
  Cannot get property 'user' on null object

- Failed to deploy Spinnaker.
```

#### Provider config

```bash
hal config provider kubernetes account get k8sdev
+ Get current deployment
  Success
+ Get k8sdev account
  Success
+ Account k8sdev:
KubernetesAccount(context=dev, cluster=null, user=null, configureImagePullSecrets=true, serviceAccount=null, cacheThreads=1, namespaces=[], omitNamespaces=[], kinds=[], omitKinds=[], customResources=[], cachingPolicies=[], kubeconfigFile=/home/spinnaker/.kube/config, kubeconfigContents=null, kubectlPath=null, kubectlRequestTimeoutSeconds=null, checkPermissionsOnStartup=true, liveManifestCalls=null, oAuthServiceAccount=null, oAuthScopes=[], namingStrategy=null, skin=null, onlySpinnakerManaged=false, debug=null, secretSessionManager=null)
+ K8SDEV

KubernetesAccount(context=dev, cluster=null, user=null,
configureImagePullSecrets=true, serviceAccount=null, cacheThreads=1,
namespaces=[], omitNamespaces=[], kinds=[], omitKinds=[], customResources=[],
cachingPolicies=[], kubeconfigFile=/home/spinnaker/.kube/config,
kubeconfigContents=null, kubectlPath=null, kubectlRequestTimeoutSeconds=null,
checkPermissionsOnStartup=true, liveManifestCalls=null,
oAuthServiceAccount=null, oAuthScopes=[], namingStrategy=null, skin=null,
onlySpinnakerManaged=false, debug=null, secretSessionManager=null)
```

#### kubeconf

Kubeconf is mapped in pod `spinnaker-spinnaker-halyard` to `~\.kube\conf`

```yaml
apiVersion: v1
clusters:
- cluster:
  certificate-authority-data:   <redacted>
  server: https://k8s.intra/k8s/clusters/xxxxx
  name: dev
contexts:
- context:
  cluster: dev
  namespace: spinnaker
  user: token-xxxxx
  name: dev
current-context: dev
kind: Config
preferences: {}
users:
- name: token-xxxxx
  user:
    token: token-xxxxx:<redacted>
```
