### ISSUE TITLE
Deplyoment of Helm Chart fails as  Clouddriver warns HelmArtifactCredentials : Invalid url: for local repos

### ISSUE THREAD

**Issue by papanito** [spinnaker/spinnaker#4177]
### Issue Summary:

I get the following error in the `bake` stage

```json
responseBody	"{\"timestamp\":1553266171400,\"status\":500,\"error\":\"Internal Server Error\",\"exception\":\"com.netflix.spinnaker.kork.web.exceptions.GenericExceptionHandlers$RetrofitErrorWrapper\",\"message\":\"500 \",\"body\":\"{\\\"error\\\":\\\"Internal Server Error\\\",\\\"exception\\\":\\\"com.netflix.spinnaker.clouddriver.artifacts.helm.HelmArtifactCredentials$FailedDownloadException\\\",\\\"message\\\":\\\"Unable to download the contents of artifact\\\",\\\"status\\\":500,\\\"timestamp\\\":1553266171397}\",\"url\":\"http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/\"}"
rootException	"com.netflix.spinnaker.kork.web.exceptions.GenericExceptionHandlers$RetrofitErrorWrapper"
```

### Cloud Provider(s):

On-premise kubernetes

### Environment:

CentOS 7
air-gapped

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

clouddriver

### Description:

Log of `rosco`

```java
--> HTTP PUT http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/
<--- HTTP 500 http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/ (89ms)
---> HTTP PUT http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/
<--- HTTP 500 http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/ (22ms)
---> HTTP PUT http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/
<--- HTTP 500 http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/ (37ms)
---> HTTP PUT http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/
<--- HTTP 500 http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/ (31ms)
---> HTTP PUT http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/
<--- HTTP 500 http://spin-clouddriver.spinnaker-2:7002/artifacts/fetch/ (85ms)
2019-03-22 14:49:31.399  WARN 1 --- [0.0-8087-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [retrofit.RetrofitError: 500 ]
```

Log of `clouddriver`

```java
2019-03-29 07:54:04.026 WARN 1 --- [ MvcAsync5] c.n.s.c.a.helm.HelmArtifactCredentials : Invalid url:

2019-03-29 07:54:04.029 ERROR 1 --- [0.0-7002-exec-4] c.n.s.k.w.e.GenericExceptionHandlers : Internal Server Error

com.netflix.spinnaker.clouddriver.artifacts.helm.HelmArtifactCredentials$FailedDownloadException: Unable to download the contents of artifact
at com.netflix.spinnaker.clouddriver.artifacts.helm.HelmArtifactCredentials.download(HelmArtifactCredentials.java:113) ~[clouddriver-artifacts.jar:na]
at com.netflix.spinnaker.clouddriver.artifacts.ArtifactDownloader.download(ArtifactDownloader.java:62) ~[clouddriver-artifacts.jar:na]
at com.netflix.spinnaker.clouddriver.controllers.ArtifactController.lambda$fetch$0(ArtifactController.java:65) ~[clouddriver-web.jar:na]
at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:106) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
at org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBodyReturnValueHandler$StreamingResponseBodyTask.call(StreamingResponseBodyReturnValueHandler.java:93) ~[spring-webmvc-4.3.20.RELEASE.jar:4.3.20.RELEASE]
at org.springframework.web.context.request.async.WebAsyncManager$5.run(WebAsyncManager.java:332) ~[spring-web-4.3.20.RELEASE.jar:4.3.20.RELEASE]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_191]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]
```

### Steps to Reproduce:

1. Setup a internal artifact helm-repo (Artifactory, Nexus)
1. Add repo to hal config example:

  ```bash
  hal config artifact helm account add helm-mycompany\
   --repository https://nexus.intra/repository/helm-mycompany/ --username=jfrog-rt-spinnaker --password
   ```
1. Create a pipeline with an expected artifact from helm repo
1. Create a bake step using the expected artifact
1. Trigger pipeline

### Additional Details

- It is not a permission problem as I can download the artifact with the user from within the clouddriver container using wget
- we use self-signed certificates in the artifact repos, but this cannot be the problem
   - spinnaker is able to read the index from the repo and thus get the artifacts

``` bash
hal --version
1.17.0-20190311152807
```

#### helm config (hal)

```yml
....
  helm:
    enabled: true
    accounts:
    - name: helm-mycompany
      repository: https://nexus.intra/repository/helm-mycompany/
    - name: helm-kubernetes-charts
      repository: https://nexus.intra/repository/helm-kubernetes-charts/
  ...
```

#### kubeconf

Kubeconf is mapped in pod spinnaker-spinnaker-halyard to `~\.kube\conf`

```yml
apiVersion: v1
clusters:
- cluster:
  certificate-authority-data:   <redacted>
  server: https://k8s.intra/k8s/clusters/xxxxx
  name: dev
- cluster:
  certificate-authority-data:   <redacted>
  server: https://k8s.intra/k8s/clusters/xxxxx
  name: sit
contexts:
- context:
  cluster: dev
  namespace: spinnaker
  user: token-xxxxx
  name: dev
- context:
  cluster: sit
  namespace: spinnaker
  user: token-xxxxx
  name: sit
current-context: dev
kind: Config
preferences: {}
users:
- name: token-xxxxx
  user:
    token: token-xxxxx:<redacted>
```

#### Spinnaker version info

`1.12.5` but with custom bom
```

version: 1.12.5
timestamp: '2019-03-08 23:26:14'
services:
  echo:
	version: 2.3.1-20190214121429
	commit: 5db9d437ca7f2fa374dcada17f77bbbb2965bd67
  clouddriver:
	version: 4.3.5-20190307172446
	commit: f87eb66fd55cd4df7497ef22528a11709745075d
  deck:
	version: 2.7.5-20190308182538
	commit: e9b899d63cb6ea15dc2d6c99a810c8b48886c6a5
  fiat:
	version: 1.3.2-20190128153726
	commit: daf21b24330a5f22866601559aa0f7ac99590274
  front50:
	version: 0.15.2-20190222161456
	commit: 3105e86b8c084ad6ad78507e3a5e5a427f290b99
  gate:
	version: 1.5.2-20190301030607
	commit: b238ab993ab25381ce907260879548ed74a4953f
  igor:
	version: 1.1.1-20190213190226
	commit: 63d06a5c5d55f07443dd60a81035b35cf96238e7
  kayenta:
	version: 0.6.1-20190221030610
	commit: 81d906bf8307143f40fe88f8554baa318de25ef1
  orca:
	version: 2.4.0-20190308182538
	commit: 5e911ff1c29bbc443ce48bcaefbc45f27d389edd
  rosco:
	version: 0.9.0-20190123170846
	commit: 42f81a2501de6d40676d47661579a6106b5c3e8a
  defaultArtifact: {}
  monitoring-third-party:
	version: 0.11.2-20190222030609
	commit: 232c84a8a87cecbc17f157dd180643a8b2e6067a
  monitoring-daemon:
	version: 0.11.2-20190222030609
	commit: 232c84a8a87cecbc17f157dd180643a8b2e6067a
dependencies:
  redis:
	version: 2:2.8.4-2
  consul:
	version: 0.7.5
  vault:
	version: 0.7.0
artifactSources:     
  debianRepository: https://nexus.intra/repository/spinnaker-releases/                
  dockerRegistry: nexus.intra:5000/spinnaker-marketplace           
  googleImageProject: marketplace-spinnaker-release                  
  gitPrefix: https://bitbucket.intra/scm/SPIN/repos
```

**Comment by frederiksf** [comment]
same version of spinnaker same issue.

**Comment by papanito** [comment]
I have tried the whole with different repositories
- local helm repo
- chartmuseum proxy

Tried it with artifactory and nexus as repo to exclude any issue particular to one tool

**Comment by papanito** [comment]
Eventually this may be an issue with the parsing of the `index.yml`

```
apiVersion: v1
entries:
  acs-engine-autoscaler:
  - apiVersion: v1
    created: 2019-03-28T15:23:45.781Z
    description: Scales worker nodes within agent pools
    digest: a6505719ff0efb8c1d26f8d8de7129c6d5c05572cdbdb1cadd79f0c7e42ce4d5
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: acs-engine-autoscaler
    sources:
    - https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
    urls:
    - local://acs-engine-autoscaler-0.1.0.tgz
    version: 0.1.0
  aerospike:
  - appVersion: v3.14.1.2
    created: 2019-03-28T15:23:46.423Z
    description: A Helm chart for Aerospike in Kubernetes
    digest: 9b21417f989f4beba7174ffcbeeb34e91254f7494ed39f61905b3f3b8cfae002
    home: http://aerospike.com
    icon: https://s3-us-west-1.amazonaws.com/aerospike-fd/wp-content/uploads/2016/06/Aerospike_square_logo.png
    keywords:
    - aerospike
    - big-data
    maintainers:
    - email: k.mousavizamani@travelaudience.com
      name: kavehmzta
    name: aerospike
    sources:
    - https://github.com/aerospike/aerospike-server
    urls:
    - local://aerospike-0.1.5.tgz
    version: 0.1.5
  airflow:
  - appVersion: 1.10.0
    created: 2019-03-28T15:23:47.811Z
    description: Airflow is a platform to programmatically author, schedule and monitor
      workflows
    digest: 0d2c965f5412309df0514660e212753099c7b61e74fd04bba8520e86adf02ca0
    home: https://airflow.apache.org/
    icon: https://airflow.apache.org/_images/pin_large.png
    keywords:
    - workflow
    - dag
    maintainers:
    - email: gaetan@xeberon.net
      name: gsemet
    name: airflow
    sources:
    - https://airflow.apache.org/
    urls:
    - local://airflow-0.9.0.tgz
    version: 0.9.0
  ambassador:
  - apiVersion: v1
    appVersion: 0.50.1
    created: 2019-03-28T15:23:48.256Z
    description: A Helm chart for Datawire Ambassador
    digest: aa09c62be843190cc85736ba59d6411579d83ba30e9305e6b2420ea013bb5979
    engine: gotpl
    home: https://www.getambassador.io/
    keywords:
    - api gateway
    - ambassador
    - datawire
    - envoy
    maintainers:
    - email: markus@maga.se
      name: flydiverny
    - email: flynn@datawire.io
      name: kflynn
    name: ambassador
    sources:
    - https://github.com/datawire/ambassador
    - https://github.com/prometheus/statsd_exporter
    urls:
    - local://ambassador-1.0.0.tgz
    version: 1.0.0
  ark:
  - apiVersion: v1
    appVersion: 0.8.2
    created: 2019-03-28T15:23:48.799Z
    description: A Helm chart for ark
    digest: 41b18bc9a4c6d0f301955d3e9109bffe4cedcf35066eb0be2ad5aba46f6f87cb
    home: https://heptio.com/products/#heptio-ark
    maintainers:
    - email: d-caruso@hotmail.it
      name: domcar
    - email: unguiculus@gmail.com
      name: unguiculus
    name: ark
    sources:
    - https://github.com/heptio/ark
    urls:
    - local://ark-1.0.0.tgz
    version: 1.0.0
  apm-server:
  - apiVersion: v1
    appVersion: 6.2.4
    created: 2019-03-28T15:23:49.006Z
    description: The server receives data from the Elastic APM agents and stores the
      data into a datastore like Elasticsearch
    digest: abc6f74b45f07ef2989bc49fe644acb04161c36e60fe21d5361b4e07f2b60fdb
    home: https://www.elastic.co/solutions/apm
    icon: https://www.elastic.co/assets/blt47799dcdcf08438d/logo-elastic-beats-lt.svg
    maintainers:
    - email: ykuoka@gmail.com
      name: mumoshu
    name: apm-server
    sources:
    - https://www.elastic.co/guide/en/apm/get-started/current/index.html
    urls:
    - local://apm-server-0.1.0.tgz
    version: 0.1.0
  anchore-engine:
  - appVersion: 0.1.6
    created: 2019-03-28T15:23:49.226Z
    description: Anchore container analysis and policy evaluation engine service
    digest: 11c02b84b885675ffec9556d02c56d75bfeea27f2360c8266682881bb7eaa02c
    engine: gotpl
    home: https://anchore.io
    icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
    keywords:
    - analysis
    - docker
    - anchore
    - anchore-engine
    - image
    - security
    maintainers:
    - email: zach@anchore.com
      name: zhill
    name: anchore-engine
    sources:
    - https://github.com/anchore/anchore-engine
    urls:
    - local://anchore-engine-0.1.0.tgz
    version: 0.1.0
generated: 2019-03-28T15:33:29.160Z
```
