### ISSUE TITLE
RFC: Network policies support (Halyard)

### ISSUE THREAD

**Issue by ncknt** [spinnaker/spinnaker#4200]
It is common for deployments to use network policies. In order to do that, users need to know the dependencies of the services (gate → fiat). This proposal aims to make it easy for users to define network policies without intimate knowledge of how Spinnaker services interact - while keeping the possibility to support sidecars.

Users typically need to apply network policies:
- on a deployment to a new namespace
- when new services are added/deployed
- on external CIDR change

## Scope
The scope of the changes is limited to Halyard.

## Defining ingress/egress rules
To define an ingress/egress rule, user would just need to provide the extra information:

e.g. 
```
    ingress:
    - from:
      - namespaceSelector:
        matchLabels:
          name: ingress-nginx
        ports:
        - protocol: TCP
          port: 8084
    egress:
    - to:
      - ipBlock:
        cidr: 172.0.0.0/8
```

Halyard would supplement with the rules that it knows are required:
```
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: spin-gate-network-policy
      namespace: NAMESPACE_NAME
    spec:
      podSelector:
        matchLabels:
          cluster: spin-gate
      ingress:
      - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
          ports:
          - protocol: TCP
            port: 8084
      egress :
      - to:
        - ipBlock:
            cidr: 172.0.0.0/8
      - to:
        - podSelector:
            matchLabels:
              cluster: spin-echo
        ports:
        - protocol: TCP
          port: 8089
    ...
      # Added iff Fiat is enabled
      - to:
        - podSelector:
            matchLabels:
              cluster: spin-fiat
        - protocol: TCP
          port: 7003
      # Added iff Redis is managed
      - to:
        - podSelector:
            matchLabels:
              cluster: spin-redis
        - protocol: TCP
          port: 6379
```

## Redis/Fiat/Kayenta/…

When Redis `skipLifeCycleManagement` is false, Redis rules would be added for the services that need it.

Similarly, Fiat and Kayenta rules would only be added if the services are enabled.

## New Configuration Directory

`.hal/<profile>/network-policies`: contains additional network policy definitions. It follows the usual spec and defines additional ingress and egress.

The file name reflects the service it’s customizing (`gate.yml`, `deck.yml`…)

## New commands
`hal network-policies apply` would generate the `NetworkPolicy` manifests and apply them in the namespace Spinnaker is deployed.

`hal network-policies generate` generates the manifests in `staging/network-policies`

## Implementation
pseudo-code.

Add NetworkPolicy data classes like in https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/api/networking/v1/types.go

```
    interface KubernetesSelector{}
    
    class PodSelector implements KubernetesSelector
      // matchLabels...
    
    class NamespaceSelector implements KubernetesSelector
     // MatchLabels...
    
    class IPBlock implements KubernetesSelector
     // cidr/except...
    
    class RulePortTarget 
      String protocol
      int port
    
    class NetworkPolicyRule
      List<KubernetesSelector> selectors
      List<RulePortTarget> portTargets
      
    class NetworkPolicy
      String namespace
      String policyName
      List<NetworkPolicyRule> from
      List<NetworkPolicyRule> to
```

```    
    // Changes to existing classes  
    interface KubernetesV2Service
     ...
      List<NetworkPolicyRule> getDefaultIngressRules();
      List<NetworkPolicyRule> getDefaultEgressRules();
```

On a `hal network-policies apply`, we’d:
For each service:
- Read and parse the customized services from `network-policies/`
- Add the default ingress/egress rules
- Add the namespace
- Submit the manifest

## Future improvements
- `hal network-policies validate` to validate common errors such as missing cidr from igor for Jenkins if configured.
