### ISSUE TITLE
Feature request: Cleanup kubernetes resources in cluster automatically 

### ISSUE THREAD

**Issue by ealebed** [spinnaker/spinnaker#4236]
### Issue Summary:
When resource manifest (yaml file) deleted from source of truth (github repo), resource should be deleted in k8s cluster

### Cloud Provider(s):
Kubernetes V2 (GKE)

### Environment:
I am running Spinnaker on Kubernetes GKE, version: 1.13.0

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@provider/kubernetes-v2

### Description:
1. When I have in my yaml file something like this:
```
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-memory-defaults-limit-range
  namespace: analytics
spec:
  limits:
  - default:
      cpu: "0.8"
      memory: 5.9Gi
    defaultRequest:
      cpu: "0.8"
      memory: 5.9Gi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    name: analytics
  name: analytics
  namespace: analytics
spec:
  hard:
    limits.cpu: "155"
    limits.memory: 1010Gi
    requests.cpu: "155"
    requests.memory: 1010Gi
```
And delete section `ResourceQuota`, this resource was not deleted in k8s cluster - I did it manually, by hand.

2. When I delete whole file (yaml manifect), resource is still running in cluster too.

Maybe will be good idea do something like `--prune` subcommand (in native `kubectl apply`) when deploy starts by GIT trigger?
