### ISSUE TITLE
Deployment fails with io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET

### ISSUE THREAD

**Issue by papanito** [spinnaker/spinnaker#4290]
### Issue Summary:

In a multi-cluster setup with configured proxy, `hal deploy apply` fails with
```bash
! ERROR Unexpected exception:
  io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET
  at:
  https://rancher.sc.intra/k8s/clusters/c-xxxxx/api/v1/namespaces/spinnaker/services/spin-redis-bootstrap.
```

### Cloud Provider(s):

On-premise kubernetes

### Environment:

CentOS 7
air-gapped

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

??

### Description:

We have multiple clusters which resides in different network zones.
- `sit`, `uat`, `dev` and `nop` are in the same zone `nonprd-zone`
- `tooling` and `acquiring` are in the same zone `prd-zone`
- spinnaker will be installed in `tooling` cluster
- `prd-zone` and `nonprd-zone` have a firewall in between, but `prd-zone` can connect to `nonprd-zone`
- To access external resources there is a `proxy` configured via `JAVA_OPTS`

```yaml
    env:
      - name: JAVA_OPTS
        value: -Dhttps.proxyHost=proxy.sc.intra -Dhttps.proxyPort=8080 -Dhttp.proxyHost=proxy.sc.intra -Dhttp.proxyPort=8080  -DnonProxyHosts="rancher.sc.intra|rancher.nop.sc.intra|*.nop.sc.intra|*.sc.intra|localhost|127.0.0.1"
```

When running `hal deploy apply` it seems the connection goes over the proxy and not directly as the error message suggests

```bash
spinnaker@spinnaker-spinnaker-halyard-0:/workdir$ hal deploy apply --no-validate
+ Get current deployment
  Success
+ Prep deployment
  Success
+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Problems in Global:
! ERROR Unexpected exception:
  io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET
  at:
  https://rancher.sc.intra/k8s/clusters/c-xxxxx/api/v1/namespaces/spinnaker/services/spin-redis-bootstrap.
  Message: Forbidden! User u-bbbbb doesn't have permission. <!DOCTYPE html PUBLIC
  "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
```

### Steps to Reproduce:
- spin up halyard
- login to halyard pod
- run `hal deploy apply`

### Additional Details:

```bash
$ hal --version
1.18.0-20190325172326
```

Curl from within `spinnaker` pod works fine towards the rancher url
```bash
spinnaker@spinnaker-spinnaker-halyard-0:/workdir$ curl -k https://rancher.sc.intra
{"type":"collection","links":{"self":"https://rancher.sc.intra/"},"actions":{},"pagination":{"limit":1000,"total":4}, ....
```
Also `kubectl` works fine:

```bash
spinnaker@spinnaker-spinnaker-halyard-0:~/.kube$ kubectl config use-context sit
Switched to context "sit".
spinnaker@spinnaker-spinnaker-halyard-0:~/.kube$ kubectl get pods -n ci-cd
NAME                                      READY     STATUS    RESTARTS   AGE
jenkins-slaves-acq-6f999bbf7-56tpg        2/2       Running   0          12h
jenkins-slaves-firebird-dc6c96554-sjzqx   2/2       Running   0          12h
jenkins-slaves-mpc-7c47cbdf4d-r56wb       2/2       Running   0          12h
spinnaker@spinnaker-spinnaker-halyard-0:~/.kube$ kubectl config use-context tooling
Switched to context "tooling".
spinnaker@spinnaker-spinnaker-halyard-0:~/.kube$ kubectl get pods -n spinnaker
NAME                                READY     STATUS      RESTARTS   AGE
spinnaker-install-using-hal-7mglp   0/1       Completed   0          9h
spinnaker-minio-6858999c6c-g8btj    1/1       Running     0          9h
spinnaker-redis-master-0            1/1       Running     0          9h
spinnaker-spinnaker-halyard-0       1/1       Running     0          2h
```` 

#### `kubeconf`

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: spinnaker-kubeconf 
type: Opaque
stringData:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        certificate-authority-data: <redacted>
        server: https://rancher.nop.sc.intra/k8s/clusters/c-aaaaa
      name: dev
    - cluster:
        certificate-authority-data: <redacted>
        server: https://rancher.nop.sc.intra/k8s/clusters/c-bbbbb
      name: nop
    - cluster:
        certificate-authority-data: <redacted>
        server: https://rancher.nop.sc.intra/k8s/clusters/c-ccccc
      name: sit
    - cluster:
        certificate-authority-data: <redacted>
        server: https://rancher.nop.sc.intra/k8s/clusters/c-ddddd
      name: uat
    - name: tooling
      cluster:
        server: https://rancher.sc.intra/k8s/clusters/c-xxxxx
        certificate-authority-data: <redacted>
    - name: acquiring
      cluster:
        server: https://rancher.sc.intra/k8s/clusters/c-yyyy
        certificate-authority-data: <redacted>
    contexts:
    - context:
        cluster: dev
        namespace: spinnaker
        user: u-aaaaa
      name: dev
    - context:
        cluster: nop
        user: u-aaaaa
      name: nop
    - context:
        cluster: rancher
        user: u-aaaaa
      name: rancher
    - context:
        cluster: sit
        user: u-aaaaa
      name: sit
    - context:
        cluster: uat
        user: u-aaaaa
      name: uat
    - context:
        cluster: tooling
        user: u-bbbbb
      name: tooling
    - context:
        cluster: acquiring
        user: u-bbbbb
      name: acquiring
    users:
    - name: u-aaaaa
      user:
        token: token-yyyy:xxxxx
    - name: u-bbbbb
      user:
        token: token-yyyy:xxxxxxx
    current-context: tooling
````
