### ISSUE TITLE
Gate does not start (Java Keystore file not found) when using Halyard 1.19.0

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#4294]
### Issue Summary:

When trying to "hal deploy apply" with SAML enabled - Gate does not start (complaining about missing Java Keystore file):

````
Caused by: java.io.FileNotFoundException: class path resource [home/halyard/.hal/default/staging/dependencies/1745581636-keystore.jks] cannot be opened because it does not exist
````

The keystore file does exist on the setup - and the permissions are fine. The only change in between two "hal deploy apply"'s are the version of Halyard (1.18.0 vs. 1.19.0).

### Cloud Provider(s):

Any.

### Environment:

Spinnaker version: 1.13.1 - running in GKE
Halyard version: 1.19.0 (broken) - 1.18.0 (working)

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

Halyard + Gate

### Steps to Reproduce:

Should be repeatable like this:

1. install Spinnaker with Halyard - using Halyard version 1.18.0 - configuring also SAML
2. Spinnaker gets deployed correct (also Gate starts fine)
3. upgrade Halyard to version 1.19.0 - and run "hal deploy apply"
4. witness Gate not starting (see below where the change is)

### Additional Details:

For some reason, Halyard configured the JKS location differently between Halyard versions, like this (generated config from ~/.hal/default/staging/gate.yml):

in 1.18.0 (working version):

````
saml:
  enabled: true
  issuerId: https://spinnaker.redbullmediahouse.com
  metadataUrl: file:/home/halyard/.hal/default/staging/dependencies/362827086-metadata.xml
  keyStore: file:/home/halyard/.hal/default/staging/dependencies/1745581636-keystore.jks
  keyStorePassword: topSecretPassword
  keyStoreAliasName: saml
  redirectProtocol: https
  redirectHostname: spinnaker-api.company.com
  userAttributeMapping: {}
````

in 1.19.0 (broken one):

````
saml:
  enabled: true
  issuerId: https://spinnaker.redbullmediahouse.com
  metadataUrl: file:/home/halyard/.hal/default/staging/dependencies/362827086-metadata.xml
  keyStore: /home/halyard/.hal/default/staging/dependencies/1745581636-keystore.jks
  keyStorePassword: topSecretPassword
  keyStoreAliasName: saml
  redirectProtocol: https
  redirectHostname: spinnaker-api.company.com
  userAttributeMapping: {}
````
