### ISSUE TITLE
add HAL configurations for Artifactory and Concourse

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#4301]
### Issue Summary:
add configuration to HAL to allow users to add `artifactory` triggers and `concourse` triggers

### Cloud Provider(s):
All

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
HAL

### Description:
a user should be able to configure `artifactory` or `concourse` through HAL

### Additional Details:

HAL should out put the following configurations for the different trigger types.

sample artifactory configuration:

```
artifactory:
      enabled: true
      searches:
        - name: local-snapshots
          base-url: ${ARTIFACTORY_URL}
          repo: libs-snapshot-local
          groupId: io.pivotal.spinnaker
          username: '${ARTIFACTORY_USER}'
          password: '${ARTIFACTORY_PASSWORD}'
```

sample concourse configuration:

```
    concourse:
      enabled: true
      masters:
        - name: spin-concourse
          url: '${SPIN_CONCOURSE_URL}'
          username: '${SPIN_CONCOURSE_USER}'
          password: '${SPIN_CONCOURSE_PASSWORD}'

```
