### ISSUE TITLE
CF - support YAML structure as a parameter value for service manifests

### ISSUE THREAD

**Issue by Jammy-Louie** [spinnaker/spinnaker#4333]
### Issue Summary:
Currently the service manifest expects the value for `parameters` to be JSON.

example:
```yml
---
service_name: mysqlservice
service: p.mysql
service_plan: db-small
tags:
- tag1
parameters: |
   { "foo": "bar" }
```

In addition we want to be able to support a YAML structure for parameters:

example:
```yml
---
service_name: mysqlservice
service: p.mysql
service_plan: db-small
tags:
- tag1
parameters:
   foo: bar
``` 

or 
```yml
---
service_name: mysqlservice
service: p.mysql
service_plan: db-small
tags:
- tag1
parameters:
   foo:
     bar: value
``` 

### Cloud Provider(s):
CF

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Cloud driver

### Description:
Cloud driver is going to need to be able to process a fully structured YAML file and be backwards compatible with accepting json as a value for parameters.

![Screen Shot 2019-04-24 at 4 20 52 PM](https://user-images.githubusercontent.com/8474965/56691091-07ef2800-66ad-11e9-87e5-6761051a256a.png)
