### ISSUE TITLE
helm Bake artifact rendering issue

### ISSUE THREAD

**Issue by warroyo** [spinnaker/spinnaker#4349]
### Issue Summary:

@spinnaker/ui-ux-team when trying to add a helm chart as an artifact in the bake stage the UI fails to render the charts. I see the below error in the console when selecting my helm chart repo.

![image](https://user-images.githubusercontent.com/616621/56841029-5f75cb00-6848-11e9-8a44-a943e64b3f1d.png)

when looking at the actual api call made the charts are returned fine:

https://api.spinnaker.mydomain.com/artifacts/account/harbor-helm/names?type=helm%2Fchart

output:
```
[
"library/mysql",
"library/redis"
]
```

### Cloud Provider(s):
k8s & cloudfoundry

### Environment:

BOM:
```
version: 1.13.5
timestamp: '2019-04-20 09:03:23'
services:
  echo:
    version: 2.4.2-20190416050308
    commit: 28bde7adc277258306b5c0f93020aa54b4246829
  clouddriver:
    version: 4.4.4-20190420050307
    commit: db3dcaf54838be535e3ab3fc3f0853a22732186e
  deck:
    version: 2.8.4-20190415113424
    commit: 96b7b06755f673e921b78e9a5414f54c6ddbb8cf
  fiat:
    version: 1.4.1-20190418153116
    commit: 13f855f166350e78222c7a54d17af4f006eb16ac
  front50:
    version: 0.16.2-20190406050308
    commit: b796e8041055fc1e27074a236003261148f44801
  gate:
    version: 1.7.2-20190418153116
    commit: 28beaaa288464b5a079da0f9f2d5d50f32d4c7a7
  igor:
    version: 1.2.1-20190404161844
    commit: 98de62d636b520ba82dfc589830aa4cdc7451596
  kayenta:
    version: 0.7.0-20190315122808
    commit: f18fee7771190a2bd6809b5b47db1c62f876820e
  orca:
    version: 2.6.2-20190406050308
    commit: ae652510faf6f53584dd7a83f5f2ceec9bc6076e
  rosco:
    version: 0.11.0-20190322234525
    commit: 95a2e29f53def2fce614412d0d9b27f273fc62d7
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.12.1-20190417133517
    commit: efa6f3fb810ce4d403cff81abc96d35a7f77118e
  monitoring-daemon:
    version: 0.12.1-20190417133517
    commit: efa6f3fb810ce4d403cff81abc96d35a7f77118e
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker

```
