### ISSUE TITLE
Annotations are not propagates on deployment resources

### ISSUE THREAD

**Issue by thecodejunkie** [spinnaker/spinnaker#4355]
### Issue Summary:
Annotations are not propagates on deployment resources

### Cloud Provider(s):
GCP

### Environment:
Spinnaker v1.13.5 hosted on GKE

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Pipelines

### Description:

I noticed that Spinnaker does not seem to propagate user-defined annotations in a workload of `kind: Deployment`. They are simply discarded and only the Spinnaker annotations are present after deployment.

This does not seem to be the case for ingress workloads, where the annotations are propagates to the cluster.

Here's an example, that I tried with some parameters 

```
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    test: 'hi'
    spinnaker.test/string: '${ parameters.stringvalue }'
    spinnaker.test/integer: '${ #toInt( parameters.integervalue  ) }'
```

> ℹ️ Update! It seems that it's the usage of `#toInt`, in the annotation section, that is causing problems. If I remove it, then the other two annotations are propagated. `#toInt` also works fine in other parts of the manifest, just not in the annotations section. 

### Steps to Reproduce:

1. Create a manifest of `kind: Deployment` and add annotation to the metadata section
2. Deploy the manifest, using a `Deploy (Manifest)` stage
3. Inspect the annotations, in the deployed workload, and notice that non of the user-defined annotations are there. Only Spinnaker related annotations are present.
4. Also notice that they're not in the annotations section of the `kubectl.kubernetes.io/last-applied-configuration` annotation either
