### ISSUE TITLE
helm bake fails to get artifact versions

### ISSUE THREAD

**Issue by warroyo** [spinnaker/spinnaker#4370]
### Issue Summary:

when using the helm bake option in a pipeline the artifact versions are failing to be retrieved. it looks like the api call to pull back versions is missing the account name.

screenshot:

![image](https://user-images.githubusercontent.com/616621/57161070-d874a580-6da7-11e9-925f-8ae6cae39a02.png)

here is the failing call that returns a 404
```
https://api.spinnaker.mydomain.com/artifacts/account/versions?artifactName=library%2Fredis&type=helm%2Fchart
```

this is successful in the `configuration` stage of the pipeline. see below for the successful version retrieval 

Screenshot of success in the expected artifacts section:

![image](https://user-images.githubusercontent.com/616621/57161152-0d80f800-6da8-11e9-927f-1fef96b99277.png)

and successful api call:

```
https://api.spinnaker.mydomain.com/artifacts/account/harbor-helm/versions?artifactName=library%2Fspring-music&type=helm%2Fchart
```

### Environment:

verison BOM:

```
version: master-latest-unvalidated
timestamp: '2019-05-03 15:30:08'
services:
  echo:
    version: 2.5.0-20190430163248
    commit: 9d174d1ae859552b47968820ab6283e898358e10
  clouddriver:
    version: 4.5.0-20190503112955
    commit: 05a7276efda72d4a5106a2433436ee39a8e48bef
  deck:
    version: 2.9.0-20190502142808
    commit: 9e03e52fbaf480b5689e4e186b7f5928c976cf6f
  fiat:
    version: 1.5.0-20190501182810
    commit: fa5915a6f1ca63fd774aef4dc6c45d90fce4359c
  front50:
    version: 0.17.0-20190501182810
    commit: 02e94311eb1452d4423175686e85e696cef79ef8
  gate:
    version: 1.8.0-20190502012809
    commit: 0513b8321e973ce2944690ab3c6f0d4d70f4e1a4
  igor:
    version: 1.3.0-20190430163248
    commit: 31c3f8415e52e86e26043e5bedde499479694f17
  kayenta:
    version: 0.8.0-20190501182810
    commit: 1e9224b3aa155caa01b9844660136c0f42c68b86
  orca:
    version: 2.7.0-20190502211050
    commit: 3dbe0b6371bddcf452093a9f546d9bf68865a323
  rosco:
    version: 0.12.0-20190430163248
    commit: 6ce454526d1e21fc19326740d3762ab398132a34
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.13.0-20190430163248
    commit: bf01bf225168919ad13d63b82f93c39061e0b544
  monitoring-daemon:
    version: 0.13.0-20190430163248
    commit: bf01bf225168919ad13d63b82f93c39061e0b544
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker
````
