### ISSUE TITLE
Arifactory trigger says `Unable to query Artifactory for artifacts (HTTP 500)`

### ISSUE THREAD

**Issue by papanito** [spinnaker/spinnaker#4381]
### Issue Summary:

I've added an artifactory trigger to the spinnaker deployment but this fails with `Arifactory` trigger says `Unable to query Artifactory for artifacts (HTTP 500)` even so the repo is configured

### Cloud Provider(s):

On-premise kubernetes

### Environment:

CentOS 7
air-gapped

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

igor

### Description:

Log of `igor`

```java
2019-05-08 11:43:45.510 WARN 1 --- [RxIoScheduler-5] c.n.s.i.a.ArtifactoryBuildMonitor : Unable to query Artifactory for artifacts (HTTP 500): {
"errors" : [ {
"status" : 500,
"message" : "Repo key cannot be empty. Path: api/search/aql"
} ]
```

### Steps to Reproduce:

1. Setup artifactory with local helm repo: `https://artifactory.svc.prd.sc.intra/artifactory/local-helm-sc/`
1. Configure a artifactory trigger by add the following to `local-igor.yaml` in the `spinnaker-halyard

   ```bash
   spinnaker@spinnaker-spinnaker-halyard-0:~/.hal/default/profiles$ cat > igor-local.yml <<EOF
   spinnaker:
     pollingSafeguard:
     itemUpperThreshold: 50000
   artifactory:
     enabled: true
     searches:
       - name: artifactory-local-helm-sc
         base-url: https://artifactory.svc.prd.sc.intra/artifactory
         repo: local-helm-sc
         username: <redacted>
         password: <redacted>
   ```
 
1. Apply the changes

   ```bash
   spinnaker@spinnaker-spinnaker-halyard-0:~/.hal/default/profiles$ hal deploy apply
   ....
   + Deploy spin-igor
     Success
   ...
   ```

1, check `igor-local.yaml` in conatiner `igor`

   ```bash
   bash-4.4$ cat /opt/spinnaker/config/igor-local.yml 
   spinnaker:
     pollingSafeguard:
     itemUpperThreshold: 50000
   artifactory:
     enabled: true
     searches:
      - name: artifactory-local-helm-swisscard
        base-url: https://artifactory.svc.prd.sc.intra/artifactory
        repo: local-helm-swisscard 
        username: jfrog-rt-cicd
        password: xxxxxxx
   ```

Expected:
- No errors in igor

Actual:
- Error `c.n.s.i.a.ArtifactoryBuildMonitor : Unable to query Artifactory for artifacts (HTTP 500)`

### Additional Details

``` bash
hal --version
1.19.2-20190417142815
```

#### Spinnaker version info

`1.13.6` but with custom bom
```
bom_1.13.6.yml: |
version: 1.13.6
timestamp: '2019-04-27 09:03:24'
services:
  echo:
    version: 2.4.2-20190416050308
    commit: 28bde7adc277258306b5c0f93020aa54b4246829
  clouddriver:
    version: 4.4.5-20190427050308
    commit: 19481d4157fc86483b71e3e9113fdca8777df40b
  deck:
    version: 2.8.5-20190425050308
    commit: 2bffa2f0d52616bac7815dd07af788a74b411509
  fiat:
    version: 1.4.1-20190418153116
    commit: 13f855f166350e78222c7a54d17af4f006eb16ac
  front50:
    version: 0.16.2-20190406050308
    commit: b796e8041055fc1e27074a236003261148f44801
  gate:
    version: 1.7.2-20190418153116
    commit: 28beaaa288464b5a079da0f9f2d5d50f32d4c7a7
  igor:
    version: 1.2.1-20190404161844
    commit: 98de62d636b520ba82dfc589830aa4cdc7451596
  kayenta:
    version: 0.7.1-20190425050308
    commit: f95afd1661cf9ccc85d8f0d444c9ac9d9a136aa5
  orca:
    version: 2.6.2-20190406050308
    commit: ae652510faf6f53584dd7a83f5f2ceec9bc6076e
  rosco:
    version: 0.11.0-20190322234525
    commit: 95a2e29f53def2fce614412d0d9b27f273fc62d7
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.12.1-20190417133517
    commit: efa6f3fb810ce4d403cff81abc96d35a7f77118e
  monitoring-daemon:
    version: 0.12.1-20190417133517
    commit: efa6f3fb810ce4d403cff81abc96d35a7f77118e
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  #debianRepository: https://dl.bintray.com/spinnaker-releases/debians           
  debianRepository: https://ci-tools.sc.intra/nexus3/repository/spinnaker-releases/           
  #dockerRegistry: gcr.io/spinnaker-marketplace           
  dockerRegistry: ci-tools.sc.intra:5000/spinnaker-marketplace           
  googleImageProject: marketplace-spinnaker-release           
  #gitPrefix: https://github.com/spinnaker           
  gitPrefix: https://scm.sc.intra/scm/SPIN/repos
```
