### ISSUE TITLE
Canary Report summary immediately crashes after loading

### ISSUE THREAD

**Issue by Fmowers** [spinnaker/spinnaker#4389]
### Issue Summary:
When trying to view summary of any canary report. The UI crashes immediately after loading the contents of the summary. 

### Cloud Provider(s):
AWS
Kubernetes

### Environment:
I am running canaries using newrelic as my metric-account and aws as my storage-account

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Additional Details:

Error message in devtool console shows:

Uncaught TypeError: Cannot read property 'queryFinder' of undefined
    at Object.getContent (lib.js:8122)
    at ResultMetadataRow (lib.js:8066)
    at eh (react-dom.production.min.js:169)
    at ai (react-dom.production.min.js:202)
    at bi (react-dom.production.min.js:203)
    at Fi (react-dom.production.min.js:218)
    at Gi (react-dom.production.min.js:217)
    at ii (react-dom.production.min.js:214)
    at xg (react-dom.production.min.js:212)
    at Object.enqueueSetState (react-dom.production.min.js:133)

Screenshot after navigating to the Canary Reports tab:

<img width="1423" alt="Screen Shot 2019-05-09 at 2 54 13 PM" src="https://user-images.githubusercontent.com/22055702/57479087-a614ed80-726a-11e9-985e-ebecf333c29a.png">

Screenshot moments before UI crash:

<img width="1427" alt="Screen Shot 2019-05-09 at 2 55 10 PM" src="https://user-images.githubusercontent.com/22055702/57479148-c8a70680-726a-11e9-8c1e-18fd5b3ddf8f.png">

Screenshot after UI crash:

<img width="1430" alt="Screen Shot 2019-05-09 at 2 55 47 PM" src="https://user-images.githubusercontent.com/22055702/57479216-e96f5c00-726a-11e9-8074-512772b2284c.png">

---

**_Please delete the instructions below this line prior to submitting_**

**Comment by milesmatthias** [comment]
I'm seeing this as well but getting different errors in the console, see screenshot.

![Screen Shot 2019-06-05 at 3 12 58 PM](https://user-images.githubusercontent.com/600638/58994177-7e02a680-87a4-11e9-915e-7b8bbb435046.png)

**Comment by icoolchn** [comment]
![image](https://user-images.githubusercontent.com/39686015/59481445-d3bb0b00-8e96-11e9-8f16-bcae084b446b.png)
I also appeared the same problem. Please help us to solve, thank you
Configuration information
hal config canary edit --default-metrics-store prometheus
hal config canary edit --default-storage-account ceph-rgw-s3
hal config canary edit --default-metrics-account prometheus-dev
spinnaker version : 1.14.3
Kubernetes : 1.12.1
halyard config
```
canary:
    enabled: true
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: true
      accounts:
      - name: canary-kayenta-prometheus
        endpoint:
          baseUrl: http://10.10.1.123:32123
        username: admin
        password: admin
        supportedTypes:
        - METRICS_STORE
    - name: datadog
      enabled: false
      accounts: []
    - name: aws
      enabled: true
      accounts:
      - name: canary-kayenta-s3
        bucket: canary-kayenta-s3
        rootFolder: canary-kayenta-s3
        endpoint: http://11.7.148.163
        accessKeyId: accesskey
        secretAccessKey: secretkey
        supportedTypes:
        - CONFIGURATION_STORE
        - OBJECT_STORE
      s3Enabled: true
    reduxLoggerEnabled: true
    defaultMetricsAccount: canary-kayenta-prometheus
    defaultStorageAccount: canary-kayenta-s3
    defaultJudge: NetflixACAJudge-v1.0
    defaultMetricsStore: prometheus
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true
```
