### ISSUE TITLE
Issues connecting to minio(Front50)

### ISSUE THREAD

**Issue by warroyo** [spinnaker/spinnaker#4431]
### Issue Summary:
Using the `master-latest-unvalidated` being deployed by helm I am seeing an error connecting to minio with default settings. below is the error.

```
o.s.b.c.embedded.tomcat.TomcatStarter    : Error starting Tomcat context. Exception: org.springframework.beans.factory.UnsatisfiedDependencyException. Message: Error creating bean with name 'graphQLServletRegistrationBean' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLServletRegistrationBean' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLServlet' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLServlet' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchemaProvider' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchemaProvider' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchema' defined in class path resource [com/netflix/spinnaker/front50/config/GraphQLSchemaConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchema' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'runtimeWiring' defined in class path resource [com/netflix/spinnaker/front50/config/GraphQLSchemaConfiguration.class]: Unsatisfied dependency expressed through method 'runtimeWiring' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pipelinesDataFetcher' defined in URL [jar:file:/opt/front50/lib/front50-web.jar!/com/netflix/spinnaker/front50/graphql/datafetcher/PipelinesDataFetcher.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pipelineDAO' defined in class path resource [com/netflix/spinnaker/front50/config/S3Config.class]: Unsatisfied dependency expressed through method 'pipelineDAO' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 's3StorageService' defined in class path resource [com/netflix/spinnaker/front50/config/S3Config.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.front50.model.S3StorageService]: Factory method 's3StorageService' threw exception; nested exception is com.amazonaws.SdkClientException: Unable to execute HTTP request: spinnaker.spin-minio
```
### Steps to Reproduce:
Update to `master-latest-unvalidated` using helm

Version BOM:

```
version: master-latest-unvalidated
timestamp: '2019-05-20 15:28:26'
services:
  echo:
    version: 2.5.0-20190517172808
    commit: 1a1dc7c1dc2341b9ff5c04d8af7bf1ae86ff0b61
  clouddriver:
    version: 4.5.0-20190520112809
    commit: fddfd83e1e8f08bbafe59f71f2c3624e33f4616f
  deck:
    version: 2.9.0-20190520112809
    commit: 3fd183ef3aa86808cc9cdb3b6ef09821acc8ac35
  fiat:
    version: 1.5.0-20190513170244
    commit: bdc3367f531cd61db57e412eb118fc1dd5ff7255
  front50:
    version: 0.17.0-20190517190542
    commit: 2443dd1ae71dc4ceb40a5b5a875c39621e6862eb
  gate:
    version: 1.8.0-20190517142809
    commit: e1cafc7224c74d210302033726f62e29735373c3
  igor:
    version: 1.3.0-20190515122714
    commit: aeddd7fcbc3d1e8aeb11411d497a12e98452b754
  kayenta:
    version: 0.8.0-20190506142808
    commit: 5a46e7c40152f457ae4d4e173bd595fed289d957
  orca:
    version: 2.7.0-20190520112809
    commit: 6cdb4464d035ea1095a69cef7035943b87f0a5e3
  rosco:
    version: 0.12.0-20190520112809
    commit: a86c365bb9744a1fe9592ebd4ff8bfe8f7936f8c
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.13.0-20190430163248
    commit: bf01bf225168919ad13d63b82f93c39061e0b544
  monitoring-daemon:
    version: 0.13.0-20190430163248
    commit: bf01bf225168919ad13d63b82f93c39061e0b544
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker
```
