### ISSUE TITLE
Email Notification not working 

### ISSUE THREAD

**Issue by bhaktibhoj** [spinnaker/spinnaker#4439]
### Issue Summary:
We are using email notification to get notify after build success/failure. Though after setting notification. We unable to get any email.

![Issue Image](https://www.spinnaker.io/guides/user/applications/event_notification_prefs.png)

### Cloud Provider(s):
Google cloud Provider

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Notification

### Steps to Reproduce:
1. Go to any pipeline 
2. Click on Notification
3. Add notification and save
4. Run the pipeline

**Comment by eddycharly** [comment]
Did you configure your smtp for sending mails ?
https://www.spinnaker.io/setup/features/notifications/

**Comment by bhaktibhoj** [comment]
I just perform following steps.
https://www.spinnaker.io/guides/user/applications/configure/#create-pipeline-notifications

Please let me know is there any need to separately configure smtp. 

If yes where should I setup it. at cluster level?

**Comment by eddycharly** [comment]
You need to configure your smtp settings for echo to send emails.
Basically it requires to create the echo-local.yml file as explained in the link i posted in my previous reply.
The section about settings.js is outdated thoudh, you should use settings-local.js instead.

**Comment by bhaktibhoj** [comment]
Done with all the required changes as suggested in given URL. 

Still not working. Does spinnaker require any restart or where do this files get referred to spinnaker?

**Comment by eddycharly** [comment]
Are you using halyard ?

**Comment by bhaktibhoj** [comment]
No. I am not using halyard.

**Comment by eddycharly** [comment]
You should have an echo.yml file to configure echo on the machine running the echo microservice.
Add the smtp configuration in this file and restart the service.

If it doesn't work check your smtp settings, you can also check echo logs to see if there is an error.

**Comment by bhaktibhoj** [comment]
I had following command to edit the echo.yaml file

`gcloud container clusters get-credentials k8-qore-qpathways --zone us-central1-a --project qpathways-dev  && kubectledit deployment spin-spinnaker-echo`

which showing following error after editing the file with smtp configurations. 

Fetching cluster endpoint and auth data.
kubeconfig entry generated for [cluster_name]
error: deployments.extensions "spin-spinnaker-echo" is invalid
A copy of your changes has been stored to "/tmp/kubectl-edit-eayaa.yaml"
error: Edit cancelled, no valid changes were saved.

**Comment by eddycharly** [comment]
Ah ok, you're using helm.
Sorry i don't know how to configure echo with helm, guess there's a setting for it in the chart.

**Comment by eddycharly** [comment]
From the chart documentation it looks like the chats procides a way to create the echo-local.yml config map.

Something along those lines should create the configmap :
```
halyard:
  additionalProfileConfigMaps:
    create: true
    data:
      echo-local.yml: |-
        put the smtp configuration here
```

Not sure how if it will be mounted in the container though.

**Comment by bhaktibhoj** [comment]
Still not working. 
config file giving error

**Comment by eddycharly** [comment]
The echo-local.yml file (or config map) should be as simple as this :
```
mail:
  enabled: true
  from: ** sender email **
spring:
  mail:
    host: ** smtp host **
    username: ** smtp user **
    password: ** smtp password **
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
```

You should not need to modify the echo.yml file at all.

**Comment by bhaktibhoj** [comment]
Done with changes in echo-local.yml as well as echo.yml 

Nothing works for me.

**Comment by bhaktibhoj** [comment]
I am closing this issue, as my notifications are working now. 

There's need to update documentation. 

[https://www.spinnaker.io/setup/features/notifications/#email](url)

```
mail:
      enabled: true
      host: smtphost
      from: mailaddress
      properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
    
    spring:
      mail:
        host: smtphost
        port: 587
        username: mailaddress
        password: password
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
```
