### ISSUE TITLE
[ECS] Clusters from different accounts showing in one account in the clusters view

### ISSUE THREAD

**Issue by marcinwalczyk** [spinnaker/spinnaker#4448]
### Issue Summary:
Clusters from different accounts showing in one account in the clusters view

### Cloud Provider(s):
ECS

### Environment:
I am running Spinnaker on EKS. Version 1.13.8
### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
@spinnaker/ui-ux-team

### Description:
Application deployed  to two accounts  appear in one account in the clusters view. Application is deployed correctly in AWS/ECS. This is only Spinnaker showing the instances in the wrong places.

### Additional Details:
I have two pipelines one for test and one for prod and both are working correctly but clusters from both accounts are displayed under one although V009 is from test and v001 is from prod.
 
![Screenshot 2019-05-24 at 13 52 53](https://user-images.githubusercontent.com/6472766/58326611-a1853300-7e2d-11e9-908c-1d87487faba3.png)

Gate returns 404 when I try to check details for v001 which is incorrectly assigned:
```
/applications/billingsubmitter/serverGroups/ecs-keen-test/us-west-2/billingsubmitter-v001?includeDetails=false
Request Method: GET
Status Code: 404 
```

Gate also returns both server groups assigned to ecs-keen-test:
```
Request:
/applications/billingsubmitter/serverGroups

Response: 
-
    account: ecs-keen-test
    application: billingsubmitter
    capacity:
        desired: 1
        max: 1
        min: 1
    cloudProvider: ecs
    cluster: billingsubmitter
    createdTime: 1558689918948
    instanceCounts:
        down: 0
        outOfService: 0
        starting: 0
        total: 1
        unknown: 0
        up: 1
    instances:
        -
            availabilityZone: us-west-2a
            health: [{state: Up, type: loadBalancer}]
            healthState: Up
            id: 2e447403-a684-4e1a-8bea-e46de342e25c
            launchTime: 1558689924826
            name: 2e447403-a684-4e1a-8bea-e46de342e25c
    isDisabled: false
    moniker:
        app: billingsubmitter
        cluster: billingsubmitter
        sequence: 9
    name: billingsubmitter-v009
    region: us-west-2
    securityGroups:
        - sg-0473f5b6af5c11c6f
    serverGroupManagers: []
    type: ecs
    vpcId: vpc-b0020ed5
-
    account: ecs-keen-test
    application: billingsubmitter
    capacity:
        desired: 1
        max: 1
        min: 1
    cloudProvider: ecs
    cluster: billingsubmitter
    createdTime: 1558619357561
    instanceCounts:
        down: 0
        outOfService: 0
        starting: 0
        total: 1
        unknown: 0
        up: 1
    instances:
        -
            availabilityZone: us-west-2b
            health: [{state: Up, type: loadBalancer}]
            healthState: Up
            id: 91896bee-c166-4522-af46-46ccdc6b5145
            launchTime: 1558619374247
            name: 91896bee-c166-4522-af46-46ccdc6b5145
    isDisabled: false
    moniker:
        app: billingsubmitter
        cluster: billingsubmitter
        sequence: 1
    name: billingsubmitter-v001
    region: us-west-2
    securityGroups:
        - sg-0bfa1531800529998
    serverGroupManagers: []
    type: ecs
    vpcId: vpc-6224c906
```
