### ISSUE TITLE
Slash dropped in Annotation key of Custom Job Stage

### ISSUE THREAD

**Issue by derek9gag** [spinnaker/spinnaker#4465]
### Issue Summary:

The `/` character is unexpectedly removed from Custom Job Stage pod annotation keys.

### Cloud Provider(s):

 - Kubernetes (AWS/kops)

### Environment:

 - Spinnaker 1.14.1
     - Orca 2.7.1; Clouddriver 4.5.1
 - kubernetes (v2)

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):

 - orca

### Description:

If the custom job stage has a '/' character in the pod annotation, e.g. `"key-with/slash": value`, the resulting pod will have an annotation of `"key-withslash": value` instead - the slash is removed from the key.

### Steps to Reproduce:

1. Add the following to `orca-local.yaml`, under `jobs.preconfigured` and re-deploy (`hal deploy apply`).

```yaml
      - label: Echo
        type: echoPhrase
        description: Echo a configured phrase
        cloudProvider: kubernetes
        account: kubernetes3
        credentials: kubernetes3
        waitForCompletion: true
        application: spinnaker
        parameters: []
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: say-hello
            namespace: spinnaker
          spec:
            backoffLimit: 0
            template:
              metadata:
                annotations:
                  "annotation-with/slash": "some-value"
              spec:
                restartPolicy: Never
                containers:
                  - name: hello
                    image: alpine:latest
                    command: ["echo", "hello"]
```
2. Create a pipeline with only the `echoPhrase` stage. Start a manual execution.

3. Check the resulting manifest in execution source (`stages[0].context.manifest.spec.template.metadata.annotations`), or on kubernetes (`kubectl describe pod`). The annotation key loses the '/' character. 

Example describe-pod output:
```
...
Annotations:        annotation-withslash: some-value
                    artifact.spinnaker.io/location: spinnaker
                    artifact.spinnaker.io/name: say-hello-3fe408513b062ae6
                    artifact.spinnaker.io/type: kubernetes/job
                    moniker.spinnaker.io/application: spinnaker
                    moniker.spinnaker.io/cluster: job say-hello-3fe408513b062ae6
Status:             Succeeded
```

### Additional Details:

It seems not to happen when the same manifest is used directly in a `Run Job (manifest)` stage.
