### ISSUE TITLE
Unable to create projects using helm installation method

### ISSUE THREAD

**Issue by theothermike** [spinnaker/spinnaker#4480]
### Issue Summary:

Unable to create 'Projects' once Spinnaker is installed using Helm on AWS/EKS w/S3

### Cloud Provider(s):

AWS

### Environment:

EKS cluster.  Using S3 data store

### Description:

Installing spinnaker using helm (tried 1.10.1 and 1.11.1 of the chart)

it appears to finish setting up successfully, and discovers the applications running on the kubernetes cluster I configured for 'kubeConfig'.    I connect to the cluster with port forward

```
kubectl port-forward --namespace spinnaker svc/spin-deck 9000:9000
```

When I try to create a 'Project' (tried many different inputs), the Popup says 'Upsert Project (00:00) Operation succeeded!" and then tries a redirect which shows some HTML over the background saying '<404> Please check your URL - we can't find any data for the project test2' 

I dug through the logs of all spinnaker pods, and the only relevant log lines I found in 'spin-gate':

```
2019-06-04 17:16:16.429  INFO 1 --- [trix-projects-7] c.n.s.g.s.internal.Front50Service        : ---> HTTP GET http://spin-front50.spinnaker:8080/v2/projects/test2
2019-06-04 17:16:16.472  INFO 1 --- [trix-projects-7] c.n.s.g.s.internal.Front50Service        : <--- HTTP 404 http://spin-front50.spinnaker:8080/v2/projects/test2 (42ms)
2019-06-04 17:16:16.474  WARN 1 --- [0.0-8084-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [com.netflix.spinnaker.gate.retrofit.UpstreamBadRequest: 404 ]
```

and front50

```
2019-06-04 17:15:43.598  WARN 1 --- [0.0-8080-exec-5] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [com.netflix.spinnaker.front50.exception.NotFoundException: Object not found (key: test2)]
```

### Steps to Reproduce:

helm install --name spinnaker stable/spinnaker -f spinnaker.yaml 

spinnaker.yaml (redacted)

```
kubeConfig:
  enabled: true
  secretName: my-kubeconfig
  secretKey: config
  contexts:
    # Names of contexts available in the uploaded kubeconfig
    - cluster-staging
    - cluster-operations
  # This is the context from the list above that you would like
  # to deploy Spinnaker itself to.
  deploymentContext: cluster-operations
s3:
  enabled: true
  accessKey: <redacted>
  secretKey: <redacted>
  bucket: bucket
  region: region
  endpoint: http://bucket.s3-region.amazonaws.com
minio:
  enabled: false
```

### Additional Details:
