### ISSUE TITLE
ttlSecondsAfterFinished is removed from Custom Job Stage

### ISSUE THREAD

**Issue by bvanosten** [spinnaker/spinnaker#4528]
### Issue Summary:
When using a Kubernetes Custom Job Stage, .spec.ttlSecondsAfterFinished is removed from the deployed job, meaning jobs can never be cleaned up (without something extra / manual), everything else seems to work fine.

I do have TTLAfterFinished enabled on my cluster, and when running this with just the normal Run Job stage it works fine and is not removed, just seems to be with Custom Stages

This is what the final job has:
```
$ kubectl get job <the-custom-job> -o yaml
...
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
...
```

This is what I'm setting in orca-local.yaml
```
job:
  preconfigured:
    kubernetes:
      - label: MyJob
        ...
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: my-job
          spec:
            ttlSecondsAfterFinished: 100
            backoffLimit: 0
            template:
```

### Environment:
Kubernetes: 1.12.7

```
version: 1.14.5
timestamp: '2019-06-12 07:40:25'
services:
  echo:
    version: 2.5.1-20190612034009
    commit: e68a464bbb3dcef8ebdb6a7e608a08730af317cd
  clouddriver:
    version: 4.6.1-20190611034010
    commit: deec4874d99ae0b1fc1e4e8d81dafa8562a38aec
  deck:
    version: 2.9.5-20190612034009
    commit: 2f0cf9ddbe83d63faf3774d94f3b5631e8720458
  fiat:
    version: 1.5.1-20190529034009
    commit: 381db2c99a8756af92cac6cf8274cac5ea3408ee
  front50:
    version: 0.17.0-20190510203645
    commit: 0540599582fdefaf5249009c3efdb10d26854956
  gate:
    version: 1.8.2-20190525034011
    commit: ee90e98cabd184cbad4b34b8502eab169b5782b9
  igor:
    version: 1.3.0-20190515102735
    commit: b3f354f0bd49d0656217998108f522519b30444c
  kayenta:
    version: 0.8.1-20190522034010
    commit: cf89374218731b8d2937dbd30a56326e91a4a7e8
  orca:
    version: 2.7.3-20190612034009
    commit: 75ec09ed88b3b7e92c2a9c270d9a5afe88dc70a7
  rosco:
    version: 0.12.0-20190517180000
    commit: 59f79299a3fcfb39229cbd0a2e52bf435c340f4a
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.13.0-20190430163248
    commit: bf01bf225168919ad13d63b82f93c39061e0b544
  monitoring-daemon:
    version: 0.13.0-20190430163248
    commit: bf01bf225168919ad13d63b82f93c39061e0b544
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker
```
