### ISSUE TITLE
Feature request: Add ability to set `affinity` for each service kubernetes specific setting

### ISSUE THREAD

**Issue by ealebed** [spinnaker/spinnaker#4541]
### Issue Summary:
If I use spinnaker HA-services and customSizing (e.g. set several replicas count for each service), I cann't set affinity in deployment manifest for this service. For better HA I should do it.

Right now I do this manually, with `kubectl edit deployment spin-orca -n spinnaker` and add:
```...
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-orca
            topologyKey: kubernetes.io/hostname
...
```

Please, add ability to set `affinity` for each service kubernetes specific setting (like annotations, described [here](https://www.spinnaker.io/reference/halyard/custom/#podannotations)
### Cloud Provider(s):
Kubernetes GKE

### Environment:
Spinnaker 1.14.6 deployed to Kubernetes (V2) GKE cluster via halyard

**Comment by ealebed** [comment]
any updates?

**Comment by rverma-nikiai** [comment]
Came to create the exact same issue and found this. Even though if we are not in HA, I would want to run clouddriver and orca on different hosts since both of them consume good cpu.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by rverma-nikiai** [comment]
@spinnakerbot remove-label stale

**Comment by ealebed** [comment]
any updates?

**Comment by gochist** [comment]
@ealebed :wave: I found that it was implemented by the #1273 while I could not find any document describing about it.

```
    deploymentEnvironment:
        affinity:
            spin-orca:
                podAntiAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: cluster
                        operator: In
                        values:
                        - spin-orca
                    topologyKey: kubernetes.io/hostname
```

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by ealebed** [comment]
@spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by ealebed** [comment]
@spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by nerddelphi** [comment]
@spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by ScOut3R** [comment]
> @ealebed wave I found that it was implemented by the #1273 while I could not find any document describing about it.
> 
> ```
>     deploymentEnvironment:
>         affinity:
>             spin-orca:
>                 podAntiAffinity:
>                   requiredDuringSchedulingIgnoredDuringExecution:
>                   - labelSelector:
>                       matchExpressions:
>                       - key: cluster
>                         operator: In
>                         values:
>                         - spin-orca
>                     topologyKey: kubernetes.io/hostname
> ```

@gochist I'm trying to get your suggestion working, but having trouble with it. I have the following in clouddriver's service setting but it is not being applied to the service.

```
kubernetes:
  deploymentEnvironment:
    affinity:
      spin-clouddriver:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: in
                      values:
                        - clouddriver
                topologyKey: topology.kubernetes.io/zone
```

Do you have any idea what I'm doing wrong?
