### ISSUE TITLE
Cloud driver fails to find Vertical Pod Autoscaler after upgrading apiVersion

### ISSUE THREAD

**Issue by vbhavsar** [spinnaker/spinnaker#4544]
### Issue Summary:
Cloud driver takes hours to determine that a kubernetes deployment is successful despite the new deployment being up and running within minutes.

### Cloud Provider(s):
Google Kubernetes Engine

### Environment:
1.12.5

### Description:
Upgrading the apiVersion of Vertical Pod Autoscaler from `poc.autoscaling.k8s.io/v1alpha1` to `autoscaling.k8s.io/v1beta2` causes cloud driver to not apply the resource.

### Steps to Reproduce:
1. Install [vpa-release-0.2](https://github.com/kubernetes/autoscaler/tree/vpa-release-0.2/vertical-pod-autoscaler#install-command). 
1. Add VerticalPodAutoscaler in hal config
```
  providers:
    kubernetes:
      accounts:
      - configureImagePullSecrets: true
        context: <context>
        customResources:
        - kubernetesKind: CeloSecret
          spinnakerKind: Configs
          versioned: false
        - kubernetesKind: VerticalPodAutoscaler
          spinnakerKind: Unclassified
          versioned: false
...
        kinds:
...
        - VerticalPodAutoscaler
```
1. Upgrade vpa to [vpa-release-0.5.0](https://github.com/kubernetes/autoscaler/tree/vertical-pod-autoscaler-0.5.0/vertical-pod-autoscaler#installation). 
1. Apply a VPA resources that uses apiVersion `autoscaling.k8s.io/v1beta2`.

### Additional Details:
```
$ hal version bom
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
+ Get BOM for 1.12.5
  Success
version: 1.12.5
timestamp: '2019-03-08 23:26:14'
services:
  echo:
    version: 2.3.1-20190214121429
    commit: 5db9d437ca7f2fa374dcada17f77bbbb2965bd67
  clouddriver:
    version: 4.3.5-20190307172446
    commit: f87eb66fd55cd4df7497ef22528a11709745075d
  deck:
    version: 2.7.5-20190308182538
    commit: e9b899d63cb6ea15dc2d6c99a810c8b48886c6a5
  fiat:
    version: 1.3.2-20190128153726
    commit: daf21b24330a5f22866601559aa0f7ac99590274
  front50:
    version: 0.15.2-20190222161456
    commit: 3105e86b8c084ad6ad78507e3a5e5a427f290b99
  gate:
    version: 1.5.2-20190301030607
    commit: b238ab993ab25381ce907260879548ed74a4953f
  igor:
    version: 1.1.1-20190213190226
    commit: 63d06a5c5d55f07443dd60a81035b35cf96238e7
  kayenta:
    version: 0.6.1-20190221030610
    commit: 81d906bf8307143f40fe88f8554baa318de25ef1
  orca:
    version: 2.4.0-20190308182538
    commit: 5e911ff1c29bbc443ce48bcaefbc45f27d389edd
  rosco:
    version: 0.9.0-20190123170846
    commit: 42f81a2501de6d40676d47661579a6106b5c3e8a
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.11.2-20190222030609
    commit: 232c84a8a87cecbc17f157dd180643a8b2e6067a
  monitoring-daemon:
    version: 0.11.2-20190222030609
    commit: 232c84a8a87cecbc17f157dd180643a8b2e6067a
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: gcr.io/spinnaker-marketplace
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker
```

Example VPA:
```
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  namespace: alf
  name: role-resolver
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: role-resolver
  updatePolicy:
    updateMode: "Off"
```

[cloud driver logs](https://gist.github.com/vbhavsar/8db6555cf8340629aa4b2bc43b3590d2)
