### ISSUE TITLE
--omit-namespaces not work for namespace "default"

### ISSUE THREAD

**Issue by tiggerlee2** [spinnaker/spinnaker#4566]
### Issue Summary:

I added **default** to omitNamespaces

> hal config provider kubernetes account edit **ACCOUNT** --add-omit-namespace default

But It did not raise error when deploy manifest to default namespace. 

```
apiVersion: v1
kind: Service
metadata:
  name: my-service-name
  # namespace: default  # unmark this, omitNamespaces can work.
spec:
  ports:
    - name: http-service
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: service-label
```

### Cloud Provider(s):

kubernetes V2 Provider

### Environment:

spinnaker 1.14.0
