### ISSUE TITLE
adding providerRequirements for github leads to too many redirects while logging in

### ISSUE THREAD

**Issue by vchrisb** [spinnaker/spinnaker#4588]
### Issue Summary:

I'm trying to restrict login via oauth2 github provider to only a specific organization.
For that I've added the following to the `gate-local.yml`
```
security:
  oauth2:
    providerRequirements:
      type: github
      organization: XXX
```

With this extra configuration logging it fails with `ERR_TOO_MANY_REDIRECTS` in the browser. This is the only information in `gate-local.yml`. When I remove the configuration again, log in with Github works again.

### Environment:

halyard: 1.20.2
spinnaker: 1.14.8
deployed on kubernetes via helm chart

### Steps to Reproduce:

- Enable Github authentication
- configure providerRequirements for github
