### ISSUE TITLE
Deploy (Manifest) converts string to boolean

### ISSUE THREAD

**Issue by enrichman** [spinnaker/spinnaker#4613]
### Issue Summary:
It seems that the type of the yaml of a pipeline as code are not respected.

Trying to deploy this

```yaml
schema: "1"
id: some-id

stages:
- id: deployTest
  type: deployManifest
  name: Deploy (Manifest)
  config:
    account: myaccount
    cloudProvider: kubernetes
    source: text
    manifests:
    - apiVersion: v1
      kind: Pod
      metadata:
        name: mypod
        namespace: dev
        annotations:
          strategy.spinnaker.io/versioned: "false"
      spec:
        containers:
        - name: mypod
          image: my.image.com/user/pod:latest
    moniker:
      app: myapp
```

I'm getting a `java.lang.Boolean cannot be cast to java.lang.String`

```json
"exception": {
    "cause": "ClassCastException",
    "message": "java.lang.Boolean cannot be cast to java.lang.String",
    "operation": "KubernetesDeployManifestOperation",
    "type": "EXCEPTION"
}
```

Inspecting the source of the resolved manifest it looks like this:

```json
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "annotations": {
            "strategy.spinnaker.io/versioned": false
        },
        "name": "mypod",
        "namespace": "dev"
    },
    "spec": {
        "containers": [
            {
                "image": "my.image.com/user/pod:latest",
                "name": "mypod"
            }
        ]
    }
}
```

I'm working around this with a SpEL: `strategy.spinnaker.io/versioned: ${"false"}` but I suppose that Spinnaker should respect the types.

### Cloud Provider(s):
Kubernetes

### Description:
A provided String value shouldn't be parsed to a Boolean.
