### ISSUE TITLE
SSL HandShake Failure Bitbucet (hosted) Server

### ISSUE THREAD

**Issue by geek876** [spinnaker/spinnaker#4619]
Trying to fetch an artifact from bitbucket server (internal hosted).

It fails with

```
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
We do have the CA within keystore

output of hal config

```
security:
  apiSecurity:
    ssl:
      enabled: true
      keyAlias: spinnaker
      keyStore: /opt/ssl/keystore.jks
      keyStoreType: jks
      keyStorePassword: xxxx
      trustStore: /opt/ssl/keystore.jks
      trustStoreType: jks
      trustStorePassword: xxxx
```
