### ISSUE TITLE
Rosco fails when the `google.accounts.jsonPath` references s3 in the halyard config.

### ISSUE THREAD

**Issue by gochist** [spinnaker/spinnaker#4631]
### Issue Summary:

Rosco fails when the `google.accounts.jsonPath` references s3 in the halyard config.

### Cloud Provider(s):
GCP

### Environment:
- Halyard version: 1.21.2-20190701132842
- Spinnaker version: 1.14.9
- AWS EKS hosting my Spinnaker: 1.13.7-eks-c57ff8

### Steps to Reproduce:

1. Edit `~/.hal/config` to reference s3 path for the `google.accounts.jsonPath`
2. Deploy spinnaker by `hal deploy apply`

### Additional Details:

I verified that rosco runs well when I use local path for the `gce-account.json` file.
This is the google account part of my halyard config that I used. 

```yaml
    google:
      enabled: true
      accounts:
      - name: my-gce-account
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        project: <redacted>
        jsonPath: encrypted:s3!r:us-east-1!b:<redacted>!f:gce-account.json
        alphaListed: false
        imageProjects: []
        consul:
          enabled: false
          agentEndpoint: localhost
          agentPort: 8500
          datacenters: []
```

And this is rosco log.

```

***************************                                                                                                                      
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call the method org.apache.http.conn.ssl.SSLConnectionSocketFactory.<init>(Ljavax/net/ssl/SSLContext;Ljavax/net/ssl/HostnameVerifier;)V but it does not exist. Its class, org.apache.http.conn.ssl.SSLConnectionSocketFactory, is available from the following locations:

    jar:file:/opt/rosco/lib/httpclient-4.3.5.jar!/org/apache/http/conn/ssl/SSLConnectionSocketFactory.class

It was loaded from the following location:

    file:/opt/rosco/lib/httpclient-4.3.5.jar


Action:

Correct the classpath of your application so that it contains a single, compatible version of org.apache.http.conn.ssl.SSLConnectionSocketFactory


```
