### ISSUE TITLE
Spinnaker "Tweakable" Service Settings didn't work as expected

### ISSUE THREAD

**Issue by ealebed** [spinnaker/spinnaker#4692]
### Issue Summary:
Spinnaker "Tweakable" Service Settings didn't work as expected. I tried customize [Kubernetes specific service settings](https://www.spinnaker.io/reference/halyard/custom/#kubernetes), [Deployment Strategy](https://www.spinnaker.io/reference/halyard/custom/#deployment-strategy) 

### Cloud Provider(s):
Kubernetes GKE

### Environment:
Spinnaker 1.15.1 deployed to Kubernetes (V2) GKE cluster via halyard
(the same behaviour was in previous version spinnaker too)

### Description:
When I set custom Service Settings (for example, for rosco in .../service-settings/rosco.yml):
```
kubernetes:
  podAnnotations:
    prometheus_scrape: "true"
    prometheus_metric_path: /prometheus_metrics
    prometheus_metric_port: "8008"
  deploymentStrategy:
    type: rollingUpdate
    strategySettings:
      maxSurge: 100%
      maxUnavailable: 50%
```

and deploy spinnaker via `hal deploy apply`, new settings applied **partially**, e.g.:

```
kubectl get deployment spin-rosco -o yaml -n spinnaker

...
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: spin
      cluster: spin-rosco
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus_metric_path: /prometheus_metrics
        prometheus_metric_port: "8008"
        prometheus_scrape: "true"
      creationTimestamp: null
      labels:
        app: spin
        app.kubernetes.io/managed-by: halyard
        app.kubernetes.io/name: rosco
        app.kubernetes.io/part-of: spinnaker
        app.kubernetes.io/version: 1.15.1
        cluster: spin-rosco
...
```
What am I doing wrong?
