### ISSUE TITLE
Halyard doesn't work with new EKS kube config (no aws cli)

### ISSUE THREAD

**Issue by costimuraru** [spinnaker/spinnaker#4712]
### Issue Summary:
The halyard docker image does not have the `aws-cli`, which is required in newer versions of eks kube configs.

### Cloud Provider(s):
Kubernetes (EKS)

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Halyard

### Description:
Previously, the EKS kube config was relying on the `aws-iam-authenticator` CLI, in order to retrieve an AWS token.
Example:
`aws eks update-kubeconfig --name mycluster`

Would generate something like:

```
$cat ~/.kube/config
....
- name: mycluster
  user:
    exec:
      command: aws-iam-authenticator
      args:
      - token
      - -i
      - dev-va6-ee-eks-experiments
```

This was working fine with halyard, which is installing this binary in the docker image: https://github.com/spinnaker/halyard/blob/master/Dockerfile.local#L25

The latest versions of the aws-cli are not using the `aws-iam-authenticator` anymore. Instead, they are using the `aws-cli` itself:

```
$ cat ~/.kube/config
- name: mycluster
  user:
    exec:
      command: aws
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - dev-va6-ee-eks-experiments
```

This requires the aws cli to be present on the halyard docker image. Currently, the aws cli is not present.
