### ISSUE TITLE
RunJob Manifest state fails

### ISSUE THREAD

**Issue by rverma-nikiai** [spinnaker/spinnaker#4721]
### Issue Summary:
Run Job state failing in UI even though its success in k8 

```
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: issue-cleaner
  name: issue-cleaner
  namespace: app
spec:
  activeDeadlineSeconds: 300
  backoffLimit: 0
  template:
    metadata:
      name: issue-cleaner
      namespace: app
    spec:
      containers:
        - env:
            - name: CLOSED_STATES
              value: 'Done,Closed,Ready for Release'
            - name: IN_CLUSTER
              value: 'true'
            - name: JIRA_TOKEN
              value: sss
            - name: JIRA_URL
              value: 'https://ss.atlassian.net/'
            - name: JIRA_USERNAME
              value: rohit.verma@niki.ai
          image: 'asia.gcr.io/niki-ai/issues-cleaner:1.0.6'
          imagePullPolicy: IfNotPresent
          name: issue-cleaner
          resources: {}
      restartPolicy: Never
```
The job ran successfully and completed within 26s.
```
issue-cleaner-3fc07f1e653dcffc   1/1           26s        5m37s
```
However spinnaker shows error as
```
"details": {
  "responseBody": "{\"error\":\"Not Found\",\"message\":\"Job not found (account: dev, location: 
  app, id: job issue-cleaner-3fc07f1e653dcffc)\",\"status\":404,\"timestamp\":1565096984335}",
  "kind": "HTTP",
  "error": "Not Found",
  "errors": [
   "Job not found (account: dev, location: app, id: job issue-cleaner-3fc07f1e653dcffc)"
  ],
"url": "http://spin-clouddriver-rw.spinnaker:7002/applications/issue-cleaner/jobs/dev/app/job%20issue-cleaner-3fc07f1e653dcffc",
"status": 404
},
"operation": "waitOnJobCompletion",
```
What am I missing? (edited) 

Is this related if we are running spinnaker in HA mode

### Cloud Provider(s):
EKS

### Environment:
Kubernetes 1.13.7

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Run Job
