### ISSUE TITLE
Disable (Manifest) is not working

### ISSUE THREAD

**Issue by gtpark** [spinnaker/spinnaker#4830]
### Issue Summary:
Disable (Manifest) not working

### Cloud Provider(s):
* Kubernetes

### Environment:
* Spinnaker 14.14
* I am running Spinnaker using the helm/chart spinnaker images to deploy into Private kubernetes cluster

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
* Stage > Disable (Manifest)

### Description:
Disable (Manifest) stage is not working.
I know that Spiannker supports the blue / green deployment. (See [link](https://www.spinnaker.io/guides/user/kubernetes-v2/traffic-management/))

But this doesn't work. ReplicaSets are not disabled.
The following error message occurs during the disable stage.

#### Error message
```
Patch failed: Error from server: jsonpatch remove operation does not apply: 
doc is missing path: /spec/template/metadata/labels/app.kubernetes.io/instance
```

#### ReplicaSet YAML
```yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: hello
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: hello   # Auto-Generated by Spinnaker
        app.kubernetes.io/managed-by: spinnaker   # Auto-Generated by Spinnaker
        app.kubernetes.io/name: hello-rs   # Auto-Generated by Spinnaker
        moniker.spinnaker.io/sequence: "15"   # Auto-Generated by Spinnaker
```

My guess is that it's the wrong jsonpatch path. Slash is ambiguous. When I tested on [this site](https://json-patch-builder-online.github.io/), if the name includes a slash, it must be escaped as '~ 1'.

### Steps to Reproduce:
Same step below 
https://www.spinnaker.io/guides/user/kubernetes-v2/traffic-management/

[Summary]
(1) Create bake stage by Helm2
(2) Create deploy stage
(3) Create Disable stage by dynamic or static
(4) deploy
