### ISSUE TITLE
SAML, Okta integration authz roles issue

### ISSUE THREAD

**Issue by utkarsh-sharma-dragon** [spinnaker/spinnaker#4839]
We've integrated Okta with spinnaker which is working perfectly fine. Before okta, We were using roles.yml for RBAC `FILE` which had all the users defined with their respective roles.
```
#/home/spinnaker/roles.yaml
  5 users:
  6   - username: service-account
  7     roles:
  8       - admin
  9       - read
 11   - username: utkarsh@xyz.com
 12     roles:
 13       - admin
 14       - read
```

Later, in order to use okta groups we changed `FILE` to `EXTERNAL` in the authz section. This disabled all users from roles.yml and added okta groups, The permissions/roles were working as expected.
```
#halyard config file
     authz:
       groupMembership:
         service: FILE == changed to EXTERNAL
         google:
           roleProviderType: GOOGLE
         github:
           roleProviderType: GITHUB
         file:
           roleProviderType: FILE
           path: /home/spinnaker/roles.yaml
         ldap:
           roleProviderType: LDAP
       enabled: true
```

But the roles.yaml file also had `service-account` user manage fiat and cloudriver. After disabling `file` from authz section, the pipelines with an automated trigger doesn't show the service account
We have also tried recreating the pipeline but the fiat service account is not visible in the automated trigger section.

I am getting the below warning in fiat.
```
WARN 1 — [ront50Service-9] c.n.s.okhttp.OkHttpMetricsInterceptor    : [] Request GET:http://spin-front50.spinnaker:8080/permissions/applications is missing [X-SPINNAKER-USER, X-SPINNAKER-ACCOUNTS] authentication headers and will be treated as anonymous.
Request from: com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:94)
at 
```

![Screen Shot 2019-09-05 at 20 23 06](https://user-images.githubusercontent.com/52151459/64353486-75c43c80-d01b-11e9-80dc-7d25a2c6e7ab.png)

Need help on the following:
- How to enable the [fiat service account](https://www.spinnaker.io/setup/security/authorization/service-accounts/) with okta saml. As the service account disappears on after changing the authz type to `EXTERNAL`
