### ISSUE TITLE
Halyard: Add support for specifying lifecycleHooks for AWS accounts

### ISSUE THREAD

**Issue by costimuraru** [spinnaker/spinnaker#4851]
### Issue Summary:
Spinnaker supports an option to automatically add lifecycle hooks to the Auto Scale Groups (ASGs) created in AWS accounts. We previously added these hooks directly in `clouddriver-local.yaml`, before using halyard. However, now that we've moved to hal, we are not able to set these lifecycle hooks, because no command exists for it yet.

### Cloud Provider(s):
AWS

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Halyard

### Description:

`clouddriver-local.yaml`

```yaml
aws:
  accounts:
    - name: sae
      assumeRole: role/spinnakermanaged
      accountId: 000000000
      regions:
        - name: sa-east-1
      lifecycleHooks:
      - defaultResult: 'CONTINUE'
        heartbeatTimeout: 1200
        lifecycleTransition: 'autoscaling:EC2_INSTANCE_LAUNCHING'
        notificationTargetARN: 'arn:aws:sns:{{region}}:{{accountId}}:spinnaker-lifecycle-pending'
        roleARN: 'arn:aws:iam::{{accountId}}:role/spinnakerasg'
      - defaultResult: 'CONTINUE'
        heartbeatTimeout: 7200
        lifecycleTransition: 'autoscaling:EC2_INSTANCE_TERMINATING'
        notificationTargetARN: 'arn:aws:sns:{{region}}:{{accountId}}:spinnaker-lifecycle-pending'
        roleARN: 'arn:aws:iam::{{accountId}}:role/spinnakerasg'
```
