### ISSUE TITLE
New UI does not add the 'reference' field in the inputArtifact

### ISSUE THREAD

**Issue by joariasl** [spinnaker/spinnaker#4874]
### Issue Summary:

`Bake (Manifest)` Helm task returns an exception if you create the stage completely using the New UI because it does not add the `reference` field.

### Cloud Provider(s):

Kubernetes

### Environment:

All

### Feature Area:

@spinnaker/ui-ux-team

### Description:

This is caused why the New UI create all the expected Helm Chart using the `inputArtifacts` array inside the stage instead of the old implementation using an `expectedArtifacts` configuration in the Pipeline and it does not add the reference field in the configured artifact attributes like the old implementation that adds the same name of the Helm artifact account.

Additionally, the Helm Chart configured as artifact in the stage is not visible as consumed artifact in the pipeline detail and don't show the option of specify another Helm Chart in the start of the pipeline included in the Spinneker version 1.16.0.

Additionally, the new UI does not allow to see the configuration of the Helm Chart artifact and edit it.

### Steps to Reproduce:

1. To compare create a Pipeline using the old UI with a Stage to `Bake (Manifest)` a configured Helm Chart as expected artifact.
2. Enable the new UI adding the configuration `window.spinnakerSettings.feature.artifactsRewrite = true;` in the file `~/.hal/default/profiles/settings-local.js` and re-deploy Spinnaker using halyard
3. Create a Pipeline similar to the previous using the new UI in the `Bake (Manifest)` to configure the inputArtifacts Helm Chart using the interface.
4. Notice that the Pipeline generated using the old UI looks like

```yaml
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "artifactAccount": "helm-account",
        "id": "yyy",
        "name": "chart",
        "reference": "helm-account",
        "type": "helm/chart",
        "version": "0.1.0"
      },
      "displayName": "chart",
      "id": "xxx",
      "matchArtifact": {
        "artifactAccount": "helm-account",
        "id": "zzz",
        "name": "chart",
        "reference": "helm-account",
        "type": "helm/chart",
        "version": "0.1.0"
      },
      "useDefaultArtifact": true,
      "usePriorArtifact": false
    }
  ],
# ...
  "stages": [
    {
      # ...
      "inputArtifacts": [
        {
          "account": "helm-account",
          "id": "xxx"
        }
      ],
      "name": "Bake (Manifest)",
      "templateRenderer": "HELM2",
      "type": "bakeManifest"
      # ...
    }
  ]
```

and the Pipeline using the new UI looks like

```yaml
# "expectedArtifacts": [], # Does not exist in this Pipeline (it's OK, it's not required because the artifact is configured in the stage itself)
# ...
  "stages": [
    {
      # ...
      "inputArtifacts": [
        {
          "account": "helm-account",
          "artifact": {
            "artifactAccount": "helm-account",
            "id": "xxx",
            "name": "scotia-chart",
            # "reference": "helm-account", # The missing field
            "type": "helm/chart",
            "version": "0.1.0"
          }
        }
      ],
      "name": "Bake (Manifest)",
      "templateRenderer": "HELM2",
      "type": "bakeManifest"
      # ...
    }
  ]
```

### Additional Details:

Error in Pipeline stage

![image](https://user-images.githubusercontent.com/8829064/64713868-070c3680-d494-11e9-98fe-2659d1d4bdf3.png)
