### ISSUE TITLE
Basic auth passwords containing `$` are not handled correctly

### ISSUE THREAD

**Issue by willgorman** [spinnaker/spinnaker#4920]
I've noticed that login fails with a `.spin/config` of

```
auth:
  enabled: true
  basic:
    username: someuser
    password: pas$word
```
 
After adding some more logging I can see that the value `spin` gets for the password is just `pas`.  If I escape the `$` like

```
auth:
  enabled: true
  basic:
    username: someuser
    password: pas$$word
```

then the value that `spin` attempts to use is `pasword`.  I've also tried double quotes, single quotes and multiline strings to see if there some way to get it to be preserved but haven't found anything that works yet.
