### ISSUE TITLE
ReplicaSets aren't deployed correctly

### ISSUE THREAD

**Issue by denysvitali** [spinnaker/spinnaker#4923]
### Issue Summary:
This basic pipeline stage fails unexpectedly, I don't seem to be able to find a reason for that and I don't see it mentioned anywhere in the documentation.

```json
{
  "account": "k8s-dev",
  "cloudProvider": "kubernetes",
  "expectedArtifacts": [],
  "manifests": [
    {
      "apiVersion": "apps/v1",
      "kind": "ReplicaSet",
      "metadata": {
        "labels": {
          "app": "deployment-test-1",
          "branch": "dev",
          "env": "dev"
        },
        "name": "rs-deployment-test-1-dev-dev"
      },
      "spec": {
        "replicas": 2,
        "selector": {
          "matchLabels": {
            "app": "deployment-test-1",
            "branch": "dev",
            "env": "dev"
          }
        },
        "template": {
          "metadata": {
            "labels": {
              "app": "deployment-test-1",
              "branch": "dev",
              "env": "dev"
            }
          },
          "spec": {
            "containers": [
              {
                "env": [
                  {
                    "name": "ENV",
                    "value": "dev"
                  }
                ],
                "image": "${IMAGE}",
                "name": "deployment-ctr-dev-dev",
                "ports": [
                  {
                    "containerPort": 3000
                  }
                ]
              }
            ],
            "imagePullSecrets": [
              {
                "name": "regcred"
              }
            ]
          }
        }
      }
    }
  ],
  "moniker": {
    "app": "dt1"
  },
  "name": "Deploy (Manifest)",
  "namespaceOverride": "",
  "requiredArtifactIds": [],
  "requiredArtifacts": [],
  "skipExpressionEvaluation": false,
  "source": "text",
  "trafficManagement": {
    "enabled": true,
    "options": {
      "enableTraffic": true,
      "namespace": "default",
      "services": [
        "service svc-deployment-test-1-dev-dev"
      ],
      "strategy": "redblack"
    }
  },
  "type": "deployManifest"
}
```

Which basically deploys the following manifest and attaches service `svc-deployment-test-1-dev-dev` as a Load Balancer:

```yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: deployment-test-1
    branch: dev
    env: dev
  name: rs-deployment-test-1-dev-dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-test-1
      branch: dev
      env: dev
  template:
    metadata:
      labels:
        app: deployment-test-1
        branch: dev
        env: dev
    spec:
      containers:
        - env:
            - name: ENV
              value: dev
          image: '${IMAGE}'
          name: deployment-ctr-dev-dev
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: regcred
```

### Cloud Provider(s):
OVH's managed K8s

### Environment:
Spinnaker (1.16.0) deployed on a k8s cluster (dev), creating deployments on other k8s clusters (including its own)

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
Pipelines

### Description:
When the pipeline step is triggered, the following error is thrown:
![Screenshot 2019-09-18 at 12 40 09](https://user-images.githubusercontent.com/4939519/65141772-8e682580-da11-11e9-9abb-f409a795e033.png)

```
Exception ( Monitor Disable )
Patch failed: The ReplicaSet "rs-deployment-test-1-dev-dev-v019" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app.kubernetes.io/managed-by":"spinnaker", "app.kubernetes.io/name":"dt1", "moniker.spinnaker.io/sequence":"19"}: selector does not match template labels
```

![Screenshot 2019-09-18 at 12 41 37](https://user-images.githubusercontent.com/4939519/65141821-adff4e00-da11-11e9-857d-92a4ddad3255.png)

### Steps to Reproduce:
Import the pipeline, add the following as LB:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: svc-deployment-test-1-dev-dev
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: deployment-test-1
    env: dev
    branch: dev
  type: NodePort
```

and the following as a Server Group:
```yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: deployment-test-1
    env: dev
    branch: dev
  name: 'rs-deployment-test-1-dev-dev'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-test-1
      env: dev
      branch: dev
  template:
    metadata:
      labels:
        app: deployment-test-1
        env: dev
        branch: dev
    spec:
      containers:
        - image: 'some-image'
          name: deployment-ctr-dev-dev
          ports:
            - containerPort: 3000
          env:
            - name: ENV
              value: dev
      imagePullSecrets:
        - name: regcred
```
### Additional Details:
This might be entirely my fault based on my low-knowledge of Spinnaker - or it might be a bug
