### ISSUE TITLE
Deploy Manifest fails to resolve variables set by 'Evaluate variables' stage

### ISSUE THREAD

**Issue by DmitrySolodovnyk** [spinnaker/spinnaker#4932]
### Issue Summary:

Deploy Manifest fails to resolve variables set by 'Evaluate variables' stage if Manifest source is a git artifact. 

### Cloud Provider(s):
GKE
### Environment:
Kubernetes V2

### Feature Area 
Pipelines, SpEL expressions.

### Description:

I'd like to have a common manifest artifact for different environments changing behavior with  SpEL expressions. It can be done with pipeline parameters but if there are more than 3 parameters it looks messy.
I try to set variables with 'Evaluate variables' stage and then use it in manifest. 
It works fine if Deploy stage has configured Manifest Source as Text. But if Manifest source is an artifact in git (exactly the same manifest code) - it fails to resolve variables

### Steps to Reproduce:

Create a pipeline, add 'Evaluate variable' stage with two variables :
namespace - default
stack - stg
Add 'Deploy (Manifest)' stage

Manifest code:
```
- apiVersion: v1
  kind: Service
  metadata:
    name: example-com
    namespace: ${ namespace }
    annotations:
      moniker.spinnaker.io/stack: ${ stack }
  spec:
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 80
    selector:
      load-balancer-example-com: "true"
    sessionAffinity: None
    type: LoadBalancer
```

If the manifest source is text  - it works. The same code at github as an artifact would fail to resolve variables. 

### Additional Details:
![Screenshot from 2019-09-19 19-10-05](https://user-images.githubusercontent.com/1533610/65261601-4cbea400-db11-11e9-980a-0eba07a5b247.png)
![Screenshot from 2019-09-19 19-10-36](https://user-images.githubusercontent.com/1533610/65261623-5942fc80-db11-11e9-9166-4e68d4d24cdf.png)
