### ISSUE TITLE
Custom webhook stage: Can not pre-configure `Fail Fast HTTP Statuses`

### ISSUE THREAD

**Issue by afcastano** [spinnaker/spinnaker#5009]
### Issue Summary:
We are configuring a custom webhook stage. There is no way of pre-configuring the field: `Fail Fast HTTP Statuses` so it always shows up in the UI.

<img width="1232" alt="Screen Shot 2019-10-08 at 3 47 27 pm" src="https://user-images.githubusercontent.com/3589427/66368191-027b6500-e9e3-11e9-84fe-48fc1075bf7e.png">

### Environment:
Spinnaker 1.16.1 running on GKE

### Feature Area:
Custom webhooks. UI Deck and Orca

### Description:
We have a custom webhook configured, but there is no way to preconfigure the field: `Fail Fast HTTP Statuses` so it always appears as a field in the UI.

Our configuration in `orca-local.yml` is as follows:
```yaml
webhook:
          preconfigured:
          - label: my-webhook
            type: myWebhook
            enabled: true
            description: Do custom stuff
            method: GET
            url: http://spike-service:8088/user/${trigger['user']}/account/${parameterValues['myAccount']}
            customHeaders: 
               x-custom: true    
            payload: ''
            waitForCompletion: false
            terminalStatuses: ''
            parameters:
            - label: account name
              name: myAccount
              description: blah
              defaultValue: ''
              type: string
```
Looking at the code, it seems the feature is not implemented.  
In `deck`, we can see this line: https://github.com/spinnaker/deck/blob/7368523f7485726a069e9ad8b06558f147125508/app/scripts/modules/core/src/pipeline/config/stages/webhook/webhookStage.html#L17
Which always show the field `Fail Fast HTTP Statuses`.  

Also in `orca` there is no way to pre populate the field as we can see here:
https://github.com/spinnaker/orca/blob/2d2f9240a3989853f111c074ae6845e1a3ccaf05/orca-webhook/src/main/java/com/netflix/spinnaker/orca/webhook/config/WebhookProperties.java#L69-L90
So the method: `getPreconfiguredProperties()` will never return such property.

### Steps to Reproduce:
NA

### Additional Details:
Ideally we could configure that field so that users wont get confused by it.
