### ISSUE TITLE
issue with spinnaker during redirection to spinnaker-api

### ISSUE THREAD

**Issue by erlchamp** [spinnaker/spinnaker#5013]
### Issue Summary:
I deployed Spinnaker on GKE using Halyard and expose the Spinnaker UI and API to public and access it via http://spinnaker.$DOMAIN 

I can see the home page but when it "authenticates" then redirects to http://spinnaker-api.$DOMAIN - I am getting error response

<img width="400" alt="Screenshot 2019-10-10 at 3 00 53 PM" src="https://user-images.githubusercontent.com/37998321/66546120-da207180-eb6e-11e9-9940-b2e24d179c0f.png">

<img width="684" alt="Screenshot 2019-10-10 at 2 34 59 PM" src="https://user-images.githubusercontent.com/37998321/66545263-e1468000-eb6c-11e9-9ef0-77d26612d96d.png">

### Cloud Provider(s):
GKE

### Environment:
my Halyard is installed on EC2 and Spinnaker on GKE

Here is my /.hal/config

```
spinnaker@ip-10-0-0-41:~/.hal$ cat config 
currentDeployment: default
deploymentConfigurations:
- name: default
  version: 1.16.2
  providers:
    appengine:
      enabled: false
      accounts: []
    aws:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
    azure:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      clusters: []
    dockerRegistry:
      enabled: true
      accounts:
      - name: my-docker-registry
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        address: https://index.docker.io
        username: **REDACTED**
        password: **REDACTED**
        email: fake.email@spinnaker.io
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 1
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories:
        - /hugo
      primaryAccount: my-docker-registry
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        useInternalIp: false
    kubernetes:
      enabled: true
      accounts:
      - name: my-k8s-account
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        dockerRegistries:
        - accountName: my-docker-registry
          namespaces: []
        context: gke_terraform-gke-252715_us-central1-a_gkecluster
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/spinnaker/.kube/config
        oAuthScopes: []
        onlySpinnakerManaged: false
      primaryAccount: my-k8s-account
    oracle:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: oci.json
        baseImages: []
    cloudfoundry:
      enabled: false
      accounts: []
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: my-k8s-account
    imageVariant: SLIM
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    customSizing: {}
    sidecars: {}
    initContainers: {}
    hostAliases: {}
    affinity: {}
    tolerations: {}
    nodeSelectors: {}
    gitConfig:
      upstreamUser: spinnaker
    livenessProbeConfig:
      enabled: false
    haServices:
      clouddriver:
        enabled: false
        disableClouddriverRoDeck: false
      echo:
        enabled: false
  persistentStorage:
    persistentStoreType: gcs
    azs: {}
    gcs:
      jsonPath: /home/spinnaker/.gcp/gcs-account.json
      project: terraform-gke-252715
      bucket: spin-1abb7f51-7d39-468c-9ad9
      rootFolder: front50
      bucketLocation: us
    redis: {}
    s3:
      rootFolder: front50
    oracle: {}
  features:
    auth: false
    fiat: false
    chaos: false
    entityTags: false
    jobs: false
  metricStores:
    datadog:
      enabled: false
      tags: []
    prometheus:
      enabled: false
      add_source_metalabels: true
    stackdriver:
      enabled: false
    period: 30
    enabled: false
  notifications:
    slack:
      enabled: false
    twilio:
      enabled: false
      baseUrl: https://api.twilio.com/
    github-status:
      enabled: false
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: false
      masters: []
    travis:
      enabled: false
      masters: []
    wercker:
      enabled: false
      masters: []
    concourse:
      enabled: false
      masters: []
    gcb:
      enabled: false
      accounts: []
  repository:
    artifactory:
      enabled: false
      searches: []
  security:
    apiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://spinnaker-api.$DOMAIN
    uiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://spinnaker.$DOMAIN
    authn:
      oauth2:
        enabled: true
        client:
          clientId: **REDACTED**
          clientSecret: **REDACTED**
          accessTokenUri: https://www.googleapis.com/oauth2/v4/token
          userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
          scope: profile email
        userInfoRequirements:
          hd: $DOMAIN
        resource:
          userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
        userInfoMapping:
          email: email
          firstName: given_name
          lastName: family_name
        provider: GOOGLE
      saml:
        enabled: false
        userAttributeMapping: {}
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: true
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
        ldap:
          roleProviderType: LDAP
      enabled: false
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    oracle:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    gitlab:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    helm:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []
    maven:
      enabled: false
      accounts: []
    templates: []
  pubsub:
    enabled: false
    google:
      enabled: false
      pubsubType: GOOGLE
      subscriptions: []
      publishers: []
  canary:
    enabled: false
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: false
      accounts: []
    - name: datadog
      enabled: false
      accounts: []
    - name: signalfx
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    - name: newrelic
      enabled: false
      accounts: []
    reduxLoggerEnabled: true
    defaultJudge: NetflixACAJudge-v1.0
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true
  plugins:
    plugins: []
    enabled: false
    downloadingEnabled: false
    pluginConfigurations:
      plugins: {}
  webhook:
    trust:
      enabled: false
  telemetry:
    enabled: false
    endpoint: https://stats.spinnaker.io
    instanceId: 01DPRAMNGWPC037TSP
    connectionTimeoutMillis: 3000
    readTimeoutMillis: 5000
```

### Steps to Reproduce:
I changed the deck and gate to NodePort and created one ingress to expose Spinnaker to public

```
spinnaker@ip-10-0-0-41:~/.hal$ kubectl get svc -n spinnaker
NAME                         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                         AGE
spin-clouddriver             ClusterIP   10.59.242.140   <none>        7002/TCP,8008/TCP               3h5m
spin-clouddriver-bootstrap   ClusterIP   10.59.254.217   <none>        7002/TCP,8008/TCP               167m
spin-deck                    NodePort    10.59.243.65    <none>        9000:32275/TCP,8008:32445/TCP   3h4m
spin-echo                    ClusterIP   10.59.250.127   <none>        8089/TCP,8008/TCP               3h4m
spin-front50                 ClusterIP   10.59.247.53    <none>        8080/TCP,8008/TCP               3h5m
spin-gate                    NodePort    10.59.255.147   <none>        8084:30337/TCP,8008:30303/TCP   3h4m
spin-igor                    ClusterIP   10.59.247.144   <none>        8088/TCP,8008/TCP               3h4m
spin-orca                    ClusterIP   10.59.250.142   <none>        8083/TCP,8008/TCP               3h5m
spin-orca-bootstrap          ClusterIP   10.59.251.49    <none>        8083/TCP,8008/TCP               165m
spin-redis                   ClusterIP   10.59.248.144   <none>        6379/TCP,8008/TCP               4h18m
spin-redis-bootstrap         ClusterIP   10.59.252.214   <none>        6379/TCP,8008/TCP               167m
spin-rosco                   ClusterIP   10.59.250.188   <none>        8087/TCP,8008/TCP               3h4m
```

```
spinnaker@ip-10-0-0-41:~/.hal$ kubectl get ingress -n spinnaker
 NAME                HOSTS                                                     ADDRESS        PORTS   AGE
spinnaker-ingress   spinnaker-api.$DOMAIN,spinnaker.$DOMAIN   x.x.x.x   80      146m
```

### Additional Details:

I followed this guide

https://itnext.io/deploying-spinnaker-on-gke-125ef47a8c9
