### ISSUE TITLE
Trying to deploy a service with Spring Config Server fails in halyard

### ISSUE THREAD

**Issue by dbason** [spinnaker/spinnaker#5016]
### Issue Summary:
Trying to deploy clouddriver with a Spring Config Server from halyard in docker and is is failing with the error `Config Server repository not configured for resource`

### Cloud Provider(s):
Kubernetes V2

### Feature Area:
Halyard/Clouddriver Deployment

### Description:
Expect Halyard to deploy Clouddriver with the expected config.  However it throws an error.

### Steps to Reproduce:
Have the following content in both clouddriver-local.yml and clouddriverconfig.yml in the profiles folder:
```
spring:
  profiles:
    include: vault
  cloud:
    config:
      server:
        vault:
          host: [vaulturl]
          port: 443
          scheme: https
          backend: spinnakerdev
          kvVersion: 2
          default-key: kubeconfigs
          token: [token]
```
Have also tried this with the file called spinnakerconfig.yml and spinnaker-config-local.yml and other files referenced in the docs.
### Additional Details:

---
