### ISSUE TITLE
All enabled expected artifacts are not showing

### ISSUE THREAD

**Issue by erlchamp** [spinnaker/spinnaker#5027]
### Issue Summary:
After enabling Github artifact via hal, and re-deploy spinnaker. It doesn't show 'Github" under **Expected Artifacts**

<img width="945" alt="Screenshot 2019-10-15 at 5 41 17 PM" src="https://user-images.githubusercontent.com/37998321/66821017-4ab2fe00-ef74-11e9-9d5f-96ea821235fc.png">

hal config artifact github enable
hal config artifact github account add my-git-artifact-account --token-file $TOKEN_FILE

```
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    oracle:
      enabled: false
      accounts: []
    github:
      enabled: true
      accounts:
      - name: my-git-artifact-account
        tokenFile: /home/centos/github-token
```

### Cloud Provider(s):
GKE

### Additional Details:
hal version: 1.24.0-20191002142815
