### ISSUE TITLE
Kubernetes Provider V2: LoadBalancer Service does not exist

### ISSUE THREAD

**Issue by tonyg4864** [spinnaker/spinnaker#5040]
### Issue Summary:
I am currently facing an issue where a Deploy (Manifest) stage fails to find a pre-existing Kubernetes service/loadbalancer. This happens while I have enabled Red/Black Rollout Strategy.

### Cloud Provider(s):
Kubernetes

### Environment:

1. Spinnaker v1.16.2 with no MYSQL enabled. 
2. Spinnaker v1.16.3 with MYSQL enabled for Orca, Front50 and Clouddriver.
3. liveManifestCalls = true

### Feature Area:

- Kubernetes Provider V2
- CloudDriver
- Pipelines
- Rollout Strategies
- Red/Black

### Description:

- I am currently facing an issue where a Deploy (Manifest) stage fails to find a pre-existing Kubernetes service/loadbalancer. This happens while I have enabled Red/Black Rollout Strategy. I am using the Kubernetes V2 provider. 

- I noticed that this happens while I'm using a Helm Chart Artifact to deploy the ReplicaSet. If I copy paste the rendered replicaset.yaml file out of the HelmChart into a raw text Deploy(Manifest ) stage, the issue does not happen.

- I see a potential issue with a clouddriver query. It seems it’s using the Spinnaker application name where the service name is supposed to be used instead. In the query below san-tony-bluegreen is my Spinnaker application name , not my Kubernetes service name. :

```2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Executing query          : SELECT id FROM cats_v1_loadBalancers WHERE id LIKE 'kubernetes:loadBalancers:%:%:san-tony-bluegreen'```

Here is my Spinnaker Deployed Load Balancer:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    artifact.spinnaker.io/location: san-tony-bluegreen
    artifact.spinnaker.io/name: mediastreaming-ovsys-22644-bluegreen
    artifact.spinnaker.io/type: kubernetes/service
    moniker.spinnaker.io/application: san-tony-bluegreen
    moniker.spinnaker.io/cluster: service mediastreaming-ovsys-22644-bluegreen
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: san-tony-bluegreen
  name: mediastreaming-ovsys-22644-bluegreen
  namespace: san-tony-bluegreen
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    frontedByInstance: ovsys-22644-bluegreen
    frontedByName: mediastreaming
  type: NodePort
```

- In the query , it seems that the first wildcard is meant for the kubernetes account name, the second wildcard is meant for the Spinnaker application name, and the 3rd field should be the name of the Loadbalancer which in this case is “mediastreaming-ovsys-22644-bluegreen” .

The log shows 0 records found for that query .

But I know my loadbalancer does exist in the DB. If I manually run the following query, I get a matching record:
    SELECT id FROM cats_v1_loadBalancers where id like '%san-tony-bluegreen%';

Found Record:
    kubernetes:loadBalancers:my-k8s-account:san-tony-bluegreen:mediastreaming-ovsys-22644-bluegreen

### Steps to Reproduce:
1. Deploy a Kubernetes Service/ Spinnaker LoadBalancer using the "Create Load Balancer" Option under a Spinnaker Application in Infrastructure->LoadBalancers. Use the Kubernetes V2 provider. 
Sample Service:
 ```
apiVersion: v1
kind: Service
metadata:
  name: mediastreaming-ovsys-22644-bluegreen
  namespace: san-tony-bluegreen
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    frontedByInstance: ovsys-22644-bluegreen
    frontedByName: mediastreaming
  type: NodePort
```
2. Create a Pipeline that contains a Deploy (Manifest) stage. Configure the Stage to deploy a ReplicaSe using a Helm Chart artifact. 
3. Enable the Red/Black Rollout Strategy functionality. Select the service previously created. 
4. Run the pipeline to deploy the application. 
5. Notice that the deployment stage fails with the following error:
```
Exception ( Monitor Deploy )
Load balancer service mediastreaming-ovsys-22644-bluegreen does not exist
```
![ServiceNotFound](https://user-images.githubusercontent.com/25211037/67055879-a4dfca80-f0fe-11e9-9ad9-72ac4e01a7e9.png)

### Additional Details:

1. My Deployment Manifest stage uses a Helm Chart artifact to deploy the ReplicaSet.
2. Although Im testing this by deploying the Service separately and manually...It'll be great if this scenario also works when including the deployment of the Service in the HelmChart. In practice we use one HelmChart to deploy most of our Kubernetes manifest/resources . Example: We use 1 HelmChart to deploy the ingress, service, secrets, configmaps and replica sets for a particular application.
3.  The sample log message from clouddriver that I feel is performing the incorrect query is : 
```2019-10-17 20:33:14.346 DEBUG 1 --- [0.0-7002-exec-3] o.a.c.loader.WebappClassLoaderBase       :     findClass(com.netflix.spinnaker.clouddriver.search.SearchProvider$search)
2019-10-17 20:33:14.347 DEBUG 1 --- [pool-8-thread-3] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@462ea3ed
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched result           : +----+
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : |id  |
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : +----+
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched row(s)           : 0
2019-10-17 20:33:14.347 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Executing query          : SELECT id FROM cats_v1_loadBalancers WHERE id LIKE 'kubernetes:loadBalancers:%:%:san-tony-bluegreen'
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-1] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2019-10-17 20:33:14.347 DEBUG 1 --- [pool-8-thread-3] org.jooq.impl.DefaultConnectionProvider  : commit
2019-10-17 20:33:14.347 DEBUG 1 --- [0.0-7002-exec-3] o.a.c.loader.WebappClassLoaderBase       :     --> Returning ClassNotFoundException
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@14505491
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : Executing query          : delete from cats_agent_locks where (agent_name = ? and lock_expiry = ?)
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : -> with bind values      : delete from cats_agent_locks where (agent_name = 'SqlTableMetricsAgent' and lock_expiry = '1571344390184')
2019-10-17 20:33:14.348 DEBUG 1 --- [gentScheduler-1] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@462ea3ed
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched result           : +----+
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : |id  |
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            :                          : +----+
2019-10-17 20:33:14.349 DEBUG 1 --- [0.0-7002-exec-1] org.jooq.tools.LoggerListener            : Fetched row(s)           : 0
2019-10-17 20:33:14.349 DEBUG 1 --- [pool-8-thread-3] org.jooq.impl.DefaultConnectionProvider  : setting auto commit      : true
2019-10-17 20:33:14.350 DEBUG 1 --- [0.0-7002-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Using 'application/json;charset=UTF-8', given [application/json;charset=UTF-8] and supported [application/json]
2019-10-17 20:33:14.350 DEBUG 1 --- [0.0-7002-exec-1] m.m.a.RequestResponseBodyMethodProcessor : Writing [[KubernetesV2LoadBalancer(serverGroups=[], manifest={metadata={annotations={artifact.spinnaker.io/lo (truncated)...]
2019-10-17 20:33:14.350 DEBUG 1 --- [0.0-7002-exec-1] o.s.web.servlet.DispatcherServlet        : Completed 200 OK
2019-10-17 20:33:14.351 DEBUG 1 --- [pool-8-thread-3] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.mysql.cj.jdbc.ConnectionImpl@4119dd79
2019-10-17 20:33:14.351 DEBUG 1 --- [pool-8-thread-3] o.s.jdbc.datasource.DataSourceUtils      : Fetching JDBC Connection from DataSource
2019-10-17 20:33:14.351 DEBUG 1 --- [0.0-7002-exec-1] o.a.c.http11.filters.GzipOutputFilter    : Flushing the compression stream!
2019-10-17 20:33:14.351 DEBUG 1 --- [gentScheduler-1] org.jooq.tools.LoggerListener            : Affected row(s)          : 1
2019-10-17 20:33:14.352 DEBUG 1 --- [0.0-7002-exec-1] o.s.s.w.a.ExceptionTranslationFilter     : Chain processed normally
2019-10-17 20:33:14.352 DEBUG 1 --- [pool-8-thread-3] org.jooq.impl.DefaultConnectionProvider  : setting auto commit      : false
2019-10-17 20:33:14.352 DEBUG 1 --- [gentScheduler-1] com.zaxxer.hikari.pool.PoolBase          : default - Reset (isolation) on connection com.```
