### ISSUE TITLE
Hal config provider google account add fails with  "Required 'compute.projects.get' permission"

### ISSUE THREAD

**Issue by zirzirikos** [spinnaker/spinnaker#5045]
### Issue Summary:
I have been following the installation instructions after setting up a GCP service account and attempting to set up Halyard I get the error "Required 'compute.projects.get' permission for 'projects/my-project'"

### Cloud Provider(s):
GCP

### Environment:
Running halyard as local docker image with the following command line:

`docker run -p 8084:8084 --name halyard --rm -v ~/.hal:/home/spinnaker/.hal -v ~/.gcp:/home/spinnaker/.gcp -it gcr.io/spinnaker-marketplace/halyard:stable`

### Feature Area:
Installation / Documentation

### Description:
I have validated the correct permissions exist on the service account. I'm a bit of a GCP newbie so maybe I'm doing something wrong...

### Steps to Reproduce:

(project name replaced with `my-project`)

1. Created a brand new GCP project
1. Enabled Google Compute API
1. Ran halyard in a Docker container with `docker run -p 8084:8084 --name halyard --rm -v ~/.hal:/home/spinnaker/.hal -v ~/.gcp:/home/spinnaker/.gcp -it gcr.io/spinnaker-marketplace/halyard:stable`
1. Followed [Halyard installation instructions for GCP](https://www.spinnaker.io/setup/install/providers/gce/) and when I get to this step 

`hal config provider google account add spinnaker-service-account --project my-project --json-path ~/.gcp/spinnaker-service-account.json`

I get this output:

```
+ Get current deployment
  Success
- Add the spinnaker-service-account account
  Failure
Problems in default.provider.google:
! ERROR Failed to load project "my-project": 403
  Forbidden
{
"code" : 403,
"errors" : [ {
"domain" : "global",
"message" : "Required 'compute.projects.get' permission for
  'projects/my-project'",
"reason" : "forbidden"
} ],
"message" : "Required 'compute.projects.get' permission for
  'projects/my-project'"
}.

! ERROR Zone us-central1-f not found via any configured google
  account.

! ERROR Network default not found via any configured google
  account.

- Failed to add account spinnaker-service-account for provider
  google.

```

### Additional Details:

Output of last `gcloud projects add-iam-policy-binding` command shown below, showing service account has required role bindings (project name, my primary admin account email and other identifiers replaced with generic strings).

Have also validated this on Console and have checked the JSON key is accessible and readable on the Halyard container and generally done a *lot* of checking for typos etc.

```
Updated IAM policy for project [my-project].
bindings:
- members:
  - serviceAccount:spinnaker-service-account@my-project.iam.gserviceaccount.com
  role: roles/compute.instanceAdmin
- members:
  - serviceAccount:spinnaker-service-account@my-project.iam.gserviceaccount.com
  role: roles/compute.networkAdmin
- members:
  - serviceAccount:spinnaker-service-account@my-project.iam.gserviceaccount.com
  role: roles/compute.securityAdmin
- members:
  - serviceAccount:service-1234567890@compute-system.iam.gserviceaccount.com
  role: roles/compute.serviceAgent
- members:
  - serviceAccount:spinnaker-service-account@my-project.iam.gserviceaccount.com
  role: roles/compute.storageAdmin
- members:
  - serviceAccount:1234567890-compute@developer.gserviceaccount.com
  - serviceAccount:1234567890@cloudservices.gserviceaccount.com
  role: roles/editor
- members:
  - serviceAccount:spinnaker-service-account@my-project.iam.gserviceaccount.com
  role: roles/iam.serviceAccountActor
- members:
  - serviceAccount:spinnaker-service-account@my-project.iam.gserviceaccount.com
  role: roles/iam.serviceAccountUser
- members:
  - user:my@personal.email
  role: roles/owner
```
