### ISSUE TITLE
MPT V1 Template escape double quotes

### ISSUE THREAD

**Issue by NasAmin** [spinnaker/spinnaker#5064]
### Issue Summary:
We have started using Spin CLI in V2 Pipeline Templates. Our pipelines are mainly K8s deployments.
We deploy ingresses as deployManifest for a few of our apps. 

### Feature Area:
MPT v1

### Description:

The ingress controller seems to expect all values as strings but if we have something like this:

```
 apiVersion: extensions/v1beta1
      kind: Ingress
      metadata:
        annotations:
          certmanager.k8s.io/acme-challenge-type: http01
          certmanager.k8s.io/issuer: letsencrypt
          kubernetes.io/ingress.class: nginx          
          nginx.ingress.kubernetes.io/add-base-url: "true"      
          nginx.ingress.kubernetes.io/app-root: index.html
          nginx.ingress.kubernetes.io/base-url-scheme: https
          nginx.ingress.kubernetes.io/rewrite-target: /token
        name: "token-ingress"
      spec:
        rules:
          - host: "myhost.com"
            http:
              paths:
                - backend:
                    serviceName: "myHost-service"
                    servicePort: 80
                  path: /auth/token

```
Problem:
nginx.ingress.kubernetes.io/add-base-url: **"true"**
is rendered as
nginx.ingress.kubernetes.io/add-base-url: **true**

Note that quotes have been removed from the bolean however the ingress controller expects it to be a string which breaks our ingress from working correctly.

### Cloud Provider(s):
AWS EKS

I'll really appreciate some guidance please.

PS: I ditched MPT v2 because it doesn't allow inject entire manifests for deployManifest stages as variables unless someone can help with that?

Regards,

Nas
