### ISSUE TITLE
Unable to specify YAML/JSON text body in patch (manifest) stage [UI]

### ISSUE THREAD

**Issue by danigar** [spinnaker/spinnaker#5093]
### Issue Summary:
Cannot set the text body of `patch (manifest)` stage. UI text editor looks broken.

### Cloud Provider(s):
kubernetes V2

### Environment:
Spinnaker 1.16.1

### Feature Area:
Deck UI. Cloud driver?

### Description:
I'm trying to use `patch (manifest)` to modify custom kubernetes resources (istio virtual services). As strategic merge patch is not supported for custom resources I've used `JSON strategy patch`. Adding patch body in JSON format seems not to work, as the UI converts it automatically to yaml.

I've also used yaml format to specify the patch body, but the UI text editor seems broken:
- I can't enter almost anything in the editor because code gets duplicated, the lines of text disappear, new text get duplicated on multiple areas of the text-box.
- I can't copy-paste YAML code beacuse it is automatically modified (code duplication etc.) after saving and navigating between steps.

I've found a similar issue https://github.com/spinnaker/spinnaker/issues/3418 that is already closed.

### Steps to Reproduce:
1. Create a stage `Patch (manifest)`
2. Select `json` merge strategy
3. Try to add the JSON operations using a JSON format (it is automatically parsed to YAML)
4. Try to add JSON operations using YAML format (its almost impossible because the editor overwrites everything is added to the text-box).

### Additional Details:
This is the patch body i'm trying to add:

```
- op: replace
  path: /spec/http/0/route/0
  value:
    - destination:
      host: random-host
      subset: stable
    weight: 80
- op: add
  path: /spec/http/0/route/-
  value:
    - destination: 
      host: random-host
      subset: canary
    weight: 20
```
