### ISSUE TITLE
Linking to external logging system from Kubernetes job doesn't work

### ISSUE THREAD

**Issue by gnarea** [spinnaker/spinnaker#5099]
### Issue Summary:

[According to the documentation](https://www.spinnaker.io/guides/user/kubernetes-v2/run-job-manifest/#link-to-external-system), I should be able to get Deck to redirect me to my external logging system when I click on the logs for a job if that job has the `job.spinnaker.io/logs` annotation set to a URL. However, this doesn't work and Spinnaker continues to use the default behaviour.

### Cloud Provider(s):

GCP

### Environment:

Spinnaker 1.17. Spinnaker for GCP.

### Feature Area:

Deck

### Steps to Reproduce:

Create a job manifest with the `job.spinnaker.io/logs` annotation set to a URL and create a `Run job` stage to run it.

### Additional Details:

See the relevant portion of my job manifest:

<img width="1373" alt="Screenshot 2019-11-05 at 16 53 27" src="https://user-images.githubusercontent.com/369863/68229009-55e6d000-ffee-11e9-8e32-bfd302ee62bb.png">

And here's what I get if tried to get the logs from Spinnaker:

<img width="934" alt="Screenshot 2019-11-05 at 16 56 07" src="https://user-images.githubusercontent.com/369863/68229822-d65a0080-ffef-11e9-81eb-29f47306b0bc.png">

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by spinnakerbot** [comment]
This issue is tagged as 'to-be-closed' and hasn't been updated  in 45 days, so we are closing it. You can always reopen this issue if needed.

**Comment by aman-agrawal** [comment]
With below config, it is redirecting to mentioned link with Spinnaker 1.30.1
```
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    job.spinnaker.io/logs: 'https://www.opsmx.com/'
  name: sleep-job
spec:
  backoffLimit: 4
  template:
    metadata:
      name: sleep-pod
    spec:
      containers:
        - command:
            - /bin/sh
            - '-c'
            - 'sleep 10 && echo ''Hello, Kubernetes!'' && sleep 10 && echo ''aman-agrawal'''
          image: busybox
          name: sleep-container
      restartPolicy: Never
```
![image](https://github.com/spinnaker/spinnaker/assets/18665546/aa3aa9ef-e3ad-42e7-8e7f-c7c3c273a3b6)
