### ISSUE TITLE
Pipeline Templates rendering 'null' for expected Artifacts

### ISSUE THREAD

**Issue by geek876** [spinnaker/spinnaker#5117]
Hi,

I think the issue below is still happening. Even after setting the expected artifacts, they are not visible in the subsequent stages. (bake stage for me)

https://github.com/spinnaker/spinnaker/issues/2654

My Template is as below

```
schema: "1"
id: TemplateV1
metadata:
  name: Generic_Template
  description: Generic_Template
  owner: x@emai.com
  scopes: [global]
variables:
- name: env
  description: Environment
configuration:
  expectedArtifacts:
  - defaultArtifact:
      artifactAccount: DevOps_Virtual
      name: micro-service
      reference: DevOps_Virtual_Repo
      type: helm/chart
      version: 0.1.2
    displayName: HelmChart
    id: HelmChart
    matchArtifact:
      artifactAccount: DevOps_Virtual
      name: micro-service
      reference: DevOps_Virtual_Repo
      type: helm/chart
      version: 0.1.2
    useDefaultArtifact: true
    usePriorArtifact: false
  concurrentExecutions: {}
  triggers: []
  parameters: []
  notifications: []
  description: ""
stages:
- config:
    expectedArtifacts:
    - defaultArtifact:
        customKind: true
      displayName: baked-helm-chart
      id: some-id
      matchArtifact:
        name: baked-helm-chart
        type: embedded/base64
      useDefaultArtifact: false
      usePriorArtifact: false
    inputArtifacts:
    - account: DevOps_Virtual
      id: HelmChart
    namespace: default
    outputName: helm
    overrides: {}
    templateRenderer: HELM2
  id: bakeManifest1
  inheritanceControl: {}
  inject: {}
  name: Bake (Manifest)
  type: bakeManifest
partials: []

```

The rendered Stage is:

```
{
  "expectedArtifacts": [
    {
      "defaultArtifact": {
        "customKind": true
      },
      "displayName": "baked-helm-chart",
      "id": "some-id",
      "matchArtifact": {
        "name": "baked-helm-chart",
        "type": "embedded/base64"
      },
      "useDefaultArtifact": false,
      "usePriorArtifact": false
    }
  ],
  "id": "4add483d-c160-463b-a4d3-b6ed2fcc1c25",
  "inputArtifacts": [
    {
      "account": "DevOps_Virtual",
      "id": "HelmChart"
    }
  ],
  "name": "Bake (Manifest)",
  "namespace": "default",
  "outputName": "helm",
  "overrides": {},
  "templateRenderer": "HELM2",
  "type": "bakeManifest"
}```
