### ISSUE TITLE
front50 doesn't accept region passed to minio

### ISSUE THREAD

**Issue by bernadinm** [spinnaker/spinnaker#5124]
### Issue Summary:

When connecting front50 to Minio, we receive 400 errors where the Minio server doesn't accept the request that front50 is attempting to make via HTTP.

### Cloud Provider(s):

- AWS

### Environment:

- Kubernetes v2

### Description:

When passing in the proper s3 paramaterts and region to halconfig, hal deploys spinnaker and all its sub services to kubernetes as expected however when spinnaker's metadata service, Front50, attempts to communicate to Minio, it decides to use `us-east-1` as a region of choice when it was explicit within the configuration what region to choose:

https://gist.github.com/bernadinm/d7b12192e7ed00a219c44e45808c1e15#file-halconfig
```
  persistentStorage:
    persistentStoreType: s3
    azs: {}
    gcs: {}
    redis: {}
    s3:
      bucket: spinnaker
      rootFolder: front50
      region: us-west-2
      pathStyleAccess: true
      endpoint: http://spin-minio:9000
      accessKeyId: AKIZBHUJMRCSWFEXAMPLE
      secretAccessKey: hiabMI4jGnz2NVGIH5foL1J9ZqSDQ9NEXAMPLE
```  

#### Entire Logs
https://gist.github.com/bernadinm/d7b12192e7ed00a219c44e45808c1e15

### Steps to Reproduce:

1. Stand up Spinnaker and point to your own Minio configuration.
2. Use any other region than `us-east-1`
3. Observe the 400 errors printed here https://gist.github.com/bernadinm/d7b12192e7ed00a219c44e45808c1e15#file-front50-log

### Additional Details:

After enabling further debugging on minio and front50, I've observed that the failure was related to a region that front50 mistakenly used:

##### Expected Payload

```
    spin-minio [REQUEST s3.ListBuckets] 00:15:59.502
    spin-minio GET /
    spin-minio Host: spin-minio:9000
    spin-minio X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    spin-minio X-Amz-Date: 20191113T001559Z
    spin-minio Authorization: AWS4-HMAC-SHA256 Credential=AKIZBHUJMRCSWFEXAMPLE/20191113/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=4d61e01dc6c0a1d1cccb053db3d2509ac4a23d2cbc49a25e1e5d87f9e066249f
```

##### Observed Payload

```
    spin-minio [REQUEST s3.HeadBucket] 00:16:52.171
    spin-minio HEAD /spinnaker/
    spin-minio Host: spin-minio:9000
    spin-minio Connection: Keep-Alive
    spin-minio Content-Length: 0
    spin-minio Amz-Sdk-Retry: 0/0/500
    spin-minio Authorization: AWS4-HMAC-SHA256 Credential=AKIZBHUJMRCSWFEXAMPLE/20191113/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=265f6f9fd7e37919f4bce452fda64eabab8730403ba449d0ba4a3229f711b0de
```
