### ISSUE TITLE
Documentation: How to read SSL certificates from a mounted volume

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [spinnaker/spinnaker#5127]
### Issue Summary:
I struggled a bit with reading SSL certificates from a mounted volume. And found a kind of convoluted solution. I suggested it be documented for future users:

1. In halyard, disable SSL for both API and UI (we will re-enable them from somewhere else):

set apiSecurity.ssl.enabled and uiSecurity.ssl.enabled to false. If you set them to true it will force you to provide other parameters:
   ```
   hal config security api ssl disable
   hal config security ui ssl disable
   ```
2. For deck, provide the following service settings:
```
kubernetes:
  volumes:
    - id: the_name_of_the_secret_volume
      type: secret
      mountPath: the_mount_path
env:
  DECK_CERT: the_mount_path/certificate_file
  DECK_KEY: the_mount_path/key_file
  PASSPHRASE: the_passphrase
scheme: https
```
3. For gate, provide the following service settings:
```
kubernetes:
  volumes:
    - id: the_name_of_the_secret_volume
      type: secret
      mountPath: the_mount_path
env:
  JAVA_OPTS: "-Dserver.ssl.enabled=true -Dserver.ssl.key-store-type=your_type -Dserver.ssl.key-store=the_mount_path/keystore_name -Dserver.ssl.key-store-password=keystore_password -Dserver.ssl.key-alias=key_alias
scheme: https
```

The flow is similar for Deck and Halyard:
1. The first part mounts the secret containing the certificates into the service
2. The second part reads the secrets into the required environment variables
3. The third enforces the scheme of the service to be https (which was set to http because we disabled SSL in halyard).

The main difference between the two flows is that `Gate` expects a keystore, while `Deck` expects a pem-formatted certificate.

The main limitation of this approach is that the `keystore password` and the `passphrase` cannot be read from the mounted volumes, and thus must be provided in other ways.

### Feature Area:
Documentation
