### ISSUE TITLE
Helm Chart install fails w/ unusable ingress 

### ISSUE THREAD

**Issue by darkn3rd** [spinnaker/spinnaker#5128]
### Issue Summary:

The helm chart `stable/spinnaker` fails to install a functional ingress with spinnaker cluster.

### Cloud Provider(s):

* AWS Cloud

### Environment:

Private domains/cert/etc obfuscated. 

* `stable/external-dns` chart with values below:

  ```
  domainFilters: ["mycompany.com"]
  txtOwnerId: "externaldns"
  aws:
    zoneType: public
    region: ""
  image:
    registry: registry.opensource.zalan.do
    repository: teapot/external-dns
    tag: latest
  ```
* `stable/nginx-ingress` chart with values below:

  ```
  controller:
    publishService:
      enabled: true
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:177194259482:certificate/dd0dc4f0-2e34-487f-9d02-75b4b8333e6d"
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-west-2:XXXXXXXXXXXX:certificate/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
  ```
* EKS (created w/ `eksctl` - k8s 1.14) with `eksctl create cluster -f cluster.yaml` (yaml below)

  ```yaml
  apiVersion: eksctl.io/v1alpha5
  kind: ClusterConfig
  metadata:
    name: demo-cluster
    region: us-west-2
  nodeGroups:
    - name: demo-workers
      instanceType: t3.medium
      desiredCapacity: 4
      minSize: 1
      maxSize: 4
      iam:
        withAddonPolicies:
          externalDNS: true
  ```

### Feature Area:

* helm chart

### Description:

Installing Spinnaker through helm chart `stable/spinnaker` creates unusable ingress. 

### Steps to Reproduce:

1. create eks cluster  with tiller installed
1. install/configure `stable/external-dns` + `stable/nginx-ingress` charts
1. install `stable/spinnaker` chart with the values below:
   ```yaml
   ingress:
     enabled: true
       host: spinnaker.clearmeatal.io
       annotations:
         kubernetes.io/ingress.class: nginx
    ```

### Actual Results

The tiller logs show the following:

```
W1114 19:05:29.986255       6 controller.go:920] Service "default/spin-deck" does not have any active Endpoint.
```

Despite this failure, no exit code or error communicated.

### Additional Details:

Service Description: 

```bash
kubectl describe service/spin-deck
Name:                     spin-deck
Namespace:                default
Labels:                   app=spin
                          cluster=spin-deck
Annotations:              kubectl.kubernetes.io/last-applied-configuration:
                            {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"spin","cluster":"spin-deck"},"name":"spin-deck","namespa...
Selector:                 app=spin,cluster=spin-deck
Type:                     NodePort
IP:                       10.100.26.171
Port:                     <unset>  9000/TCP
TargetPort:               9000/TCP
NodePort:                 <unset>  30110/TCP
Endpoints:                192.168.86.72:9000
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

Ingress Description: 

```
kubectl describe ing spin-ingress-spinnaker-deck
Name:             spin-ingress-spinnaker-deck
Namespace:        default
Address:          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXX.us-west-2.elb.amazonaws.com.us-west-2.elb.amazonaws.com
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                      Path  Backends
  ----                      ----  --------
  spinnaker.mycompany.com
                            /   spin-deck:9000 (192.168.86.72:9000)
Annotations:
  kubernetes.io/ingress.class:  nginx
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  CREATE  25m   nginx-ingress-controller  Ingress default/spin-ingress-spinnaker-deck
  Normal  UPDATE  25m   nginx-ingress-controller  Ingress default/spin-ingress-spinnaker-deck
```
