### ISSUE TITLE
github/file artifact issue since 1.17

### ISSUE THREAD

**Issue by jantebeest** [spinnaker/spinnaker#5136]
### Issue Summary:
GitHub/file artifact is failing with `Artifact credentials 'xxx' cannot handle artifacts of type 'github/file'` since upgrade to 1.17.

### Cloud Provider(s):
Kubernetes

### Environment:
We're running spinnaker on Kubernetes with a GitHub artifact configured as follows:
```
artifacts:
    github:
      enabled: true
      accounts:
      - name: xxx
        token: yyy
```

### Feature Area:
github/file artifact

### Description:
This used to work fine, but since upgrading to 1.17 (tried both 1.17.0 and 1.17.1) this fails with the aforementioned error.
Downgrading to 1.16.5 gets rid of the error, but doesn't allow me to use the Kustomize bake stage.

### Steps to Reproduce:
Upgrade to 1.17, configure a github/file artifact and the error occurs when trying to use the Kubernetes V2 manifest/deploy stage.
