### ISSUE TITLE
Replace "mapping" for parameter names in custom job stages with just using the parameter name anywhere in the config

### ISSUE THREAD

**Issue by AbdulRahmanAlHamali** [spinnaker/spinnaker#5147]
### Issue Summary:
In custom job stages, when specifying parameters, we list the parameters as follows:
```yaml
parameters:
          - name: PHRASE
            label: Phrase to say
            description: Phrase to be echoed.
            mapping: manifest.spec.template.spec.containers[0].env[0].value
            defaultValue: "Hello world!"
```
specifying where the parameter will go exactly in the configuration. This restricts us to using the parameter only once in the configuration, and disallows us from using parameters as parts of strings. 

For example, we can't do something like:
```yaml
some_config: sometext-{%my_parameter%}
```
I suggest to provide an alternative to `mapping` that allows us to simply do a search-replace, where we search for strings that look like {%parameter_name%} and replace them with the parameter value.

### Feature Area:
Orca
