### ISSUE TITLE
kubernetes v2 provider: Empty entries get removed from Kubernetes manifest

### ISSUE THREAD

**Issue by justinrlee** [spinnaker/spinnaker#5151]
If you are deploying Kubernetes resources that have null entries, those get removed from the Kubernetes manifest.  In some situations, this is undesirable.

For example, if you have this in a Spinnaker deploy manifest stage:

```
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-route
spec:
  host: hello-world
  to:
    kind: Service
    name: hello-service
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
```

When you save, it'll be reduced to this:

```
piVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-route
spec:
  host: hello-world
  to:
    kind: Service
    name: hello-service
    weight: 100
  wildcardPolicy: None
status: {}
```

This is problematic in this specific situation because for some reason, the OpenShift API validator is expecting the spec.status.ingress field to be present (side note, this occurs with `kubectl` in the CLI, but not with `oc`).

I would argue that in the generic, items should not be removed unless they are explicitly null (or not removed at all, ideally).
