### ISSUE TITLE
Local Git Spinnaker: Clouddriver failing when cloud provider is AWS and storage is minio

### ISSUE THREAD

**Issue by kirangodishala** [spinnaker/spinnaker#5157]
### Issue Summary:
In a local git spinnaker installation, Clouddriver is failing when cloud provider is AWS and persistent storage is minio which is an s3-compatible storage.

### Cloud Provider(s):
AWS

### Environment:
Local git Spinnaker installation 

### Description:
Halyard, upon "hal deploy apply" is creating ~/.aws/credentials file with minio's access key id and secret access key instead of AWS accounts' access key id and secret access key. So clouddriver picksup these minio's credentials, tries to validate against AWS account and fails with the following error:  
```
com.amazonaws.services.ec2.model.AmazonEC2Exception: AWS was not able to validate the provided access credentials (Service: AmazonEC2; Status Code: 401; Error Code: AuthFailure; Request ID: 58ced878-
```

### Steps to Reproduce:
Add an AWS account and credentials and enable using [hal commands](https://www.spinnaker.io/reference/halyard/commands/#hal-config-provider-aws)

hal config under providers should look like the following:
```
  providers:
    aws:
      enabled: **true**
      accounts:
      - name: my-aws-account
        requiredGroupMembership: []
        providerVersion: V1
        permissions: {}
        accountId: ''
        regions: []
        assumeRole: role/spinnakerManaged
        lifecycleHooks: []
      bakeryDefaults:
        baseImages: []
      **accessKeyId**: xxxxxxxxxxxxxxxxxx
      **secretAccessKey**: xxxxxxxxxxxxxxxxxx
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
```
Add persistent storage as minio (minio should already be installed) using [hal command](https://www.spinnaker.io/reference/halyard/commands/#hal-config-storage-s3-edit).
hal config persistent storage section looks like the following:
```
  persistentStorage:
    persistentStoreType: s3
    azs: {}
    gcs: 
      rootFolder: front50
    redis: {}
    s3:
      bucket: spin-31c69bd2-0b38-4b37-8765-ddd0b94458d3
      rootFolder: front50
      region: us-west-2
      pathStyleAccess: false
      endpoint: http://127.0.0.1:9001
      **accessKeyId**: xxxxxxx
      **secretAccessKey**: xxxxxxxx
```

Run "hal deploy apply" and check clouddriver logs.
