### ISSUE TITLE
FR: Allow OSS approvers to auto-submit without review

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#5189]
### Issue Summary:
Mergify allows an oss-approver to add the `ready-to-merge` label that will auto submit a PR once all checks have passed. This is a really nice feature, because the approver doesn't have to wait around for the build to succeed in order to merge.

If the PR author is also a member of the oss-approvers list, they have the ability to merge anyway, but the current Mergify settings require an LGTM from someone else (as GH doesn't allow you to approve your own PR).  Adding these settings would make life easier for oss-approvers who author small, no-review-needed PRs:

```
  - name: Automatically merge PRs from maintainers on CI success and review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - "label=ready to merge"
      - "author=@oss-approvers"
    actions:
      merge:
        method: squash
        strict: smart
      label:
        add: ["auto merged"]
```
