### ISSUE TITLE
 Load Balancer-terminated SSL for saml without specifying the keystore

### ISSUE THREAD

**Issue by bernadinm** [spinnaker/spinnaker#5206]
### Issue Summary:

I am unable to get Spinnaker to allow you to use Load Balancer-terminated SSL for SAML.

### Cloud Provider(s):

```
AWS
```

### Environment:
```
k8s 1.15.2
```

### Feature Area:

* gate
* deck

### Description:
When attempting to use SAML I am not getting any 

```
$ hal config security authn saml edit --service-address-url https://example.net.
+ Get current deployment
  Success
+ Get authentication settings
  Success
+ Edit saml authentication settings
  Success
+ Successfully edited saml method.
```

```
hal config security authn saml enable
+ Get current deployment
  Success
- Edit saml authentication settings
  Failure
Problems in default.security.authn.saml:
! ERROR No keystore specified.
! ERROR No keystore password specified.
! ERROR No keystore alias specified.
! ERROR Keystore validation problem: null
- Failed to enable saml
```

The custom halyard config looks like this:

```
      saml:
        enabled: true
        metadataLocal: /home/spinnaker/.hal/metadata.xml
        issuerId: example
        serviceAddress: http://example:8084/
        userAttributeMapping:
          firstName: givenName
          lastName: sn
          roles: memberOf
          rolesDelimiter: ;
```

### Steps to Reproduce:

Create the halyard config with the config above and deploy. Cluster comes up but does not attempt to perform SAML auth.
