### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token '<'" at login page

### ISSUE THREAD

**Issue by nequid** [spinnaker/spinnaker#5262]
### Issue Summary:
When i try to connect spinnaker ui after install i got error on console "Uncaught SyntaxError: Unexpected token '<'" and login form is not loading.

### Cloud Provider(s):
DigitalOcean

### Environment:
This is my ingress file to connect ui
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spin-ingress
  namespace: spinnaker
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: spinnaker-api.abc.com
      http:
        paths:
          - backend:
              serviceName: spin-gate
              servicePort: 8084
    - host: spinnaker.abc.com
      http:
        paths:
          - backend:
              serviceName: spin-deck
              servicePort: 9000
```

This is my bash file prepared to install spinnaker on kubernetes
https://paste.ofcode.org/4jcCsSQyLUpjze2RFCLtFw

### Feature Area:
UI

### Additional Details:
Screenshot at login page with errors
https://prnt.sc/qe5kwn
