### ISSUE TITLE
Slow ECR trigger

### ISSUE THREAD

**Issue by rverma-jm** [spinnaker/spinnaker#5281]
### Issue Summary:
Hi all, we started using ecr with eks, but it seems spinnaker is taking too much time to pickup a new image pushed. We hardly had 50 images in ecr and its usually take 10-30 minutes. I tried with cache interval of 10 and even then it took same time. What am I missing? How can we optimize this behaviour.

### Cloud Provider(s):
AWS

### Environment:
EKS
Spinnaker running on m5xlarge
```
custom-sizing: 
           spin-clouddriver:
              requests:
                memory: 1.5Gi
                cpu: 1
            spin-deck:
              requests:
                memory: 64Mi
                cpu: 50m
            spin-echo:
              requests:
                memory: 1Gi
                cpu: 100m
            spin-front50:
              requests:
                memory: 650Mi
                cpu: 200m
            spin-gate:
              requests:
                memory: 650Mi
                cpu: 100m
            spin-orca:
              requests:
                memory: 1Gi
                cpu: 300m
            spin-rosco:
              requests:
                memory: 650Mi
                cpu: 100m
            spin-igor:
              requests:
                memory: 1Gi
                cpu: 400m
```

### Feature Area:
Igor
Clouddriver
