### ISSUE TITLE
[FEATURE]: Dynamic editing/creation of kustomization file

### ISSUE THREAD

**Issue by colincgn** [spinnaker/spinnaker#5322]
### Issue Summary:
This is a feature request to support adding additional dynamic information to kustomization files, similarly as you would override values in the HELM template engine.

### Feature Area:
Baking Kubernetes manifests using Kustomize.

### Description:
kustomize does not support env variables, which is [described here](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/eschewedFeatures.md#build-time-side-effects-from-cli-args-or-env-variables).

There is a [general discussion](https://github.com/kubernetes-sigs/kustomize/issues/388) within the kustomize project on how to achieve this and what are some of the use cases, like image tags.

In particular, my current use case is I have docker-registry artifacts that trigger my pipeline as well as allowing developers to deploy any versions on an application on demand, and using the tag selected `${trigger["tag"]}` to label kubernetes resources appropriately.

In kustomization it would look something like this (which does not, and will not work)

Need to set this somehow `APP_VERSION=${trigger["tag"]}`

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - git@github.com:colincgn/my-repo.git/kustomize/base?ref=master

commonLabels:
  version: APP_VERSION
  
images:
  - name: base-application-image
    newName: hello-world
    newTag: APP_VERSION
```

**Comment by bee-keeper** [comment]
For what it's worth, I'm going to outline my use case for this.

I'm submitting a simple job manifest via CI and need to dynamically apply 4 fields.  This is the kind of thing that is easily done with Helm (using --set) but Helm doesn't support doing this with a single job.  It feels the only way I could make this work with kustomize is creating a temp kustomize file but this seems absurd.  

I understand it's purely for philosophical reasons that kustomize doesn't support build time args ("kustomize supports the best practice of storing one's entire configuration in a version control system").  However, in my case I'm dealing with dynamically created one off jobs.  There is no reason for them to be in VCS at all. 

This incredibly common use case should not be so convoluted.

**Comment by alex-berger** [comment]
I have similar use cases, nearly every other day.

During deployment we (dynamically) create AWS resources (e.g. using Pulumi, Terraform or AWS CDK) and then need to inject some resource identifiers (ARN) into Kubernetes YAML files. One specific example that I had today is:

- We create an IAM Role in AWS using Pulumi
- I have to create a k8s service account which uses that IAM role and for that reason I have to inject it's ARN into the corresponding k8s resource file.

Note, how the exact value of the information that needs to be injected into the YAML resources is not known ahead of time and therefore cannot be part of version control anyway.

While I understand and support the intentions of Kustomize's philosophy that everything should be under version control, I think it is a little bit to "fundamentalistic" (or idealistic) and simply ignores reality. I would really like to see Kustomize adding such a feature, which would make it much simpler to solve those corner cases and reduce the need for other tools like `sed` or templating tools.

**Comment by colindev** [comment]
I need this too
In other use case, i have many pv resources all use the same nfs server ip
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: $(NFS_STORAGE_CAPACITY)
  nfs:
    path: $(NFS_SHARED_PATH)
    server: $(NFS_SERVER)
``` 

If i use patch file, i need repeat it by myself.... 
It's not make sense
