### ISSUE TITLE
auth.permissions.source.application.prefix does not apply for CREATE permissions

### ISSUE THREAD

**Issue by cross-wind** [spinnaker/spinnaker#5334]
### Issue Summary:
The create permissions for the prefix feature in 1.17.* is failing.

I have configured fiat to grant read, write and create permissions to app bar* to a fake group. The read and write permissions are functioning as they should -- I cannot see or edit bar* applications (i.e. bar11, etc.), however I can still create an application named "bar11" or such. Once created I can no longer see them (due to lacking read permissions), however the application object is created and is stored in S3 bucket via front 50.

My fiat-local.yml is:

```auth:
  permissions:
    provider:
      application: aggregate
    source:
      application:
        front50:
          enabled: true
        prefix:
          enabled: true
          prefixes:
          - prefix: "bar*"
            permissions:
              CREATE:
              - "fake@fake.com"
              WRITE:
              - "fake@fake.com"
              READ:
              - "fake@fake.com"

**Comment by plumpy** [comment]
@AbdulRahmanAlHamali

**Comment by cross-wind** [comment]
I have upgraded test cluster to 1.18.0, and the behaviour persists there as well.

**Comment by AbdulRahmanAlHamali** [comment]
Hmm it's possible that it's some conflict between the front50 permissions and the prefix permissions. Can you try disabling `front50`?

**Comment by cross-wind** [comment]
Thank you for looking at this.
I have made two adjustments to fiat-local.yml, and tested both of them out.

1) I explicitly disabled fron50 auth, while leaving rest untouched. The resultant behaviour was same as above -- the prefix permissions for READ were acting as they should, however CREATE was not working. In other words I could create application named "bar50", however I could not access it. When I tried creating application named "bar50" again I got the following error, which indicated that READ permissions are enforced:
<img width="576" alt="READ auth" src="https://user-images.githubusercontent.com/26663254/72937846-bc8ea680-3d1e-11ea-919e-45b4bcff1106.png">.
The config looked as such:

```yaml
auth:
  permissions:
    provider:
      application: aggregate
    source:
      application:
        front50:
          enabled: false
        prefix:
          enabled: true
          prefixes:
          - prefix: "bar*"
            permissions:
              CREATE:
              - "fake@fake.com"
              WRITE:
              - "fake@fake.com"
              READ:
              - "fake@fake.com"
```  
2) I removed any mention of front50, as well as `application: aggregate`. As a result no permissions specified in prefix were enforced. The config looked as such:
```yaml
auth:
  permissions:
    source:
      application:
        prefix:
          enabled: true
          prefixes:
          - prefix: "bar*"
            permissions:
              CREATE:
              - "fake@fake.com"
              WRITE:
              - "fake@fake.com"
              READ:
              - "fake@fake.com"
```

**Comment by AbdulRahmanAlHamali** [comment]
ohh did you set `restrictApplicationCreation` to true?

**Comment by cross-wind** [comment]
Sorry for lated reply, and thank you for getting back to me!

The behaviour persists with the addition of this setting. Current config looks as such:
`fiat:
  restrictApplicationCreation: true
auth:
  permissions:
    provider:
      application: aggregate
    source:
      application:
        front50:
          enabled: true
        prefix:
          enabled: true
          prefixes:
          - prefix: "bar*"
            permissions:
              CREATE:
              - "fake@fake.com"
              WRITE:
              - "fake@fake.com"
              READ:
              - "fake@fake.com"`

**Comment by AbdulRahmanAlHamali** [comment]
This is the fiat configuration that I use in my installation:

```
auth:
  permissions:
    provider:
      application: aggregate
    source:
      application:
        front50:
          # do not read permissions from inside the applications
          enabled: false
        prefix:
          enabled: true
          prefixes:
            - prefix: '*'
              permissions:
                READ:
                  - "developers"
                  - "qa"
                EXECUTE:
                  - "developers"
                  - "qa"
                # infra team will temporarily have write and create privileges on applications
                WRITE:
                  - "infrastructure"
                CREATE:
                  - "infrastructure"
fiat:
  restrictApplicationCreation: true
  admin:
    roles:
      - "admin"
      - "admin-service-users"
```
Notice that I'm using group authorization here. I see you are referring to specific users/emails. Not sure if this is the same thing
