### ISSUE TITLE
[Clouddriver]:Kubernetes accounts are not loading dynamically in Spinnaker

### ISSUE THREAD

**Issue by aniketksh** [spinnaker/spinnaker#5354]
### Issue Summary:
Following the documentation [External Account Configuration](https://www.spinnaker.io/setup/configuration/), I have configured the Spinnaker to pick the Kubernetes account added into Git repo. But when clouddriver is trying to load the Kubernetes account, it is giving me the following error message and failing to get up and running

Error Message:
```
2020-01-24 10:44:45.406 WARN 1 — [ main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization – cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name ‘configurationRefreshListener’ 
defined in URL [jar:file:/opt/clouddriver/lib/clouddriver-web.jar!/com/netflix/spinnaker/clouddriver/listeners/ConfigurationRefreshListener.class]: Unsatisfied dependency expressed through constructor parameter 0; 
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name ‘kubernetesV1ProviderSynchronizable’: Invocation of init method failed; 
nested exception is com.netflix.spinnaker.kork.configserver.ConfigFileLoadingException: File “/home/aniket/.kube/config” not found or is not readable
``` 

### Cloud Provider(s):
I am using the AKS cluster to deploy Spinnaker. 
Kubernetes Version: v1.12.5

### Environment:
Hal Version: 1.29.0-20200106172816
Spinnaker version: 1.18.0 
Distributed Halyard

### Feature Area:
Dynamic account for k8s related to clouddriver

### Description:
I am trying to dynamically configure k8s accounts using a given document in Spinnaker 1.18. As per the documentation, I have places the `spinnakerconfig.yml` file at `$HOME/.hal/default/profile` location. 
I have a Git Private repo, in which file names `clouddriver-local.yml` is placed at root level, This file content exact 2 Kubernetes account. 
After using comment `hal deploy apply` clouddriver is trying to pick the Kubernetes account configuration from Git repo, but getting Error mentioned above.
```
File “/home/aniket/.kube/config” not found or is not readable
```
With this issue, Spinnaker is not showing the account which has been added into Git repo. 

###### spinnakerconfig.yml
```
spring:
  profiles:
    include: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aniketksh167/spinnaker-external-config.git
          username: xxxx
          password: xxxx
```
###### clouddriver-local.yml
```
kubernetes:
  enabled: true
  accounts:
  - name: aniket-playground
    requiredGroupMembership: []
    providerVersion: V1
    permissions: {}
    dockerRegistries:
    - accountName: spin-acr
      namespaces: []
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces: []
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /home/aniket/.kube/config
    oAuthScopes: []
    onlySpinnakerManaged: false
  - name: aniket-playground-1
    requiredGroupMembership: []
    providerVersion: V1
    permissions: {}
    dockerRegistries:
    - accountName: spin-acr
      namespaces: []
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces: []
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /home/aniket/.kube/config
    oAuthScopes: []
    onlySpinnakerManaged: false
  primaryAccount: sre-am-playground
```

### Steps to Reproduce:

Follow the enclosed document.
Expected: K8s accounts should be picked dynamically.
Actual: None of the proposed k8s accounts appear in clouddriver
