### ISSUE TITLE
Front50 using both SQL and GCS backend

### ISSUE THREAD

**Issue by eboumendil** [spinnaker/spinnaker#5358]
### Issue Summary:
I have an issue with setting up Front50 with SQL as backend where front50 fails to start with both SQL and GCS backend configured at the same time
### Cloud Provider(s):
Kubernetes, GKE

### Environment:
GKE

### Feature Area:
Front50

### Description:
I have an issue with setting up Front50 with SQL as backend where front50 fails to start with both SQL and GCS backend configured at the same time:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 0 of method applicationDAO in com.netflix.spinnaker.front50.config.CommonStorageServiceDAOConfig required a single bean, but 2 were found:
	- defaultGoogleCloudStorageService: defined by method 'defaultGoogleCloudStorageService' in class path resource [com/netflix/spinnaker/front50/config/GcsConfig.class]
	- sqlStorageService: defined by method 'sqlStorageService' in class path resource [com/netflix/spinnaker/config/SqlConfiguration.class]
Action:
Consider marking one of the beans as @Primary, updating the consumer to accept multiple beans, or using @Qualifier to identify the bean that should be consumed
```

### Steps to Reproduce:
Run Front50 using GCS backend
Add SQL support to Front50

**Comment by eboumendil** [comment]
More info on Slack: https://spinnakerteam.slack.com/archives/C091CCWRJ/p1580164242095700

**Comment by aadir7** [comment]
What was the solution? i am not able to access the slack link.
I am facing similar issue with sql and AWS.

**Comment by eboumendil** [comment]
Here is what worked for me:
```
spinnaker:
  migration:
    enabled: false # Turn to true the first time to run the migration between GCS-->SQL
    primaryClass: com.netflix.spinnaker.front50.model.SqlStorageService
    previousClass: com.netflix.spinnaker.front50.model.GcsStorageService
    compositeStorageService:
      enabled: true
      reads:
        primary: true
        previous: false
sql:
  enabled: true
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:mysql://{{ .Values.halServices.front50.databaseHost }}:3306/front50
      user: {{ .Values.halServices.front50.databaseUser }}
      password: {{ .Values.halServices.front50.databasePassword | quote }}
  migration:
    jdbcUrl: jdbc:mysql://{{ .Values.halServices.front50.databaseHost }}:3306/front50
    user: {{ .Values.halServices.front50.databaseUser }}
    password: {{ .Values.halServices.front50.databasePassword | quote }}
  default:
    jdbcUrl: jdbc:mysql://{{ .Values.halServices.front50.databaseHost }}:3306/front50
    user: front50-db-user
    password: {{ .Values.halServices.front50.databasePassword | quote }}
```
