### ISSUE TITLE
spin oauth2 github provider not showing access token

### ISSUE THREAD

**Issue by erickardus** [spinnaker/spinnaker#5367]
### Issue Summary:
unable to authenticate with Spinnaker using github oauth2. After executing spin command (e.g spin application list) I get a URL to copy to the browser, but the browser authenticates and immediately redirects to the Spinnaker UI, I never get a chance to get the access token (even inspecting browser developer tools)

### Cloud Provider(s):
AWS, Spinnaker runs inside an EKS cluster

### Environment:
Prod

### Feature Area:
spin authentication using github oauth2 provider

### Description:
We have Spinnaker running inside AWS EKS. 
Installed via stable/spinnaker helm chart (spinnaker-1.23.0, app=1.16.2 )
TLS is being terminated at an LB (AWS ALB)
Authentication and authorization is enabled using Oauth2, github as provider.
Spinnaker authentication and authorization work well using the UI.
The problem is using spin, when authenticating with Spinnaker via the same github oauth provider.

### Steps to Reproduce:

Execute spin (any command):
```
$ spin application list
Navigate to https://github.com/login/oauth/authorize?access_type=offline&client_id=e461baaaaaca161bbb1&code_challenge=HFJaaaaaaaaaaZf1AoE5c61vQXYxSgw4uJeifeug&code_challenge_method=S256&prompt=consent&redirect_uri=http%3A%2F%2Flocalhost%3A8085&response_type=code&scope=profile&state=state-token and authenticate
Paste authorization code:
```

Then copy the URL in the browser. Since I'm already logged-in in Github it immediately redirects me to Spinnaker UI (already logged in). I would expect to see a blank screen with the access token (as it happens with Google Oauth provider), but this isn't the case with Github

### Additional Details:
This is $HOME/.spin/config

```
gate:
  endpoint: https://gate.mycompanydomain.com
auth:
  enabled: true
  oauth2:
    tokenUrl: https://github.com/login/oauth/access_token
    authUrl: https://github.com/login/oauth/authorize
    clientId: xxxxxxxxxxxxx
    clientSecret: 11c9xxxxxxxxxxxxx226a1
    scopes:
    - profile
```
---
