### ISSUE TITLE
Facing intermittent issues while accessing the cluster, deployment, pods, LoadBalancer details for Kubernetes v2 Provider

### ISSUE THREAD

**Issue by thekalpesh7** [spinnaker/spinnaker#5368]
### Issue Summary:

After migrating to the Kubernetes v2 Provider we are facing intermittent issues while accessing the cluster, deployment, pods, LoadBalancer details.

### Cloud Provider(s):

- Kubernetes (Azure Kubernetes Service) v1.14.8

### Environment:

I am running Spinnaker using AKS cluster with v2 Provider to deploy the Docker image on the AKS clusters

### Feature Area:

- UI
- API
- Cloud-driver

### Description:

We have deployed Spinnaker on the Kubernetes cluster. The Kubernetes cluster on which the Spinnaker is deployed is also configured in Kubernetes v2 Provider. Along with this, there are around 25 Kubernetes Accounts that are configured in the Spinnaker and around 15 of them have provider version v2.

After migrating to the Kubernetes v2 Provider we are facing intermittent issues while displaying the contents under LoadBalancer as well as Cluster Tab:

1. Cluster/Load Balancer Content block doesn't load.
2. Cluster/Load Balancer Content block loads but the data shown contains a very older image tag.
3. Cluster Content block loads but unable to fetch pod details.
4. This issue is not only while displaying the accessing the contents from Spin UI but also with the spin-gate APIs.

I have started facing this issue recently after I started using the RBAC enabled KubeConfig file of AKS and Kubernetes v2 Provider. Earlier I used the Admin KubeConfig file to configure the Kubernetes account in the Spinnaker.

To resolve this I have configure the Spinnaker HA for cloud-driver and echo but it also did not resolve the issue for us.

Please let me know if you need more details.

### Steps to Reproduce:

- **Spinnaker Version:** 1.16.6
- **Kubernetes (Azure Kubernetes Service) Version:** 1.14.8

Find below the sample .hal/config file we are using. 

```
---
- name: default
  version: 1.16.6
  providers:
    dockerRegistry:
      enabled: true
      accounts:
        - name: registry-name
          requiredGroupMembership: []
          providerVersion: V1
          permissions: {}
          address: ACR_URL
          username: ACR_USER
          password: ACR_PASS
          email: email@domain.com
          cacheIntervalSeconds: 30
          clientTimeoutMillis: 60000
          cacheThreads: 1
          paginateSize: 100
          sortTagsByDate: false
          trackDigests: false
          insecureRegistry: false
          repositories: []
    kubernetes:
      enabled: true
      accounts:
        - name: kubernetes-account-v2
          requiredGroupMembership: []
          providerVersion: V2
          permissions: {}
          dockerRegistries: []
          context: AKS-CONTEXT
          configureImagePullSecrets: true
          cacheThreads: 1
          namespaces: []
          omitNamespaces: []
          kinds: []
          omitKinds: []
          customResources: []
          cachingPolicies: []
          kubeconfigFile: /.kube/config
          liveManifestCalls: true
          oAuthScopes: []
          onlySpinnakerManaged: false
        - name: kubernetes-account-v1
          requiredGroupMembership: []
          providerVersion: V1
          permissions: {}
          dockerRegistries: []
          configureImagePullSecrets: true
          cacheThreads: 1
          namespaces: []
          omitNamespaces: []
          kinds: []
          omitKinds: []
          customResources: []
          cachingPolicies: []
          kubeconfigFile: /home/.kube/config2
          oAuthScopes: []
          onlySpinnakerManaged: false
      primaryAccount: kubernetes-account-v2
    oracle:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: oci.json
        baseImages: []
    cloudfoundry:
      enabled: false
      accounts: []
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: kubernetes-account-v2
    imageVariant: SLIM
    updateVersions: true
```

### Additional Details:

Apart from the following, there are no error logs or as such in the cloud-driver pods:

[clouddriver-log.txt](https://github.com/spinnaker/spinnaker/files/4133378/clouddriver-log.txt)
