### ISSUE TITLE
First-class injection does not work when using a manifest artifact for stage Deploy (Manifest)

### ISSUE THREAD

**Issue by jacogreyling** [spinnaker/spinnaker#5416]
### Issue Summary:

If the Deploy (Manifest) stage use an Artifact (and not Text) for the manifest source, Spinnaker doesn't match the field’s referenced type and value with an incoming artifact’s type. 

### Cloud Provider(s):

Kubernetes

### Environment:

Kubernetes 1.13.9
Spinnaker 1.13.2
Clouddriver 4.5.1

### Feature Area:

Artifacts In Kubernetes (Manifest Based)

### Description:

When we use the Text manifest, the system will successfully replace the configmap from a previous Deploy (ConfigMap) stage. As per the documentation. However when the manifest is loaded from an Artifact, it's not done. First-class ways of injecting them into your manifests are broken in this particular scenario. Pipeline expressions are working but not the 'first-class' injection into the manifest.

### Steps to Reproduce:

1. Create stage to deploy a manifest (configmap):

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-api-configmap
data:
  MY_ENVIRONMENT: "test"
```

2. Create stage to deploy a manifest (replicaset):
NOTE: this must come from a 'Expected Artifact' of type 'bitbucket/file'.
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-api
  annotations:
    moniker.spinnaker.io/application: example-api
    moniker.spinnaker.io/cluster: replicaSet example-api
    strategy.spinnaker.io/max-version-history: '2'
  labels:
    app.kubernetes.io/name: example-api
    app.kubernetes.io/managed-by: spinnaker
  namespace: '${parameters["environment"]}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: example-api
  template:
    metadata:
      annotations:
        moniker.spinnaker.io/application: example-api
        moniker.spinnaker.io/cluster: replicaSet example-api
      labels:
        app.kubernetes.io/name: example-api
        app.kubernetes.io/managed-by: spinnaker
    spec:
      containers:
      - name: example-api
        image: '<image>:${trigger["buildNumber"]}'
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: example-api-configmap
```

### Additional Details:

The manifest artifact definition:

```
    {
      "defaultArtifact": {
        "id": "<id>",
        "reference": "http://url/path/to/manifests/example-api.yaml",
        "type": "bitbucket/file"
      },
      "displayName": "example-api.yaml",
      "id": "<id>",
      "matchArtifact": {
        "id": "<id>",
        "name": "manifests/example-api.yaml",
        "type": "bitbucket/file"
      },
      "useDefaultArtifact": true,
      "usePriorArtifact": false
    }
```

---
