### ISSUE TITLE
Orca: Redis to SQL Migration not working

### ISSUE THREAD

**Issue by NicoXcc** [spinnaker/spinnaker#5509]
### Issue Summary:
We are using Spinnaker 1.11.3 on GCP K8s cluster. 
We wanted to use MySQL instead of Redis for Orca pods. 
Our MySQL is a managed GCP instance with private IP. 

### Cloud Provider(s):
GCP

### Environment:
Spinnaker 1.11.3 Or 1.18.1

### Description:
We are making the following changes on top of vanilla Spinnaker installation.
Following links may be useful https://www.spinnaker.io/guides/operator/orca-redis-to-sql/#enable-dualexecutionrepository

### Steps to Reproduce:
Update `orca-local.yml` as 

```
tasks:
  daysOfExecutionHistory: 180     

sql:
  enabled: true
  connectionPool:
    jdbcUrl: jdbc:mysql://<SOME_IP>:3306/orca
    user: orca_service
    password: <Pass-1>
    connectionTimeout: 5000
    maxLifetime: 30000
    # MariaDB-specific:
    maxPoolSize: 50
  migration:
    jdbcUrl: jdbc:mysql://<SOME_IP>:3306/orca
    user: orca_migrate
    password: <Pass-1>

monitor:
  activeExecutions:
    redis: false

executionRepository:
  dual:
    enabled: true
    primaryClass: com.netflix.spinnaker.orca.sql.telemetry.SqlInstrumentedExecutionRepository
    previousClass: com.netflix.spinnaker.orca.telemetry.RedisInstrumentedExecutionRepository
  sql:
    enabled: true
  redis:
    enabled: true

spring:
  profiles: sqlmigration

pollers:
  orchestrationMigrator:
    enabled: true
    intervalMs: 1800000
  pipelineMigrator:
    enabled: true
    intervalMs: 1800000  
  oldPipelineCleanup:
    enabled: true                  
    intervalMs: 86400000            

    thresholdDays: 30              
    minimumPipelineExecutions: 20   

queue:
  redis:
    enabled: false

keiko:
  queue:
    enabled: false

```

### Additional Details:
After adding the orca-local.yml with configurations and redeploying Spinnaker through halyard we can see all pods are coming up properly with no errors. There are no error logs as well in pods. MySQL instance logs also showing no errors. Spinnaker is working as expected. 
Now if we want to see that any table gets populated with migration data we do the following: 
Login to  MySQL instance and use queries..

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| orca               |
| performance_schema |
| sys                |
+--------------------+
5 rows in set (0.01 sec)

mysql> use orca;
Database changed
mysql> show tables;
Empty set (0.00 sec)

```
We feel the migration will populate tables in orca database. This is not working at all.
