### ISSUE TITLE
Spinnaker forces users to re-login multiple times a day (maxAuthenticationAge has no impact anymore)

### ISSUE THREAD

**Issue by iniinikoski** [spinnaker/spinnaker#5539]
### Issue Summary:

Even though maxAuthenticationAge is set for multiple days, Spinnaker forces users to re-login multiple times a day.

This setting was working for some months when it was fixed last summer in https://github.com/spinnaker/gate/pull/861 - but looks like something happened some months ago which broke this.

Unfortunately, I'm not able to debug this much... Just wanted to address this here as there are multiple people with the same issue.

And: the session timeout in provider end is already set to multiple days - so this really looks like a Spinnaker issue.

### Cloud Provider(s):

N/A

### Environment:

Spinnaker 1.18.4 running on GKE. Also was broken in 1.17.X ...

### Feature Area:

Gate / authentication

### Description:

With settin maxAuthenticationAge in gate-local, we should be able to keep users logged in longer.

### Steps to Reproduce:

-

### Additional Details:

The full gate-local here:

```
halyard@halyard:~/.hal/default/profiles$ less gate-local.yml
redis:
  configuration:
    secure: true
default:
#  apiPort: 8084
  apiPort: 8443
  legacyServerPort: 8085
# Setting the SAML login interval to 3 days...
saml:
  maxAuthenticationAge: 259200
#logging:
#  level:
```

---
