### ISSUE TITLE
LDAP(AD) users don't get any roles

### ISSUE THREAD

**Issue by razvan-ig** [spinnaker/spinnaker#5576]
### Issue Summary:
Testing Spinnaker release 1.19.0 with Hal 1.32.0, trying to enable RBAC using LDAP auth and prefixes as per https://www.spinnaker.io/community/releases/versions/1-17-6-changelog#more-flexible-authorization-model, any prefix set blocks all the users.

### Cloud Provider(s):
Kubernetes v2

### Environment:
EKS

### Feature Area:
FIAT

### Description:
LDAP auth does work, although the `--group-search-base` parameter seems ignored and any valid user can log on, regardless of group membership.

### Steps to Reproduce:
Deploy Spinnaker using https://github.com/helm/charts/tree/master/stable/spinnaker
Config done with
```
        $HAL_COMMAND config security authn ldap edit --url "${ ldap_url }" --manager-dn "${ ldap_user }" --manager-password "${ ldap_password }" \
          --user-search-filter "(&(objectClass=user)(sAMAccountName={0}))" --group-search-base "(OU=Groups,OU=Users)"
        $HAL_COMMAND config security authz ldap edit --url "${ ldap_url }" --manager-dn "${ ldap_user }" --manager-password "${ ldap_password }" \
          --user-search-filter "(&(objectClass=user)(sAMAccountName={0}))" --group-search-base "(OU=Groups,OU=Users)" \
          --group-search-filter "(&(objectClass=group)(member={1}))" --group-role-attributes cn
```
The "Groups,Users" bit is correct, and works with eg Jenkins
Also tried "member={0}"
LDAP uses show up in Fiat and in the S3 bucket, with no roles are assigned and access only to apps that don't have any restrictions set
```
$ curl $FIAT/authorize/ldapuser
{
  "name" : "ldapuser",
  "accounts" : [ {
    "name" : "default",
    "authorizations" : [ "READ", "WRITE", "EXECUTE", "CREATE" ]
  } ],
  "applications" : [ {
    "name" : "AAA",
    "authorizations" : [ "READ", "WRITE", "EXECUTE", "CREATE" ]
  } ],
  "serviceAccounts" : [ ],
  "roles" : [ ],
  "buildServices" : [ ],
  "admin" : false,
  "legacyFallback" : false,
  "allowAccessToUnknownApplications" : false
}
```
Checking the apps,
```
bash-3.2$ for a in $(aws s3 ls s3://spinnaker/front50/applications/ | grep PRE | awk '{print $2}') ; do aws s3 cp s3://spinnaker/front50/applications/${a}application-permission.json - | jq -r '.name + ": " + .permissions.READ[]'; done
jq: error (at <stdin>:0): Cannot iterate over null (null) <-- this is app aaa
bbb: admins
```
```
$ curl $FRONT50/serviceAccounts
[{"name":"ldapuser","lastModified":1584350046000,"lastModifiedBy":"anonymous","memberOf":["admins"]}]
```
Setting a prefix with
```
  additionalProfileConfigMaps:
    create: true
    data:
      fiat-local.yml: |
        fiat.restrictApplicationCreation: true
        admin.roles:
           - admins
        auth.permissions.provider.application: aggregate
        auth.permissions.source.application.prefix:
          enabled: true
          prefixes:
            - prefix: "*"
              permissions:
                CREATE:
                  - "admins"
                READ:
                  - "admins"
                  - "everybody"
                WRITE:
                  - "admins"
                EXECUTE:
                  - "admins"
```
Now nobody can create or read any apps, including those that should be "admins"
