### ISSUE TITLE
Deploy red/black failed - No reason provided - with evidence

### ISSUE THREAD

**Issue by dpolicastro** [spinnaker/spinnaker#5580]
### Issue Summary:
After triggering a pipeline to deploy the application for the first time using Spinnaker, I enabled the `Rollout Strategy Options` with a red/black strategy, then triggered a new deploy that failed. The Exception was on `Deploy (Manifest)` stage with `No reason provided`. Looking the Logs the issue happens during the `disableManifest` step: 
```
"Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n"
```

### Cloud Provider(s):
AWS/K8s

### Environment:
Spinnaker 1.19.0

### Feature Area:
Orca / Clouddriver ?

### Steps to Reproduce:
- Trigger the pipeline to deploy the application for the first time
- Enable Rollout Strategy and select the service
- Trigger the pipeline again

### Additional Details:
K8s Manifest (Generated by `helm template`): 
```
---
# Source: nodeapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: nodeapp
  labels:
    app: nodeapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort:
  selector:
    app: nodeapp
  sessionAffinity: None
  type: ClusterIP
---
# Source: nodeapp/templates/deployment.yaml
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nodeapp
  namespace: nodeapp
  annotations:
    version: "1"
    traffic.spinnaker.io/load-balancers: '["service nodeapp"]'
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
      annotations:
        timestamp: ""
        version: "1"
    spec:
      containers:
        - name: nodeapp
          image: dpolicastro/node-http-server:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          env:
          - name: APP_NAME
            value: nodeapp
          - name: APP_PORT
            value: "80"
          - name: APP_HOST
            value: "0.0.0.0"
          - name: APP_VERSION
            value: "1"
          - name: TIME_BEFORE_START
            value: "5000"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi

```
JSON for the first deploy (without traffic management enabled):
Contains two artifacts:
- Helm Chart from Chart Museum
- Values file stored on S3
Contains one parameter:
- image_tag: Not relevant
```
{
    "appConfig": {},
    "expectedArtifacts": [
        {
            "defaultArtifact": {
                "artifactAccount": "helm",
                "id": "26045f06-476e-45e5-837e-b66833a80309",
                "reference": "s3://S3_PATH",
                "type": "s3/object"
            },
            "displayName": "values file",
            "id": "1c0f515b-4e4d-440c-8340-d8428ce7e200",
            "matchArtifact": {
                "artifactAccount": "helm",
                "id": "4e94730e-8a01-4fdc-a342-2b333b2758ce",
                "name": "s3://S3_PATH",
                "type": "s3/object"
            },
            "useDefaultArtifact": true,
            "usePriorArtifact": false
        },
        {
            "defaultArtifact": {
                "artifactAccount": "chart-museum",
                "id": "d4e2d5fb-7e85-4b08-b722-88206988de79",
                "reference": "http://MUSEUM",
                "type": "http/file"
            },
            "displayName": "helm-chart",
            "id": "24dbe4bd-87f2-49a6-8ee2-68af876de859",
            "matchArtifact": {
                "artifactAccount": "chart-museum",
                "id": "aaf65045-7a3d-449e-ad3d-151193c8f082",
                "reference": "http://MUSEUM",
                "type": "http/file"
            },
            "useDefaultArtifact": true,
            "usePriorArtifact": false
        }
    ],
    "keepWaitingPipelines": false,
    "lastModifiedBy": "anonymous",
    "limitConcurrent": true,
    "parameterConfig": [
        {
            "default": "",
            "description": "The image tag ",
            "hasOptions": false,
            "label": "Image Tag",
            "name": "image_tag",
            "options": [
                {
                    "value": ""
                }
            ],
            "pinned": true,
            "required": true
        }
    ],
    "spelEvaluator": "v4",
    "stages": [
        {
            "evaluateOverrideExpressions": true,
            "expectedArtifacts": [
                {
                    "defaultArtifact": {
                        "customKind": true,
                        "id": "6aacdfcc-7969-46ef-b1c9-36f211fbcc9a"
                    },
                    "displayName": "base64-chart",
                    "id": "131716ea-9f01-4a04-8035-deb513397dab",
                    "matchArtifact": {
                        "artifactAccount": "embedded-artifact",
                        "id": "783d4ced-dce7-474a-ae97-2a34dddb88d5",
                        "name": "base64-chart",
                        "type": "embedded/base64"
                    },
                    "useDefaultArtifact": false,
                    "usePriorArtifact": false
                }
            ],
            "inputArtifacts": [
                {
                    "account": "chart-museum",
                    "id": "24dbe4bd-87f2-49a6-8ee2-68af876de859"
                },
                {
                    "account": "helm",
                    "id": "1c0f515b-4e4d-440c-8340-d8428ce7e200"
                }
            ],
            "name": "Bake (Manifest)",
            "namespace": "nodeapp",
            "outputName": "nodeapp",
            "overrides": {
                "version": "${parameters[\"image_tag\"]}"
            },
            "rawOverrides": false,
            "refId": "1",
            "requisiteStageRefIds": [],
            "templateRenderer": "HELM3",
            "type": "bakeManifest"
        },
        {
            "account": "default",
            "cloudProvider": "kubernetes",
            "manifestArtifactId": "131716ea-9f01-4a04-8035-deb513397dab",
            "moniker": {
                "app": "nodeapp"
            },
            "name": "Deploy (Manifest)",
            "namespaceOverride": "",
            "refId": "2",
            "requisiteStageRefIds": [
                "1"
            ],
            "skipExpressionEvaluation": false,
            "source": "artifact",
            "trafficManagement": {
                "enabled": false,
                "options": {
                    "enableTraffic": true,
                    "namespace": "nodeapp",
                    "services": [
                        "service nodeapp"
                    ],
                    "strategy": "redblack"
                }
            },
            "type": "deployManifest"
        }
    ],
    "triggers": [
        {
            "enabled": true,
            "expectedArtifactIds": [
                "1c0f515b-4e4d-440c-8340-d8428ce7e200",
                "24dbe4bd-87f2-49a6-8ee2-68af876de859"
            ],
            "source": "chapeu",
            "type": "webhook"
        }
    ],
    "updateTs": "1584372551000"
}

```

After the first deploy, I enabled the traffic management on Deck:
```
"trafficManagement": {
        "enabled": true,
        "options": {
          "enableTraffic": true,
          "namespace": "nodeapp",
          "services": [
            "service nodeapp"
          ],
          "strategy": "redblack"
        }
      },
```

The Exception from the logs:
```
[spin-clouddriver-869978cf49-gjm4b] 2020-03-16 15:41:15.229 ERROR 1 --- [ionProcessor-11] c.n.s.c.o.DefaultOrchestrationProcessor  : 
com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor$KubectlException: 
Patch failed: The ReplicaSet "nodeapp-v000" is invalid: spec.template.metadata.labels:
Invalid value: map[string]string{"app.kubernetes.io/managed-by":"spinnaker", "app.kubernetes.io/name":"nodeapp", "moniker.spinnaker.io/sequence":"0"}: 
`selector` does not match template `labels`
[spin-clouddriver-869978cf49-gjm4b]
[spin-clouddriver-869978cf49-gjm4b] 	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor.patch(KubectlJobExecutor.java:734)
[spin-clouddriver-869978cf49-gjm4b] 	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.job.KubectlJobExecutor.patch(KubectlJobExecutor.java:683)
```
Deck:
![image](https://user-images.githubusercontent.com/29067941/76775790-a7fde600-6784-11ea-8177-c749c44aaae4.png)

Pipeline Source:
```
{
      "id": "01E3J035XERKD1VE05R4TY8VJ0",
      "refId": "2>1",
      "type": "disableManifest",
      "name": "disableManifest",
      "startTime": 1584373274585,
      "endTime": 1584373280097,
      "status": "TERMINAL",
      "context": {
        "app": "nodeapp",
        "manifest.account.name": "default",
        "manifestName": "replicaSet nodeapp-v000",
        "kato.task.terminalRetryCount": 0,
        "kato.task.firstNotFoundRetry": -1,
        "outputs.manifestNamesByNamespace": {
          "nodeapp": [
            "replicaSet nodeapp-v000"
          ]
        },
        "manifest.location": "nodeapp",
        "cloudProvider": "kubernetes",
        "kato.result.expected": false,
        "manifest.name": "replicaSet nodeapp-v000",
        "location": "nodeapp",
        "kato.tasks": [
          {
            "exception": {
              "cause": "Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n",
              "details": [
                {
                  "message": "Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n"
                }
              ],
              "message": "Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n",
              "type": "EXCEPTION",
              "operation": "KubernetesDisableManifestOperation"
            },
            "resultObjects": [
              {
                "cause": "Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n",
                "details": [
                  {
                    "message": "Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n"
                  }
                ],
                "message": "Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n",
                "type": "EXCEPTION",
                "operation": "KubernetesDisableManifestOperation"
              }
            ],
            "id": "01E3J0366XNQA8WJ2DB31ERY07",
            "history": [
              {
                "phase": "ORCHESTRATION",
                "status": "Initializing Orchestration Task"
              },
              {
                "phase": "ORCHESTRATION",
                "status": "Processing op: KubernetesDisableManifestOperation"
              },
              {
                "phase": "DISABLE_MANIFEST",
                "status": "Starting disable operation..."
              },
              {
                "phase": "DISABLE_MANIFEST",
                "status": "Getting load balancer list to disable..."
              },
              {
                "phase": "DISABLE_MANIFEST",
                "status": "Using annotated list [service nodeapp]"
              },
              {
                "phase": "DISABLE_MANIFEST",
                "status": "Patching target for 'service nodeapp\""
              },
              {
                "phase": "ORCHESTRATION",
                "status": "Orchestration failed: KubernetesDisableManifestOperation | KubectlException: [Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n]"
              },
              {
                "phase": "ORCHESTRATION",
                "status": "Orchestration failed: KubernetesDisableManifestOperation | KubectlException: [Patch failed: The ReplicaSet \"nodeapp-v000\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{\"app.kubernetes.io/managed-by\":\"spinnaker\", \"app.kubernetes.io/name\":\"nodeapp\", \"moniker.spinnaker.io/sequence\":\"0\"}: `selector` does not match template `labels`\n]"
              }
            ],
            "status": {
              "retryable": false,
              "completed": true,
              "failed": true
            }
          }
        ],
        "kato.last.task.id": {
          "id": "01E3J0366XNQA8WJ2DB31ERY07"
        },
        "kato.task.notFoundRetryCount": 0,
        "account": "default",
        "kato.task.lastStatus": "TERMINAL"
      },
      "outputs": {
        
      },
      "tasks": [
        {
          "id": "1",
          "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ResolveTargetManifestTask",
          "name": "resolveTargetManifest",
          "startTime": 1584373274656,
          "endTime": 1584373274734,
          "status": "SUCCEEDED",
          "stageStart": true,
          "stageEnd": false,
          "loopStart": false,
          "loopEnd": false
        },
        {
          "id": "2",
          "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.manifest.DisableManifestTask",
          "name": "disableManifest",
          "startTime": 1584373274752,
          "endTime": 1584373274899,
          "status": "SUCCEEDED",
          "stageStart": false,
          "stageEnd": false,
          "loopStart": false,
          "loopEnd": false
        },
        {
          "id": "3",
          "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.MonitorKatoTask",
          "name": "monitorDisable",
          "startTime": 1584373274917,
          "endTime": 1584373280078,
          "status": "TERMINAL",
          "stageStart": false,
          "stageEnd": false,
          "loopStart": false,
          "loopEnd": false
        },
        {
          "id": "4",
          "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.manifest.ManifestForceCacheRefreshTask",
          "name": "forceCacheRefresh",
          "status": "NOT_STARTED",
          "stageStart": false,
          "stageEnd": false,
          "loopStart": false,
          "loopEnd": false
        },
        {
          "id": "5",
          "implementingClass": "com.netflix.spinnaker.orca.clouddriver.tasks.manifest.WaitForManifestStableTask",
          "name": "waitForManifestToStabilize",
          "status": "NOT_STARTED",
          "stageStart": false,
          "stageEnd": true,
          "loopStart": false,
          "loopEnd": false
        }
      ],
      "syntheticStageOwner": "STAGE_AFTER",
      "parentStageId": "01E3J0209N0NCJJGKD862BQC9Z",
      "requisiteStageRefIds": [
        
      ]
    }
```
