### ISSUE TITLE
Add support for option on notification target in AWS lifecycle hooks

### ISSUE THREAD

**Issue by nohyunho** [spinnaker/spinnaker#5584]
### Issue Summary:
Halyard can't configure the notification target of lifecycle hooks as options. We get an error when auto scaling group is deployed on a region which is not the region of notification target arn.

### Cloud Provider(s):
AWS

### Environment:
any spinnaker version that supports lifecycle hooks

### Feature Area:
Halyard

### Description:
Halyard supports the following lifecycle hooks configuration per aws account.
```
 --launching-lifecycle-hook-default-result CONTINUE
 --launching-lifecycle-hook-heartbeat-timeout-seconds 1200
 --launching-lifecycle-hook-notification-target-arn arn:aws:sns:region:123456789012:my-sns-topic
 --launching-lifecycle-hook-role-arn arn:aws:iam::123456789012:role/my-notification-role

 --terminating-lifecycle-hook-default-result CONTINUE
 --terminating-lifecycle-hook-heartbeat-timeout-seconds 7200
 --terminating-lifecycle-hook-notification-target-arn arn:aws:sns:region:123456789012:my-sns-topic
 --terminating-lifecycle-hook-role-arn arn:aws:iam::123456789012:role/my-notification-role
```

One aws account contains multiple regions. The notification target arn is region-specific. Therefore, spinnaker can deploy auto scaling group on only region which is the same region of the notification target arn.
The following parameters should be taken as options. (Using aws console or cli, we can configure the notification target as options.)
```
 --launching-lifecycle-hook-notification-target-arn 
 --launching-lifecycle-hook-role-arn 
 --terminating-lifecycle-hook-notification-target-arn
 --terminating-lifecycle-hook-role-arn 
```

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by spinnakerbot** [comment]
This issue is tagged as 'to-be-closed' and hasn't been updated  in 45 days, so we are closing it. You can always reopen this issue if needed.

**Comment by kskewes** [comment]
I'm not sure about Halyard, but we have something like this in our `clouddriver.yml` file.
Clouddriver automatically replaces the jinja-esque variables `{{region}}` and `{{accountId}}` as required.

```
        lifecycleHooks:
        - defaultResult: 'CONTINUE'
          heartbeatTimeout: 3600
          lifecycleTransition: 'autoscaling:EC2_INSTANCE_TERMINATING'
          notificationTargetARN: 'arn:aws:sns:{{region}}:{{accountId}}:spinnaker-asg-lifecycle-hook'
          roleARN: 'arn:aws:iam::{{accountId}}:role/asg-lifecycle-hook'
```
