### ISSUE TITLE
Spinnaker adds service label selector to wrong RS

### ISSUE THREAD

**Issue by dpolicastro** [spinnaker/spinnaker#5591]
### Issue Summary:
I have a need to deploy two ReplicaSets for the same application, let's think about an API and a Worker application. The API needs a service attached to it, the Worker doesn't. So when trying to accomplish this, Spinnaker adds the label which the service points to both ReplicaSets, even if I just specified the `traffic.spinnaker.io/load-balancers: ["service nodeapp"]` annotation to just one of then.

### Cloud Provider(s):
AWS/K8s

### Environment:
Spinnaker 1.19.1

### Description:
I was expecting that Spinnaker would manage the ReplicaSets according to the `traffic.spinnaker.io/load-balancers` label.

### Steps to Reproduce:
- Trigger the pipeline to deploy the following manifest
- Enable **Spinnaker manages traffic based on your selected strategy** on Deploy (Manifest) stage
- Trigger the pipeline again

#### Labels for the Pods (First deploy)
```
kgp --show-labels
NAME                 READY   STATUS    RESTARTS   AGE     LABELS
jod-v000-mct22       1/1     Running   0          2m53s   app.kubernetes.io/managed-by=spinnaker,app.kubernetes.io/name=test-app,app=jod,moniker.spinnaker.io/sequence=0
nodeapp-v000-62sf2   1/1     Running   0          2m54s   app.kubernetes.io/managed-by=spinnaker,app.kubernetes.io/name=test-app,app=nodeapp,frontedBy=nodeapp,moniker.spinnaker.io/sequence=0
```

#### Labels for the Pods (Second deploy) - Note that both ReplicaSets for v001 got the label `frontedBy`.
```
kgp --show-labels
NAME                 READY   STATUS    RESTARTS   AGE   LABELS
jod-v000-mct22       1/1     Running   0          18m   app.kubernetes.io/managed-by=spinnaker,app.kubernetes.io/name=test-app,app=jod,moniker.spinnaker.io/sequence=0

jod-v001-ljr6b       1/1     Running   0          15m   app.kubernetes.io/managed-by=spinnaker,app.kubernetes.io/name=test-app,app=jod, --> frontedBy=nodeapp <-- ,moniker.spinnaker.io/sequence=1

nodeapp-v000-62sf2   1/1     Running   0          18m   app.kubernetes.io/managed-by=spinnaker,app.kubernetes.io/name=test-app,app=nodeapp,moniker.spinnaker.io/sequence=0

nodeapp-v001-8wqs8   1/1     Running   0          15m   app.kubernetes.io/managed-by=spinnaker,app.kubernetes.io/name=test-app,app=nodeapp, --> frontedBy=nodeapp <-- ,moniker.spinnaker.io/sequence=1
```

#### Service Selector
```
kgs -o wide
NAME      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE   SELECTOR
nodeapp   ClusterIP   172.20.78.150   <none>        80/TCP    28m   frontedBy=nodeapp
```

<details>
<summary><b>Manifest.yaml</b></summary>
<br>
<pre>
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: nodeapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    frontedBy: nodeapp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service nodeapp"]'
    version: '1'
  labels:
    app: nodeapp
  name: nodeapp
  namespace: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      annotations:
        timestamp: ''
        version: '1'
      labels:
        app: nodeapp
    spec:
      containers:
        - env:
            - name: APP_NAME
              value: nodeapp
            - name: APP_PORT
              value: '80'
            - name: APP_HOST
              value: 0.0.0.0
            - name: APP_VERSION
              value: '1'
            - name: TIME_BEFORE_START
              value: '5000'
          image: 'dpolicastro/node-http-server:latest'
          imagePullPolicy: Always
          name: nodeapp
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: jod
    version: '1'
  name: jod
  namespace: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jod
  template:
    metadata:
      labels:
        app: jod
    spec:
      containers:
        - env:
            - name: URL
              value: 'http://nodeapp'
            - name: INTERVAL
              value: '2000'
          image: 'dpolicastro/jubilant-octo-disco:latest'
          imagePullPolicy: Always
          name: jod
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
</pre>
</details>

**Comment by dpolicastro** [comment]
I changed the manifests adding new service for the second ReplicaSet. I cleaned up all resources, triggered the pipeline for the first time and deployed the resources again. When triggering the pipeline for the second time, after enable the traffic management, I got a new error:

Deck:
```
Exception ( Monitor Deploy )
Manifest already has traffic.spinnaker.io/load-balancers annotation set to [service nodeapp]. Failed attempting to set it to [service nodeapp, service nodeapp-2].
```

Manifest.yaml
```
apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: nodeapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    frontedBy: nodeapp
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-2
  namespace: nodeapp
spec:
  clusterIP: None
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    frontedBy: nodeapp-2
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service nodeapp"]'
    version: '1'
  labels:
    app: nodeapp
  name: nodeapp
  namespace: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      annotations:
        timestamp: ''
        version: '1'
      labels:
        app: nodeapp
    spec:
      containers:
        - env:
            - name: APP_NAME
              value: nodeapp
            - name: APP_PORT
              value: '80'
            - name: APP_HOST
              value: 0.0.0.0
            - name: APP_VERSION
              value: '1'
            - name: TIME_BEFORE_START
              value: '5000'
          image: 'dpolicastro/node-http-server:latest'
          imagePullPolicy: Always
          name: nodeapp
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service nodeapp-2"]'
  labels:
    app: jod
    version: '1'
  name: jod
  namespace: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jod
  template:
    metadata:
      labels:
        app: jod
    spec:
      containers:
        - env:
            - name: URL
              value: 'http://nodeapp'
            - name: INTERVAL
              value: '2000'
          image: 'dpolicastro/jubilant-octo-disco:latest'
          imagePullPolicy: Always
          name: jod
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
```

Clouddriver Logs
```
[spin-clouddriver-5f9cdcdbb-lvcjd] 2020-03-17 18:41:23.444 ERROR 1 --- [ionProcessor-33] c.n.s.c.o.DefaultOrchestrationProcessor  : java.lang.RuntimeException: Manifest already has traffic.spinnaker.io/load-balancers annotation set to [service nodeapp]. Failed attempting to set it to [service nodeapp, service nodeapp-2].
[spin-clouddriver-5f9cdcdbb-lvcjd] 	at com.netflix.spinnaker.clouddriver.kubernetes.v2.description.manifest.KubernetesManifestAnnotater.setTraffic(KubernetesManifestAnnotater.java:249)
[spin-clouddriver-5f9cdcdbb-lvcjd] 	at com.netflix.spinnaker.clouddriver.kubernetes.v2.op.manifest.KubernetesDeployManifestOperation.setTrafficAnnotation(KubernetesDeployManifestOperation.java:245)
```
