### ISSUE TITLE
Igor does not load encrypted secrets

### ISSUE THREAD

**Issue by Derenge** [spinnaker/spinnaker#5595]
### Issue Summary:

When specifying the `jsonKey` as an "encrypted" file in gcs, Igor attempts to use the JSON as the file path.

I tried to track down the difference between `cloud-driver` and `igor`, but they both seem to be doing the same operations on the account `jsonPath` and `jsonKey` respectively. From the logs I can see that in `cloud-driver` it appears to write the json into a temporary file and use that path.

I'd love to help fix this by modeling it after `cloud-driver` and maybe rename `Key` to `Path`, but I am unable to find where `cloud-driver` is writing the JSON to a tmp file.

```
gcb:
  enabled: true
  accounts:
  - name: cloud-build
    permissions: {}
    project: my-project
    subscriptionName: spinnaker-cloud-build
    jsonKey: encrypted:gcs!b:bucket!f:spinnaker-gcb-account.json
```

Other accounts can be specified like so

```
gcs:
  enabled: true
  accounts:
  - name: google-cloud-storage
    jsonPath: encrypted:gcs!b:bucket!f:spinnaker-gcs-account.json
```

### Cloud Provider(s):

GKE

### Environment:

Spinnaker Version: 1.18.4, installed following https://www.spinnaker.io/setup/install/ with Kubernetes V2 cloud provider

### Feature Area:
GCB - Igor
