### ISSUE TITLE
clouddriver-local.yml is being ignored 

### ISSUE THREAD

**Issue by Narrayahodeir** [spinnaker/spinnaker#5613]
### Issue Summary:
After issuing a customized clouddriver-local.yml file under .hal/default/profiles/clouddriver-local.yml it is being ignored by Halyard.

### Cloud Provider(s):
AWS

### Environment:
I' running Spinnaker 1.19.2 and Halyard 1.32 within a distributed installation on AWS EKS 1.15.

### Feature Area:
Clouddriver, Cloud Providers

### Description:
With a Kubernets ConfigMap I write a clouddriver-local.yml file to the halyard container under .hal/default/profiles/clouddriver-local.yml. The content is like this:
```
aws:
  enabled: true
  accounts:
  - name: cloud_prod
    accountId: 111111111111
    regions:
    - name: eu-west-1
    assumeRole: role/SpinnakerManagedRole
```
Running `hal config` doesn't recognized the content of the clouddriver-local.yml file and the AWS provider still remains disabled and the account config is ignored.

I want the AWS provider enabled and the accounts shown in `hal config`

### Steps to Reproduce:

1. Set the clouddriver-local.yml file with a ConfigMap mounted at `/home/spinnaker/.hal/default/profiles/clouddriver-local.yml` in the Halyard container.
2. The file then is being automatically copied to `/home/spinnaker/.hal/default/staging/clouddriver-local.yml`
3. Running `hal deploy apply` without any errors.
4. Running `hal config` to list the configuration

### Additional Details:
Only configuration stored in `/home/spinnaker/.hal/config` is loaded. I verified the file permissions and ownership. I use the default configuration profile.

The halyard log writes: `Writing profile to /home/spinnaker/.hal/default/staging/clouddriver-local.yml with 0 required files`

in `/home/spinnaker/.hal/default/history/service-profiles.yml` I have:

```
clouddriver:
  clouddriver-local.yml:
    requiredFiles: []
    decryptedFiles: {}
    env: {}
    name: clouddriver-local.yml
    version: 6.7.1-20200319123809
    outputFile: /opt/spinnaker/config/clouddriver-local.yml
    executable: false
    user: spinnaker
    group: spinnaker
```

I followed the guide provided here: https://www.spinnaker.io/reference/halyard/custom/
