### ISSUE TITLE
spin-gate health check

### ISSUE THREAD

**Issue by jefimm** [spinnaker/spinnaker#5615]
### Issue Summary:
Change spin-gate health check to allow gke ingress to properly create the load-balancer health check

### Cloud Provider(s):
GKE

### Description:

When trying to use Ingress in GKE. with the spinnaker the following issue prevents GKE ingress to properly configure load balancer:
current health check for the service is 
```
        livenessProbe:
          exec:
            command:
            - wget
            - --no-check-certificate
            - --spider
            - -q
            - http://localhost:8084/health
```
to the following
```
        readinessProbe:
          httpGet:
            path: /health
            port: 8084
```

reference: https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks

Alternatively allow spin-gate to answer to / url too.

[I know that the better way would be to allow GKE to define custom health checks but this is not something that is easily achieved]
