### ISSUE TITLE
Spinnaker 1.19.2 helm upgrade fail : Unrecognized field "plugins"

### ISSUE THREAD

**Issue by zdevi** [spinnaker/spinnaker#5619]
I am trying to upgrade my spinnaker helm release to 1.19.2
Halyard gives me an error i did not get before :

```
+ hal --daemon-endpoint http://spinnaker-spinnaker-halyard:8064 --ready
+ bash -xe /opt/halyard/scripts/config.sh
+ hal --daemon-endpoint http://spinnaker-spinnaker-halyard:8064 config version edit --version 1.19.2
- Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "plugins" (class
  com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration), not
  marked as ignorable (18 known properties: "security", "artifacts", "providers",
  "pubsub", "persistentStorage", "ci", "notifications", "repository", "name",
  "deploymentEnvironment", "webhook", "version", "timezone", "features", "stats",
  "metricStores", "canary", "spinnaker"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["plugins"])

- I know everything hasn't been quite right with me, but I can
  assure you now, very confidently, that it's going to be alright again.
- Failed to get deployment name.
```

I have no "plugins" value in my values.yaml configuration :

```
halyard:
  spinnakerVersion: 1.19.2
  image:
    repository: gcr.io/spinnaker-marketplace/halyard
    tag: 1.32.0
  additionalScripts:
    create: true
    data:
      configure.sh: |-
        export HAL_COMMAND="hal --daemon-endpoint http://spinnaker-spinnaker-halyard:8064"
        if $HAL_COMMAND config provider docker-registry account get gcr; then
          EDIT_COMMAND='edit'
        else
          EDIT_COMMAND='add'
        fi
        $HAL_COMMAND config provider docker-registry account $EDIT_COMMAND gcr --address eu.gcr.io --password-file /opt/gcs/key.json  --username _json_key
        $HAL_COMMAND config security api edit --override-base-url https://spinnaker-gate.test.xxxxx.hosting --cors-access-pattern https://spinnaker.test.xxxxxx.hosting
        $HAL_COMMAND config security ui edit --override-base-url https://spinnaker.test.xxxxxx.hosting
  additionalProfileConfigMaps:
    create: false
    data:
      settings-local.js: |-
        window.spinnakerSettings.authEnabled = true;
      spinnaker-local.yml: |-
        services:
          # deck:
            auth:
              enabled: true
      gate-local.yml: |-
        server:
          tomcat:
            protocolHeader: X-Forwarded-Proto
            remoteIpHeader: X-Forwarded-For
            internalProxies: .*
            httpsServerPort: X-Forwarded-Port
        security:
          basicform:
            enabled: true
          user:
            name: spinnaker
            password: xxxxxxxxxxxxx
## REDIS FLUSH
      orca-local.yml: |-
        pollers:
          oldPipelineCleanup:
            enabled: true
            intervalMs: 3600000
            thresholdDays: 30
            minimumPipelineExecutions: 5

dockerRegistry:
  enabled: true
  accounts:
  - name: dockerhub
    address: index.docker.io
    repositories:
      - library/alpine
      - library/ubuntu
      - library/centos
      - library/nginx

# Google Cloud Storage
gcs:
  enabled: true
  project: test
  bucket: spinnaker-test
  ## if jsonKey is set, will create a secret containing it
  jsonKey: '{
  "type": "service_account",
  "project_id": "test",
  "private_key_id": "xxxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\-----END PRIVATE KEY-----\n",
  "client_email": "xxxx",
  "client_id": "xxxxxx",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "xxxxxx"
}
'
  #secretName: spinnaker-gcs-secret
  ## override the name of the secret to use for jsonKey, if `jsonKey`
  ## is empty, it will not create a secret assuming you are creating one
  ## external to the chart. the key for that secret should be `key.json`.
kubernetes:
  enabled: true
  accounts:
  - name: default
    requiredGroupMembership: []
    providerVersion: V2
    permissions: {}
    dockerRegistries:
    - accountName:
      namespaces: []
    context: default
    configureImagePullSecrets: true
    serviceAccount: true
    cacheThreads: 1
    namespaces: []
    omitNamespaces:
    - kube-system
    - kube-public
    - spinn
    - nginx
    - kubernetes
    kinds: []
    omitKinds: []
    customResources: []
    cachingPolicies: []
    oauthScopes: []
    oAuthScopes: []
    onlySpinnakerManaged: false
  primaryAccount: default

ingress:
  enabled: true
  tls:
    - secretName: ui-tls
      hosts:
        - spinnaker.test.xxx.hosting
  host: spinnaker.test.xxx.hosting
  annotations:
    kubernetes.io/ingress.ssl-redirect: 'true'
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"


ingressGate:
  enabled: true
  tls:
    - secretName: api-tls
      hosts:
        - spinnaker-gate.test.xxx.hosting
  host: spinnaker-gate.test.xxx.hosting
  annotations:
    kubernetes.io/ingress.ssl-redirect: 'true'
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"

serviceType: NodePort 
```

I don't believe this is a helm issue so that's why i'm posting it here.
