### ISSUE TITLE
Pipeline expressions not evaluated in pipeline templates

### ISSUE THREAD

**Issue by dpolicastro** [spinnaker/spinnaker#5630]
### Issue Summary:
Not all fields are being evaluated using pipeline templates. It's not clear which fields can be replaced using pipeline expressions inside the pipeline template.

Both variables in the template and in the config file are correct.
```
# pipeline-template.yaml
pipeline:
  appConfig: {}
  keepWaitingPipelines: false
  lastModifiedBy: anonymous
  limitConcurrent: true
  spelEvaluator: v4
  expectedArtifacts:
  - defaultArtifact:
      artifactAccount: s3
      name: "${ templateVariables.s3Path }" # Ok
      type: s3/object
    displayName: values file
    id: "helm values file"
    matchArtifact:
      artifactAccount: s3
      name: "${ templateVariables.s3Path }" # Ok
      type: s3/object
    useDefaultArtifact: true
    usePriorArtifact: false

  stages:
  - type: bakeManifest
    namespace: "${ templateVariables.serviceName }" # Not ok
    outputName: "${ templateVariables.serviceName }" # Not ok
  - type: deployManifest
    trafficManagement:
      enabled: true
      options:
        enableTraffic: true
        namespace: "${ templateVariables.serviceName }" # Not ok
        services:
        - service ${ templateVariables.serviceName }-api # Not ok
        strategy: redblack
```

![image](https://user-images.githubusercontent.com/29067941/77930369-31331380-7281-11ea-8d9d-bc73c7e95f53.png)

![image](https://user-images.githubusercontent.com/29067941/77931040-04333080-7282-11ea-9da3-83d162718608.png)

### Cloud Provider(s):
AWS / K8s

### Environment:
Spinnaker 1.19.1

### Feature Area:
Pipeline Templates
