### ISSUE TITLE
High Redis memory usage

### ISSUE THREAD

**Issue by axot** [spinnaker/spinnaker#5678]
### Issue Summary:
We found recently redis memory keep growing, I did some analysis on it, the result shows `pipeline:.*` keys used 1.83GB of memory.

![image](https://user-images.githubusercontent.com/611054/79320672-234de580-7f45-11ea-9e81-ec59f34e8b63.png)

![image](https://user-images.githubusercontent.com/611054/79320506-e386fe00-7f44-11ea-8a5e-b538aac8c94c.png)

### Cloud Provider(s):
GKE

### Redis Version
MemoryStore(Redis v4)

### Version
1.18.4

**Comment by ajordens** [comment]
I would suggest following up on the Spinnaker Slack, there should be a cleanup agent that can be activated to periodically cleanup old pipeline executions.

**Comment by axot** [comment]
Thanks, finally I found a document about how to configure it. https://www.spinnaker.io/setup/productionize/caching/configure-redis-usage/

**Comment by axot** [comment]
Hello, with setup cleanup agent, the memory usage has been greatly improved. We found these days memory usage raised again. I did a simple investigation below,

1. Is it safe to delete `kato:taskmap` and `kubernetes:event`?
2. If [1] is yes, should we delete these keys using a cron job?

Thanks.
```
bash-4.4# redis-cli -h 10.x.x.4 keys "*"  | head -100000 | awk -F":" '{print $1 ":" $2}' | sort -rn | uniq -c | sort -rn | head -10
  21455 kato:taskmap
  14761 kubernetes:event
  12237 kubernetes:artifact
   5601 com.netflix.spinnaker.clouddriver.docker.registry.provider.DockerRegistryProvider:taggedImage
   5544 com.netflix.spinnaker.clouddriver.docker.registry.provider.DockerRegistryProvider:imageId
   5493 igor:dockerRegistry
   5195 kubernetes:pod
   4884 kubernetes:replicaSet
   2321 kubernetes:clusters
   2275 kubernetes:clusterRole
```

**Comment by lub0v-parsable** [comment]
Hi @axot, did you end up finding a solution for this? we have same issue

**Comment by toVersus** [comment]
Hi @lub0v-parsable

As @axot said, we configured these parameters to save Redis memory usage.
https://spinnaker.io/docs/setup/productionize/caching/configure-redis-usage/

1. We didn't use the Spinnaker feature to show current status of our infrastructure on the UI (e.g. [Clusters](https://spinnaker.io/docs/concepts/clusters/)), so increased the interval to cache Kubernetes objects.

    ```yaml
    $ cat ~/.hal/default/profiles/clouddriver-local.yml
    redis.agent.maxConcurrentAgents: 20
    redis.agent.agent-lock-acquisition-interval-seconds: 5
    redis.poll.intervalSeconds: 300
    ```

1. Also, we configured the pipeline cleanup as follows:

    ```yaml
    $ cat ~/.hal/default/profiles/orca-local.yml
    pollers:
      oldPipelineCleanup:
        enabled: true                  # This enables old pipeline execution cleanup (default: false)
        intervalMs: 3600000            # How many milliseconds between pipeline cleanup runs (default: 1hr or 3600000)
        thresholdDays: 14              # How old a pipeline execution must be to be deleted (default: 30)
        minimumPipelineExecutions: 5   # How many executions to keep around (default: 5)

    tasks:
      daysOfExecutionHistory: 30      # How many days to keep old task executions around.
    ```

After upgrading Spinnaker to 1.26.7 with those changes, we don't see any issues related to Redis memory usage anymore. It seems that Spinnaker also gets to delete stalled container images from Redis cache at some point. We periodically delete the unused images from our container registry, so it might also improve the Redis cache usage.
