### ISSUE TITLE
GCE servergroups not displayed with sql backed clouddriver

### ISSUE THREAD

**Issue by luckoseabraham** [spinnaker/spinnaker#5734]
### Issue Summary:
We have spinnaker with HA enabled and orca running on mysql and clouddriver on redis. Migration to mysql for orca brought really great differences to our spinnaker. Due to increase in the instances, deployment and applications, decided to try out the mysql backend for clouddriver cache.

We use spinnaker to deploy both kubernetes and GCE workloads.
All the kubernetes based deployments and functionalities work perfectly.
When navigating to a GCE deployed infrastructure tab, the server groups are just empty.
Looking at the mysql instance for cats_v1_clusters and cats_v1_serverGroup, all the entries are available.

Note that deployments to GCE is working fine without any issues.

### Environment:

```
sql:
  enabled: true
  taskRepository:
    enabled: true
  cache:
    enabled: true
    readBatchSize: 500
    writeBatchSize: 300
  scheduler:
    enabled: false
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:mysql://ip:3306/clouddriver
      user: clouddriver_service
      password: *****
  migration:
    user: clouddriver_migrate
    jdbcUrl: jdbc:mysql://ip:3306/clouddriver
    password: *****

redis:
  enabled: true
  cache:
    enabled: false
  scheduler:
    enabled: true
  taskRepository:
    enabled: true

dualTaskRepository:
  enabled: true
  primaryClass: com.netflix.spinnaker.clouddriver.sql.SqlTaskRepository
  previousClass: com.netflix.spinnaker.clouddriver.data.task.jedis.RedisTaskRepository
```

### Steps to Reproduce:
spinnaker version : 1.18.9
Migrate clouddriver cache backend from redis to mysql with gce deployments available.
Navigate to the infrastructure tab of a gce deployed applications. No server groups are available which are being displayed with redis.

### Additional Details:
Trying to debug a bit more, I enabled jooq debug level for clouddriver-ro component and saw the below query,
Not sure why the clustersrel is being looked up with kuberenetes.v2 provider instead of gce or if it was some rogue query that got my eye.
```select body as `body`, null as `id`, null as `rel_id`, null as `rel_type` from cats_v1_clusters where ID in ('kubernetes.v2:logical:clusters:[[accountname]]]:[[application]]:[[servergroupname]]')```
