### ISSUE TITLE
1.19.8 or 1.20.1 Front50 not starting on AWS EC2 Instance

### ISSUE THREAD

**Issue by amiteshchandra** [spinnaker/spinnaker#5763]
### Issue Summary:
I installed 1.19.8 first and then 1.20.1 in AWS EC2  instance (Ubuntu 16.04).
Front50 is not starting. 

### Cloud Provider(s):
AWS and EKS

### Environment:
Halyard latest
Spinnaker 1.19.8 (Also tried 1.20.1)

### Feature Area:
Pipeline

### Description:

Below is the error
`2020-05-13 17:33:02.192  WARN 18597 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pluginVersionController' defined in URL [jar:file:/opt/front50/lib/front50-web-0.23.1-20200509020016.jar!/com/netflix/spinnaker/front50/controllers/PluginVersionController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'pluginVersionPinningService' defined in class path resource [com/netflix/spinnaker/front50/config/PluginVersioningConfiguration.class]: Unsatisfied dependency expressed through method 'pluginVersionPinningService' parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.netflix.spinnaker.front50.model.plugins.PluginVersionPinningRepository' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
`

```
[18597]: Parameter 0 of method pluginVersionPinningService in com.netflix.spinnaker.front50.config.PluginVersioningConfiguration required a bean of type 'com.netflix.spinnaker.front50.model.plugins.PluginVersionPinningRepository' that could not be found.
May 13 17:33:03 ip-XX-XX-44-101 front50[18597]: Action:
May 13 17:33:03 ip-XX-XX-44-101 front50[18597]: Consider defining a bean of type 'com.netflix.spinnaker.front50.model.plugins.PluginVersionPinningRepository' in your configuration.
```

This is in front50.yml (~/.hal/default/staging/front50.yml)
```
spinnaker:
  spinnaker:
    extensibility:
      plugins: {}
      repositories: {}
      plugins-root-path: /opt/front50/plugins
      strict-plugin-loading: false
  azs:
    enabled: false
  gcs:
    rootFolder: front50
    enabled: false
  redis:
    host: localhost
    port: 6379
    enabled: true
  s3:
    rootFolder: front50
    enabled: false
  oracle:
    enabled: false
```

### Steps to Reproduce:
Follow the Setup steps provided in https://www.spinnaker.io/setup/

### Additional Details:

---
