### ISSUE TITLE
CloudFormation stage for deleting stacks

### ISSUE THREAD

**Issue by clayvan** [spinnaker/spinnaker#5764]
### Issue Summary:
Currently the only available stage is Deploy cloudformation, but that actually does either Create or Update depending on the state of the stack. I would propose a third possible stack action of Delete.

It's great that we can create stacks as a Spinnaker stage now, but without a delete stage we're relying on a separate tool for that work.

### Cloud Provider(s):
aws

### Environment:
Spinnaker 1.17.6 (I'm nowhere near the latest but as far as I'm aware this isn't available in latest either.)

### Feature Area:
Pipelines

**Comment by aleon1220** [comment]
I agree. It would be nice to have some sort of UI to manage the config as a code deployments. A terraform management UI and a Cloud Formation Management UI to see the Deployed stacks and list of resources. 

That would be useful to track and manage from Spinnaker what is deployed in AWS CF or any other cloud provider if using Terraform.

**Comment by atyutyunnik** [comment]
this can be worked around by having a Spinnaker Custom Stage Job, I will later post a sample

**Comment by atyutyunnik** [comment]
in general, cloudformation deletion may not be possible without custom scripting anyway. For example, if you put images in AWS ECR repository, cloudformation removal will be natively blocked, so you have to remove the images first, which again requires custom scripting

**Comment by clayvan** [comment]
@atyutyunnik hmm sure, but that would still be sent back to Spinnaker as a CloudFormation Delete failure, in the same way any other CF error would return. That's like saying that we couldn't add Create/Updates because there might be a CloudFormation error creating the stack.

In my mind, there's no reason Delete stack couldn't be added in the same way Create and Update are.

**Comment by atyutyunnik** [comment]
> @atyutyunnik hmm sure, but that would still be sent back to Spinnaker as a CloudFormation Delete failure, in the same way any other CF error would return. That's like saying that we couldn't add Create/Updates because there might be a CloudFormation error creating the stack.
> 
> In my mind, there's no reason Delete stack couldn't be added in the same way Create and Update are.

certainly, however, CF Creation/Update ops don't require any customization to be successful, yet, Delete CF operation would require customization almost all the time. Here is an example of Run Job (Manifest) for a simple stack that uses AWS ECR, where you must use customization, and therefore, a standard Spinnaker stage would be useless:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: cloudformation-delete

spec:
  backoffLimit: 0
  template:
    metadata:
      name: ${execution-application}-cloudformation-delete
    spec:
      containers:
        - args:
            - |-
              set -vx;

              for SVC in `aws ecr describe-repositories --output text --query "repositories[?starts_with(repositoryName, '$APP-$ENV-')][repositoryName]"`
              do
                 aws ecr delete-repository --force --repository-name $SVC;
              done

              aws cloudformation delete-stack --stack-name $APP-$ENV;

              aws cloudformation wait stack-delete-complete --stack-name $APP-$ENV || echo Failed but who cares...
          command:
            - /bin/bash
            - '-c'
          env:
            - name: ENV
              value: staging
            - name: AWS_DEFAULT_REGION
              value: us-west-1
            - name: APP
              value: '${execution.application}'

          image: amazon/aws-cli
          name: cf
          volumeMounts:
            - mountPath: /root/.aws
              name: aws-creds
      restartPolicy: Never
      volumes:
        - name: aws-creds
          secret:
            secretName: aws-credentials
```


if you use ECS, you will have to customize even more. Create/Update doesn't have an issue like that
