### ISSUE TITLE
"Monitor Deploy" step of pipeline invocation/deploy duration unaffected by upping number of orcas/clouddriver replicas

### ISSUE THREAD

**Issue by RochesterinNYC** [spinnaker/spinnaker#5770]
### Issue Summary:

When using the Kubernetes manifest-based provider, we are invoking a pipeline execution that deploys out about 800 different Kubernetes resources to a single K8s cluster. The manifests/resources have no functional differences from what is currently live on the cluster. This pipeline/invocation is the only thing that this Spinnaker instance is configured to deploy.

We're seeing that the "Monitor Deploy" part of the execution takes upwards of 45-60 minutes. More confusing is that fact that upping the number of clouddriver and orca replicas (from 1 and 2 to respectively 5 and 10) has no impact at all on the amount of time this "Monitor Deploy" part takes.

### Cloud Provider(s):

GCP/GKE

### Environment:

Running Spinnaker on Kubernetes/GKE, configured via Halyard.

Halyard version 1.19.4.

Logs from orca, clouddriver, or any other component available on hand.

**Comment by RochesterinNYC** [comment]
Here's the size of our Spinnaker components:

```
  deploymentEnvironment:
    customSizing:
      clouddriver:
        requests:
          cpu: 20
          memory: 20Gi
        limits:
          cpu: 20
          memory: 20Gi
      deck:
        requests:
          cpu: 1
          memory: 100Mi
        limits:
          cpu: 1
          memory: 100Mi
      echo:
        requests:
          cpu: 1
          memory: 6Gi
        limits:
          cpu: 1
          memory: 6Gi
      front50:
        requests:
          cpu: 1
          memory: 6Gi
        limits:
          cpu: 1
          memory: 6Gi
      gate:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          cpu: 1
          memory: 4Gi
      spin-orca:
          replicas: 10
      spin-clouddriver:
          replicas: 5
      orca:
        requests:
          cpu: 8
          memory: 24Gi
        limits:
          cpu: 8
          memory: 24Gi
      redis:
        requests:
          cpu: 1
          memory: 1.2Gi
        limits:
          cpu: 1
          memory: 1.2Gi
      rosco:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          cpu: 1
          memory: 2Gi
```
