### ISSUE TITLE
Manual execution stuck at "Wait For Manifest To Stabilize" when specific CRD artefact is being used

### ISSUE THREAD

**Issue by p3rshin** [spinnaker/spinnaker#5786]
### Issue Summary:
Manual pipeline execution initiated by "non-admin" user results in `Wait For Manifest To Stabilize` stage until the timeout is reached, but the change is actually going through - pod is live and healthy. Issue is not reproducible when "admin" users manually start the the pipeline, but both groups have identical permissions to `ci-service-account`.

### Cloud Provider(s):
kubernetes 1.16.7

### Environment:
Self-managed Kubernetes on AWS
Spinnaker 1.18.9 on EC2, SQL cache store with the Redis-backed scheduler

### Feature Area:
clouddriver/orca

### Description:
Expected behavior: acknowledge stage as complete and progress further.

No Fiat errors, Orca shows `Unable to read manifest 'SQSQueue.sqs.xxx xxx-service' in 'ci' for account ci-service-account`

Clouddrives shows `Encountered exception while processing request GET:/manifests/ci-service-account/ci/SQSQueue.sqs.xxx%20xxx-service with headers...` and `org.springframework.security.access.AccessDeniedException: Access is denied
	at org.springframework.security.access.expression.method.ExpressionBasedPostInvocationAdvice.after(ExpressionBasedPostInvocationAdvice.java:77)`

Issue is specific to SQSQueue artefacts, other custom resources are being deployed successfully. Clouddriver config has identical permissions for admin/users (non-admins)
```
name: ci-service-account
    requiredGroupMembership: []
    providerVersion: V2
    permissions:
      READ:
      - users
      - admins
      WRITE:
      - users
      - admins
      EXECUTE:
      - users
      - admins
    dockerRegistries: []
    context: ci-service-account
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces:
    - ci
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources:
    - kubernetesKind: DynamoDBTable
      versioned: false
    - kubernetesKind: IAMRole
      versioned: false
    ...
    - kubernetesKind: SNSTopic
      versioned: false
    - kubernetesKind: SNSTopicSubscription
      versioned: false
    - kubernetesKind: SQSQueue
      versioned: false
    cachingPolicies: []
    kubeconfigFile: xxx-config
    liveManifestCalls: true
    oAuthScopes: []
```
### Steps to Reproduce:
N/A

### Additional Details:
Authorisation in FIAT is based on GitHub teams.
