### ISSUE TITLE
Authentication redirect loop

### ISSUE THREAD

**Issue by RubyLangdon** [spinnaker/spinnaker#5794]
### Issue Summary:
We are suddenly in a redirect loop with gitlab auth.

### Cloud Provider(s):
AWS

### Environment:
Spinnaker  v1.18.12
Halyard v1.31.1
Oauth provider is Gitlab
Authz provider type is FILE

### Feature Area:
Authentication / authorization

### Description:
We suddenly notice that we cannot log in to the spinnaker UI. The browser has a too many redirects error. We've changed nothing, it was working one day and not the next.

If we upgrade to 1.19.10 or 1.20.3 it works fine. (We'd prefer not to upgrade at the moment due to https://github.com/spinnaker/spinnaker/issues/5701). 
When we downgrade back to 1.18.12 it's broken again. The issue also occurred when we tested versions 1.15.5, 1.16.7, and 1.17.10.

We tried flushing the redis cache which didn't help.
We can't see any error logs in any spinnaker pods. Gate debug logs are attached.
[gatelogs.txt](https://github.com/spinnaker/spinnaker/files/4685677/gatelogs.txt)

### Steps to Reproduce:
Contents of `gate-local.yaml`

```
security:
  oauth2:
    client:
      clientId: xxxxxx
      clientSecret: xxxxxx
      userAuthorizationUri: https://gitlab.com/oauth/authorize
      accessTokenUri: https://gitlab.com/oauth/token
      scope: read_user openid
      preEstablishedRedirectUri: <our-gate-base-url>/login
    resource:
      userInfoUri: https://gitlab.com/api/v4/user          
    userInfoMapping:        
      email: email
      firstName: ''
      lastName: name
      username: username
```

**Comment by bcornils** [comment]
Hello @RubyLangdon Thanks for filing the issue. Unfortunately, no one is available to work on this at the moment, but we welcome contributions from our community. We strongly encourage you to discuss your plans here or on the SIG's [slack channel](https://join.spinnaker.io/) before you start working on the issue. Additionally, I encourage you to leverage our community in slack.  Use the search functionality to find users who have a similar experience, or post a message in `#general` or another related channel. If no one is able to assist please let us know here. Thank you.

**Comment by RubyLangdon** [comment]
Hi @bcornils, so far we haven't made any progress and I haven't managed to find anyone with a similar issue.

**Comment by bcornils** [comment]
Hi @RubyLangdon I'll bring this to the Security SIG this thursday, please feel free to join us to discuss further.

**Comment by alchen99** [comment]
@RubyLangdon your scope `read_user`, userInfoUri, and userInfoMapping is not correct. This will cause an endless redirect loop. Also some tomcat overrides are usually needed. Please try the following in `gate-local.yml`

```
server:
  tomcat:
    httpsServerPort: X-Forwarded-Port
    internalProxies: .*
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For

security:
  oauth2:
    enabled: true
    client:
      clientId: xxxxx
      clientSecret: xxxxx
      accessTokenUri: https://gitlab.com/oauth/token
      userAuthorizationUri: https://gitlab.com/oauth/authorize
      scope: openid,email
    resource:
      userInfoUri: https://gitlab.com/oauth/userinfo
    userInfoMapping:
      email: email
      firstName: name
      lastName: ''      
      username: nickname
```
