### ISSUE TITLE
[Feature/ECS/Lambda] Lambdas not being shown for ECS accounts

### ISSUE THREAD

**Issue by awsiv** [spinnaker/spinnaker#5817]
### Issue Summary:
Looks like Lambda integration is not fully supported for ECS applications 

### Cloud Provider(s):
aws, ecs, lambda

### Environment:
local-debian

### Feature Area:
clouddriver, lambda

### Description:
Looks like Lambda integration is not fully supported for ECS applications - at least the caching of functions

The following does not error out and I can create lambda from deck, however they are not displayed back even after successful deployment because the lambda is deployed in an EcS application. Works fine for aws/ec2 application
```
ecs:
  enabled: true
  lambda:
    enabled: true
  accounts:
    - name: dev-ecs
      lambdaEnabled: true
      environment: ecs
      requiredGroupMembership: []
      providerVersion: V1
      permissions: {}
      awsAccount: dev
```

Ref: https://aws.amazon.com/blogs/opensource/how-to-integrate-aws-lambda-with-spinnaker/
