### ISSUE TITLE
Add Support to creation of Kubernetes Kinds: CronJob and Job

### ISSUE THREAD

**Issue by prashanthh727** [spinnaker/spinnaker#5851]
### Issue Summary:
Add Support to creation of Kubernetes Kinds: CronJob and Job

### Cloud Provider(s):
Kubernetes in GCP

### Environment:
GCP

### Feature Area:
Spinnaker pipeline

### Description:
Add support to creation of k8s kind job and cron-job in a similar way where spinnaker allows creating pods and ReplicaSets, 

Below is the template to create job and cronjob:
https://kubernetes.io/docs/concepts/workloads/controllers/job/
```

apiVersion: batch/v1
kind: Job
metadata:
  # Unique key of the Job instance
  name: PARAM_JOB_NAME
  namespace: PARAM_NAME_SPACE
spec:
  ttlSecondsAfterFinished: 100
  completions: PARAM_POD_INSTANCES
  parallelism: PARAM_POD_INSTANCES
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      name: PARAM_JOB_NAME
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: ENV_JAVA_OPTS
        name: PARAM_CONTAINER_NAME
        image: PARAM_IMAGE_NAME
        resources:
          limits:
            memory: "PARAM_MEMORY_LIMIT"
            cpu: "PARAM_CPU_LIMIT"
          requests:
            memory: "PARAM_MEMORY_REQUESTS"
            cpu: "PARAM_CPU_REQUESTS"
      # Do not restart containers after they exit
      restartPolicy: Never
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: PARAM_SERVICE_ACCOUNT
      serviceAccountName: PARAM_SERVICE_ACCOUNT
      terminationGracePeriodSeconds: 30
  # of retries before marking as failed.
  backoffLimit: PARAM_BACK_OFF_LIMIT
```
https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
```

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  # Unique key of the CRON Job instance
  name: PARAM_JOB_NAME
  namespace: PARAM_NAME_SPACE
spec:
  schedule: "PARAM_CRON"
  failedJobsHistoryLimit: 3
  concurrencyPolicy: PARAM_POLICY # allow, forbid and replace
  startingDeadlineSeconds: 1800 #30 mins time to start the jobs
  jobTemplate:
    metadata:
      namespace: PARAM_NAME_SPACE
    spec:
      ttlSecondsAfterFinished: 100
      completions: PARAM_POD_INSTANCES
      parallelism: PARAM_POD_INSTANCES
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"
          name: PARAM_CONTAINER_NAME
        spec:
          containers:
          - env:
            - name: JAVA_OPTS
              value: PARAM_JAVA_OPTS
            name: PARAM_JOB_NAME
            image: PARAM_IMAGE_NAME
            resources:
              limits:
                memory: "PARAM_MEMORY_LIMIT"
                cpu: "PARAM_CPU_LIMIT"
              requests:
                memory: "PARAM_MEMORY_REQUESTS"
                cpu: "PARAM_CPU_REQUESTS"
          # Do not restart containers after they exit
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: gcr
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: PARAM_SERVICE_ACCOUNT
          serviceAccountName: PARAM_SERVICE_ACCOUNT
          terminationGracePeriodSeconds: 30
      # of retries before marking as failed.
      backoffLimit: PARAM_BACK_OFF_LIMIT
```

### Additional Details:
Externalized parameters for the job/cronjob template:
PARAM_JOB_NAME
PARAM_NAME_SPACE
PARAM_POD_INSTANCES
PARAM_BACK_OFF_LIMIT
PARAM_POLICY 
PARAM_CRON

Container Details:
PARAM_IMAGE_NAME
PARAM_CONTAINER_NAME
PARAM_MEMORY_LIMIT
PARAM_CPU_LIMIT
PARAM_MEMORY_REQUEST
PARAM_CPU_REQUEST
PARAM_SERVICE_ACCOUNT

Environment Variables:
list of key:value pairs
