### ISSUE TITLE
SAML /auth redirection is not going to gate

### ISSUE THREAD

**Issue by dilipgb6594** [spinnaker/spinnaker#5855]
### Issue Summary:
I'm facing issue while setting up the SAML Authentication. I'm using PING Identity for SAML federated access. After Tocker is posted to /gate/saml/SSO its getting redirected to /auth/redirect instead of /gate/auth/redirect.
```
10.99.1.21 - - [18/Jun/2020:15:35:13 +0000] "GET /gate/auth/redirect?to=https%3A%2F%2Fspinnaker-dev.endpoints.cicd-spinnaker-dev-7961.cloud.goog%2F%23%2Fsearch HTTP/1.1" 200 2972
10.99.1.23 - - [18/Jun/2020:15:35:15 +0000] "POST /gate/saml/SSO HTTP/1.1" 302 -
10.99.1.23 - - [18/Jun/2020:15:35:16 +0000] "GET /auth/redirect?to=https%3A%2F%2Fspinnaker-dev.endpoints.cicd-spinnaker-dev-7961.cloud.goog%2F%23%2Fsearch HTTP/1.1" 404 322
10.99.1.23 - - [18/Jun/2020:15:35:20 +0000] "GET / HTTP/1.1" 200 17747
10.99.1.22 - - [18/Jun/2020:15:35:32 +0000] "GET / HTTP/1.1" 200 17747
10.99.1.22 - - [18/Jun/2020:15:35:34 +0000] "GET / HTTP/1.1" 200 17747
10.99.1.21 - - [18/Jun/2020:15:35:35 +0000] "GET / HTTP/1.1" 200 17747
10.99.1.21 - - [18/Jun/2020:15:35:37 +0000] "GET / HTTP/1.1" 200 17747 
```
### Cloud Provider(s):
Google Cloud Platform (hosted on GKE)

### Environment:
Spinnaker version 1.19.3 on GKE and backend is configured on GCS.

### Feature Area:
Provide redirect URI field for the SAML authentication which can redirect to /auth/* to gate properly.

### Description:
We have used spinnaker quickstart images to provision spinnaker which is working fine from few months. Now we are trying to configure SAML authentication and we are using PING identity for federated access provider. All the configuration done as per the documentation available here (https://www.spinnaker.io/setup/security/authentication/saml/). All the things works fine except this redirection. We tried changing logout URL, redirect URL in PING Identity but nothing really worked.
When I use <spinnaker-url>/gate to login to spinnaker it works fine. 

So I suspect its apache2 reverse proxy not routing URL properly. Can you please provide a feature to customize the proxy settings for apache using profiles just like we have for tomcat for gate?

Below is the security configuration.
```
security:
    apiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: https://<spinnaker-url>/gate
    uiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: https://<spinnaker-url>/
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: true
        metadataLocal: spinnaker.xml
        issuerId: spinnaker
        keyStore: saml.jks
        keyStorePassword: spinnaker
        keyStoreAliasName: saml
        serviceAddress: https://<spinnaker-url>/gate
        userAttributeMapping: {}
```
