### ISSUE TITLE
Spin 1.17 doesn't work with OAuth cachedToken

### ISSUE THREAD

**Issue by cablespaghetti** [spinnaker/spinnaker#5891]
### Issue Summary:
Spin 1.14 works fine with this config file, but Spin 1.17 does not despite there being no change in the documentation as far as I can see.
```
gate:
  endpoint: https://spinnaker-gate.mydomain.com
auth:
  enabled: true
  oauth2:
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    authUrl: https://accounts.google.com/o/oauth2/v2/auth
    scopes:
    - profile
    - email
    cachedToken:
      accesstoken: ${ACCESS_TOKEN}
      refreshtoken: ${REFRESH_TOKEN}
```
The error with 1.17
```
Could not deserialize config file with contents: gate:
  endpoint: https://spinnaker-gate.mydomain.com
auth:
  enabled: true
  oauth2:
    authUrl: https://accounts.google.com/o/oauth2/v2/auth
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    scopes:
      - profile
      - email
    cachedToken:
      accesstoken: ${ACCESS_TOKEN}
      refreshtoken: ${REFRESH_TOKEN}

, failing.
error unmarshaling JSON: while decoding JSON: json: unknown field "accesstoken"
```

If this is a documentation issue, the page I'm following is here: https://spinnaker.io/setup/spin/#access-and-refresh-token

Thanks

**Comment by silvez-dh** [comment]
Same issue here (spin version as well) but using Github instead

**Comment by Chinikins** [comment]
hi all, this is a documentation issue - if you update your configs to the following: https://github.com/spinnaker/spin/pull/262 it should begin working for ya'll

**Comment by ISPHOST** [comment]
I have issue with Login Failed:

File: .spin/config

```
  endpoint: https://spinnaker.myorg.com/gate/
auth:
  enabled: true
  oauth2:
    authUrl: https://accounts.google.com/o/oauth2/v2/auth
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    scopes:
      - profile
      - email
    cachedToken:
      access_token: google_access_token_from_GCLOUD
      token_type: bearer
      refresh_token: google_refresh_token_from_GCLOUD
  ldap: null
```

```
[me@centos-7]$ ./spin app ls
OAuth2 Authentication failed.
login failed
```
