### ISSUE TITLE
Halyard not allowing to map roles from OIDC, KeyCloak, in OAuth2 UserInfoMapping

### ISSUE THREAD

**Issue by shubhamc183** [spinnaker/spinnaker#5902]
### Cloud Provider(s): Kubernetes 
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Halyard
```
gcr.io/spinnaker-marketplace/halyard@sha256:d23153a44eef1ade80756ce6cc234ddbc33c5d8c4d49cfb2561ae6bd4528a314
Tags: 1.37.0, stable, 1.37.0-20200630110018, 1.37.0-20200630110018-slim
```
### Description:
I am trying to use OIDC, [Keycloak](https://www.keycloak.org/) for **authentication** and as well as **authorization**. Authentication is working fine and I am able to log in user from KeyCloak. I want to map `roles` from the `groups` value returned by the Keycloak.

I have confirmed from the keycloak that `group` is passed in the token.

```
    authn:
      oauth2:
        enabled: true
        client:
          clientId: spinnaker
          clientSecret: XXXXXXXXXXXXX
          accessTokenUri: https://XXXXXXXXXXXXX.com/auth/realms/XXXXXXXXXXXXX/protocol/openid-connect/token
          userAuthorizationUri: https://XXXXXXXXXXXXX.com/auth/realms/XXXXXXXXXXXXX/protocol/openid-connect/auth
          scope: openid roles email profile groups
          preEstablishedRedirectUri: https://XXXXXXXXXXXXXcom/login
        resource:
          userInfoUri: https://XXXXXXXXXXXXX.com/auth/realms/XXXXXXXXXXXXX/protocol/openid-connect/userinfo
        userInfoMapping:
          email: email
          firstName: given_name
          lastName: family_name
          username: preferred_username
          roles: groups
```
The `role:groups` mapping is important for me as I want to map to the `roles` from the `groups` to achieve authorization via OIDC. But while halyard deploy it's failing but I confirmed in Slack channel that it has worked and a lot of users have used it.

### `hal deploy apply`

```
bash-5.0$ hal deploy apply
- Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "roles" (class
  com.netflix.spinnaker.halyard.config.model.v1.security.OAuth2$UserInfoMapping),
  not marked as ignorable (4 known properties: "lastName", "firstName", "email",
  "username"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["security"]->com.netflix.spinnaker.halyard.config.model.v1.security.Security["authn"]->com.netflix.spinnaker.halyard.config.model.v1.security.Authn["oauth2"]->com.netflix.spinnaker.halyard.config.model.v1.security.OAuth2["userInfoMapping"]->com.netflix.spinnaker.halyard.config.model.v1.security.OAuth2$UserInfoMapping["roles"])
```

### Additional Details:
![image](https://user-images.githubusercontent.com/15362871/87295793-59d6d480-c523-11ea-9af2-5df02392761d.png)

**Comment by silvez-dh** [comment]
passing **--no-validate** parameter doesn't helps either...

**Comment by shubhamc183** [comment]
Even using **--no-validate** doesn't help.

```
bash-5.0$ hal deploy apply --no-validate
- Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "roles" (class
  com.netflix.spinnaker.halyard.config.model.v1.security.OAuth2$UserInfoMapping),
  not marked as ignorable (4 known properties: "lastName", "firstName", "email",
  "username"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["security"]->com.netflix.spinnaker.halyard.config.model.v1.security.Security["authn"]->com.netflix.spinnaker.halyard.config.model.v1.security.Authn["oauth2"]->com.netflix.spinnaker.halyard.config.model.v1.security.OAuth2["userInfoMapping"]->com.netflix.spinnaker.halyard.config.model.v1.security.OAuth2$UserInfoMapping["roles"])

- Failed to get deployment name.
bash-5.0$ 
```

**Comment by silvez-dh** [comment]
@shubhamc183 i was able to overcome the hal config check adding gate values directly into its profile file:
`.hal/default/profiles/gate-local.yml` 

The values where:

```
security:
  oauth2:
    userInfoMapping:
      email: email
      firstName: given_name
      lastName: family_name
      username: preferred_username
      roles: groups
    client:
      scope: openid,spinroles
```

Still playing a little bit around but at least roles are shown on spinnaker.

**Comment by silvez-dh** [comment]
>  --no-validate

@maggieneterval do you know if this parameter should skip this error and move forward in execution?

**Comment by shubhamc183** [comment]
My ~/.hal/config.yml

```
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: false
        userAttributeMapping: {}
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: false
```
~/.hal/default/profiles/gate-local.yml

```
security:
      oauth2:
        client:
          clientId: spinnaker
          clientSecret: XXXXXXXXXXXXXXXXXXXX
          userAuthorizationUri: https://XXXXXXXXXXXXXXXXXXXX/auth/realms/ZZZZZ/protocol/openid-connect/auth
          accessTokenUri: https://XXXXXXXXXXXXXXXXXXXX/auth/realms/ZZZZZ/protocol/openid-connect/token
          scope: roles,email,profile,groups,openid
          preEstablishedRedirectUri: https://YYYYY.com/login
        resource:
          userInfoUri: https://XXXXXXXXXXXXXXXXXXXX/auth/realms/ZZZZZ/protocol/openid-connect/userinfo
        userInfoMapping:
          email: email
          firstName: given_name
          lastName: family_name
          username: preferred_username
          roles: groups
        provider: KEYCLOAK
```
gate-local.yml is getting copied to ~/.hal/default/staging but spinnaker can be accessed without authn and authz.

**Then, I made ~/.hal/config.yml > security > enabled > true but no outh2 data in there. Ran `hal deploy apply`.**

Spinnaker is again accessed without any authentication. But when I am hitting the gate URL it's taking to keycloak fine.

gate-local.yml is getting copied into the gate pod(I checked).

Now even Authn is not working.

@silvez-dh can you share your ~/.hal/config `security` section? Thanks

**Comment by silvez-dh** [comment]
@shubhamc183, that's basicaly what is inside security session (from inside halyard pod, under .hal/config)

```
security:
  basic:
    enabled: true
  user: {}
  oauth2:
    enabled: true
    client:
      clientId: XXX
      clientSecret: XXX
      accessTokenUri: XXX
      userAuthorizationUri: XXX
    resource:
      userInfoUri: XXX
    userInfoMapping: {}
    provider: OTHER
```

and the remaining are inside gate-local.yml file like mentioned above. Maybe change provider to **OTHER**? The identation seems looks good also for you?

The files were copied inside gate pod (not merged inside one config file as i first expected:

```
find /opt/spinnaker/config/ -type f
/opt/spinnaker/config/..2020_07_17_16_35_29.430834081/gate-local.yml
/opt/spinnaker/config/..2020_07_17_16_35_29.430834081/spinnaker.yml
/opt/spinnaker/config/..2020_07_17_16_35_29.430834081/gate.yml
```
