### ISSUE TITLE
Spin CLI v1.17.0 - unable to authenticate with oauth2

### ISSUE THREAD

**Issue by hugocortes** [spinnaker/spinnaker#5913]
### Issue Summary:
I receive this error when attempting to authenticate using oauth2 on spin cli version 1.17.0:
```sh
OAuth2 Authentication failed.
login failed
```
If spin config has `cachedToken` object then spin cli will fail to serialize the config file and get this error:
```
error unmarshaling JSON: while decoding JSON: json: unknown field "accesstoken"
```

Downgrading to 1.14.0 using the same config file works just fine.

### Cloud Provider(s):
n/a

### Environment:
Spinnaker deployed on baremetal
spin cli v1.17.0

### Feature Area:
spin cli - authentication

### Description:
Here is the spin config file I've been using before upgrade to 1.17.0 which worked in the past:
```yaml
gate:
  endpoint: <gate api domain>
auth:
  enabled: true
  oauth2:
    tokenUrl: <idp token url>
    authUrl: <idp auth url>
    clientId: spinnaker
    clientSecret: ""
    scopes:
    - openid
    - email
    - profile
```

I also downgraded to 1.14.0 and successfully authenticated on spin cli as the `cachedToken` object was added to the auth object:
```yaml
auth:
...
...
    cachedToken:
      accesstoken: <access token>
      tokentype: bearer
      refreshtoken: <refresh token>
      expiry: 2020-07-15T06:38:12.017684167-07:00
```

After authenticating, I upgraded back to 1.17.0 to find out if I can use the cached token and skip authentication on 1.17.0 but then I received this error:
```sh
Could not deserialize config file with contents: gate:
  endpoint: <gate api domain>
auth:
  enabled: true
  oauth2:
    tokenUrl: <idp token url>
    authUrl: <idp auth url>
    clientId: spinnaker
    clientSecret: <client secret>
    scopes:
    - openid
    - email
    - profile
    cachedToken:
      accesstoken:  <1.14.0 access token>
      tokentype: bearer
      refreshtoken: <1.14.0 refresh token>
      expiry: 2020-07-15T06:38:12.017684167-07:00
  ldap: null
, failing.
error unmarshaling JSON: while decoding JSON: json: unknown field "accesstoken"
```

### Steps to Reproduce:
1. Create a spin config file using oauth2 for authentication and without `cachedToken`
2. Make any cli request, `spin application list`
3. Perform authentication steps prompted by spin cli and error will be shown

### Additional Details:
My identity provider does not log any error and the session is initiated in the identity provider's Spinnaker client when I provide the authorization code to spin cli.

**Comment by cwadley** [comment]
We are also seeing this issue

**Comment by Chinikins** [comment]
I originally got this error when the spacing in my file wasn't correct. Upon fixing the spacing, spin CLI parsed the token correctly.

**Comment by Chinikins** [comment]
This isn't actually broken just need to update your config to match the example given in https://github.com/spinnaker/spin/pull/262 and the cached token gets parsed correctly!

**Comment by hugocortes** [comment]
Thanks! Changing the keys in `cachedToken` object to snake case resolves the parsing error.

However, I'm still receiving the authentication failed error:
```
~ » ./spin app ls
OAuth2 Authentication failed.
login failed
```

My updated config:
```yaml
gate:
  endpoint: https://<gate url>
auth:
  enabled: true
  oauth2:
    tokenUrl: <token url>
    authUrl: <auth url>
    clientId: spinnaker
    clientSecret: <secret>
    scopes:
      - openid
      - email
      - profile
    cachedToken:
      access_token: "access token"
      token_type: bearer
      refresh_token: "refresh token"
      expiry: 2020-07-19T22:55:10.980528886-07:00
  ldap: null

```
