### ISSUE TITLE
nodeSelectors not getting repsected for deployment of Spinnaker

### ISSUE THREAD

**Issue by shubhamc183** [spinnaker/spinnaker#5916]
### Cloud Provider(s): Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

## Halyard
```
gcr.io/spinnaker-marketplace/halyard@sha256:d23153a44eef1ade80756ce6cc234ddbc33c5d8c4d49cfb2561ae6bd4528a314
Tags: 1.37.0, stable, 1.37.0-20200630110018, 1.37.0-20200630110018-slim
```

### Description:

I have used the Halyard configuration as

```
nodeSelectors:
   spinnaker: true
```

**But halyard as well all the microservices pods are not getting deployed on the nodes which have the label `spinnaker:true`.**

**Comment by shubhamc183** [comment]
Meanwhile, affinity can be used.
https://github.com/spinnaker/spinnaker/issues/5916

**Comment by awilkins-frel** [comment]
#5947 
This seem to related to another ticket.
Suggests a work around of using nodeSelector not nodeSelectors
I am trying to use spinnaker operator and this work around does not work for me as it failed validation when trying to use nodeSelector

There is also something wrong using affinity it seems to be validating against a key at the wrong level - eg it is checking that deploymentEnvironment.affinity.something.something matches the 3 known properties, when it should be checking deploymentEnvironment.affinity.something

**Comment by shubhamc183** [comment]
I have used `affinity` @awilkins-frel.

https://github.com/spinnaker/spinnaker.github.io/pull/1993/files

FYI: https://github.com/spinnaker/spinnaker.github.io/pull/1905

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by Hunter-Thompson** [comment]
Any updates on this? 

I am using both, `nodeSelectors` and `nodeAffinity`, still pods are being scheduled randomly.

```
    affinity:
      spin-clouddriver:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: service
                operator: In
                values:
                - spinnaker
    tolerations: {}
    nodeSelectors:
      service: spinnaker
 ```

**Comment by Hunter-Thompson** [comment]
@spinnakerbot remove-label to-be-closed

**Comment by shubhamc183** [comment]
I am using `nodeAffinity` and it's working fine.

```
    affinity:
      spin-clouddriver:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
    tolerations: {}
    nodeSelectors: {}
```

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by shubhamc183** [comment]
Closing this ticket due to inactivity.

**Comment by liorfranko** [comment]
@shubhamc183 can you share the config file?
I'm trying all the following options without any success:
```
halyard:
  additionalServiceSettings:
    clouddriver.yml:
      kubernetes:
        nodeSelector:
          intent: middleware
        nodeSelectors:
          intent: middleware  
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: intent
                  operator: In
                  values:
                  - middleware
          spin-clouddriver:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: intent
                    operator: In
                    values:
                    - middleware
kubectl -n spinnaker get configmaps spinnaker-spinnaker-service-settings -o yaml
apiVersion: v1
data:
  clouddriver.yml: |
    kubernetes:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: intent
                operator: In
                values:
                - middleware
        spin-clouddriver:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: intent
                  operator: In
                  values:
                  - middleware
      nodeSelector:
        intent: middleware
      nodeSelectors:
        intent: middleware
```

But the clouddrive pod boots without any nodeSelector or Affinity.

**Comment by shubhamc183** [comment]
```
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: TARGET_ACCOUNT_NAME
    imageVariant: SLIM
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    location: spinnaker
    customSizing:
      spin-clouddriver-caching:
        replicas: 6
      spin-clouddriver-ro:
        replicas: 2
      spin-clouddriver-ro-deck:
        replicas: 2
      spin-orca:
        replicas: 2
      spin-clouddriver-rw:
        replicas: 2
    sidecars: {}
    initContainers: {}
    hostAliases: {}
    affinity:
      spin-clouddriver:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-clouddriver-caching:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-clouddriver-ro:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
                - spin-clouddriver-ro
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-clouddriver-ro-deck:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
                - spin-clouddriver-ro-deck
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-clouddriver-rw:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
                - spin-clouddriver-rw
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-deck:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-echo:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-fiat:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-front50:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-gate:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-igor:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-orca:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
                - spin-orca
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-redis:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
      spin-rosco:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: cluster
                operator: In
                values:
                - spin-clouddriver-caching
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker
                operator: In
                values:
                - 'true'
```
