### ISSUE TITLE
Cannot bind docker image to custom k8s resource

### ISSUE THREAD

**Issue by mikekamornikov** [spinnaker/spinnaker#5926]
### Issue Summary:
I cannot deploy Strimzi `KafkaConnect` resource because image substitution doesn't work. The setup works just fine with services using `Deployment` resource.

### Cloud Provider(s):
- Kubernetes

### Environment:
- k8s manifest is a github-account-name artifacts
- docker image is a docker-registry artifact
- we have 2 params - commit and tag
### Feature Area:
- Pipelines

### Description:
The only documentation I could find is https://spinnaker.io/reference/artifacts/in-kubernetes-v2/#binding-artifacts-in-manifests. 
> The field spec.template.spec.containers.*.image always refers to a Docker image, so clearly it matches the artifact type docker/image

If this path is the only available one and it's not configurable we can't deploy custom resources in more or less manageable way. As I understand it's also a valid issue for regular k8s `Deployment` if you use init containers.

### Additional Details:

Spinnaker version: `2.19.8`

`KafkaConnect` resource example:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  # ...
spec:
  bootstrapServers: b1,b2,b3
  config:
    # ...
  image: quay.io/org/image
  version: 2.4.0
```

```
Exception ( Monitor Deploy )

The following required artifacts could not be bound: '[ArtifactKey(type=docker/image, name=quay.io/sugarcrm/kafka-connect, version=cxp-79c7e0764ac45b0adc8bdece6b453149980d8626c05b8f3afde0a5972f3e81d5, location=null, reference=quay.io/sugarcrm/kafka-connect:cxp-79c7e0764ac45b0adc8bdece6b453149980d8626c05b8f3afde0a5972f3e81d5)]'. Check that the Docker image name above matches the name used in the image field of your manifest. Failing the stage as this is likely a configuration error.
```
