### ISSUE TITLE
Halyard/Kubernetes NodeSelector documentation is innacurate

### ISSUE THREAD

**Issue by jaygorrell** [spinnaker/spinnaker#5947]
### Issue Summary:
[Documentation](https://spinnaker.io/reference/halyard/custom/#nodeselectors) calls for using the following to add a nodeSelector to Spinnaker components using service settings files:
```
kubernetes:
  nodeSelectors:
     exampleNodeKey: exampleNodeValue
```

However, the key that works is actually `nodeSelector`. Using this is a workaround, but it's difficult to discover.

In addition, the hal config file has `deploymentEnvironment.nodeSelectors`, which doesn't do anything. I suspect this should also be `nodeSelector` similar to the above, but that causes halyard to throw an error.

Tangentially related, the nodeSelector affinity also throws key errors with the following, meaning it can't be used as a viable alternative:
```
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: exampleNodeKey
                operator: In
                values:
                - exampleNodeValue
```
This results in halyard saying it didn't find one of the 3 allowed keys, but one of them is `nodeAffinity`.

### Cloud Provider(s):
AWS

### Environment:
Spinnaker 1.20.3
AWS / EKS

### Feature Area:
Halyard
Kubernetes
