### ISSUE TITLE
Halyard antiAffinity config not working

### ISSUE THREAD

**Issue by talbright** [spinnaker/spinnaker#5949]
### Issue Summary:

Halyard is not accepting antiAffinity config(s). PodAffinity and NodeAffinity configs are working.

### Cloud Provider(s): 

K8S v2

### Environment:

EKS

### Feature Area:

Halyard

### Description:

halyard isn't accepting `podAntiAffinity` configuration

### Steps to Reproduce:

```yaml
    affinity:
      clouddriver:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - store
            topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - storex
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: spinnaker.io/reserved
                operator: In
                values:
                - true
```
```
$ hal deploy apply --service-names=clouddriver,monitoring-daemon
- Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "labelSelector" (class
  com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig$WeightedPodAffinityTerm),
  not marked as ignorable (2 known properties: "weight", "podAffinityTerm"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["deploymentEnvironment"]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment["affinity"]->java.util.LinkedHashMap["clouddriver"]->com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig["podAffinity"]->com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig$PodAffinity["preferredDuringSchedulingIgnoredDuringExecution"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig$WeightedPodAffinityTerm["labelSelector"])

- Failed to get deployment name.
```
Note: if the `antiAffinity` clause is removed the deploy works as expected.

### Additional Details:

Looks like https://github.com/spinnaker/halyard/pull/1273 left out class definitions for `antiAffinity`: https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/AffinityConfig.java#L29-L45

See also: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

* An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 
* Before you open an issue, please [check if a similar issue already exists](https://github.com/spinnaker/spinnaker/issues) or has been closed before.
* Make sure you have read through the [Spinnaker FAQ](https://www.spinnaker.io/community/faqs/) and [Halyard FAQ](https://www.spinnaker.io/setup/quickstart/faq/) to provide as much information as possible.

Descriptions:

* Issue Summary: A brief description of what you're seeing.
* Cloud Provider: AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc. Please assign a label from the right so your issue can be properly sorted.
* Environment: As much information about your Spinnaker environment and configuration that might be relevant to the issue. For example: "I am running Spinnaker using the Amazon images to deploy into AWS and GCP."
* Feature Area: Notifications, Pipelines, UI, Jenkins, etc. Please assign a label from the right so your issue can be properly sorted.
* Description: The behavior you expect to see, and the actual behavior.
* Steps to reproduce: Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.
* Additional Details: Additional information such as screenshots and exception logs.

**Comment by perek** [comment]
The class has the antiaffinity here: https://github.com/spinnaker/halyard/blob/master/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/AffinityConfig.java#L25

This config works fine for us so either there is a new regression in halyard or something else is awry:
```

spin-rosco:
--
  | podAntiAffinity:
  | requiredDuringSchedulingIgnoredDuringExecution:
  | - labelSelector:
  | matchExpressions:
  | - key: app.kubernetes.io/name
  | operator: In
  | values:
  | - rosco
  | topologyKey: kubernetes.io/hostname


````

**Comment by perek** [comment]
Preferred expects a weighted term iirc: https://github.com/spinnaker/halyard/blob/75bd3219dfaf0d8b0f735f29e5a9f6db70c3a338/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/AffinityConfig.java#L81

**Comment by perek** [comment]
see: https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/pods/pod-with-node-affinity.yaml

**Comment by perek** [comment]
try the format:
```
podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: security
              operator: In
              values:
              - S2
          topologyKey: failure-domain.beta.kubernetes.io/zone
```

**Comment by talbright** [comment]
Sorry to be a bother, you are absolutely right, my syntax was off from the spec. I went with something like:
 
```yaml
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - clouddriver
                  - front50
                  - fiat
              topologyKey: kubernetes.io/hostname
```

Thanks for taking a look!
