### ISSUE TITLE
Oauth - Redirects loop when userInfoRequirements is set for authn EXTERNAL provider

### ISSUE THREAD

**Issue by silvez-dh** [spinnaker/spinnaker#5960]
### Issue Summary:
Whenever **userInfoRequirements** parameter is set using authn EXTERNAL provider plus oauth, spinnaker authentication falls into an endless 302 loop whereas a HTTP 403 (or some landing page) where expected

### Cloud Provider(s):
k8s

### Environment:
Spinnaker version: 1.21.x (deployed via helm), backend S3 + redis
Running on EKS cluster
Oauth provider is OTHER (keycloak)
Authz provider type is EXTERNAL (keycloak)

### Feature Area:
gate

### Description:
Whenever **userInfoRequirements** parameter is set using authn EXTERNAL provider plus oauth, spinnaker authentication falls into an endless 302 loop whereas a HTTP 403 (or some landing page) where expected

No matter which value *userInfoRequirements* has (or authn configuration combination is set) it falls into an endless redirect loop. An authn configuration that supposedly should work:

.hal/config

```
    authn:          
      oauth2:     
        enabled: true
        client:                       
          clientId: ***
          clientSecret: ***
          accessTokenUri: https://my_identity_provider.com/access_token
          userAuthorizationUri: https://my_identity_provider.com/authorize
        userInfoRequirements:
          groups: spinnaker_allowed
        resource:                  
          userInfoUri: https://my_identity_provider.com/protocol/openid-connect/userinfo
        userInfoMapping: {}       
        provider: OTHER
```

./.hal/default/profiles/gate-local.yml

```
security:
  oauth2:
    userInfoMapping:
      email: email
      firstName: given_name
      lastName: family_name
      username: preferred_username
      roles: groups
    client:
      scope: openid,spinroles
server:
  tomcat:
    httpsServerPort: X-Forwarded-Port
    internalProxies: .*
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
```

### Steps to Reproduce:
Setup spinnaker authn via oauth (using OTHER provider), make sure it works, then set the *userInfoRequirements* parameter (to what is available/configured into the identity provider)

### Additional Details:

Gate logs (most relevant one)

```
2020-08-04 13:58:33.046  WARN 1 --- [0.0-8084-exec-8] c.n.s.gate.filters.FiatSessionFilter     : Authenticated user was not present in authenticated request. Check authentication settings.
```

### Observations:
Disabling authz and/or removing tomcat proxy configuration didn't worked either

### Probably similar issues:
https://github.com/spinnaker/spinnaker/issues/5514
https://github.com/spinnaker/spinnaker/issues/5794
https://github.com/spinnaker/spinnaker/issues/5918
