### ISSUE TITLE
Application not really being deleted if there are clusters left

### ISSUE THREAD

**Issue by billcchung** [spinnaker/spinnaker#5985]
### Issue Summary:
Delete application did not really delete the application if there are `clusters` left.

### Cloud Provider(s):
kubernetes (GKE)

### Environment:
Spinnaker 1.19.8
Kubernetes 1.16.3

### Feature Area:
UI

### Description:
When there are still `clusters` (from https://${spinnaker-api}/applications/${application-name}/clusters) left, e.g., 
```
{"account":["service service-name"]}
```
kubernetes manifest is like:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    artifact.spinnaker.io/location: k8s-namespace
    artifact.spinnaker.io/name: service-name
    artifact.spinnaker.io/type: kubernetes/service
    moniker.spinnaker.io/application: spin-application-name
    moniker.spinnaker.io/cluster: service service-name
  labels:
    app.kubernetes.io/managed-by: spinnaker
    app.kubernetes.io/name: spin-application-name
  name: service-name
  namespace: k8s-namespace
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: app
  sessionAffinity: None
  type: ClusterIP
```
this is hidden from the `clusters` tab form spinnaker UI, and the `delete applications` becomes available. 

I know if there are other clusters like replicasets, the `delete application` will not be available, instead it'll show `You cannot delete this application because it has server groups.`, but what I'm seeing is it's available and clicking on it will succeed but ended up with not really deleting the application:
<img width="1531" alt="Screen Shot 2020-08-19 at 11 15 12" src="https://user-images.githubusercontent.com/5371682/90595770-8b307780-e228-11ea-9a7e-8475a620cfcf.png">
but the application is not actually deleted, it just becomes `unconfigured`
