### ISSUE TITLE
Kubernetes Projected Volume manifests aren't supported by Versioning

### ISSUE THREAD

**Issue by kskewes** [spinnaker/spinnaker#6002]
### Issue Summary:

[Kubernetes Project Volumes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-projected-volume-storage/) are a clean way to mount multiple files (via `ConfigMap` and or `Secret`) to a common parent directory.

Spinnaker supports versioning `ConfigMap` and `Secret` versioning via [Strategy](https://spinnaker.io/reference/providers/kubernetes-v2/#strategy) annotation `strategy.spinnaker.io/versioned: "true|false"`

At deploy time, Spinnaker will add a version suffix to the ConfigMap and then hydrate a Deployment's reference to the new ConfigMap.

This doesn't work for Projected Volumes however.

### Cloud Provider(s):

Kubernetes

### Environment:

Spinnaker 1.21 on Kubernetes

### Feature Area:

Clouddriver

### Steps to Reproduce:

1. Create a configmap
2. Create a deployment that uses a projected volume for this configmap
3. deploy - note that the configmap will be versioned but the deployment won't have correct reference to it

```
...
kind: Deployment
<snip>
      volumes:
      - name: spinnaker-config
        projected:
          sources:
          - configMap:
              name: spinnaker
              items:
              - key: spinnaker.yml
                path: spinnaker.yml
              - key: spinnaker-local.yml
                path: spinnaker-local.yml
          - configMap:
              name: orca
              items:
              - key: orca.yml
                path: orca.yml
```

### Additional Details:

It looks like we need to add some additional places to look for the configmap reference here:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/Replacer.java#L168

```
  private static final Replacer CONFIG_MAP_PROJECTED_VOLUME =
      builder()
          .path("$..spec.template.spec.volumes.[?].projected.sources.[?].configMap.name")
          .replaceFilter(a -> filter(where("configMap.name").is(a.getName())))
          .type(KubernetesArtifactType.ConfigMap)
          .build();

  private static final Replacer SECRET_PROJECTED_VOLUME =
      builder()
          .path("$..spec.template.spec.volumes.[?].projected.sources.[?].secret.name")
          .replaceFilter(a -> filter(where("secret.name").is(a.getName())))
          .type(KubernetesArtifactType.Secret)
          .build();

...

  public static Replacer configMapProjectedVolume() {
    return CONFIG_MAP_PROJECTED_VOLUME;
  }

  public static Replacer secretProjectedVolume() {
    return SECRET_PROJECTED_VOLUME;
  }
```

And extend the test here: https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/test/groovy/com/netflix/spinnaker/clouddriver/kubernetes/op/handler/KubernetesDeploymentHandlerSpec.groovy#L70
