### ISSUE TITLE
Orca: excessive MySQL DB usage for pipelines with many stages

### ISSUE THREAD

**Issue by alex-lee2** [spinnaker/spinnaker#6006]
### Issue Summary:
When running Spinnaker a pipeline with a large number of stages (~200), all parallel stages each calling a sub pipeline, Orca seems to be making ~200-300 calls per second to MySQL DB for the entire pipeline execution detail for the main pipeline. This results in high DB bandwidth saturating the 10G DB networking

### Cloud Provider(s):
On Premise

## Feature Area:
Orca

## Environment:
* Kubernetes + Halyard
* Bare Metal MySQL

## Description:
When running a pipeline that has ~200 parallel stages with each stage calling another pipeline, Orca appears to be making ~200-300 calls per second to MySQL DB querying the entire pipeline. The contents of each query is ~22MB which includes the pipeline JSON itself and all the deployed Kubernetes manifests in the output.  This results in up to 10Gbps of network usage on the MySQL DB, essentially taking it down.

We noticed in Spinnaker documentation that Orca polls the queue every 10ms - which seems somewhat aggressive and was wondering if it’s configurable. Could the polling be the cause of the DB usage?

https://spinnaker.io/guides/developer/service-overviews/orca/

## Steps to Reproduce:
1. Create 1 “main pipeline” that calls ~200 sub pipelines in parallel
2. Sub pipeline is a simple Bake → Deploy. Actual manifest can be a small Deployment + Service.
3. Observe DB usage when this main pipeline runs.

## Main Concerns:
1. What exactly does each 10ms poll do with regards to its interactions with the database?
2. Can the 10ms interval configurable be made configurable?
3. Is there a potential bug in Orca’s operation that’s causing it excessively pull data from the database for such style of pipelines with many stages?

## Additional Details:

* When we tested running each of the sub pipelines individually without the main pipeline that calls all of it, the database usage was much lower. So something with the main pipeline keeping track of all the sub pipelines is causing the issues.

Some of our Orca settings:
```
...
  connectionPools:
    default:
      default: true
      jdbcUrl: ...
      ...
      maxPoolSize: 30
...

keiko:
  queue:
    handlerCorePoolSize: 20
    handlerMaxPoolSize: 30
    fillExecutorEachCycle: false
    requeueDelaySeconds: 10
...
```
