### ISSUE TITLE
Deck: some docker image tags are invalid

### ISSUE THREAD

**Issue by micnncim** [spinnaker/spinnaker#6021]
### Issue Summary:

Some Deck docker image tags for `gcr.io/spinnaker-marketplace/deck` looks invalid. When I deployed `gcr.io/spinnaker-marketplace/deck:spinnaker-1.20.8`, I ran the following errors:

![Screenshot 2020-09-03 at 13 17 41](https://user-images.githubusercontent.com/21333876/92072687-c87e3300-edec-11ea-8548-3b49fd460367.png)

### Environment:

- GKE

### Feature Area:

- Deck

### Description:

The errors shouldn't appear because Spinnaker `1.20.x` doesn't stop supporting Kubernetes Provider V1. And I've avoided the error when I deployed `gcr.io/spinnaker-marketplace/deck:3.1.0-20200502170018`. So I guess the tags are invalid.

### Steps to Reproduce:

Deploy Spinnaker with Kleat and the following image tags specified `kustomization.yaml`:

```yaml
images:
- name: gcr.io/spinnaker-marketplace/clouddriver
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/deck
  newTag: 3.1.0-20200502170018
- name: gcr.io/spinnaker-marketplace/echo
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/fiat
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/front50
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/gate
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/igor
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/kayenta
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/monitoring-daemon
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/orca
  newTag: spinnaker-1.20.8
- name: gcr.io/spinnaker-marketplace/rosco
  newTag: spinnaker-1.20.8
```
