### ISSUE TITLE
Amazon AWS Pub/Sub 403 Unauthorized

### ISSUE THREAD

**Issue by nikita-tkachov** [spinnaker/spinnaker#6026]
### Issue Summary:
I am following the instructions on https://spinnaker.io/setup/triggers/amazon/ to setup the Pub/Sub triggers for AWS.

I followed all of the instructions, and my queue appears to be initializing from the "echo" logs, but I am receiving a 403 error.

I looked at the PR that created this pub/sub (https://github.com/spinnaker/echo/pull/231), and it appears that there isn't a way to set credentials that the Pub/Sub will use? I do have an AWS provider setup, so I would assume it uses those credentials?

My environment is running on EKS, so maybe it doesn't have access to SQS?

### Cloud Provider(s):
AWS, Kubernetes

### Environment:
Running Spinnaker on a Distributed Kubernetes environment using AWS EKS.

### Feature Area:
Pub/Sub AWS triggers

### Description:
I expect the Pub/Sub to initialize without permission issues, but I get a 403 error for SQS.

### Steps to Reproduce:
I think if you just set up Spinnaker with EKS, it won't let you access the queue?

### Additional Details:
Exception from "echo"

`2020-09-05 01:06:36.284  INFO 1 --- [           main] c.n.s.e.p.aws.SQSSubscriberProvider      : Bootstrapping SQS for SNS topic: arn:aws:sns:us-west-2:xxxxx:spinnaker-sns
2020-09-05 01:06:36.287  INFO 1 --- [           main] ubsubProperties$AmazonPubsubSubscription : Using message format: S3 to process artifacts for subscription: environment-update
2020-09-05 01:06:36.610 DEBUG 1 --- [           main] c.n.s.e.p.aws.SQSSubscriberProvider      : Created worker for subscription: environment-update
2020-09-05 01:06:36.616  INFO 1 --- [pool-3-thread-1] c.n.s.echo.pubsub.aws.SQSSubscriber      : Starting arn:aws:sqs:us-west-2:xxxxx:spinnaker-sqs/SQSSubscriber
2020-09-05 01:06:53.120 ERROR 1 --- [pool-3-thread-1] c.n.s.echo.pubsub.aws.SQSSubscriber      : Error initializing queue ARN{arn='arn:aws:sqs:us-west-2:xxxx:spinnaker-sqs'}
com.amazonaws.services.sqs.model.AmazonSQSException: Access to the resource https://sqs.us-west-2.amazonaws.com/ is denied. (Service: AmazonSQS; Status Code: 403; Error Code: AccessDenied; Request ID: b3400bea-f04d)`

**Comment by atyutyunnik** [comment]
I think it must be the role that lacks permission to access the SQS. Does your worker node's or corresponding service account's role in EKS role have something like this below?
```
        - PolicyName: <your SQS policy name>
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - sqs:*
              Resource: <your SQS resource>

            - Effect: Allow
              Action:
                - kms:GenerateDataKey
                - kms:Decrypt
              Resource: "*"
```
