### ISSUE TITLE
Unable to add Jfrog Artifactory as docker-resgistry for Installation of Spinnaker in Air-gapped Server.

### ISSUE THREAD

**Issue by vividly789** [spinnaker/spinnaker#6046]
### Issue Summary:
Unable to add **Jfrog Artifactory** as docker-resgistry for the Installation of Spinnaker in **Air-gapped** Server and halyard is trying to connect to Internet for version verification.

### Cloud Provider(s):
On-prem

### Environment:
Dev Env (POC)

### Feature Area:
Spinnaker Air-gap Installation 

### Description:
Hello team,
I am actually doing a **POC** with Spinnaker (CD-Tool) for deploying an app in our **air-gapped** environment. 
On that, I am trying to install Spinnaker 1.20.7 version in my **air-gapped** server.
I am leveraging the **BOMs** for that with halyard docker container.
But I am unable to add my Jfog Artifactory as a docker-registry where I have downloaded all the spinnaker services docker-images (dependencies).
When i fire **hal deploy apply** command, halyard tries to connect to the internet for version verification.
But I have already, disabled read from GCR and also to set BOMs to read from local filesystem, i have ran 
**hal config version edit --version local:1.20.7**  command.
I have attached the screenshot with the error messages and the folder structure of BOMS.
Can anybody please help me with this?

### Additional Details:
**This is what I get when I try to add my Jfrog Artifactory as a custom registry!**

```
bash-5.0$ hal config provider docker-registry account add my-docker-registry \
     --address docker-dev-artifactory.*****.com \
     --repositories docker-images-dev/spinnaker \
     --username niraj.gurung \
     --password
Your docker registry password: 
+ Get current deployment
  Success
- Add the my-docker-registry account
  Failure
Validation in
  default.provider.dockerRegistry.my-docker-registry:
! ERROR Unable to fetch tags from the docker repository:
  docker-images-dev/spinnaker, docker-dev-artifactory.*****.com: Try again
? Can the provided user access this repository?

- WARNING None of your supplied repositories contain any  #tags.
  Spinnaker will not be able to deploy any docker images.
? Push some images to your registry.

- Failed to add account my-docker-registry for provider
  dockerRegistry.

```

**Also, When I run  #(hal deploy apply), I get the following error!**

```
bash-5.0$ hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Validation in default.features:
- WARNING Field Features.artifacts not supported for Spinnaker
  version local:1.20.7: Artifacts are now enabled by default.
? You no longer need this.

Validation in default.stats:
- INFO Stats are currently ENABLED. Usage statistics are being
  collected. Thank you! These stats inform improvements to the product, and that
  helps the community. To disable, run `hal config stats disable`. To learn more
  about what and how stats data is used, please see
  https://www.spinnaker.io/community/stats.

Validation in default.provider.dockerRegistry:
- WARNING Provider dockerRegistry is enabled, but no accounts have
  been configured.

+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Validation in Global:
! ERROR Could not load "versions.yml" from config bucket:
  www.googleapis.com.

- Failed to deploy Spinnaker.

```

**Also this is how my BOMs looks like for 1.20.7 version!**

```
version: 1.20.7                                                                                                                                                                 
timestamp: '2020-07-22 20:14:30'                                                                                                                                                
services:                                                                                                                                                                       
  echo:                                                                                                                                                                         
    version: local:.2.12.1-20200507020017                                                                                                                                       
    commit: 7b04fb3d80dacba05dad29b754615a546168c8cc                                                                                                                            
  clouddriver:                                                                                                                                                                  
    version: local:6.9.3-20200624125711                                                                                                                                         
    commit: f19e19583bc3981ebf7b74342ca01b3febb5c8b3                                                                                                                            
  deck:                                                                                                                                                                         
    version: local:3.1.2-20200601092739                                                                                                                                         
    commit: 0631f28ff743a30577e64c9fe13f813fe30271fa                                                                                                                            
  fiat:                                                                                                                                                                         
    version: local:1.11.0-20200428134356                                                                                                                                        
    commit: c88008c3a1359c445eee8cff23184e5484e472a9                                                                                                                            
  front50:                                                                                                                                                                      
    version: local:0.23.2-20200617020018                                                                                                                                        
    commit: e2487aa10b27d38da1d4dc3d5027fbed05ab7c5c                                                                                                                            
  gate:                                                                                                                                                                         
    version: local:1.16.1-20200522020017                                                                                                                                        
    commit: b1b14ffb59c0de6fb975aea7a003f0a8332e5c79                                                                                                                            
  igor:                                                                                                                                                                         
    version: local:1.10.1-20200722161347                                                                                                                                        
    commit: b7cfb02f8dc5d4e9d3653424669746eb37ebfe9e                                                                                                                            
  kayenta:                                                                                                                                                                      
    version: local:0.15.1-20200509020016                                                                                                                                        
    commit: f3af8422684b1c95eced83020e14c8e27ed7b466                                                                                                                            
  orca:                                                                                                                                                                         
    version: local:2.14.3-20200625020222                                                                                                                                        
    commit: 7ce831e4579cbb9d366937da0fe436d7bb859a63                                                                                                                            
  rosco:                                                                                                                                                                        
    version: local:0.19.0-20200428134356                                                                                                                                        
    commit: 32481f1ed3532ac802cb9dc9cff719a480f63a20                                                                                                                            
  defaultArtifact: {}                                                                                                                                                           
  monitoring-third-party:                                                                                                                                                       
    version: local:0.17.0-20200501020017                                                                                                                                        
    commit: 226f54ffe8a49df95af290bcd57aa0c2f225ed36                                                                                                                            
  monitoring-daemon:                                                                                                                                                            
    version: local:0.17.0-20200501020017                                                                                                                                        
    commit: 226f54ffe8a49df95af290bcd57aa0c2f225ed36                                                                                                                            
dependencies:                                                                                                                                                                   
  redis:                                                                                                                                                                        
    version: local:2:2.8.4-2                                                                                                                                                    
  consul:                                                                                                                                                                       
    version: local:0.7.5                                                                                                                                                        
  vault:                                                                                                                                                                        
    version: local:0.7.0                                                                                                                                                        
artifactSources:                                                                                                                                                                
  dockerRegistry: docker-dev-artifactory.******.com
```
