### ISSUE TITLE
Custom Job Stages broken after upgrade to 1.22.x

### ISSUE THREAD

**Issue by dil-dbakker** [spinnaker/spinnaker#6052]
### Issue Summary:
We are currently unable to upgrade our prod spinnaker instance to 1.22.x due to issues with our custom job stages. 

### Cloud Provider(s):
On Prem - Kubernetes

### Environment:
Self hosted spinnaker on Kubernetes

### Feature Area:
Orca

### Description:
Expected: After upgrade our custom job stages in our templates can be saved and run
Actual: When running a custom job stage we get the following error message: 

`Exception`
`Cannot invoke method split() on null object`

### Steps to Reproduce:
Create a Custom Job Stage containing a parameter with no mapping attribute.
Run this stage in a pipeline.

### Additional Details:
Here is an example of one of our existing Custom Jobs that works in Spinnaker 1.20.x but is broken in 1.22.x

```
- label: Send RFC Email
        type: rfcEmail
        description: Send a RFC for a deployment
        cloudProvider: kubernetes
        account: test-account
        credentials: test-account
        application: ${#currentStage()['context']['parameters']['application']}
        waitforCompletion: true
        parameters:
          - name: application
            label: Spinnaker app
            description: Spinnaker application
          - name: appVersion
            label: Application version
            description: The version of the application being deployed
          - name: ccAddress
            label: CC recipient for the RFC email
            description: Email address to CC the RFC email to
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            labels:
              type: tests
            generateName: send-rfc-email-${#currentStage()['context']['parameters']['application']}-
            namespace: rfc-email
          spec:
            backoffLimit: 2
            template:
              metadata:
                labels:
                  type: tests
              spec:
                containers:
                  - command:
                      - /script/send-rfc-email.sh
                    env:
                      - name: SCRIPT_APP_NAME
                        value: ${#currentStage()['context']['parameters']['application']}
                      - name: SCRIPT_APP_VERSION
                        value: ${#currentStage()['context']['parameters']['appVersion']}
                      - name: SCRIPT_CC_ADDRESS
                        value: ${#currentStage()['context']['parameters']['ccAddress']}
                    image: "namshi/smtp:latest"
                    name: send-rfc-email
                    volumeMounts:
                      - mountPath: /script/send-rfc-email.sh
                        name: send-rfc-email
                        subPath: send-rfc-email.sh
                restartPolicy: Never
                volumes:
                  - configMap:
                      defaultMode: 511
                      name: send-rfc-email
                    name: send-rfc-email
```

Here is a previous discussion related to this issue [https://github.com/spinnaker/spinnaker/issues/5147](https://github.com/spinnaker/spinnaker/issues/5147)
