### ISSUE TITLE
Documentation is wrong/missing. Spinnaker Active Directory integration doesn't work as documented.

### ISSUE THREAD

**Issue by tirelibirefe** [spinnaker/spinnaker#6060]
### Issue Summary:

Documentation is wrong/missing. Spinnaker Active Directory integration doesn't work as documented.

### Cloud Provider(s):
On-prem Kubespray-Kubernetes on vSphere 6.7U3

### Environment:
Halyard works in Docker container. gcr.io/spinnaker-marketplace/halyard:stable is used.
Nginx Ingress controller with custom cert is used.
Kubernetes distributed installation steps were followed.
as storage provider, on-prem Minio in the same Kubernets is used.
hal config version is 1.22.1

### Feature Area:
LDAP/Active Directory integration.

### Description:
I did whatever recommended here >>> https://spinnaker.io/setup/security/authentication/ldap/ but Spinnaker cannot authenticate:

`[LDAP: error code 49 - 80090308: LdapErr: DSID-0C090436, comment: AcceptSecurityContext error, data 52e, v4563]; nested exception is javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C090436, comment: AcceptSecurityContext error, data 52e, v4563]`

![image](https://user-images.githubusercontent.com/71238946/93735913-40b76780-fbe7-11ea-8660-a981b5ff6e3f.png)

### Steps to Reproduce:
![image](https://user-images.githubusercontent.com/71238946/93735231-f3d29180-fbe4-11ea-9cfd-d14c83100699.png)

```
hal config security authn ldap edit \
  --manager-dn 'CN=spin_svc,OU=users,OU=mydomain,O=io' \
  --user-search-filter '(&(objectClass=user)(sAMAccountName={0}))' \
  --url ldap://192.168.215.4:389/
```

`hal config security authn ldap enable`

`hal config security authn ldap edit --manager-password`

**gate.yml**

```
ldap:
  enabled: true
  url: ldap://192.168.215.4:389/
  userSearchFilter: (&(objectClass=user)(sAMAccountName={0}))
  managerDn: CN=spin_svc,OU=users,OU=mydomain,O=io
  managerPassword: super-secret-password
```

if I configure as  `url: ldap://192.168.215.4:389/searchbase` , gate pod doesn't start.
