### ISSUE TITLE
Halyard allows two same Helm Provider with the same name

### ISSUE THREAD

**Issue by shubhamc183** [spinnaker/spinnaker#6074]
### Cloud Provider(s): Kubernetes
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.10", GitCommit:"1bea6c00a7055edef03f1d4bb58b773fa8917f11", GitTreeState:"clean", BuildDate:"2020-02-11T20:13:57Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-f459c0", GitCommit:"f459c0672169dd35e77af56c24556530a05e9ab1", GitTreeState:"clean", BuildDate:"2020-03-18T04:24:17Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

### Halyard
```
gcr.io/spinnaker-marketplace/halyard@sha256:d23153a44eef1ade80756ce6cc234ddbc33c5d8c4d49cfb2561ae6bd4528a314
Tags: 1.37.0, stable, 1.37.0-20200630110018, 1.37.0-20200630110018-slim
```

### Description:
**As of now, no `HelmAccountValidator` is implemented which allows having more than one HELM provider with the same name.**

By mistakenly I have use a-helm-charts and halyard allowed it even when I do ```hal deploy apply```

```
hal config artifact helm account add a-helm-charts --repository https://MY_ORG/repository/helm-charts-a/ --username=USERNAME1 --password=PASSWORD1
hal config artifact helm account add a-helm-charts --repository https://MY_ORG/repository/helm-charts-b/ --username=USERNAME2 --password=PASSWORD2
```

~\.hal\config

```
    helm:
      enabled: true
      accounts:
      - name: a-helm-charts
        repository: https://MY_ORG/repository/helm-charts-1/
        username: USERNAME1
        password: PASSWORD1
      - name: a-helm-charts
        repository: https://MY_ORG/repository/helm-charts-2/
        username: USERNAME2
        password: PASSWORD2
```
