### ISSUE TITLE
Echo not using IAM Role for Service Account for encrypted configuration secrets

### ISSUE THREAD

**Issue by tompiscitell** [spinnaker/spinnaker#6089]
### Issue Summary:
When fetching encrypted configuration values from AWS Secrets Manager, echo is using the IAM role of the EC2 instance instead of assuming the IAM role of the k8s service account. 

### Cloud Provider(s):
AWS

### Environment:
Running Spinnaker 1.22.1 deployed on EKS 1.17.

### Feature Area:
Secrets 

### Description:
Echo  is using the IAM role of the EC2 instance, not the k8s service account when fetching encrypted configuration values. I turned up logging and noticed this:

```
2020-10-01 13:33:40.874 DEBUG 1 --- [           main] c.a.auth.AWSCredentialsProviderChain     : Unable to load credentials from WebIdentityTokenCredentialsProvider: To use assume role profiles the aws-java-sdk-sts module must be on the class path.
```

Checking out the container, I see that the sts jar is not in the class path:

```
spinnaker@ce1e81386e89:/$ ls /opt/echo/lib/ | grep aws
aws-java-sdk-core-1.11.802.jar
aws-java-sdk-kms-1.11.802.jar
aws-java-sdk-s3-1.11.802.jar
aws-java-sdk-secretsmanager-1.11.802.jar
aws-java-sdk-sns-1.11.802.jar
aws-java-sdk-sqs-1.11.802.jar
echo-pubsub-aws.jar
kork-aws-7.59.0.jar
kork-pubsub-aws-7.59.0.jar
kork-secrets-aws-7.59.0.jar
spectator-ext-aws-0.103.0.jar
spinnaker@ce1e81386e89:/$ exit
```

### Steps to Reproduce:
1. Configure an [IAM Role for a k8s service account in EKS](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) 
2. Assign that service account to the echo deployment
3. Set a configuration item to an encrypted value. In my deployment, `slack.token`

### Additional Details:

I confirmed adding the sts jar fixes this by adding `com.amazonaws:aws-java-sdk-sts` as a dependency of echo. Though I think the "right" fix would be to add it to kork instead.

**Comment by kskewes** [comment]
Interesting find. We use IRSA for clouddriver and used to for front50. I guess they have different dependencies listed in Gradle.
Agree kork might be good to enable consistent behavior unless there's a reason otherwise?

I didn't realize Secrets Manager was supported and is something we might change to. Can you please provide an example secure string to use in echo.yaml so I can see format?

**Comment by tompiscitell** [comment]
Sure. Here is what is what is in my `.hal/default/config`:
```
notifications:
    slack:
      enabled: true
      botName: spinnaker-slack
      token: encrypted:secrets-manager!r:us-west-2!s:some-aws-secret
```

Which results in this in `echo.yml`:
```
slack:
  enabled: true
  botName: spinnaker-slack
  token: encrypted:secrets-manager!r:us-west-2!s:some-aws-secret
```

**Comment by tompiscitell** [comment]
FWIW Gate has the same problem. Just ran into it when setting up OAuth. Here is a snipped from `.hal/default/config`
```
authn:
      oauth2:
        enabled: true
        client:
          clientId: REDACTED
          clientSecret: encrypted:secrets-manager!r:us-west-2!s:another-aws-secret
```

and like Echo, no sts jar:
```
bash-5.0$ ls /opt/gate/lib | grep aws
aws-java-sdk-core-1.11.802.jar
aws-java-sdk-kms-1.11.802.jar
aws-java-sdk-s3-1.11.802.jar
aws-java-sdk-secretsmanager-1.11.802.jar
kork-secrets-aws-7.59.0.jar
```

I've been playing wack-a-mole with this problem by building custom service containers w. the missing jar for our Spinnaker deployment. I'll open a PR to add the dependency to Kork-secrets later today.
