### ISSUE TITLE
Deploy CronJob Manifest Issue : Unable to bind docker image to Cronjob

### ISSUE THREAD

**Issue by sgrmgj777** [spinnaker/spinnaker#6132]
### Issue Summary:
Cannot bind docker image artifact as part of CronJob through Spinnaker UI. It does not replace the specific image tag specified in the configuration.

**_Exception ( Monitor Deploy )
The following required artifacts could not be bound: '[ArtifactKey(type=docker/image, name=gcr.io/myproject/abc-job, version=, location=null, reference=gcr.io/myproject/abc-job)]'. Check that the Docker image name above matches the name used in the image field of your manifest. Failing the stage as this is likely a configuration error._**
### Cloud Provider(s):
Google Cloud - Google Kubernetes Engine

### Environment:
GKE - I am running Spinnaker using the images in google container registry to deploy to GKE.
Spinnaker version - 1.22.2
### Feature Area:
spinnaker/clouddriver

### Description:
While deploying CronJob through Spinnaker (using the - following recommended halyard option)
```
name: my-k8s-v2-acccount
  customResources:
  - kubernetesKind: cronJob
```

I am unable to bind a docker image to the cronjob - my cronjob manifest looks like the following - 
```
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: dev
  name: abc-job
spec:
  schedule: "0 */8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          name: abc-job
          namespace: dev
        spec:
          containers:
          - name: abc-job-container
            image: gcr.io/myproject/abc-job
            volumeMounts:
              - name: config-volume
                mountPath: /config
                readOnly: true
          volumes:
            - name: config-volume
              configMap:
                name: abc-job
                items:
                  - key: application.yaml
                    path: application.yaml
          restartPolicy: Never
```

When I dug through this code - https://github.com/spinnaker/clouddriver/pull/2691/files - I noticed that in the dockerImageReplacerMethod() - 
`.replacePath("$..spec.template.spec.containers.[?( @.image == \"{%name%}\" )].image")
  .findPath("$..spec.template.spec.containers.*.image" )
`
The above code will probably not replace the docker image because the path is **_.spec.jobTemplate_** and **_not .spec.template_** as per the manifest file as the per apiVersion: batch/v1beta1.
Hence to get the image bounded correctly from Spinnaker UI, don't you think the above change is necessary?

### Steps to Reproduce:
![image](https://user-images.githubusercontent.com/59741660/97116783-bc13a980-16bc-11eb-968a-b7b8134e3669.png)

### Additional Details:
This is a trigger based spinnaker pipeline which looks for tag being passed to spinnaker when a new build happens a new docker image is generated in the GCR.
In the logs
