### ISSUE TITLE
Orca: Redis to SQL Migration not working for spinnaker version 1.17.6

### ISSUE THREAD

**Issue by Josbrafe** [spinnaker/spinnaker#6133]
### Issue Summary:
We are using Spinnaker 1.17.6 on AWS K8s cluster.
We wanted to use MySQL instead of Redis for Orca pods.
Our Mysql is managed Aurora Mysql instance.

### Cloud Provider(s):
AWS

### Environment:
Spinnaker 1.17.6

### Description:
Following links may be useful https://www.spinnaker.io/guides/operator/orca-redis-to-sql/#enable-dualexecutionrepository

### Additional Details:

Steps to Reproduce:
Update orca-local.yml as: 

```
tasks:
  daysOfExecutionHistory: 180     

sql: 
  enabled: true
  connectionPool:
    jdbcUrl: jdbc:mysql://<SOME_IP>:3306/orca
    user: orca_service
    password: <Pass-1>
    connectionTimeout: 5000
    maxLifetime: 30000
    # MariaDB-specific:
    maxPoolSize: 50
  migration:
    jdbcUrl: jdbc:mysql://<SOME_IP>:3306/orca
    user: orca_migrate
    password: <Pass-1>

monitor:
  activeExecutions:
    redis: false

executionRepository:
  dual:
    enabled: true
    primaryName: sqlExecutionRepository
    previousName: redisExecutionRepository
  sql:
    enabled: true
  redis:
    enabled: true

spring:
  profiles: sqlmigration

pollers:
  orchestrationMigrator:
    enabled: true
    intervalMs: 1800000
  pipelineMigrator:
    enabled: true
    intervalMs: 1800000  
  oldPipelineCleanup:
    enabled: true                  
    intervalMs: 86400000            

    thresholdDays: 30              
    minimumPipelineExecutions: 20   

queue:
  redis:
    enabled: false

keiko:
  queue:
    enabled: false

```

Below is the Mysql db for orca: 
```
MySQL [orca]> select * from pipelines;
Empty set (0.00 sec)

MySQL [orca]> select * from pipeline_stages;
Empty set (0.00 sec)

MySQL [orca]> select * from orchestrations;
Empty set (0.00 sec)

MySQL [orca]> select * from orchestration_stages;
Empty set (0.00 sec)

MySQL [orca]> show tables;
+----------------------------+
| Tables_in_orca             |
+----------------------------+
| DATABASECHANGELOG          |
| DATABASECHANGELOGLOCK      |
| correlation_ids            |
| healthcheck                |
| keiko_v1_dlq_template      |
| keiko_v1_messages_template |
| keiko_v1_queue_template    |
| keiko_v1_unacked_template  |
| notification_lock          |
| orchestration_stages       |
| orchestrations             |
| pending_executions         |
| pipeline_stages            |
| pipelines                  |
+----------------------------+
14 rows in set (0.01 sec)

MySQL [orca]>
```

Kindly assist, and let me know if am missing something. 
Thanks.
