### ISSUE TITLE
GCE Internal Load Balancer with standard VM deploy broken nullpointerexception 

### ISSUE THREAD

**Issue by ddlfcloud** [spinnaker/spinnaker#6136]
### Issue Summary:
Spinnaker fails to add backendService metadata to GCE instance metadata, when using internal load balancer. (L4) Even after adding "region-backend-service-names" manually and getting the VM's deployed, the pipeline never finishes as another error is observed before old server groups are removed.

### Cloud Provider(s):

Google
### Environment:
GKE

### Feature Area:

bash-5.0$ hal version bom
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
+ Get BOM for 1.23.0
  Success
version: 1.23.0
timestamp: '2020-10-14 16:52:18'
services:
  echo:
    version: 2.15.0-20201009170017
    commit: 8c67df108a321bb293902bf5baa8b10acdc590b4
  clouddriver:
    version: 7.0.0-20201014125147
    commit: 98db33db2ef680cf41372408a984172297a91eca
  deck:
    version: 3.4.0-20201014120142
    commit: 8acc38007197829e5e4335c90be865f8e6199f5a
  fiat:
    version: 1.14.0-20201009170017
    commit: c43301cabff36b11282099aa30a1440ebfea3dc2
  front50:
    version: 0.26.0-20201013163321
    commit: 6417003054393807280f7b0aab16f0455ddec2cf
  gate:
    version: 1.19.0-20201012200017
    commit: b0bb7cbfd6426fd84b36b61e5ddd56607a373044
  igor:
    version: 1.13.0-20201009170017
    commit: 366892d6bd82e2c5265148f5407c50f3645a2194
  kayenta:
    version: 0.18.0-20201009200017
    commit: 71b1115be7f5d58f6c476679701c7dbb1508ac75
  orca:
    version: 2.17.0-20201014010017
    commit: eef8e0956cbfb6f40ba34c2354ec16b8e34f75a7
  rosco:
    version: 0.22.0-20201009170017
    commit: b4a0f0e00d46b0005c72fb5d5db2e028e272c3a5
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.19.0-20201013140017
    commit: e73ecc86cf7024c5ab2c9a9fd49fff8c71fed6d8
  monitoring-daemon:
    version: 0.19.0-20201013140017
    commit: e73ecc86cf7024c5ab2c9a9fd49fff8c71fed6d8
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: us-docker.pkg.dev/spinnaker-community/docker
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker

### Steps to Reproduce:
Deploy a GCE image using the "deploy" stage, on an existing internal load balancer. 

### Additional Details:

        "kato.tasks": [
          {
            "exception": {
              "cause": "Required parameter backendService must be specified.",
              "details": [
                {
                  "message": "Required parameter backendService must be specified."
                }
              ],
              "message": "Required parameter backendService must be specified.",
              "type": "EXCEPTION",
              "operation": "DeployAtomicOperation"
            },
            "resultObjects": [
              {
                "cause": "Required parameter backendService must be specified.",
                "details": [
                  {
                    "message": "Required parameter backendService must be specified."
                  }
                ],
                "message": "Required parameter backendService must be specified.",
                "type": "EXCEPTION",
                "operation": "DeployAtomicOperation"
              }
            ],
            "id": "519f8e30-b3cb-4be1-ba27-07c082b93d12",
            "history": [
              {
                "phase": "ORCHESTRATION",
                "status": "Initializing Orchestration Task"
              },
              {
                "phase": "ORCHESTRATION",
                "status": "Processing op: DeployAtomicOperation"
              },
              {
                "phase": "DEPLOY",
                "status": "Initializing phase."
              },
              {
                "phase": "DEPLOY",
                "status": "Looking for BasicGoogleDeployDescription handler..."
              },
              {
                "phase": "DEPLOY",
                "status": "Found handler: BasicGoogleDeployHandler"
              },
              {
                "phase": "DEPLOY",
                "status": "Invoking Handler."
              },
              {
                "phase": "DEPLOY",
                "status": "Initializing creation of server group for cluster testd in asia-northeast3-a..."
              },
              {
                "phase": "DEPLOY",
                "status": "Looking up next sequence..."
              },
              {
                "phase": "GCE_DEPLOY",
                "status": "Attempting list of aggregated managed instance groups..."
              },
              {
                "phase": "DEPLOY",
                "status": "Produced server group name: testd-v000"
              },
              {
                "phase": "DEPLOY",
                "status": "Looking up machine type g1-small..."
              },
              {
                "phase": "DEPLOY",
                "status": "Looking up network test-network..."
              },
              {
                "phase": "DEPLOY",
                "status": "Looking up subnet default in asia-northeast3..."
              },
              {
                "phase": "DEPLOY",
                "status": "Composing server group testd-v000..."
              },
              {
                "phase": "DEPLOY",
                "status": "Looking up image apache-ubuntu-2..."
              },
              {
                "phase": "ORCHESTRATION",
                "status": "Orchestration failed: DeployAtomicOperation | NullPointerException: [Required parameter backendService must be specified.]"
              }
            ],
            "status": {
              "retryable": false,
              "completed": true,
              "failed": true
            }
          }
        ],
---------------------
I manually add "region-backend-service-names": "testd" to the instance metadata in the server group and the error goes away. However the deploy stage never finishes staying in "monitor deploy" task. With the following error:

          "kato.tasks": [
            {
              "exception": {
                "cause": "Operation failed. Last attempt returned status code 400 with error message Invalid value for field 'resource.backends[2].group': 'https://compute.googleapis.com/compute/v1/projects/project/zones/asia-northeast3-a/instanceGroups/testd-v002'. Duplicate instance groups in backend service. and reason invalid.",
                "details": [
                  {
                    "message": "Operation failed. Last attempt returned status code 400 with error message Invalid value for field 'resource.backends[2].group': 'https://compute.googleapis.com/compute/v1/projects/project/zones/asia-northeast3-a/instanceGroups/testd-v002'. Duplicate instance groups in backend service. and reason invalid."
                  },
                  {
                    "message": "Failed to update of Internal load balancer backend service"
                  }
                ],
                "message": "Failed to update of Internal load balancer backend service",
                "type": "EXCEPTION",
                "operation": "DeployAtomicOperation"
              },
              "resultObjects": [
                {
                  "ancestorServerGroupNameByRegion": {
                    "asia-northeast3": "testd-v001"
                  }
                },
                {
                  "cause": "Operation failed. Last attempt returned status code 400 with error message Invalid value for field 'resource.backends[2].group': 'https://compute.googleapis.com/compute/v1/projects/project/zones/asia-northeast3-a/instanceGroups/testd-v002'. Duplicate instance groups in backend service. and reason invalid.",
                  "details": [
                    {
                      "message": "Operation failed. Last attempt returned status code 400 with error message Invalid value for field 'resource.backends[2].group': 'https://compute.googleapis.com/compute/v1/projects/project/zones/asia-northeast3-a/instanceGroups/testd-v002'. Duplicate instance groups in backend service. and reason invalid."
                    },
                    {
                      "message": "Failed to update of Internal load balancer backend service"
                    }
                  ],
                  "message": "Failed to update of Internal load balancer backend service",
                  "type": "EXCEPTION",
                  "operation": "DeployAtomicOperation"
                }
              ],
              "id": "6e35d65e-3fd0-4a03-b252-e89bb46c0f69",
              "history": [
                {
                  "phase": "ORCHESTRATION",
                  "status": "Initializing Orchestration Task"
                },
                {
                  "phase": "ORCHESTRATION",
                  "status": "Processing op: DeployAtomicOperation"
                },
                {
                  "phase": "DEPLOY",
                  "status": "Initializing phase."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Looking for BasicGoogleDeployDescription handler..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Found handler: BasicGoogleDeployHandler"
                },
                {
                  "phase": "DEPLOY",
                  "status": "Invoking Handler."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Initializing creation of server group for cluster testd in asia-northeast3-a..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Looking up next sequence..."
                },
                {
                  "phase": "GCE_DEPLOY",
                  "status": "Attempting list of aggregated managed instance groups..."
                },
                {
                  "phase": "GCE_DEPLOY",
                  "status": "Found ancestor server group, parsing details (name: testd-v001)"
                },
                {
                  "phase": "DEPLOY",
                  "status": "Produced server group name: testd-v002"
                },
                {
                  "phase": "DEPLOY",
                  "status": "Looking up machine type g1-small..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Looking up network test-network..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Looking up subnet default in asia-northeast3..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Composing server group testd-v002..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Looking up image apache-ubuntu-2..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Resolved user data."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Done operating on instance template testd-v002-85616240."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Done operating on managed instance group testd-v002."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Done creating server group testd-v002 in asia-northeast3-a."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Attempting update of Internal load balancer backend service..."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Done associating server group testd-v002 with backend service testd."
                },
                {
                  "phase": "DEPLOY",
                  "status": "Attempting update of Internal load balancer backend service..."
                },
                {
                  "phase": "ORCHESTRATION",
                  "status": "Orchestration failed: DeployAtomicOperation | GoogleOperationException: [Failed to update of Internal load balancer backend service]"
                }
              ],
              "status": {
                "retryable": false,
                "completed": true,
                "failed": true
              }
            }
          ],

**Comment by ddlfcloud** [comment]
https://github.com/spinnaker/clouddriver/pull/4879 seems to relate.

**Comment by ddlfcloud** [comment]
Note this also happens with internal HTTPS load balancer, 
`404 Not Found { "code" : 404, "errors" : [ { "domain" : "global", "message" : "The resource 'projects/my-project/global/backendServices/backend' was not found", "reason" : "notFound" } ], "message" : "The resource 'projects/my-project/global/backendServices/backend' was not found" }`

As in it expects it to be global backend when its actually regional

**Comment by qllb** [comment]
I'm having the same issues with Internal Https LoadBalancer and Internal L4 Load balancer
```
+ Get BOM for 1.23.2
  Success
version: 1.23.2
timestamp: '2020-11-16 16:34:13'
services:
  echo:
    version: 2.15.0-20201009170017
    commit: 8c67df108a321bb293902bf5baa8b10acdc590b4
  clouddriver:
    version: 7.0.2-20201116113324
    commit: a97e45fdec9e98af17d554f0b8e6cb7c68bcdf9c
  deck:
    version: 3.4.0-20201014120142
    commit: 8acc38007197829e5e4335c90be865f8e6199f5a
  fiat:
    version: 1.14.0-20201009170017
    commit: c43301cabff36b11282099aa30a1440ebfea3dc2
  front50:
    version: 0.26.0-20201013163321
    commit: 6417003054393807280f7b0aab16f0455ddec2cf
  gate:
    version: 1.19.0-20201012200017
    commit: b0bb7cbfd6426fd84b36b61e5ddd56607a373044
  igor:
    version: 1.13.0-20201009170017
    commit: 366892d6bd82e2c5265148f5407c50f3645a2194
  kayenta:
    version: 0.18.0-20201009200017
    commit: 71b1115be7f5d58f6c476679701c7dbb1508ac75
  orca:
    version: 2.17.0-20201014010017
    commit: eef8e0956cbfb6f40ba34c2354ec16b8e34f75a7
  rosco:
    version: 0.22.0-20201009170017
    commit: b4a0f0e00d46b0005c72fb5d5db2e028e272c3a5
  defaultArtifact: {}
  monitoring-third-party:
    version: 0.19.0-20201013140017
    commit: e73ecc86cf7024c5ab2c9a9fd49fff8c71fed6d8
  monitoring-daemon:
    version: 0.19.0-20201013140017
    commit: e73ecc86cf7024c5ab2c9a9fd49fff8c71fed6d8
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://dl.bintray.com/spinnaker-releases/debians
  dockerRegistry: us-docker.pkg.dev/spinnaker-community/docker
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker

```

Although L4 internal load balancers work fine in version 1.20.7
