### ISSUE TITLE
Failure adding external accounts with Git backend and kubeconfigFile in GCS

### ISSUE THREAD

**Issue by tompa911** [spinnaker/spinnaker#6156]
### Issue Summary:
External accounts configured with Git backend. kubeconfigFile points to GCS.
New/added external accounts are not refreshed.

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.22.2

### Feature Area:
clouddriver
Spring Cloud Config 

### Description:
When new external account is added to clouddriver-local.yml (which is stored Git) and kubeconfigFile points to GCS, account list is not refreshed.

### Steps to Reproduce:
Add account to clouddriver-local.yml, e.g.:
```
  - name: new-account
    requiredGroupMembership: []
    providerVersion: V2
    permissions:
      READ:
      - spin-admin
      WRITE:
      - spin-admin
    dockerRegistries: []
    context: my-context
    configureImagePullSecrets: true
    cacheThreads: 1
    namespaces:
    - mynamespace
    omitNamespaces: []
    kinds: []
    omitKinds: []
    customResources: []
    cachingPolicies: []
    kubeconfigFile: encryptedFile:gcs!b:my-bucket!f:my-kubeconfig
    oAuthScopes: []
    onlySpinnakerManaged: true
```

Account list is never dynamically refreshed.
Delete one of the accounts stored in clouddriver-local.yml, account list is correctly refreshed.
Restart clouddriver pod. All accounts are correctly loaded.

### Additional Details:
All kubeconfigs are correctly loaded from GCS despite the exception:
`com.netflix.spinnaker.kork.configserver.ConfigFileLoadingException: File "encryptedFile:gcs!b:my-bucket!f:my-kubeconfig" not found or is not readable`
see: https://gist.github.com/tompa911/5415612e6ddb2064396f56c75799b625
There is only single exception in each refresh cycle: for the first kubeconfig present in clouddriver-local.yml
