### ISSUE TITLE
Custom Job Stages are not application scoped

### ISSUE THREAD

**Issue by gothicfann** [spinnaker/spinnaker#6164]
### Issue Summary: 
When creating multiple Custom Job Stages with the same logic for different applications, I see duplicate Jobs for all applications which Jobs actually are not belonging to.

### Cloud Provider(s): 
Kubernetes

### Environment: 
GCP

### Feature Area: 
Pipelines, UI, Custom Job Stages

Please see orca-local.yml configuration and attached screenshot  

![Screenshot from 2020-11-09 10-22-18](https://user-images.githubusercontent.com/20225154/98506683-7f77ae80-2275-11eb-8262-369d7bd75664.png)

**orca-local.yml:**
```
job:
  preconfigured:
    kubernetes:

      - label: Deploy Helm Chart (Custom Job Stage)
        type: deployHelmChart
        description: Deploy helm3 charts with OCI based registry.
        cloudProvider: kubernetes
        account: spinnaker-install-account
        credentials: spinnaker-install-account
        waitForCompletion: true
        application: app
        parameters:
          ### Job parameters
          - name: JOB_IMAGE
            label: Job Image
            description: Specify full image path with tag (e.g. gcr.io/gcp-architecting/helm3deployer:v1.3.0).
            mapping: manifest.spec.template.spec.containers[0].image
            defaultValue: ""
          ### Deployment parameters
          - name: PROJECT_ID
            label: Project ID
            description: Specify GCP project id of target GKE cluster.
            mapping: manifest.spec.template.spec.containers[0].env[0].value
            defaultValue: ""
          - name: SERVICE_ACCOUNT_NAME
            label: Service Account Name
            description: GCP service account name (e.g. helm-deployment@gcp-architecting.iam.gserviceaccount.com name will be helm-deployment).
            mapping: manifest.spec.template.spec.containers[0].env[1].value
            defaultValue: ""
          - name: COMPUTE_ZONE
            label: Compute Zone
            description: GCP compute zone in which GKE cluster is running (e.g. us-central1-c).
            mapping: manifest.spec.template.spec.containers[0].env[2].value
            defaultValue: ""
          - name: CLUSTER_NAME
            label: Cluster Name
            description: Name of the GKE cluster.
            mapping: manifest.spec.template.spec.containers[0].env[3].value
            defaultValue: ""
          - name: REGISTRY_USER
            label: Registry Username
            description: Helm registry username.
            mapping: manifest.spec.template.spec.containers[0].env[4].value
            defaultValue: ""
          - name: REGISTRY_PASSWORD
            label: Registry Password
            description: Helm registry password.
            mapping: manifest.spec.template.spec.containers[0].env[5].value
            defaultValue: ""
          - name: REGISTRY_URL
            label: Registry Url
            description: Helm registry url (Note; do not specify http(s)://).
            mapping: manifest.spec.template.spec.containers[0].env[6].value
            defaultValue: ""
          - name: CHART_NAME
            label: Chart Name
            description: Name of the helm chart.
            mapping: manifest.spec.template.spec.containers[0].env[7].value
            defaultValue: ""
          - name: CHART_VERSION
            label: Chart Version
            description: Helm chart version.
            mapping: manifest.spec.template.spec.containers[0].env[8].value
            defaultValue: ""
          - name: CHART_DEFAULT_APPVERSION
            label: Chart Default appVersion
            description: Chart current appVersion (used when substituting this value with 'Image Tag').
            mapping: manifest.spec.template.spec.containers[0].env[9].value
            defaultValue: ""
          - name: NAMESPACE
            label: Namespace
            description: Target namespace for helm release deployment.
            mapping: manifest.spec.template.spec.containers[0].env[10].value
            defaultValue: ""
          - name: RELEASE_NAME
            label: Release Name
            description: Helm release name.
            mapping: manifest.spec.template.spec.containers[0].env[11].value
            defaultValue: ""
          - name: IMAGE_NAME
            label: Image Name
            description: Image name without tag (Note; chart should have value 'image.name' to make this work).
            mapping: manifest.spec.template.spec.containers[0].env[12].value
            defaultValue: ""
          - name: IMAGE_TAG
            label: Image Tag
            description: Image tag (Note; chart should have value 'image.tag' to make this work).
            mapping: manifest.spec.template.spec.containers[0].env[13].value
            defaultValue: ""
          - name: CHART_ADDITIONAL_OPTIONS
            label: Chart additional options
            description: Chart additional options.
            mapping: manifest.spec.template.spec.containers[0].env[14].value
            defaultValue: ""
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: app-helm3-job
            namespace: spinnaker-jobs
          spec:
            backoffLimit: 0
            template:
              spec:
                volumes:
                - name: spinnaker-jobs-key
                  secret:
                    secretName: spinnaker-jobs-key
                restartPolicy: Never
                containers: 
                  - name: helm3deployer
                    image: placeholder
                    volumeMounts:
                    - name: spinnaker-jobs-key
                      mountPath: /var/secrets/google
                    env:
                      - name: PROJECT_ID
                        value: placeholder
                      - name: SERVICE_ACCOUNT_NAME
                        value: placeholder
                      - name: COMPUTE_ZONE
                        value: placeholder
                      - name: CLUSTER_NAME
                        value: placeholder
                      - name: REGISTRY_USER
                        value: placeholder
                      - name: REGISTRY_PASSWORD
                        value: placeholder
                      - name: REGISTRY_URL
                        value: placeholder
                      - name: CHART_NAME
                        value: placeholder
                      - name: CHART_VERSION
                        value: placeholder                                                                    
                      - name: CHART_DEFAULT_APPVERSION
                        value: placeholder
                      - name: NAMESPACE
                        value: placeholder
                      - name: RELEASE_NAME
                        value: placeholder
                      - name: IMAGE_NAME
                        value: placeholder
                      - name: IMAGE_TAG
                        value: placeholder
                      - name: CHART_ADDITIONAL_OPTIONS
                        value: placeholder

      - label: Deploy Helm Chart (Custom Job Stage)
        type: deployHelmChart
        description: Deploy helm3 charts with OCI based registry.
        cloudProvider: kubernetes
        account: spinnaker-install-account
        credentials: spinnaker-install-account
        waitForCompletion: true
        application: api
        parameters:
          ### Job parameters
          - name: JOB_IMAGE
            label: Job Image
            description: Specify full image path with tag (e.g. gcr.io/gcp-architecting/helm3deployer:v1.3.0).
            mapping: manifest.spec.template.spec.containers[0].image
            defaultValue: ""
          ### Deployment parameters
          - name: PROJECT_ID
            label: Project ID
            description: Specify GCP project id of target GKE cluster.
            mapping: manifest.spec.template.spec.containers[0].env[0].value
            defaultValue: ""
          - name: SERVICE_ACCOUNT_NAME
            label: Service Account Name
            description: GCP service account name (e.g. helm-deployment@gcp-architecting.iam.gserviceaccount.com name will be helm-deployment).
            mapping: manifest.spec.template.spec.containers[0].env[1].value
            defaultValue: ""
          - name: COMPUTE_ZONE
            label: Compute Zone
            description: GCP compute zone in which GKE cluster is running (e.g. us-central1-c).
            mapping: manifest.spec.template.spec.containers[0].env[2].value
            defaultValue: ""
          - name: CLUSTER_NAME
            label: Cluster Name
            description: Name of the GKE cluster.
            mapping: manifest.spec.template.spec.containers[0].env[3].value
            defaultValue: ""
          - name: REGISTRY_USER
            label: Registry Username
            description: Helm registry username.
            mapping: manifest.spec.template.spec.containers[0].env[4].value
            defaultValue: ""
          - name: REGISTRY_PASSWORD
            label: Registry Password
            description: Helm registry password.
            mapping: manifest.spec.template.spec.containers[0].env[5].value
            defaultValue: ""
          - name: REGISTRY_URL
            label: Registry Url
            description: Helm registry url (Note; do not specify http(s)://).
            mapping: manifest.spec.template.spec.containers[0].env[6].value
            defaultValue: ""
          - name: CHART_NAME
            label: Chart Name
            description: Name of the helm chart.
            mapping: manifest.spec.template.spec.containers[0].env[7].value
            defaultValue: ""
          - name: CHART_VERSION
            label: Chart Version
            description: Helm chart version.
            mapping: manifest.spec.template.spec.containers[0].env[8].value
            defaultValue: ""
          - name: CHART_DEFAULT_APPVERSION
            label: Chart Default appVersion
            description: Chart current appVersion (used when substituting this value with 'Image Tag').
            mapping: manifest.spec.template.spec.containers[0].env[9].value
            defaultValue: ""
          - name: NAMESPACE
            label: Namespace
            description: Target namespace for helm release deployment.
            mapping: manifest.spec.template.spec.containers[0].env[10].value
            defaultValue: ""
          - name: RELEASE_NAME
            label: Release Name
            description: Helm release name.
            mapping: manifest.spec.template.spec.containers[0].env[11].value
            defaultValue: ""
          - name: IMAGE_NAME
            label: Image Name
            description: Image name without tag (Note; chart should have value 'image.name' to make this work).
            mapping: manifest.spec.template.spec.containers[0].env[12].value
            defaultValue: ""
          - name: IMAGE_TAG
            label: Image Tag
            description: Image tag (Note; chart should have value 'image.tag' to make this work).
            mapping: manifest.spec.template.spec.containers[0].env[13].value
            defaultValue: ""
          - name: CHART_ADDITIONAL_OPTIONS
            label: Chart additional options
            description: Chart additional options.
            mapping: manifest.spec.template.spec.containers[0].env[14].value
            defaultValue: ""
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: api-helm3-job
            namespace: spinnaker-jobs
          spec:
            backoffLimit: 0
            template:
              spec:
                volumes:
                - name: spinnaker-jobs-key
                  secret:
                    secretName: spinnaker-jobs-key
                restartPolicy: Never
                containers: 
                  - name: helm3deployer
                    image: placeholder
                    volumeMounts:
                    - name: spinnaker-jobs-key
                      mountPath: /var/secrets/google
                    env:
                      - name: PROJECT_ID
                        value: placeholder
                      - name: SERVICE_ACCOUNT_NAME
                        value: placeholder
                      - name: COMPUTE_ZONE
                        value: placeholder
                      - name: CLUSTER_NAME
                        value: placeholder
                      - name: REGISTRY_USER
                        value: placeholder
                      - name: REGISTRY_PASSWORD
                        value: placeholder
                      - name: REGISTRY_URL
                        value: placeholder
                      - name: CHART_NAME
                        value: placeholder
                      - name: CHART_VERSION
                        value: placeholder                                                                    
                      - name: CHART_DEFAULT_APPVERSION
                        value: placeholder
                      - name: NAMESPACE
                        value: placeholder
                      - name: RELEASE_NAME
                        value: placeholder
                      - name: IMAGE_NAME
                        value: placeholder
                      - name: IMAGE_TAG
                        value: placeholder
                      - name: CHART_ADDITIONAL_OPTIONS
                        value: placeholder
```
