### ISSUE TITLE
Make role sync settings to be configurable separately for service accounts and application permissions

### ISSUE THREAD

**Issue by KeisukeYamashita** [spinnaker/spinnaker#6179]
### Issue Summary:
To make performance and UX compatible, I'd like to be able to set the roleSync API of Fiat's roleSync settings in Front50 separately when creating an application and service account.

**If we disable `fiat.roleSync`, we can't save pipeline's immediately after instancing it in the UI.** If we enable it, it sometimes cause a performance issues described below.

### Cloud Provider(s):

* GKE

### Environment:
* Spinnaker 1.20.8 & 1.23.1

### Feature Area:
* Front50
* Fiat
* Deck (indirect)

### Description:
Currently, we have an API to set up in Front50 whether the Fiat roles will be synchronized when an Application or Service Account is created.

**front50-local.yaml**

```yaml
fiat:
   roleSync:
       enabled: true|false
```

However, it is implemented in such a way that a single API can be used to set up the settings when an Application is created to synchronize a Role and when a Service Account is created to synchronize a specific Role.

Synchronization of the role that is called when creating an application, as discussed in the Spinnaker community Slack post(ref: https://spinnakerteam.slack.com/archives/CC101KSNP/p1585589301029500?thread_ts=1585577275.028800&cid=CC101KSNP) here, is leading to major performance degradation, and I think it is often basically disabled.

However, I want it to be synchronized when creating a Service account (= when creating a Pipeline). Otherwise, you won't be able to save a Pipeline with a Managed Service account set up right away.

I suggest like below:

```yaml
fiat:
   roleSync:
       enabled: true|false  // for backward compatibility
       applicationPermission:
           enabled: true|false
       serviceAccount:
          enabled: true|false
```

With Authorization enabled, Spinnaker will provide a meaningful API.

### Steps to Reproduce:

* Enable authorization and managed service account feature on Spinnaker
* Disable Front50's Fiat roleSync by configuring `fiat.roleSync.enabled: false`
* Save pipeline with pipeline permissions
