### ISSUE TITLE
Clouddriver high loading time

### ISSUE THREAD

**Issue by kirangodishala** [spinnaker/spinnaker#6200]
### Issue Summary:
Clouddriver takes huge loading time for dynamic accounts at startup and at every refresh

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.23.2 and all previous versions

### Feature Area:
Spinnaker 1.23.2 and all previous versions

### Description:
Clouddriver is taking 30min to over 1hour for loading approximately 800-1000 kubernetes accounts from remote sources like git. 

### Steps to Reproduce:
Create a git repository to supply remote configurations and use it in spinnakerconfig.yml as given below.
```
spring:
  profiles:
    include: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/example/spinnaker-config
          basedir: /tmp/config-repo
```
In the above repo, checkin a clouddriver-local.yml file having around 800 kubernetes accounts. One such account is shown below.
```
kubernetes:
  enabled: true
  accounts:
  - name: k8s-acc-0
    requiredGroupMembership: []
    permissions:
      READ:
      - read1
      - read2
      WRITE:
      - write1
      - write2
    cacheThreads: 1
    namespaces:
    - oes
    - baseline-spinnaker
    - spinnaker
    - dev-spinnaker
    omitNamespaces: []
    kinds: []
    omitKinds:
    - clusterRoleBinding
    - controllerRevision
    - customResourceDefinition
    - role
    - roleBinding
    - persistentVolume
    - apiService
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /tmp/config-repo/kubeconfig
    oAuthScopes: []
    onlySpinnakerManaged: true
```
Now when clouddriver is started, it takes few tens of minutes to get to ready state based on the number of accounts.
