### ISSUE TITLE
Spin CLI v1.19.0 - unable to authenticate with oauth2

### ISSUE THREAD

**Issue by andrijaperovic** [spinnaker/spinnaker#6214]
### Issue Summary:
Spin-CLI OAuth2 config fails on AKS Kubernetes Pod 

### Cloud Provider(s):

Azure

### Environment:
Spinnaker: v1.23.3
Spinnaker CLI: v1.19.0
Deploying Spinnaker using Spinnaker operator. 

### Feature Area:

Spinnaker CLI/Gate

### Description:

I have a spin-cli pod which is running version 1.19.0 based on the installation instructions found here: 
https://spinnaker.io/setup/spin/

When trying to access the spinnaker backend with the following config I am seeing login errors (no logs in the Spinnaker backend pod logs): 
```
gate:
  endpoint: https://spinnaker-gate.custom.domain
auth:
  enabled: true
  oauth2:
    tokenUrl: https://github_enterprise.custom.domain/login/oauth/access_token
    authUrl: https://github_enterprise.custom.domain/login/oauth/authorize
    clientId: client_id_value
    clientSecret: client_secret_value
    scopes:
    - user
    cachedToken:
      access_token: cached_token
      token_type: bearer
      refresh_token: ""
      expiry: 0001-01-01T00:00:00Z
  ldap: null
```

When running this as a docker container on my local, the behavior is such that the configuration is refreshed with the new format and I am successfully able to list pipelines for a given application. 
However, when running this from my AKS cluster v1.17.11, it suddenly began to break: 

```
OAuth2 Authentication failed: login failed
login failed
```

The OAuth auth callback url is http://localhost:8085. 

I am wondering if anything custom is needed to expose the callback URL traffic to the spin-cli pod on a standard domain with a service and port routing on 8085, or if `localhost` should be sufficient. 
Or at least, is there a way to make the spin-cli errors more verbose so that it is clear why the login authentication fails. 

### Steps to Reproduce:
Follow steps described in the description. 

### Additional Details:
N/A
