### ISSUE TITLE
Deck on subpath

### ISSUE THREAD

**Issue by raduhek** [spinnaker/spinnaker#6223]
### Issue Summary:

When setting spinnaker under a subpath, deck loads `plugin-manfiest.json` from absolute path: https://github.com/spinnaker/deck/blob/master/app/scripts/modules/core/src/plugins/plugin.registry.ts#L87

### Cloud Provider(s):

Kubernetes

### Environment:

I'm running Spinnaker on a Kuberntes cluster in AWS. On k8s, there is also an envoy deployment, routing traffic from an ALB.
Relevant IngressRoute:

```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
spec:
  routes:
  - delegate:
      name: spinnaker
      namespace: spinnaker
    match: /spinnaker/
 virtualhost:
    fqdn: example.com
```
```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  routes:
    - match: /spinnaker/
      prefixRewrite: /
      services:
        - name: spin-deck
          port: 9000
    - match: /spinnaker/api
      services:
        - name: spin-gate
          port: 8084
```

### Feature Area:

Deck

### Description:

While the `prefixRewrite` directive makes Deck load all assets correctly, `plugin-manifest.json` is loaded from an absolute path, rendering the url `example.com/plugin-manifest.json` instead of `example.com/spinnaker/plugin-manifest.json`

### Steps to Reproduce:

1. Install Spinnaker in a Kubernetes cluster
2. Configure according to https://docs.armory.io/docs/armory-admin/hostname-deck-gate-configure/
3. Configure subpaths on a domain to point to `deck` and `gate`
