### ISSUE TITLE
Echo HA Kubernetes services are missing monitoring ports

### ISSUE THREAD

**Issue by FaHeymann** [spinnaker/spinnaker#6254]
### Issue Summary:

We are running Spinnaker on Kubernetes deployed through Halyard and use the Prometheus metrics store option. In our existing Kubernetes services Halyard created port configurations that point to the metrics endpoints like this:

```yaml
  ports:
  - name: monitoring
    port: 8008
    protocol: TCP
    targetPort: 8008
  <...>
```

When deploying Echo in HA mode the resulting services spin-echo-worker and spin-echo-scheduler seem to be missing the monitoring port though.

This can be easily worked around by creating services that point to the metrics manually but it would be nice if that was not necessary.

### Cloud Provider(s):

Kubernetes on AWS (EKS)

### Environment:

Halyard 1.40.0
Spinnaker 1.22.2

### Feature Area:

Halyard / Deployment
