### ISSUE TITLE
Resource limit/request fields in kubernetes manifest as part of custom kubernetes job stage is not working

### ISSUE THREAD

**Issue by j-sandy** [spinnaker/spinnaker#6257]
### Issue Summary:
Putting limits/request in a custom job through ~/.hal/default/profiles/orca-local.yml, the custom stage breaks with an error as shown below.
![image](https://user-images.githubusercontent.com/30489233/103288979-2114b400-4a0c-11eb-8ddc-9f26a6d12c14.png)

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker 1.19, 1.22, 1.23, 1.24.0

### Feature Area:
Orca, Clouddriver

### Description:
While running the custom stage in Spinnaker pipeline, defined using below given custom k8s job in orca-local.yml, it throws error as mentioned above:
```
job:
  preconfigured:
    kubernetes:
      - label: limitJob
        cloudProvider: kubernetes
        credentials: spinnaker-service-account
        application: my-app
        description: Simple limited stress manifest job
        account: spinnaker-service-account
        type: demoLimitJob
        waitForCompletion: true
        propertyFile: limitjob-pod
        source: text
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: limitjobtest
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      - '-v'
                      - '--vm'
                      - '1'
                      - '--vm-bytes'
                      - 250M
                      - '--vm-hang'
                      - '1'
                      - '--timeout'
                      - 60s
                      - '--cpu'
                      - '2'
                    command:
                      - stress
                    env:
                      - name: FRUIT
                        value: TOMATO
                    image: polinux/stress
                    resources:
                      limits:
                        memory: 200Mi
                      requests:
                        memory: 100Mi
                    imagePullPolicy: IfNotPresent
                    name: limitjob-pod
                restartPolicy: Never
```
### Steps to Reproduce:
1. Configure orca to use custom job stage using above given manifest.
2. Create pipeline to add above defined custom job stage.
3. Run the pipeline.

### Additional Details:
If the above defined k8s manifest is being used with Run Job Stage in a pipeline, it works fine and deploy the desired artifact.
