### ISSUE TITLE
Lambda Functions do not show up in "Infrastructure" view

### ISSUE THREAD

**Issue by away168** [spinnaker/spinnaker#6271]
### Issue Summary:
Lambda Functions do not show up in Infrastructure view. 
Even though the function has been created in Spinnaker, and cached by Clouddriver.

### Cloud Provider(s):
AWS, AWS Lambda

### Environment:
Spinnaker 1.24.2

### Feature Area:
Clouddriver, Lambda

### Description:
When configuring AWS Lambda on a new AWS account - Lambda functions (created by Spinnaker) - are not showing up in the Spinnaker UI.  The workaround is having to create an EC2 instance in the same Application - and then caching code is able to complete and show the functions.

Alternatively:
key `com.netflix.spinnaker.clouddriver.aws.provider.AwsProvider:applications:attributes:aws:applications:helloworld` is not populated by creating a lambda function.  

This is a brand new application - with no other AWS infrastructure associated with it.

### Steps to Reproduce:
Using Minnaker and operator_install.sh with aws lambda and lambda plugin enabled (see resulting spinsvc yaml below)

### Additional Details:
We believe the code in question is here:

https://github.com/spinnaker/clouddriver/blob/c9c9608b58d9c48ccd6545c9acdb632ebaa67c1f/cats/cats-redis/src/main/java/com/netflix/spinnaker/cats/redis/cache/RedisCache.java#L297

Since the first key returns null. 
and we believe the first key is this:
`com.netflix.spinnaker.clouddriver.aws.provider.AwsProvider:applications:attributes:aws:applications:helloworld`
where application name is "helloworld"

```
apiVersion: spinnaker.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  expose:
    type: ingress
  kustomize:
    clouddriver: {}
    deck: {}
    echo: {}
    front50: {}
    gate: {}
    igor: {}
    orca: {}
    rosco: {}
  spinnakerConfig:
    config:
      artifacts:
        http:
          accounts:
          - name: http-account
          enabled: true
      canary: {}
      ci: {}
      deploymentEnvironment: {}
      features: {}
      metricStores: {}
      notifications: {}
      persistentStorage:
        persistentStoreType: s3
        s3:
          accessKeyId: minio
          bucket: spinnaker
          endpoint: http://minio:9000
          pathStyleAccess: true
          region: us-west-2
          rootFolder: front50
          secretAccessKey: encrypted:k8s!n:spin-secrets!k:minioAccessKey
      providers:
        aws:
          accessKeyId: XXXX
          accounts:
          - accountId: "xxxx"
            assumeRole: role/DevSpinnakerManagedRole
            lifecycleHooks: []
            name: aws-dev
            permissions: {}
            providerVersion: V1
            regions:
            - name: us-west-2
          bakeryDefaults:
            baseImages: []
          defaultKeyPairTemplate: '{{"{{"}}name{{"}}"}}-keypair'
          defaultRegions:
          - name: us-west-2
          defaults:
            iamRole: BaseIAMRole
          enabled: true
          features:
            cloudFormation:
              enabled: true
          primaryAccount: aws-dev
          secretAccessKey: encrypted:k8s!n:spin-secrets!k:aws-secret-key
        dockerRegistry:
          accounts:
          - address: https://index.docker.io
            cacheIntervalSeconds: 30
            cacheThreads: 1
            clientTimeoutMillis: 60000
            email: fake.email@spinnaker.io
            insecureRegistry: false
            name: dockerhub
            paginateSize: 100
            permissions: {}
            providerVersion: V1
            repositories:
            - library/nginx
            requiredGroupMembership: []
            sortTagsByDate: false
            trackDigests: false
          enabled: true
          primaryAccount: dockerhub
        kubernetes:
          accounts:
          - cacheThreads: 1
            cachingPolicies: []
            checkPermissionsOnStartup: true
            customResources: []
            dockerRegistries: []
            kinds: []
            liveManifestCalls: false
            name: spinnaker
            namespaces: []
            oAuthScopes: []
            omitKinds: []
            omitNamespaces: []
            onlySpinnakerManaged: false
            permissions: {}
            providerVersion: V2
            serviceAccount: true
          enabled: true
          primaryAccount: spinnaker
      pubsub: {}
      repository: {}
      security: {}
      spinnaker: {}
      version: 1.24.2
    profiles:
      clouddriver:
        aws:
          accounts:
          - accountId: "xxxxx"
            assumeRole: role/DevSpinnakerManagedRole
            lambdaEnabled: true
            lifecycleHooks: []
            name: aws-dev
            permissions: {}
            providerVersion: V1
            regions:
            - name: us-west-2
          lambda:
            enabled: true
      deck:
        settings-local.js: |
          window.spinnakerSettings.feature.functions = true
      echo: {}
      front50: {}
      gate:
        server:
          tomcat:
            httpsServerPort: X-Forwarded-Port
            internalProxies: .*
            protocolHeader: X-Forwarded-Proto
            remoteIpHeader: X-Forwarded-For
        spinnaker:
          extensibility:
            deck-proxy:
              enabled: true
              plugins:
                Aws.LambdaDeploymentPlugin:
                  enabled: true
                  version: 1.0.1
            repositories:
              awsLambdaDeploymentPluginRepo:
                url: https://raw.githubusercontent.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/master/plugins.json
      igor: {}
      orca:
        spinnaker:
          extensibility:
            plugins:
              Aws.LambdaDeploymentPlugin:
                enabled: true
                version: 1.0.1
            repositories:
              awsLambdaDeploymentPluginRepo:
                id: awsLambdaDeploymentPluginRepo
                url: https://raw.githubusercontent.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/master/plugins.json
      rosco: {}
      settings-local.js: {}
      spinnaker: {}
      spinnakerconfig: {}
    service-settings:
      clouddriver:
        env:
          EC2_REGION: us-west-2
        kubernetes:
          serviceAccountName: spin-sa
      echo: {}
      front50: {}
      gate: {}
      igor: {}
      orca: {}
      rosco:
        env:
          AWS_REGION: us-west-2
      spinnaker: {}
  validation:
    providers:
      docker:
        enabled: true
      kubernetes:
        enabled: true
```

## Workaround

Deploy a new AWS ASG/EC2 Cluster in the Cluster tab.
