### ISSUE TITLE
Clouddriver caching services becoming unstable

### ISSUE THREAD

**Issue by kirangodishala** [spinnaker/spinnaker#6315]
### Issue Summary:
Clouddriver caching pods are unstable when the number of accounts are high. 

### Cloud Provider(s):
Kubernetes

### Feature Area:
Clouddriver (Caching)

### Description:
When the number of kubernetes accounts are high(1000+), the clouddriver caching pods become unstable due to heavy memory and CPU utilization and eventually crash. Increasing the number of replicas is not helping.  

### Steps to Reproduce:
Create a git repository to supply remote configurations and use it in spinnakerconfig.yml as given below.

```
spring:
  profiles:
    include: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/example/spinnaker-config
          basedir: /tmp/config-repo
```
In the above repo, checkin a clouddriver-local.yml file having around 1000+ kubernetes accounts. One such account is shown below.

```
kubernetes:
  enabled: true
  accounts:
  - name: k8s-acc-0
    requiredGroupMembership: []
    permissions:
      READ:
      - read1
      - read2
      WRITE:
      - write1
      - write2
    cacheThreads: 1
    namespaces:
    - oes
    - baseline-spinnaker
    - spinnaker
    - dev-spinnaker
    omitNamespaces: []
    kinds: []
    omitKinds:
    - clusterRoleBinding
    - controllerRevision
    - customResourceDefinition
    - role
    - roleBinding
    - persistentVolume
    - apiService
    customResources: []
    cachingPolicies: []
    kubeconfigFile: /tmp/config-repo/kubeconfig
    oAuthScopes: []
    onlySpinnakerManaged: true
```
Now when clouddriver caching service is started, within few minutes it becomes unresponsive.
