### ISSUE TITLE
Kubernetes Patch (Manifest) using payload digest instead of tag

### ISSUE THREAD

**Issue by jcurlier** [spinnaker/spinnaker#6323]
### Issue Summary:

The Kubernetes CronJob is updated with the payload digest and not the payload tag.

### Cloud Provider(s):

Google Cloud

### Feature Area:

Kubernetes Patch (Manifest) Configuration

### Description:

I have the following payload

```
payload":{"digest":"gcr.io/aura-build/iterable-service@sha256:5835d73a9e6a34e57627676a287a78f0303857c731ad04d3026708ebc0704891","action":"INSERT","tag":"gcr.io/aura-build/iterable-service:v1.1.7"}
```

and the following patch manifest configuration

```
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: '${ trigger[''payload''][''tag'']}'
              name: iterable-service-alert
```

For some reason, I am seeing the digest in the Cron Job definition after patching:

```
  Containers:
   iterable-service-alert:
    Image:      gcr.io/aura-build/iterable-service@sha256:5835d73a9e6a34e57627676a287a78f0303857c731ad04d3026708ebc0704891
```

It is pulling the right image but makes it difficult to find right away the version used.

### Steps to Reproduce:

(1) Create a patch manifest
(2) Set it to update the image
(3) Describe the updated CronJob

### Additional Details:

Seems it started to happen a couple of months back in one of the Spinnaker update.
