### ISSUE TITLE
Clouddriver dockerfile reverted AWS iam authenticator version unsupported with IRSA

### ISSUE THREAD

**Issue by battlecow** [spinnaker/spinnaker#6334]
### Issue Summary:
[Clouddriver#4696](https://github.com/spinnaker/clouddriver/pull/4696) provided a fix to utilize a service account with IRSA workflow within an AWS kubernetes deployed Spinnaker cluster (EKS).  The change was then reverted in a newer commit and backported to 1.24.x in [Clouddriver#5196](https://github.com/spinnaker/clouddriver/pull/5196)

### Cloud Provider(s):
AWS / EKS

**Comment by battlecow** [comment]
As stated in the PR but for future travelers: https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/347 don't bother using the aws-iam-authenticator and instead rely on the awscli to retrieve cluster tokens. e.g.:
```
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "<cluster-name>"
        # - "--role"
        # - "<role-arn>"
```
