### ISSUE TITLE
Exception - Wait For Manifest To Stabilize

### ISSUE THREAD

**Issue by hualoqueros** [spinnaker/spinnaker#6338]
### Issue Summary:
Some how this week i'm facing error :
```
Exception ( Wait For Manifest To Stabilize )
WaitForManifestStableTask of stage Deploy (Manifest) timed out after 30 minutes 2 seconds. pausedDuration: 0 seconds, elapsedTime: 30 minutes 2 seconds, timeoutValue: 30 minutes
```
i dont know why this happen..

### Cloud Provider(s):
GKE cluster version 1.16.15-gke.6000

### Environment:
Spinnaker 1.16.1 deployed to Kubernetes (V2) version 1.16.0

### Feature Area:
gcr.io/spinnaker-marketplace/halyard:1.23.2

### Description:
Error log from clouddriver pod:
```
com.netflix.spinnaker.clouddriver.kubernetes.v2.op.handler.UnsupportedVersionException: No deployment is supported at api version apps/v1
```

### Steps to Reproduce:
my deployment yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bla-bla
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bla-bla
  template:
    metadata:
      labels:
        app: bla-bla
    spec:
      containers:
        - image: 'gcr.io/xxx/bla-bla:latest'
          name: kbla-bla
          ports:
            - containerPort: 8080
```
