### ISSUE TITLE
Spinnaker EC2 provider authorization issues

### ISSUE THREAD

**Issue by dancb10** [spinnaker/spinnaker#6358]
### Issue Summary:
We had several AWS accounts added in our Spinnaker setup which were part of one team (and all members of that team had ldap permissions on these accounts). I’ve seen that the first account registered in Spinnaker acts as the “primaryAccount”.
We’ve onboarded a new account from another team and noticed a really strange thing when trying to deploy in this new account:

- If a user that doesn’t have ldap permissions to access the primary account tries to deploy in this new account (in which he has permissions) the execution fails with “Access denied to account primaryAccount”. Note, the user is trying to deploy in this new account which has nothing to do with the primaryAccount.
- If a user that has access in both the primaryAccount and the new account runs the same pipeline with the same parameters, the execution works.

Does Spinnaker tries to do something in this primaryAccount whenever you deploy in any another account? Or are there some permissions constrains? Have you ever encountered such issue?

### Cloud Provider(s):
AWS EC2

### Environment:
Spinnaker 1.22.1

### Feature Area:
Onboarding accounts/authorization 

### Steps to Reproduce:
- Create the first account with some ldap groups .e.g:
```
        - name: testaccount1
          account_id: xxxxxx
          assume_role: role/spinnakermanaged
          regions: "us-east-1"
          read_permissions:
            - group1
          write_permissions:
            - group1
```
Once added, this account will act as the primary account

- Add another account
``` 
       - name: testaccount2
          account_id: xxxxxx
          assume_role: role/spinnakermanaged
          regions: "us-east-1"
          read_permissions:
            - group2
          write_permissions:
            - group2
```

user1 which has access to both group1 and group2 will be able to deploy in account testaccount2
user2 which has access to group2 but **NOT** group1 will **NOT** be able to deploy to account testaccount2. Spinnaker will throw and exception "Access denied to account testaccount1" when trying to deploy to testaccount2
