### ISSUE TITLE
redirects loop when I configure oauth2 settings.

### ISSUE THREAD

**Issue by jihyun00** [spinnaker/spinnaker#6421]
### Issue Summary: 
redirects loop when I configure oauth2 setting.

### Cloud Provider(s): 
k8s

### Environment: 
Spinnaker version: 1.20.6 (deployed via halyard), backend mysql + redis
Oauth provider is OTHER (keycloak)
Authz provider type is EXTERNAL (FILE)

### Feature Area:
gate

### Description:
I am trying to configure oauth2 login via keycloak.
I set up spinnaker configuration below.

**.hal/config**
```
    authn:
      oauth2:
        enabled: true
        client:
          clientId: xxxxxx
          clientSecret: xxxx-xxxx-xxxxx-xxxx
          accessTokenUri: https://<keycloak url>/auth/realms/master/protocol/openid-connect/token
          userAuthorizationUri: https://<keycloak url>/auth/realms/master/protocol/openid-connect/auth
          scope: roles,email,profile
          preEstablishedRedirectUri: https://<spinnaker gate url>/login
        resource:
          userInfoUri: https://<keycloak url>/auth/realms/master/protocol/openid-connect/userinfo
        userInfoMapping:
          email: email
          firstName: given_name
          lastName: family_name
          username: preferred_username
        provider: OTHER
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
          path: /home/spinnaker/.hal/permission.yml
        ldap:
          roleProviderType: LDAP
      enabled: true
```

**gate-local.yml**
```
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
    httpsServerPort: X-Forwarded-Port

security:
  oauth2:
    enabled: true
    client:
      clientId: xxxx
      clientSecret: xxxx-xxxx-xxxxx-xxxx
      accessTokenUri: https://<keycloak url>/auth/realms/master/protocol/openid-connect/token
      userAuthorizationUri: https://<keycloak url>/auth/realms/master/protocol/openid-connect/auth
      scope: roles,email,profile
      preEstablishedRedirectUri: https://<spinnaker gate url>/login
    resource:
      userInfoUri: https://<keycloak url>/auth/realms/master/protocol/openid-connect/userinfo
      userInfoMapping:
        email: email
        firstName: given_name
        lastName: family_name
        username: preferred_username
```

After that, I tried to login to my spinnaker.
Even though I typed correct username and password via keycloak web console, but it redirects infinitely.

I turned on debug log, and I found below.

spinnaker-gate debug log
```
2021-05-06 19:26:27.317 DEBUG 1 --- [0.0-8084-exec-3] c.n.s.gate.filters.FiatSessionFilter     : Fiat session filter - found user: null
```

I'm not sure which configuration is incorrect.

### Steps to Reproduce:
Setup spinnaker configuration above.
