### ISSUE TITLE
Some Orca's orchestrations(Tasks) not migrating to SQL from Redis

### ISSUE THREAD

**Issue by shubhamc183** [spinnaker/spinnaker#6444]
### Component: Orca

I have also migrated Orca from Redis to SQL by following this https://spinnaker.io/guides/operator/orca-redis-to-sql/#deploy-a-migration-cluster where most of the application's orchestrations(Tasks) is not being migrated to SQL.

All the previous execution data has moved to `pipelines` table in `orca` database. All 807 objects are moved.
```
INFO 1 --- [igrationAgent-0] c.n.s.o.p.p.m.PipelineMigrationAgent     : [] 1 pipelines migrated (07b3e3cd-22db-4d13-8763-9dc0887a6555) [806/807]
```

Only a few of "Tasks" data has moved to `orchestrations` table in `orca` database. Somehow only 30 application is only being picked up whereas I have a lot of applications
```
[igrationAgent-0] .n.s.o.p.p.m.OrchestrationMigrationAgent : [] Found 30 applications
.n.s.o.p.p.m.OrchestrationMigrationAgent : [] 3 orchestrations to migrate (tpa-tpm) [29/30]
.n.s.o.p.p.m.OrchestrationMigrationAgent : [] 3 orchestrations migrated (tpa-tpm) [29/30]
```

**I am suspecting that Orca is only picking a limited number of the application instead of all applications**

For now, I have made SQL and REDIS both in READ mode and SQL in WRITE as well.
```
executionRepository:
  dual:
    enabled: true
    primaryName: sqlExecutionRepository
    previousName: redisExecutionRepository
  sql:
    enabled: true
  redis:
    enabled: true
```
