### ISSUE TITLE
EC2 deploy does not reliably use launch template

### ISSUE THREAD

**Issue by huynhsontung** [spinnaker/spinnaker#6497]
### Issue Summary:
EC2 deploy does not always deploy with launch template after enabling it in the clouddriver configuration.

### Cloud Provider(s):
AWS

### Environment:
Spinnaker 1.26.4

### Feature Area:
Clouddriver - AWS Launch Template

### Description:

After enabling launch template feature in the clouddriver config for specific apps, following deployments on those apps don't always use launch template. My pipeline have 3 different EC2 deploy stages and sometimes 1 or 2 of them will produce an ASG with launch configuration. There is no specific stage that always produces 1 type of result, they all seem to pick launch template or launch configuration at random.

Changing the service version number on deploy might resolve the issue. Applications that are freshly deployed with launch template from the start are not affected.

### Steps to Reproduce:

1. Follow [these instructions](https://spinnaker.io/docs/setup/other_config/server-group-launch-settings/aws-ec2/launch-templates-setup/#current-aws-user) to enable launch template with existing AWS user

2. Add these the following to clouddriver config
```yaml
aws:
  features:
    launch-templates:
      enabled: true
      allowed-applications: "<app1>:<account1>:us-east-2,<app2>:<account2>:us-east-2"
```
