### ISSUE TITLE
keycloak sso auth fail to set up 

### ISSUE THREAD

**Issue by huifanglu2018** [spinnaker/spinnaker#6498]
### Issue Summary:
I am setuping the sso login to spinnaker with keycloak, but there is so few article about this. I failed to login with timeout.

### Cloud Provider(s):
kubernetes

### Environment:
kubernetes

### Feature Area:
gate

### Description:
I want to enable keycloak sso auth with spinnaker, so I configure as below:
hal config:
```
    authn:
      oauth2:
        enabled: true
        client:
          clientId: spinnaker
          clientSecret: 4cca0562-78eb-41fd-8f3f-abae86f9be87
          accessTokenUri: https://keycloak.ipwg.com/auth/realms/app/protocol/openid-connect/token
          userAuthorizationUri: https://keycloak.ipwg.com/auth/realms/app/protocol/openid-connect/auth
          scope: roles,email,profile
          preEstablishedRedirectUri: http://spin-gate.spinnaker/login
          useCurrentUri: true
        resource:
          userInfoUri: https://keycloak.ipwg.com/auth/realms/app/protocol/openid-connect/userinfo
        userInfoMapping:
          email: email
          firstName: given_name
          lastName: family_name
          username: preferred_username
        provider: OTHER
      saml:
        enabled: false
        userAttributeMapping: {}
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: false
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
          path: /home/spinnaker/permissions.yml
        ldap:
          roleProviderType: LDAP
      enabled: true
```
permission.yml
```
users:
 - username: spinnaker
   roles:
   - admin
```
gate-local.yml

```
---
server:
  tomcat:
    protocolHeader: X-Forwarded-Proto
    remoteIpHeader: X-Forwarded-For
    internalProxies: .*
#    httpsServerPort: X-Forwarded-Port

security:
  oauth2:
    enabled: true
    client:
      clientId: spinnaker
      clientSecret: 4cca0562-78eb-41fd-8f3f-abae86f9be87
      accessTokenUri: https://keycloak.ipwg.com/auth/realms/app/protocol/openid-connect/token
      userAuthorizationUri: https://keycloak.ipwg.com/auth/realms/app/protocol/openid-connect/auth
      scope: roles,email,profile
      preEstablishedRedirectUri: http://spin-gate.spinnaker/login
    resource:
      userInfoUri: https://keycloak.ipwg.com/auth/realms/app/protocol/openid-connect/userinfo
    userInfoMapping:
      email: email
      firstName: given_name
      lastName: family_name
      username: preferred_username
    provider: OTHER

```
keycloak:

![image](https://user-images.githubusercontent.com/41109801/127590560-5893a614-60cb-4e7d-9353-c552f756c8eb.png)
![image](https://user-images.githubusercontent.com/41109801/127590577-821d08f7-912b-4ef2-b4a2-5d34fa91ad43.png)

gete log:
```
2021-07-30 02:18:30.983 DEBUG 1 --- [0.0-8084-exec-2] o.s.web.client.RestTemplate : HTTP POST https://keycloak.ipwg.com/auth/realms/app/protocol/openid-connect/token
```
keycloak log:
```
<html>
<body>
<!--StartFragment-->

02:17:22,809 DEBUG [org.keycloak.protocol.AuthorizationEndpointBase] (default task-26) Sent request to authz endpoint. Created new root authentication session with ID 'dd24ab05-87e4-454e-9f05-8d4476554ce9' . Client: spinnaker . New authentication session tab ID: Tt23-sHIBmM
--
Fri, Jul 30 2021 10:17:30 am | 02:17:30,732 DEBUG [org.keycloak.services.resources.SessionCodeChecks] (default task-30) Will use client 'spinnaker' in back-to-application link
Fri, Jul 30 2021 10:17:30 am | 02:17:30,901 DEBUG [org.keycloak.events] (default task-30) type=LOGIN, realmId=app, clientId=spinnaker, userId=96250697-747d-4406-934d-ca0d748f1d6a, ipAddress=10.200.9.139, auth_method=openid-connect, auth_type=code, response_type=code, redirect_uri=http://spin-gate.spinnaker/login, consent=no_consent_required, code_id=dd24ab05-87e4-454e-9f05-8d4476554ce9, username=spinnaker, response_mode=query, authSessionParentId=dd24ab05-87e4-454e-9f05-8d4476554ce9, authSessionTabId=Tt23-sHIBmM

<!--EndFragment-->
</body>
</html>
```
then it stoped as below and timeout.
![image](https://user-images.githubusercontent.com/41109801/127589946-8c4d57e4-b8c4-403f-899f-7de4bccf17a0.png)
![image](https://user-images.githubusercontent.com/41109801/127590151-5922ad0f-aff1-4114-8adb-072b7ef257f6.png)

no other log found in gate.
so what should I do for to configure it? or debug it.
It trouble me so long. please help.
thanks so much!

### Steps to Reproduce:
configure keycloak as above and configure with halyard as above

### Additional Details:

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

* An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 
* Before you open an issue, please [check if a similar issue already exists](https://github.com/spinnaker/spinnaker/issues) or has been closed before.
* Make sure you have read through the [Spinnaker FAQ](https://www.spinnaker.io/community/faqs/) and [Halyard FAQ](https://www.spinnaker.io/setup/quickstart/faq/) to provide as much information as possible.

Descriptions:

* Issue Summary: A brief description of what you're seeing.
* Cloud Provider: AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc. Please assign a label from the right so your issue can be properly sorted.
* Environment: As much information about your Spinnaker environment and configuration that might be relevant to the issue. For example: "I am running Spinnaker using the Amazon images to deploy into AWS and GCP."
* Feature Area: Notifications, Pipelines, UI, Jenkins, etc. Please assign a label from the right so your issue can be properly sorted.
* Description: The behavior you expect to see, and the actual behavior.
* Steps to reproduce: Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.
* Additional Details: Additional information such as screenshots and exception logs.
