### ISSUE TITLE
Baking with kustomize and "replacements" fails

### ISSUE THREAD

**Issue by beatrausch** [spinnaker/spinnaker#6509]
### Issue Summary:
Exception in child pipeline stage (Deploy TUI: Deploy): Exception in child pipeline stage (Deploy to Cluster: Bake (Manifest)): Bake failed: Error: json: unknown field "replacements"

### Cloud Provider(s):
Bare-Metal K8 with Ceph S3

### Environment:
Spinnaker 1.25.4 

### Feature Area:
Baking with kustomize

### Description:
Expectation: Spinnaker should generate the same output as running` kustomize build someoverlay`

Example replacement. 

````
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- source:
    kind: Deployment
    fieldPath: metadata.name
  targets:
  - select: 
      name: my-resource
````

### Steps to Reproduce:
Bake overlay with replacements fails

### Additional Details:
rosco kustomize version
{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:linux GoArch:amd64}
