### ISSUE TITLE
Getting exception while migrating front50 backend data from minio(S3) to mysql 

### ISSUE THREAD

**Issue by Galileo1** [spinnaker/spinnaker#6521]
### Issue Summary:
Getting Exception while migrating front50 backend data to mysql from minio(S3) when composite storage service is enabled.
```
  compositeStorageService:
      enabled: true 
```
### Cloud Provider(s):
KubernetesV2

### Environment:

kubernetes(On Premise)

### Feature Area:

Front50

### Description:

I have an issue with setting up migration in Front50 with SQL as backend. We have used minio(s3 api) as our backend so far. We are in process of migrating all the data to mysql.

### Steps to Reproduce:

Configuration for front50 is as below. We don't have tons of data. So using single front50 instance to enable migration.

```
spinnaker:
  migration:
    enabled: true 
    primaryClass: com.netflix.spinnaker.front50.model.SqlStorageService 
    previousClass: com.netflix.spinnaker.front50.model.S3StorageService 
    compositeStorageService:
      enabled: true 
      reads:
        primary: false 
        previous: true

azs: 
  enabled: false
gcs:
  enabled: false
oracle: 
  enabled: false
redis:
  enabled: false
s3:
  accessKeyId: ${MINIO_ACCESS_KEY_ID}
  bucket: spinnaker
  enabled: true
  endpoint: http://spinnaker-minio:9000
  pathStyleAccess: true
  rootFolder: front50
  secretAccessKey: ${MINIO_SECRET_ACCESS_KEY}
sql:
  enabled: true
  connectionPools:
    default: 
      default: true
      jdbcUrl: jdbc:mysql://spinnaker-mysql:3306/front50
      user: front50_service
      password: ${MYSQL_PASSWORD}
      connectionTimeout: 10000
      maxLifetime: 30000
      maxPoolSize: 50
  migration:
    jdbcUrl: jdbc:mysql://spinnaker-mysql:3306/front50
    user: front50_migrate
    password: ${MYSQL_PASSWORD}


```

### Additional Details:

Exception :

`2021-09-02 03:50:15.198 ERROR 1 --- [           main] o.s.b.web.embedded.tomcat.TomcatStarter  : Error starting Tomcat context. Exception: org.springframework.beans.factory.BeanCreationException. Message: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthContributorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthContributorRegistry]: Factory method 'healthContributorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationDAOHealthIndicator' defined in class path resource [com/netflix/spinnaker/front50/config/Front50WebConfig.class]: Unsatisfied dependency expressed through method 'applicationDAOHealthIndicator' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'applicationDAO' defined in class path resource [com/netflix/spinnaker/front50/config/CommonStorageServiceDAOConfig.class]: Unsatisfied dependency expressed through method 'applicationDAO' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compositeStorageService' defined in class path resource [com/netflix/spinnaker/config/CompositeStorageServiceConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.netflix.spinnaker.front50.model.CompositeStorageService]: Factory method 'compositeStorageService' threw exception; nested exception is java.util.NoSuchElementException: Collection contains no element matching the predicate.
`

**Comment by Galileo1** [comment]
I have also tried to spin up another front50 pod with following config just to enable migration. This pod is not attached to LB. Pretty much followed [these](https://spinnaker.io/docs/setup/productionize/persistence/front50-sql/#how-netflix-migrated-front50-from-s3-to-sql) steps.

```
spinnaker:
  migration:
    enabled: true 

azs: 
  enabled: false
gcs:
  enabled: false
oracle: 
  enabled: false
redis:
  enabled: false
s3:
  accessKeyId: ${MINIO_ACCESS_KEY_ID}
  bucket: spinnaker
  enabled: true
  endpoint: http://spinnaker-minio:9000
  pathStyleAccess: true
  rootFolder: front50
  secretAccessKey: ${MINIO_SECRET_ACCESS_KEY}
sql:
  enabled: true
  connectionPools:
    default: 
      default: true
      jdbcUrl: jdbc:mysql://spinnaker-mysql:3306/front50
      user: front50_service
      password: ${MYSQL_PASSWORD}
      connectionTimeout: 10000
      maxLifetime: 30000
      maxPoolSize: 50
  migration:
    jdbcUrl: jdbc:mysql://spinnaker-mysql:3306/front50
    user: front50_migrate
    password: ${MYSQL_PASSWORD}bash-5.0$ 
```

The main front50 pod has following  configurations. This is attached to LB and receiving traffic.

```
spinnaker:
  migration:
    primaryClass: com.netflix.spinnaker.front50.model.SqlStorageService 
    previousClass: com.netflix.spinnaker.front50.model.S3StorageService 
    compositeStorageService:
      reads:
        primary: false 
        previous: true

azs: 
  enabled: false
gcs:
  enabled: false
oracle: 
  enabled: false
redis:
  enabled: false
s3:
  accessKeyId: ${MINIO_ACCESS_KEY_ID}
  bucket: spinnaker
  enabled: true
  endpoint: http://spinnaker-minio:9000
  pathStyleAccess: true
  rootFolder: front50
  secretAccessKey: ${MINIO_SECRET_ACCESS_KEY}
sql:
  enabled: true
  connectionPools:
    default: 
      default: true
      jdbcUrl: jdbc:mysql://spinnaker-mysql:3306/front50
      user: front50_service
      password: ${MYSQL_PASSWORD}
      connectionTimeout: 10000
      maxLifetime: 30000
      maxPoolSize: 50
  migration:
    jdbcUrl: jdbc:mysql://spinnaker-mysql:3306/front50
    user: front50_migrate
    password: ${MYSQL_PASSWORD}

```

The writes are going to mysql for sure. I can see there are row in applications and pipeline-templates table. But migration is not working.
