### ISSUE TITLE
Proposal: Moniker Support for Clouddriver AWS provider

### ISSUE THREAD

**Issue by antdrums** [spinnaker/spinnaker#6536]
# Moniker support for AWS Clouddriver resources

| | |
|-|-|
| **Status**     | _**Proposed**_ |
| **RFC #**      | _Update after PR has been made_ |
| **Author(s)**  | Ananthapadmanabhan Ranganathan (`@antdrums`), Dan Everton (`@deverton`) |
| **SIG / WG**   | AWS SIG |

:red_circle:**TODO:** Some portions are not filled out, will be filled out based on feedback from the AWS SIG

## Overview

The default naming convention for the AWS Provider in Spinnaker prevents the use of the dash (-) character in application names. This is due to the use of the `Asgard` naming convention, and the use of `Frigga` to parse the application names. The use of Moniker for name parsing on the Kubernetes V2 provider and the ECS provider shows that it's possible to remove this limitation. This proposal is to aim to use Moniker to manage name parsing on AWS EC2 based deployments as well. 

### Goals and Non-Goals

With the changes outlined in this proposal, we intend to use a name and tag management interface in the AWS provider which works with Moniker to allow flexible naming conventions for the application names. 

## Motivation and Rationale

Currently, the naming conventions enforced via Frigga are not flexible. There are users/companies with large fleets of applications that already have hyphens/dashes in their names. In the current state, those applications cannot onboard the AWS provider in order to perform Spinnaker native EC2.

There have been multiple requests/issues raised around this limitation in clouddriver-aws: https://github.com/spinnaker/spinnaker/issues/5674, https://github.com/spinnaker/spinnaker/issues/6375

The name management process has been fixed in other providers: 
* ECS: https://github.com/spinnaker/clouddriver/pull/4936
* CF: https://github.com/spinnaker/clouddriver/pull/4670
* Kubernetes V2: https://github.com/spinnaker/clouddriver/pull/1910
* GCE: https://github.com/spinnaker/clouddriver/pull/3258

With the addition of moniker support to clouddriver-aws, it'll bring the provider usage and experience in-line with the other clouddriver providers, and allow users to be able to onboard applications without being constrained by the Asgard naming convention.

Since we have a large fleet of applications deployed on EC2 at Expedia, we would be implementing and testing these changes via a fork to validate these changes. 

## Timeline

:red_circle:**TODO:** _What is the proposed timeline for the implementation? This timeline should
encompass the entire scope of the project, not just the initial merge of the
code. If applicable, it should include when the feature will be ready for
testing by potential customers, when you will address their feedback, and when
the code will be considered production-ready._

### User facing configuration
Service names are constructed as before, however if moniker support is enabled, the moniker values are represented as tags on the EC2 instances, ASGs (and Cloudformation Stacks, if used) and are propagated to loadbalancers and other supporting infrastructure. The tag keys are similar to the ECS or Kubernetes V2 provider:

Key	| Value
----|----
`moniker.spinnaker.io/application` | The application name
`moniker.spinnaker.io/cluster` | The application cluster
`moniker.spinnaker.io/stack` | Stack the application belongs to
`moniker.spinnaker.io/detail` | Additional detail
`moniker.spinnaker.io/sequence` | The version sequence number

With a standard configuration the default Spinnaker naming strategy will be used and no tags will be applied:

```yaml
aws:
  enabled: true
  accounts:
    - name: ec2-cicddev-test
      accountId: '111111111111'
      regions:
        - name: us-east-1
        - name: us-west-2
      assumeRole: role/spinnakerManaged
```

To have moniker tags applied at the account level you can set the namingStrategy field to tags like:

```yaml
aws:
  enabled: true
  accounts:
    - name: ec2-cicddev-test
      accountId: '111111111111'
      regions:
        - name: us-east-1
        - name: us-west-2
      assumeRole: role/spinnakerManaged
      namingStrategy: "tags"
```

Or to enable it for all accounts:

```yaml
aws:
  enabled: true
  defaultNamingStrategy: "tags"
  accounts:
    - name: ec2-cicddev-test
      accountId: '111111111111'
      regions:
        - name: us-east-1
        - name: us-west-2
      assumeRole: role/spinnakerManaged
```

You can also mix strategies between accounts:

```yaml
aws:
  enabled: true
  defaultNamingStrategy: "tags"
  accounts:
    - name: ec2-cicddev-test
      accountId: '111111111111'
      regions:
        - name: us-east-1
        - name: us-west-2
      assumeRole: role/spinnakerManaged
    - name: ec2-cicddev-prod
      accountId: '222222222222'
      regions:
        - name: us-east-1
        - name: us-west-2
      assumeRole: role/spinnakerManaged
      namingStrategy: "default"
```

Based on #3258 with the tag key convention taken from the Kubernetes V2 provider.

### Internal Implementation

We will be introducing a tag and name handling interface in `clouddriver-aws` that would replace usages of Frigga's `Names` library, specifically `Names.parseName(name)`. Instead, this interface would have code to firstly check and determine if the resource has relevant tagging for moniker. If so, it would derive the names of objects based on the populated `moniker` tags. If the tags are absent (or moniker is not configured for the account, based on the AWS config), then the interface uses Frigga to parse the names. 

:red_circle:**TODO:** Will be adding tag examples and parsing examples here, as well as a high level logic for the tag/name interface. 

### Dependencies

_What existing internal and external systems does this proposal depend on?_
This depends on the following Internal systems: Frigga, Moniker, clouddriver-aws

_Are any new dependencies (libraries or systems) being introduced?_
A new name and tag handling interface for `clouddriver-aws` will be introduced

## Drawbacks

_Why should we **not** do this?_
This adds complexity by refactoring deeply embedded functionality in `clouddriver-aws` to maintain backwards compatibility, and then builds upon that to add the naming flexibility. This was investigated before in https://github.com/spinnaker/spinnaker/issues/5674 but not pursued because of the complexity involved. 

## Prior Art and Alternatives

_What other approaches did you consider?_
_What existing solutions are close but not quite right?_
_How will this project replace or integrate with the alternatives?_

The "The Motivation and Rationale" section above contains links to `moniker` based implementations in other cloud providers. As far as the clouddriver `AWS EC2` provider is concerned, there is no alternative at the moment. 

## Known Unknowns

What parts of the design do you expect to resolve through the RFC process?
1. High level design of the name/tag handling interface and handling of backwards compatibility with Frigga based name parsing
2. Tagging strategies around different resources in AWS when using `moniker`, to align with the name parsing logic in [Keys.groovy](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-aws/src/main/groovy/com/netflix/spinnaker/clouddriver/aws/cache/Keys.groovy) etc
3. Derived names of applications and resources, and visibility and user experience in Deck
4. Operations, security, privacy and compliance related aspects

What parts of the design do you expect to resolve through implementation before stabilization?
1. Implementation of the interface and handling of backwards compatibility with Frigga based name parsing
2. Tag application code and nuances while creating and updating AWS resources
3. Behaviour of the system when there are both moniker-tagged and Frigga resources on the same AWS account

What related issues do you consider out of scope for this RFC that could be addressed in the future?

- Currently, migration of existing onboarded applications into a moniker tagged system is not in the scope of this proposal, but is something most users are likely to want in the future. 
- We could allow for custom tags to define particular values. For instance, we have our apps that already use an `Application` tag. It would be great if we can specify that as the required application name tag instead of `moniker.spinnaker.io/application`
- In the future, this work could create a pluggable naming library that can replace Frigga usage, and can function as a common interface across Clouddriver providers

## Security, Privacy, and Compliance

:red_circle:**TODO:**
_What security/privacy/compliance aspects should be considered?_

_If you are not certain, never assume there aren't any._
_Always talk to the Security SIG or Technical Oversight Committee._

## Operations

:red_circle:**TODO:**
_Are you adding any new, regular human processes, or extra work for any users?_
We expect these changes to be seamlessly backwards compatible with existing deployments and applications. For users who want to enable tag based naming, they need to update their configuration accordingly and deploy an updated version of spinnaker with those changes. 

_What telemetry is needed to verify correct behavior?_
_What tooling needs to be introduced for on-going support?_

## Risks
:red_circle:**TODO:**
_What known risks exist?_
_What factors may complicate your project?_

_Include: security, complexity, compatibility, latency, service immaturity, lack of team expertise, etc._

## Future Possibilities
:red_circle:**TODO:**
_What are the natural extensions and evolution of this RFC that would affect the project as a whole?_

- Migration of existing onboarded applications into a moniker tagged system
- We could allow for custom tags to define particular values. For instance, we have our apps that already use an `Application` tag. It would be great if we can specify that as the required application name tag instead of `moniker.spinnaker.io/application`
- In the future, this work could create a pluggable naming library that can replace Frigga usage, and can function as a common interface across Clouddriver providers

_Feel free to dump ideas here, they're meant to get wheels turning, and won't affect the outcome of the approval process._
