### ISSUE TITLE
Kubernetes: patching image manifest doesn't work with registries running on a custom port

### ISSUE THREAD

**Issue by jzuijlek** [spinnaker/spinnaker#6543]
### Issue Summary:
When patching a manifest and the registry URL has a port number, it leads to the following error

```
The following required artifacts could not be bound: '[ArtifactKey(type=docker/image, name=gitlab.example.com:4567/pathc/to/image, version=null, location=null, reference=gitlab.example.com:4567/pathc/to/image:release-2021-10)]'.Check that the Docker image name above matches the name used in the image field of your manifest.Failing the stage as this is likely a configuration error.
```

### Environment:
Native Kubernetes v1.21.5
Spinnaker 1.23.* or newer

### Steps to Reproduce:
Create a "Patch (manifest)" stage with Patch content:

```
spec:
  template:
    spec:
      containers:
        - image: 'gitlab.example.com:4567/pathc/to/image'
          name: image
```

Run the pipeline with and provide an artifact. We use a webhook. This leads to the error mentioned above.

### Additional Details:
Reading the 1.23 release notes this stood out:
**kubernetes/artifacts**: Update Clouddriver's artifact replacement logic to replace docker images even if the image specified in the manifest includes a tag. ([d5a06c6e](https://github.com/spinnaker/clouddriver/commit/d5a06c6e80c638ad273b343e200edf4d1bc19802))

As both the port number and image tags are delimited by a colon, this is 

This mentions that **we don't need to check if this is a tag, or a port. ports will be matched lazily if they are numeric**:
https://github.com/spinnaker/clouddriver/blob/master/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/artifact/Replacer.java#L180

### Workaround:
When adding an arbitrary  tag to the image it works again:

```
spec:
  template:
    spec:
      containers:
        - image: 'gitlab.example.com:4567/pathc/to/image:sometag'
          name: image
```
