### ISSUE TITLE
 hal config deploy edit --type localdebian failed due to Unable to locate package spinnaker-igor

### ISSUE THREAD

**Issue by regardfs** [spinnaker/spinnaker#6568]
### Issue Summary:
```
W: The repository 'https://dl.bintray.com/spinnaker-releases/debians xenial Release' does not have a Release file.
E: Failed to fetch https://dl.bintray.com/spinnaker-releases/debians/dists/xenial/spinnaker/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.


E: Unable to locate package spinnaker-igor
! ERROR Error encountered running script. See above output for more
  details.

```
### Additional Details:

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

Descriptions:

**Comment by regardfs** [comment]
No one maintained this project？？

**Comment by mattgogerly** [comment]
Hey @regardfs, [Bintray was sunset earlier this year](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

I don't believe anybody in the community has created an alternative. Paging @dbyron-sf and @link108 who may know any plans in this area.

**Comment by dbyron-sf** [comment]
I don't know of any plans.  We'd love someone to add the logic to publish debians again, and even have a likely place for them to go: https://console.cloud.google.com/artifacts/apt/spinnaker-community/us/apt?project=spinnaker-community.  See also https://spinnakerteam.slack.com/archives/C091CCWRJ/p1634580581238600?thread_ts=1618254087.038400&cid=C091CCWRJ.

**Comment by NasrSyncBac** [comment]
Is there any progress on resolving this issue?

**Comment by maciej-wolny** [comment]
I have the same problem, trying to install Spinnaker on Azure
```
Err:8 https://dl.bintray.com/spinnaker-releases/debians bionic InRelease
  502  Bad Gateway [IP: 54.70.2.80 443]
```
followed by
```
E: Unable to locate package spinnaker-igor
! ERROR Error encountered running script. See above output for more
  details.
```

**Comment by viren1500** [comment]
Facing same problem "E: Unable to locate package spinnaker-igor" , any plans on publishing these packages to suitable repository or re-publishing these artifacts again.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by kskewes** [comment]
Thanks to a contributor for new spinnaker versions debs are published to https://console.cloud.google.com/artifacts/apt/spinnaker-community/us/apt?project=spinnaker-community.

We're getting close with releasing 1.27.0.

You can build the older debs from release-* branches by doing a `./gradlew buildDeb` potentially specifying a version too.

**Comment by ashleykleynhans** [comment]
@kskewes How can I contact you in Slack? I have spent more than 12 hours trying to get Spinnaker installed without any success.  I've tried building the debs as you suggested but it is unfortunately still trying to download dependencies from bintray:

```
* What went wrong:
A problem occurred configuring root project 'spinnaker'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.netflix.spinnaker.gradle:spinnaker-gradle-project:3.15.0.
     Required by:
         project :
      > Could not resolve com.netflix.spinnaker.gradle:spinnaker-gradle-project:3.15.0.
         > Could not get resource 'https://dl.bintray.com/spinnaker/gradle/com/netflix/spinnaker/gradle/spinnaker-gradle-project/3.15.0/spinnaker-gradle-project-3.15.0.pom'.
            > Could not GET 'https://dl.bintray.com/spinnaker/gradle/com/netflix/spinnaker/gradle/spinnaker-gradle-project/3.15.0/spinnaker-gradle-project-3.15.0.pom'.
               > Remote host terminated the handshake
```

**Comment by kskewes-sf** [comment]
I've moved to my work GitHub and Slack account now, but if you post in `#general` channel it'll likely be seen and I and others can jump in :)

What branch and commit are you trying to build Ashley?

I'm afraid I might have been incorrect about building older debs. :(
`spinnaker-gradle-project` also had references to bintray that were only recently removed. 
`release-1.27.x` branch builds, maybe `release-1.26.x` as well but I don't think any older branches will build unless their spinnaker gradle project version is bumped and there are probably other missing dependencies (big chain).

FWIW below is quick gist on using the new Google Artifact Registry APT repository for debians.
I haven't completely installed Spinnaker this way and validated all of the configuration and any help with that would be great.

Below steps are based on running in `ubuntu` container, some may not be required if running on Ubuntu VM or natively which has more base packages installed.
```
# start container
docker run --rm -it ubuntu

# fetch apt cache so can install packages
apt update

# install basic packages
apt install -y curl gnupg2 sudo

# setup GAR Apt registry
# https://cloud.google.com/artifact-registry/docs/os-packages/debian/configure
# https://console.cloud.google.com/artifacts/apt/spinnaker-community/us/apt
curl https://us-apt.pkg.dev/doc/repo-signing-key.gpg | sudo apt-key add -
echo 'deb https://us-apt.pkg.dev/projects/spinnaker-community apt main' | sudo tee -a /etc/apt/sources.list.d/spinnaker-artifact-registry.list
apt update

# search for spinnaker
apt-cache search spinnaker
# output below:
spinnaker-clouddriver - spinnaker-clouddriver
spinnaker-deck - spinnaker-deck
spinnaker-echo - spinnaker-echo
spinnaker-fiat - spinnaker-fiat
spinnaker-front50 - spinnaker-front50
spinnaker-gate - spinnaker-gate
spinnaker-halyard - spinnaker-halyard
spinnaker-igor - spinnaker-igor
spinnaker-kayenta - spinnaker-kayenta
spinnaker-keel - spinnaker-keel
spinnaker-orca - spinnaker-orca
spinnaker-rosco - spinnaker-rosco

# see available and selected versions
apt-cache policy spinnaker-clouddriver
# output below:
spinnaker-clouddriver:
  Installed: (none)
  Candidate: 5.76.1
  Version table:
     5.76.1 500
        500 https://us-apt.pkg.dev/projects/spinnaker-community apt/main all Packages
     5.76.0 500
        500 https://us-apt.pkg.dev/projects/spinnaker-community apt/main all Packages
     5.74.2 500
        500 https://us-apt.pkg.dev/projects/spinnaker-community apt/main all Packages

# install spinnaker dependencies
apt install wget

# install specific version
apt install spinnaker-clouddriver=5.74.2

# set a hold on version so it is not updated automatically
apt-mark hold spinnaker-clouddriver

# upgrade to specific version leaving hold in place
apt install spinnaker-clouddriver=5.76.1
```

In terms of service versions to install, the 1.27.0 BOM is currently looking like this, this is very much a .0 release (some testing but lots of changes):
```
artifactSources:
  debianRepository: https://us-apt.pkg.dev/projects/spinnaker-community
  dockerRegistry: us-docker.pkg.dev/spinnaker-community/docker
  gitPrefix: https://github.com/spinnaker
  googleImageProject: marketplace-spinnaker-release
dependencies:
  consul:
    version: 0.7.5
  redis:
    version: 2:2.8.4-2
  vault:
    version: 0.7.0
services:
  clouddriver:
    commit: c7fb1a6d7a5666681adf5c732b596c9c1c124a0b
    version: 5.74.3
  deck:
    commit: c1902676fe7cc0dbcc6327ad42cd84492f242b27
    version: 3.8.2
  echo:
    commit: 24f38e942e90de65f1e6978ff67ea0e5c8f242e8
    version: 2.32.3
  fiat:
    commit: 23cf00d96d55e02ff3e4ce2d0cd42ef614532bb7
    version: 1.28.4
  front50:
    commit: 260578adfe38a504da2bf7e7a1b5a74a75559f0b
    version: 2.23.3
  gate:
    commit: dba199e7cb2eb1d28192efda6e51b1685b8a3ecf
    version: 6.54.2
  igor:
    commit: 82e9489045f693ba0e43af38860d139a3e28eaef
    version: 4.6.4
  kayenta:
    commit: 72ca19f19e3ed84c0a31d904745ba87b118957d2
    version: 2.31.2
  monitoring-daemon:
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
    version: 1.4.0
  monitoring-third-party:
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
    version: 1.4.0
  orca:
    commit: 2a2a7abb7d905a186faed58b6235efe2854500a9
    version: 8.18.4
  rosco:
    commit: f612dd30ad6a7b491e0a9678e780d6982c3f3236
    version: 1.7.4
timestamp: '2022-04-29 07:50:37'
version: 1.27.0
```
