### ISSUE TITLE
Clouddriver logs are more or less useless

### ISSUE THREAD

**Issue by ttomsu** [spinnaker/spinnaker#657]
I feel that the logs in clouddriver have a terrible signal-to-noise ratio. There are a ton of output messages for each region for AWS that are constantly just scrolling off the screen.

Furthermore, Retrofit errors (such as 404s or 500s) are not printed to the logs, which would help in debugging issues.

@spinnaker/reviewers - Since you have this deployed in prod, do you find the current logging output helpful when debugging issues? Any objections to either eliminating (or at least reducing the verbosity) of  the AWS Caching agents?

**Comment by cfieber** [comment]
This should de-noise the output:

In `clouddriver.yml`:

````yaml
logging:
  level:
    com.netflix.spinnaker.oort.aws.provider.agent: WARN
    com.netflix.spinnaker.clouddriver.cache.LoggingInstrumentation: WARN
````

I've used the logging output to troubleshoot a few things in production so I'd rather not see it removed from the code
