### ISSUE TITLE
Connection failed after Set up Clouddriver to use SQL

### ISSUE THREAD

**Issue by minkjj** [spinnaker/spinnaker#6577]
### Issue Summary:
after applying  Set up Clouddriver to use SQL, intermittently sql connection is being observed.
After a while without connection, the clouddriver pod is down.

### Cloud Provider(s):
AWS/EKS 

### Environment:
spinnaker version 1.26.6 running on EKS 1.19
RDS 5.7.mysql_aurora.2.07.2

### Feature Area:
clouddriver

### Description:

**clouddriver log**
2021-12-20 02:08:30.936 ERROR 1 --- [gentScheduler-0] c.n.s.c.s.c.SqlClusteredAgentScheduler   : Failed running cache agents

org.springframework.dao.TransientDataAccessResourceException: jOOQ; SQL [delete from cats_agent_locks where (agent_name = ? and lock_expiry = ?)]; default - Connection is not available, request timed out after 5802ms.; nested exception is java.sql.SQLTransientConnectionException: default - Connection is not available, request timed out after 5802ms.

ERROR 1 --- [0-7002-exec-264] c.n.spinnaker.cats.sql.cache.SqlCache : Failed searching for identifiers type: clusters glob: kubernetes.v2:logical:clusters:*:*:* reason: jOOQ; SQL [select id from cats_v1_clusters where id like ?]; default - Connection is not available, request timed out after 6048ms.; nested exception is java.sql.SQLTransientConnectionException: default - Connection is not available, request timed out after 6048ms.

2021-12-03T14:51:18.527803Z 2978435 [Note] Aborted connection 2978435 to db: 'spin_clouddriver' user: 'cache_service' host: '10.41.147.50' (Got an error reading communication packets)
2021-12-03T14:51:43.499132Z 2978784 [Note] Aborted connection 2978784 to db: 'unconnected' user: 'unauthenticated' host: '10.41.147.50' (Got an error reading communication packets)
2021-12-03T14:58:00.284414Z 2981417 [Note] Aborted connection 2981417 to db: 'unconnected' user: 'unauthenticated' host: '10.41.147.50' (Got an error reading communication packets)

### Steps to Reproduce:

halconfig setting
/profile/clouddriver-local.yml
```yaml
sql:
    enabled: true
    # read-only boolean toggles `SELECT` or `DELETE` health checks for all pools.
    # Especially relevant for clouddriver-ro and clouddriver-ro-deck which can
    # target a SQL read replica in their default pools.
    read-only: false
    taskRepository:
        enabled: true
    cache:
        enabled: true
        # These parameters were determined to be optimal via benchmark comparisons
        # in the Netflix production environment with Aurora. Setting these too low
        # or high may negatively impact performance. These values may be sub-optimal
        # in some environments.
        readBatchSize: 500
        writeBatchSize: 300
    scheduler:
        enabled: true
        # Enable clouddriver-caching's clean up agent to periodically purge old
        # clusters and accounts. Set to true when using the Kubernetes provider.
    unknown-agent-cleanup-agent:
        enabled: false
    connectionPools:
        default:
            default: true
            jdbcUrl: jdbc:mysql://cache-mysql.common-prd-apne2:2222/spin_clouddriver
            user: cache_service
            password: @@@@@@@@@@@@
            maxPoolSize: 30
            # password: depending on db auth and how spinnaker secrets are managed
            # The following tasks connection pool is optional. At Netflix, clouddriver
            # instances pointed to Aurora read replicas have a tasks pool pointed at the
            # master. Instances where the default pool is pointed to the master omit a
            # separate tasks pool.
        tasks:
            user: cache_service
            jdbcUrl: jdbc:mysql://cache-mysql.common-prd-apne2:2222/spin_clouddriver
            password: @@@@@@@@@@@@
    migration:
        user: cache_migrate
        jdbcUrl: jdbc:mysql://cache-mysql.common-prd-apne2:2222/spin_clouddriver
        password:@@@@@@@@@@@@
redis:
    enabled: false
    cache:
        enabled: false
    scheduler:
        enabled: false
    taskRepository:
        enabled: false
```
