### ISSUE TITLE
Unable to deploy networkpolicies

### ISSUE THREAD

**Issue by davidp1404** [spinnaker/spinnaker#6579]
### Issue Summary:
My setup works fine but when I add a networkpolicy to my deployment it fails reporting this error:
```
Exception ( Deploy Manifest )
deployKubernetesManifest.deployKubernetesManifest.networkPolicy.Error reading kind [networkPolicy]. Please check connectivity and access permissions to the cluster
```

![image](https://user-images.githubusercontent.com/58428863/147553508-63ffe51e-0084-46fa-898b-e2436a3b8327.png)

I use this ClusterRole for the spinnaker-serviceaccount linked:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spinnaker-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - configmaps
  - events
  - replicationcontrollers
  - serviceaccounts
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - secrets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - get
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - list
- apiGroups:
  - extensions
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/scale
  - ingresses
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/proxy
  - pods/portforward
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  - ingresses
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
```

### Environment:
```
bash-5.0$ hal config
artifact       ci             edit           generate       metric-stores  provider       repository     stats          version
canary         deploy         features       list           notification   pubsub         security       storage        webhook
bash-5.0$ hal config version
+ Get current deployment
  Success
+ Get Spinnaker version
  Success
1.25.7
```
### Steps to Reproduce:
Add this simple networkpolicy to my deployment:
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: demoapp01
  name: demoapp01-np
  namespace: '${ parameters.namespace }'
spec:
  podSelector:
    matchLabels:
      app: demoapp01
  ingress:
    - from:
        - podSelector: {}
      ports:
        - port: 80
    - from:
        - namespaceSelector: {}
      ports:
        - port: 80
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - port: 80
```

### Additional Details:
```
bash-5.0$ hal config list
+ Get all deployment configurations
  Success
+ Retrieved all deployments.
- name: default
  version: 1.25.7
  providers:
    appengine:
      enabled: false
      accounts: []
    aws:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
    azure:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      clusters: []
    dockerRegistry:
      enabled: false
      accounts: []
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        useInternalIp: false
    huaweicloud:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
    kubernetes:
      enabled: true
      accounts:
      - name: k8spre02-account
        requiredGroupMembership: []
        permissions: {}
        dockerRegistries: []
        providerVersion: V2
        context: spinnaker@k8spre02.edosdp.ericsson.se
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces:
        - '[bmas-ndo-adpmxe'
        - bmas-ndo-cogopt
        - bmas-ndo-unit-g]
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/spinnaker/.kube/config
        rawResourcesEndpointConfig:
          kindExpressions: []
          omitKindExpressions: []
        oAuthScopes: []
        onlySpinnakerManaged: true
      - name: k8spre01-account
        requiredGroupMembership: []
        permissions: {}
        dockerRegistries: []
        providerVersion: V2
        context: spinnaker@k8spre01.edosdp.ericsson.se
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/spinnaker/.kube/config
        rawResourcesEndpointConfig:
          kindExpressions: []
          omitKindExpressions: []
        oAuthScopes: []
        onlySpinnakerManaged: true
      primaryAccount: k8spre02-account
    tencentcloud:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
    oracle:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: oci.json
        baseImages: []
    cloudfoundry:
      enabled: false
      accounts: []
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: k8spre02-account
    imageVariant: SLIM
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    customSizing: {}
    sidecars: {}
    initContainers: {}
    hostAliases: {}
    affinity: {}
    tolerations: {}
    nodeSelectors: {}
    gitConfig:
      upstreamUser: spinnaker
    livenessProbeConfig:
      enabled: false
    haServices:
      clouddriver:
        enabled: false
        disableClouddriverRoDeck: false
      echo:
        enabled: false
  persistentStorage:
    persistentStoreType: s3
    azs: {}
    gcs:
      rootFolder: front50
      bucketLocation: ''
    redis: {}
    s3:
      bucket: spin-715f1001-e0e3-4411-bcd9-e582499ab7b6
      rootFolder: front50
      pathStyleAccess: false
      endpoint: http://172.29.57.9:9000
      accessKeyId: spinnaker-********
      secretAccessKey: spinnaker-********
    oracle: {}
  features:
    chaos: false
  metricStores:
    datadog:
      enabled: false
      tags: []
    prometheus:
      enabled: false
      add_source_metalabels: true
    stackdriver:
      enabled: false
    newrelic:
      enabled: false
      tags: []
    period: 30
    enabled: false
  notifications:
    slack:
      enabled: false
    twilio:
      enabled: false
      baseUrl: https://api.twilio.com/
    github-status:
      enabled: false
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: false
      masters: []
    travis:
      enabled: false
      masters: []
    wercker:
      enabled: false
      masters: []
    concourse:
      enabled: false
      masters: []
    gcb:
      enabled: false
      accounts: []
    codebuild:
      enabled: false
      accounts: []
  repository:
    artifactory:
      enabled: false
      searches: []
    nexus:
      enabled: false
      searches: []
  security:
    apiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://172.29.57.227:8084
    uiSecurity:
      ssl:
        enabled: false
      overrideBaseUrl: http://172.29.57.227:9000
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: false
        userAttributeMapping: {}
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: false
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
        ldap:
          roleProviderType: LDAP
      enabled: false
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    oracle:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    gitlab:
      enabled: false
      accounts: []
    gitrepo:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    helm:
      enabled: false
      accounts: []
    s3:
      enabled: false
      accounts: []
    maven:
      enabled: false
      accounts: []
    templates: []
  pubsub:
    enabled: false
    google:
      enabled: false
      pubsubType: GOOGLE
      subscriptions: []
      publishers: []
  canary:
    enabled: false
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: false
      accounts: []
    - name: datadog
      enabled: false
      accounts: []
    - name: signalfx
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    - name: newrelic
      enabled: false
      accounts: []
    reduxLoggerEnabled: true
    defaultJudge: NetflixACAJudge-v1.0
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true
  spinnaker:
    extensibility:
      plugins: {}
      repositories: {}
  webhook:
    trust:
      enabled: false
  stats:
    enabled: false
    endpoint: https://stats.spinnaker.io
    instanceId: 01FPJ9FR0V84R3B1ZDFPG8YBF1
    deploymentMethod: {}
    connectionTimeoutMillis: 3000
    readTimeoutMillis: 5000
```
