### ISSUE TITLE
Allow roles/groups to filter dockerRegistry selectable results

### ISSUE THREAD

**Issue by ricardojdsilva87** [spinnaker/spinnaker#6591]
### Issue Summary:
Permissions under dockerRegistry accounts are not able to filter the results showed to the user when choosing a docker registry
The same filters on permissions work on the ci configurations for Jenkins for example.

### Cloud Provider(s):
AWS

### Environment:
Running on halyard
Spinnaker v1.26.6
Running in HA with external Redis and Aurora database

### Description:
The goal would be having the same behaviour on the docker registry option that exists for the ci (Jenkins). A user that do not have the allowed roles the option is not showed to him. The same behaviour happens when choosing a kubernetes account on where to deploy.

These are the current example configurations:

For the dockerregistries:
```
    dockerRegistry:
      enabled: true
      accounts:
      - name: example_docker_registry
        environment: DEV
        requiredGroupMembership: []
        permissions:
          READ:
          - role1
          WRITE:
          - role1
        address: https://docker.registry.com
        username: encrypted:secrets-manager!r:<region>!s:<secret-id>!k:<key>
        password: encrypted:secrets-manager!r:<region>!s:<secret-id>!k:<key>
        email: email@test.com
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 5
        paginateSize: 100
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories:
        - repo1/test
        - repo2/tes5
```

For the Jenkins CI
```
  ci:
    jenkins:
      enabled: true
      masters:
      - name: Jenkins MBIO
        permissions:
          READ:
          - role1
          WRITE:
          - role1
        address: https://jenkins.url.com/path_to_job_of_role1
        username: encrypted:secrets-manager!r:<region>!s:<secret-id>!k:<key>
        password: encrypted:secrets-manager!r:<region>!s:<secret-id>!k:<key>
```

The same behaviour happens with a cluster account, when adding roles to the permissions only the selected users are allowed to choose them:
```
    kubernetes:
      enabled: true
      accounts:
      - name: cluster1
        environment: DEV
        requiredGroupMembership: []
        permissions:
          READ:
          - role1
          WRITE:
          - role1
        dockerRegistries:
        - accountName: dockerregistry1
          namespaces: []
        - accountName: dockerregistry2
          namespaces: []
        providerVersion: V2
        context: k8scontext
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: encryptedFile:s3!b:<bucket-name>!r:<region>!f:<S3 file path>
        rawResourcesEndpointConfig:
          kindExpressions: []
          omitKindExpressions: []
        oAuthScopes: []
        onlySpinnakerManaged: true
```

If there are any logs that might be helpfull, please let me know how an I get them. The idea is that since all of these types of resources are managed by clouddriver, the permissions part would be also managed by fiat and would work for all of them.

Thanks
