### ISSUE TITLE
Allow artifacts configuration to have permissions enabled

### ISSUE THREAD

**Issue by ricardojdsilva87** [spinnaker/spinnaker#6592]
### Issue Summary:
Allow artefacts configuration to have permissions enabled like it's done in clusters, docker registries, jenkins ci so that the view can be filtered and only show the authorised artefacts

### Cloud Provider(s):
AWS

### Environment:
Running on halyard
Spinnaker v1.26.6
Running in HA with external Redis and Aurora database

### Description:
Would like to have enabled a feature to allow artefacts to be filtered on the UI based on the permissions set, like it's done with cluster, jenkins ci, etc.
For example for an helm chart type artifact we would have:
```
    helm:
      enabled: true
      accounts:
      - name: helm_chart_role_1
        permissions:
          READ:
          - role1
          WRITE:
          - role1
        repository: https://path_to_charts
        username: encrypted:secrets-manager!r:<region>!s:<id>!k:<key>
        password: encrypted:secrets-manager!r:<region>!s:<id>!k:<key>
```

That would allow to view and select certain repos from the Manifest artifact selection list:
![image](https://user-images.githubusercontent.com/12953702/150357270-d0c7dade-69f2-4d20-886f-bfc75c78797e.png)

Thanks
