### ISSUE TITLE
CloudBuild private worker pool not found

### ISSUE THREAD

**Issue by sparkacus** [spinnaker/spinnaker#6600]
I'm trying to run a GCB (Google Cloud Build) step as a text build definition source, but when executing the stage it errors.

Example manifest:

```
steps:
  - args:
      - '-c'
      - 'echo hello'
    entrypoint: bash
    name: gcr.io/cloud-builders/git
options:
  pool:
    name: projects/PROJECT_NAME/locations/REGION/workerPools/WORKER_POOL_NAME
```

So I'm trying to run this GCB using a private worker pool (names have been obfuscated) which does exist, but when running via Spinnaker results in the following error (found via the execution source):

```
"errors" : [ {
    "domain" : "global",
    "message" : "workerpool not found: \"PATH_TO_WORKER_POOL"",
    "reason" : "notFound"
 ```
 
Using gcloud locally the manifest runs perfectly fine.

After some Googling it would appear that some clients need to support overriding the region (or endpoint) in which GCB runs: https://issuetracker.google.com/issues/193685195?pli=1

I'm my specific use case I need to run the manifest as a text based source so that I can inject Spinnaker parameters, which I don't think is possible when using a pre-defined trigger. 

Any help would be appreciated.
