### ISSUE TITLE
RBAC - giving Read access to application, gives full access to Clusters/Load Balancers/Firewalls

### ISSUE THREAD

**Issue by aburkevics** [spinnaker/spinnaker#6619]
### Issue Summary:
Managing and Executing pipelines is not allowed, but creating and managing(e.g. scaling or deleting) Server Groups, Load Balancers  and Firewalls is still possible. Applicaiton-level access management was tested both by directly setting access to application in UI and separately by setting access through `fiat-local.yml` using application prefixes.

Testing the same permission setup in application where AWS cloud provider is used, creating resources throws an error "Access denied to application <appname>" as expected:
![image](https://user-images.githubusercontent.com/56545528/156786229-b957fa00-7946-44bb-a25f-9b521fa78108.png)

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker (v1.26.6) deployment is configured and managed with Halyard (us-docker.pkg.dev/spinnaker-community/docker/halyard:1.44.1) and some service-specific config directly in files (profiles & service-settings). Spinnaker is deployed in k8s cluster using kubernetes provider.

`fiat-local.yml` is used to define the "superadmin" role and allow only this role to create applications as well as defined access to applications with prefix "swagger-*" & "erp":
```
fiat:
  admin:
    roles:
      - spinnaker-staging-admins
  restrictApplicationCreation: true
auth:
  permissions:
    provider:
      application: aggregate
    source:
      application:
        prefix:
          enabled: true
          prefixes:
          - prefix: "*"
            permissions:
              CREATE:
              - "spinnaker-staging-admins"
          - prefix: "swagger-*"
            permissions:
              READ:
              - "spinnaker-staging-ca-read"
              - "spinnaker-staging-ca-execute"
              - "spinnaker-staging-cicd"
              EXECUTE:
              - "spinnaker-staging-ca-execute"
              - "spinnaker-staging-cicd"
          - prefix: "erp"
            permissions:
              READ:
              - "spinnaker-staging-ca-read"
              - "spinnaker-staging-ca-execute"
              - "spinnaker-staging-cicd"
              EXECUTE:
              - "spinnaker-staging-ca-execute"
              - "spinnaker-staging-cicd"
```

Authorization & Authentication is enabled with LDAP integration.

All, except `*-read` roles have both READ & WRITE permissions on account level (for Kubernetes & AWS accounts).

### Feature Area:
Kubernetes, RBAC, Authorization, Fiat

### Description:
*Behavior*
I log in the UI with user that has only READ(or EXECUTE) permissions to applications with prefix "swagger-*" (and READ/WRITE to the cloud provider accounts). I try to manually add new Load-Balancer in Kubernetes-based account by creating the manifest and it succeeds:
![image](https://user-images.githubusercontent.com/56545528/156787921-8b613844-c95c-4336-a195-685e95af8a23.png)

Same kind of problem spans to Server Groups (and I expect Firewalls) and also performing any actions with existing resources, like scaling or deleting the Server Group.

 *Expected*
If I do the same thing, Spinnaker should throw the error about access denied to application (like in AWS case shown in Summary).

### Steps to Reproduce:
Enable `authz` & `authn` with integration to LDAP. Create an application with Kubernetes cloud provider.
Assign some test AD group READ/WRITE permissions to the Kubernetes account and READ(or EXECUTE) permissions to the application - either via prefix configuration or directly through UI.
Log in with user which is in your test AD group and try to manually deploy a manifest in this application to the Kubernetes account.

### Additional Details:
Seems like access to Pipelines is working as expected - can't create/modify or trigger them with only READ access.

Removing READ access does what it should - user doesn't even see the application anymore.

Adding EXECUTE access allows executing pipelines as expected, but not modifying them. The other WRITE accesses are still available though, so the same problem as with only READ access is relevant.
