### ISSUE TITLE
Spin CLI broken w/ GSuite after 1.14

### ISSUE THREAD

**Issue by mr-remington** [spinnaker/spinnaker#6620]
### Issue Summary:
Spin 1.14 works fine with G-Suite oauth2 (web) but breaks for all releases after(?)

```
gate:
  endpoint: https://spinnaker-gate.company.com
auth:
  enabled: true
  oauth2:
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    authUrl: https://accounts.google.com/o/oauth2/v2/auth
    clientId: FOO.apps.googleusercontent.com
    clientSecret: FOO
    scopes:
    - email
    - profile
```

### Cloud Provider(s):
Google G-suite

### Description:
I've been setting up spinnaker and blocked for a long time here. Spinnaker using G-Suite auth all works, except the CLI throws the error with the `~/.spin/config` above with the error: `"OAuth2 Authentication failed: login failed"` 

Tried version 1.22, 1.19, 1.17. The same config will at least return a response at 1.14 on `spin pipeline list -a service`

### Steps to Reproduce:
Install latest(1.22) using the config above, watch the failure. Downgrade to 1.14 and it works
### Additional Details:
I got desperate and tried every combination of auth/token URL I could find on GitHub and from the client JSON returned from the web app in GCP. At this point im fairly sure its spin CLI related
