### ISSUE TITLE
Helm3 templating doesn't work with git-lfs subchart gzip files

### ISSUE THREAD

**Issue by a1gemmel** [spinnaker/spinnaker#6645]
### Issue Summary:

In a Bake Manifest step, using a chart with a subchart .tgz file in git-lfs gives an error:

```
Exception ( Create Bake )
Bake failed: Error: error unpacking prometheus-postgres-exporter-2.10.0.tgz in dbexporter: gzip: invalid header
```

### Cloud Provider(s):

AWS EKS

### Environment:

Spinnaker 1.26.7 running on Kubernetes

### Feature Area:

Helm3, Bake Manifest, Pipelines

### Description:

Attempting to create a Bake Manifest step using Helm3, I have a chart with a subchart. Minimal setup looks like this:

```
project
│   Chart.yaml
│   Chart.lock   
│   values.yaml
└─── charts
│   │  prometheus-postgres-exporter-2.10.0.tgz
```

Chart.yaml:
```
apiVersion: v2
appVersion: "0.10.0"
description: A chart to install prometheus-postgres-exporter
name: postgres-exporter
type: application
dependencies:
  - name: prometheus-postgres-exporter
    version: 2.10.0
    repository:  https://prometheus-community.github.io/helm-charts
version: 0.0.1
```

`prometheus-postgres-exporter-2.10.0.tgz` is a file in git-lfs, as per the configuration of the repo I'm working in.

Running `helm-template postgres-exporter .` locally works as expected.

Running the Bake Manifest in Spinnaker gives:

```
Exception ( Create Bake )
Bake failed: Error: error unpacking prometheus-postgres-exporter-2.10.0.tgz in dbexporter: gzip: invalid header
```

The same setup with a non git-lfs .tgz file works correctly, as expected.

### Steps to Reproduce:

1. Copy the minimal chart config above
2. Add `*.tgz filter=lfs diff=lfs merge=lfs -text` to your `.gitattributes` file.
3. Run `helm repo add prometheus-community https://prometheus-community.github.io/helm-charts && helm repo update && helm dependency update`
4. Create a git branch with this chart
5. Create a Bake Manifest step in a pipeline to use this chart from the git branch
