### ISSUE TITLE
Spin CLI cached token not updating (stopped after 10 redirects)

### ISSUE THREAD

**Issue by lucasoares** [spinnaker/spinnaker#6652]
### Issue Summary:

Hello.

I'm using the `spin` CLI with cacheToken configuration.

This is the configuration I'm starting with:

```
gate:
  endpoint: <my-own-spinnaker-gate>
auth:
  enabled: true
  IgnoreCertErrors: false
  oauth2:
    authUrl: https://accounts.google.com/o/oauth2/v2/auth
    tokenUrl: https://www.googleapis.com/oauth2/v4/token
    cachedToken:
      access_token: ************
      refresh_token: ************
      token_type: bearer
    scopes:
      - email
      - profile
```

After the first `spin` command, the config file is changed to:
```
Auth:
  Basic: null
  Enabled: true
  GoogleServiceAccount: null
  Iap: null
  IgnoreCertErrors: false
  Ldap: null
  OAuth2:
    AuthUrl: https://accounts.google.com/o/oauth2/v2/auth
    CachedToken:
      access_token: ***********
      expiry: "0001-01-01T00:00:00Z"
      refresh_token: ***********
      token_type: bearer
    ClientId: ""
    ClientSecret: ""
    Scopes:
    - email
    - profile
    TokenUrl: https://www.googleapis.com/oauth2/v4/token
  X509: null
Gate:
  Endpoint: <my-own-spinnaker-gate>
```

After some time all commands just stop working and I have to refresh my access token manually.

All commands I execute results in this error:
```
Could not reach Gate, please ensure it is running. Failing.
Get https://<my-own-spinnaker-gate>/login: stopped after 10 redirects
```

I'm using this [documentation](https://spinnaker.io/docs/setup/other_config/spin/#access-and-refresh-token) as reference.

### Environment:

Spinnaker version: 1.26.7
Spin version: 1.22.0
Environment: Spinnaker running on GKE

### Steps to Reproduce:

- Create the config file
- Set token and refresh token
- Wait for the token expiration
- Execute the spin command again
