### ISSUE TITLE
When refreshing properties values are read as a string literal vs. parsing it through the secret engines

### ISSUE THREAD

**Issue by jasonmcintosh** [spinnaker/spinnaker#6665]
### Issue Summary:
Refreshing credentials post initialization to read updated SCC properties causes the secrets engine to fail.  Tested against clouddriver master.  NOT tested whether other services are impacted.

### Cloud Provider(s):
Docker (likely others as well)

### Steps to Reproduce:
Setup clouddriver with:
```
        dockerRegistry:
          accounts:
          - address: someplace.example.com
            email: fake.email@armory.io
            name: repo
            passwordFile: encryptedFile:s3!r:us-west-2!b:bucket-with-secrets!f:secrets.yml!docker-password
            repositories:
            - armory/ots
            sortTagsByDate: true
```
CloudDriver will start fine.  Then... POST to
`curl -X POST https://localhost:7003/refresh`
to trigger a refresh of properties.  After this, the docker credentials (which get mapped to `/tmp/tmp14699867159249461835.secret` the passwordFile gets replaced with:
`/home/spinnaker/encryptedFile:s3!r:us-west-2!b:bucket-with-secrets!f:secrets.yml!docker-password"`
Causing docker registry auth to start failing.  Can see this by
```
curl localhost:7003/credentials
```
and inspecting the passwordFile entry.

### Additional Details:
Works in the 1.27 release of services.
