### ISSUE TITLE
"Create Server Group" in Kubernetes Only Application shows AWS Dialog instead

### ISSUE THREAD

**Issue by dhinojosa** [spinnaker/spinnaker#6674]
### Issue Summary:
When Creating a Server Group, in the Kubernetes Clusters tab location and when I click on the "Create Server Group" I get the following image. The issue is that this is a pure Kubernetes application (no AWS) and this should show a dialog that allows me to enter. Although AWS is installed as a provider, it is not used in this application.

![image](https://user-images.githubusercontent.com/410757/173477907-a95ae329-6dc1-4c0a-898c-8b252446507b.png)

### Cloud Provider(s):
Kubernetes V2

### Environment:
Running Spinnaker on Kubernetes. This 

### Feature Area:
UI

### Steps to Reproduce:
Enable Kubernetes and AWS, but create an application purely in Kubernetes. The click on "Create a Server Group"

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by spinnakerbot** [comment]
This issue is tagged as 'to-be-closed' and hasn't been updated  in 45 days, so we are closing it. You can always reopen this issue if needed.

**Comment by VayshaYsno** [comment]
Lol, when I click on `+Create server Group`, I'm getting redirected to Deploy Manifest. I do not understand how even to add a namespace to the application. Version 1.33.0.
![image](https://github.com/spinnaker/spinnaker/assets/136835466/7467a239-f10d-4e58-b1ef-b1533e034f60)
![image](https://github.com/spinnaker/spinnaker/assets/136835466/a1ee2eb8-8a83-4aab-a0a1-6b2454c6b8b7)

**Comment by dhinojosa** [comment]
Yeah, that's what this error was about. I don't know which version you have, but upgrading may fix this issue or verify that your application is "aws" did the trick. :)

**Comment by VayshaYsno** [comment]
I'm using Spinnaker Operator for deployment, and here's my versions:
 Spinnaker `v1.33.0`,  k8s `v1.28.3`, halyard `armory/halyard:operator-a6ac1d4`, spinnaker-operator `v1.3.1`
 
 This is On-Prem Kubernetes, and I've set it up like this below:
 Under `~/.hal/deploy/config`
 ```
providers:
 kubernetes:
   enabled: true
```
And `clouddriver-local.yml`
```
     kubernetes:
          accounts: 
          - name: svc_k8s_spin
            context: kubernetes-admin@k8s.cluster
            providerVersion: V2
            kubeconfigContents: encrypted:k8s!n:spinnaker-k8s-admin!k:config
            namespaces: [] 
            permissions:
              READ:
              - group1
              WRITE: 
              - group1
            configureImagePullSecrets: true
            omitNamespaces:
            - kube-system
            - kube-public
            - kube-node-lease
            cacheThreads: 1
            dockerRegistries: []
          # Second account for k8s
          - name: acc-2
            context: kubernetes-admin@k8s.cluster-acc2-sa
            providerVersion: V2
            kubeconfigContents: encrypted:k8s!n:spinnaker-k8s-projects!k:acc2
            namespaces:
            - XXXXXX
            - list
            - of-the
            - namespaces
            - XXXXXX
            permissions:
              READ:
              - "group2"
              - "group3"
              WRITE:
              - "group2"
            configureImagePullSecrets: true
            cacheThreads: 1
            dockerRegistries: []
          primaryAccount: svc_k8s_spin
```

Seems like Spinnaker thinks he's working with something else? Like, If I will apply AWS provider, I should see dialog menu from your example above. Maybe, I should put more info about provider in other config files? 

Spinnaker changing its interface depending on your settings as I see now, so maybe this is the way?
