### ISSUE TITLE
Clouddriver doesn't use sql after updating clouddriver.yml

### ISSUE THREAD

**Issue by c0debreaker** [spinnaker/spinnaker#6680]
### Issue Summary:

I don't see any traffic going to aurora-mysql. I've used tcpdump, netcat but no traffic. I used mysql client to check if it is working. Yes, it is working because I used it to create the clouddriver database. I don't see any sql information in /var/log/clouddriver.log

### Cloud Provider(s):
AWS

### Environment:
BUILD

### Description:
I added this block in clouddriver.yml and ran `systemctl stop clouddriver && systemctl start clouddriver`
```
sql:
  enabled: true
  taskRepository:
    enabled: true
  cache:
    enabled: false
    readBatchSize: 500
    writeBatchSize: 300
  scheduler:
    enabled: false
  connectionPools:
    default:
      default: true
      jdbcUrl: jdbc:mysql://aurora-mysql-on-aws:3306/clouddriver
      user: clouddriver_service
      password: mypassword
  migration:
    user: clouddriver_migrate
    jdbcUrl: jdbc:mysql://aurora-mysql-on-aws:3306/clouddriver

dualTaskRepository:
  enabled: true
  primaryClass: com.netflix.spinnaker.clouddriver.sql.SqlTaskRepository
  previousClass: com.netflix.spinnaker.clouddriver.data.task.jedis.RedisTaskRepository
```
