### ISSUE TITLE
Kustomise engine fails to render CronJob

### ISSUE THREAD

**Issue by ValdasK** [spinnaker/spinnaker#6688]
### Issue Summary:

When using `Bake (Manifest)` to build CronJob with overlay, instead of adding properties to container, they get overwritten. This is not what standalone/kubectl Kustomize does.

### Environment:

Spinnaker 1.26.7, KUSTOMIZE render engine, artifact from execution context.

Local kubectl version:
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.2", GitCommit:"f66044f4361b9f1f96f0053dd46cb7dce5e990a8", GitTreeState:"clean", BuildDate:"2022-06-15T14:22:29Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4

### Description:

Standalone Kustomize output:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronName
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: hello-world
            imagePullPolicy: Always
            name: containerName
  schedule: '* * * * *'

```

Spinnaker baked output:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronName
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - imagePullPolicy: Always
            name: containerName
  schedule: '* * * * *'
```

### Steps to Reproduce:

base/kustomization.yaml:
```
resources:
  - cronjob.yaml
```

base/cronjob.yaml:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronName
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: containerName
            image: hello-world
  schedule: "* * * * *"
```

overlays/dev/kustomisation.yaml:
```
resources:
  - ../../base
patchesStrategicMerge:
    - overwrite.yaml
```

overlays/dev/overwrite.yaml:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronName
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: containerName
            imagePullPolicy: Always
```
