### ISSUE TITLE
Front50 with mysql throws IllegalStateException: 'url' property is required for lazily initializing a Connection

### ISSUE THREAD

**Issue by iOtter** [spinnaker/spinnaker#6696]
### Issue Summary:
I configure front50 to use mysql as external storage. It throws the following error during start up. But I do provide jdbc url in front50-local.yml. Would appreciate some help here. Thanks a lot!
```
│ Caused by: java.lang.IllegalStateException: 'url' property is required for lazily initializing a Connection                                                                                                                                │
│     at org.springframework.jdbc.datasource.SingleConnectionDataSource.initConnection(SingleConnectionDataSource.java:220) ~[spring-jdbc-5.2.9.RELEASE.jar:5.2.9.RELEASE]                                                                   │
│     at org.springframework.jdbc.datasource.SingleConnectionDataSource.getConnection(SingleConnectionDataSource.java:164) ~[spring-jdbc-5.2.9.RELEASE.jar:5.2.9.RELEASE]                                                                    │
│     at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:311) ~[liquibase-core-3.8.7.jar:na]                                                                                                            │
│     at com.netflix.spinnaker.kork.sql.migration.SpringLiquibaseProxy.afterPropertiesSet(SpringLiquibaseProxy.kt:52) ~[kork-sql-7.78.0.jar:7.78.0]                                                                                          │
│     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]                                        │
│     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.2.9.RELEASE.jar:5.2.9.RELEASE]                                           │
│     ... 189 common frames omitted 
```

### Cloud Provider(s):
Alibaba Cloud

### Environment:
Spinnaker running in an Alibaba ACK k8s cluster

### Feature Area:
Front50

### Description:
I followed the doc https://spinnaker.io/docs/setup/productionize/persistence/front50-sql/ to setup Mysql as external storage.
front50 image tag 2.23.3
This is my front50-local.yml:
```
spinnaker:
  s3:
    enabled: false
sql:
  enabled: true
  connectionPools:
    default:
      # additional connection pool parameters are available here,
      # for more detail and to view defaults, see:
      # https://github.com/spinnaker/kork/blob/master/kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
      default: true
      jdbcUrl: jdbc:mysql://xxxxxx.mysql.rds.aliyuncs.com:3306/front50
      user: front50_service
      password: ......
```
      

### Steps to Reproduce:
Follow the doc above and use the above front50-local.yam at /home/spinnaker/.hal/default/profiles
then hal deploy apply

### Additional Details:

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

* An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 
* Before you open an issue, please [check if a similar issue already exists](https://github.com/spinnaker/spinnaker/issues) or has been closed before.
* Make sure you have read through the [Spinnaker FAQ](https://www.spinnaker.io/community/faqs/) and [Halyard FAQ](https://www.spinnaker.io/setup/quickstart/faq/) to provide as much information as possible.

Descriptions:

* Issue Summary: A brief description of what you're seeing.
* Cloud Provider: AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc.
* Environment: As much information about your Spinnaker environment and configuration that might be relevant to the issue. For example: "I am running Spinnaker using the Amazon images to deploy into AWS and GCP."
* Feature Area: Notifications, Pipelines, UI, Jenkins, etc.
* Description: The behavior you expect to see, and the actual behavior.
* Steps to reproduce: Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.
* Additional Details: Additional information such as screenshots and exception logs.

**Comment by mattgogerly** [comment]
Are you able to try using a newer version of Front50? 1.23.3 is nearly 2 years old and is no longer maintained.

**Comment by iOtter** [comment]
Thanks for reply! I am actually using 2.23.3 (pull from us-docker.pkg.dev/spinnaker-community/docker/front50:2.23.3)
I believe it's a recent image right?

**Comment by mattgogerly** [comment]
Ah my bad, got the tagging conventions mixed up. You're right!

Are you able to to exec into the pod and check the profile files look ok on the pod itself?

They should be somewhere under /opt/front50

**Comment by iOtter** [comment]
I found this config: /opt/front50/config/front50.yml. It looks still the default file, is it the problem?

```
server:
  port: 8080

management:
  health:
    redis:
      enabled: ${spinnaker.redis.enabled}

spinnaker:
  redis:
    enabled: false
    host: localhost
    port: 6379

swagger:
  enabled: true
  title: Spinnaker Front50 API
  description:
  contact:
  patterns:
    - /default/.*
    - /credentials.*
    - /global/.*
    - /notifications.*
    - /pipelines.*
    - /strategies.*
    - /v2/.*
```

**Comment by mattgogerly** [comment]
Looks like it's under /opt/spinnaker/config rather than front50, sorry!

If you `cat /opt/spinnaker/config/front50-local.yml` is the URL field definitely there?

**Comment by iOtter** [comment]
Thanks! Found it in front50 pod. It seems correct, everything in front50-local.yml was picked up:

bash-5.0$ cat /opt/spinnaker/config/front50-local.yml
```
spinnaker:
  s3:
    enabled: false
sql:
  enabled: true
  connectionPools:
    default:
      # additional connection pool parameters are available here,
      # for more detail and to view defaults, see:
      # https://github.com/spinnaker/kork/blob/master/kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
      default: true
      jdbcUrl: jdbc:mysql://xxxxxxxxxx.mysql.rds.aliyuncs.com:3306/front50
      user: front50_service
      password: xxxxxxxx
```
