### ISSUE TITLE
Application prefix permissions don't work with Kubernetes account + SAML authentication

### ISSUE THREAD

**Issue by MilanRusev** [spinnaker/spinnaker#6701]
### Issue Summary:
Application prefix permissions don't work with Kubernetes + SAML authentication (not sure if the SAML authentication is relevant)

### Cloud Provider(s):
Kubernetes

### Environment:
Spinnaker is installed on a k8s cluster using this helm chart (using Spinnaker version 1.26.7): https://github.com/OpsMx/spinnaker-helm
The Spinnaker components versions are the following:
```
Spinnaker: 1.26.7
Halyard: 1.41.0
Fiat: 1.16.0
Clouddriver: 8.0.4
Deck: 3.7.2
Front50: 0.27.1
Gate: 1.22.2
Igor: 1.16.0
Orca: 2.20.3
Rosco: 0.25.0
Echo: 2.17.1
```
I've setup Spinnaker to use SAML authentication/authorization with Azure AD groups.

These are the permissions for the default Kubernetes account (taken from `hal config` command):
```yaml
name: default
version: 1.26.7
providers:
  kubernetes:
    enabled: true
    accounts:
    - name: default
      requiredGroupMembership: []
      permissions:
        READ:
        - cd08ef25-6d04-47f6-ae7a-7181f4dcb99c
        - 7007ad00-2eaf-470c-bae2-f85b2a823138
        WRITE:
        - cd08ef25-6d04-47f6-ae7a-7181f4dcb99c
        - 7007ad00-2eaf-470c-bae2-f85b2a823138
      dockerRegistries:
      - accountName: dockerhub
        namespaces: []
      providerVersion: V2
      context: default
      configureImagePullSecrets: true
      serviceAccount: true
      cacheThreads: 1
      namespaces: []
      omitNamespaces:
      - kube-system
      - kube-public
      kinds: []
      omitKinds: []
      customResources: []
      cachingPolicies: []
      rawResourcesEndpointConfig:
        kindExpressions: []
        omitKindExpressions: []
      oAuthScopes: []
      onlySpinnakerManaged: false
```

### Feature Area:
Application permissions using prefixes

### Description:
Hello, I'm new to Spinnaker and I've been trying to get the prefix application permissions work but I am not able to. No applications are shown in the UI although they match the prefix. Below the SAML group `cd08ef25-6d04-47f6-ae7a-7181f4dcb99c` is an admin group, the issue is with users from the `7007ad00-2eaf-470c-bae2-f85b2a823138` group.

Test 1 is my desired setup. Test 2 is a modification of Test 1 with capitalized application name (after looking into the Fiat source code). And Test 3 just shows that if I don't use the prefixes but exact application name, things work (but that isn't what I want)

## Test 1 - using a prefix, application with lower case - doesn't work
This is my desired setup.

The contents of the `fiat-local.yml` file is this:
```yaml
fiat:
  executeFallback: WRITE
  restrictApplicationCreation: true
  admin:
    roles:
    - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
auth:
  permissions:
    provider:
      application: aggregate
    source:
      application:
        front50:
          enabled: true
        prefix:
          enabled: true
          prefixes:
          - prefix: '*'
            permissions:
              WRITE:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
              CREATE:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
              EXECUTE:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
              READ:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
          - prefix: 'myapp*'
            permissions:
              READ:
              - '7007ad00-2eaf-470c-bae2-f85b2a823138'
```

I deployed a test k8s deployment inside the default Kubernetes account (where Spinnaker is installed) with appropriate moniker annotations for `myapplication` application:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnakertest-nginx-deployment-01
  namespace: spinnakertest-ns
  labels:
    app: nginx-01
  annotations:
    moniker.spinnaker.io/application: myapplication
    moniker.spinnaker.io/cluster: mycluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-01
  template:
    metadata:
      labels:
        app: nginx-01
      annotations:
        moniker.spinnaker.io/application: myapplication
        moniker.spinnaker.io/cluster: mycluster
    spec:
      containers:
      - name: nginx-01
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

But the users from the SAML group `7007ad00-2eaf-470c-bae2-f85b2a823138` can't see the app in the Spinnaker UI:
![image](https://user-images.githubusercontent.com/15890495/183103507-d1fff101-9137-46bb-a037-f62a81c349fd.png)

## Test 2 - using a prefix, application with upper case - doesn't work

I went through Fiat's code and found that the prefix check uses a toUpperCase(): https://github.com/spinnaker/fiat/blob/v1.16.0/fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourcePrefixPermissionSource.java#L70
```java
public boolean contains(T resource) {
  if (isFullApplicationName) {
    return prefix.equalsIgnoreCase(resource.getName());
  }

  String prefixWithoutStar = prefix.substring(0, prefix.length() - 1);
  prefixWithoutStar = prefixWithoutStar.toUpperCase();
  return resource.getName().startsWith(prefixWithoutStar);
}
```

So I changed my test k8s deployment so that the application is with capital letters:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnakertest-nginx-deployment-01
  namespace: spinnakertest-ns
  labels:
    app: nginx-01
  annotations:
    moniker.spinnaker.io/application: MYAPPLICATION
    moniker.spinnaker.io/cluster: mycluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-01
  template:
    metadata:
      labels:
        app: nginx-01
      annotations:
        moniker.spinnaker.io/application: MYAPPLICATION
        moniker.spinnaker.io/cluster: mycluster
    spec:
      containers:
      - name: nginx-01
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

This time the users from the SAML group `7007ad00-2eaf-470c-bae2-f85b2a823138` can see the application in the Spinnaker UI, but when I go into the application details, no details/server groups are shown:
![image](https://user-images.githubusercontent.com/15890495/183103728-db10b549-61db-4434-983b-22a699c7928a.png)
![image](https://user-images.githubusercontent.com/15890495/183103852-6c835f55-f436-4dc5-a9d7-7e0a4ec3f020.png)

## Test 3 - using exact application name (not using a prefix), application with lower case - works
This works, but it's not a desired setup - the prefixes aren't used.

When I change the prefix application permissions to contain the whole name without `*`, then everything works fine - I can see the application in the Spinnaker UI, and the details/server groups show fine as well:
`fiat-local.yaml`:
```yaml
fiat:
  executeFallback: WRITE
  restrictApplicationCreation: true
  admin:
    roles:
    - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'         
auth:
  permissions:
    provider:
      application: aggregate
    source:
      application:
        front50:
          enabled: true
        prefix:
          enabled: true
          prefixes:
          - prefix: '*'
            permissions:
              WRITE:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
              CREATE:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
              EXECUTE:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
              READ:
              - 'cd08ef25-6d04-47f6-ae7a-7181f4dcb99c'
          - prefix: 'myapplication'
            permissions:
              READ:
              - '7007ad00-2eaf-470c-bae2-f85b2a823138'
```
Test deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnakertest-nginx-deployment-01
  namespace: spinnakertest-ns
  labels:
    app: nginx-01
  annotations:
    moniker.spinnaker.io/application: myapplication
    moniker.spinnaker.io/cluster: mycluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-01
  template:
    metadata:
      labels:
        app: nginx-01
      annotations:
        moniker.spinnaker.io/application: myapplication
        moniker.spinnaker.io/cluster: mycluster
    spec:
      containers:
      - name: nginx-01
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
Result:
![image](https://user-images.githubusercontent.com/15890495/183104004-d46064d2-46bd-4b47-806c-4a3993b5fd4f.png)
![image](https://user-images.githubusercontent.com/15890495/183104155-845d0c7d-04b7-4bbb-af7d-945b58da308b.png)

That's why I thought there might be a bug with the prefix permissions (possibly when used together with applications in a Kubernetes account + SAML authentication) - maybe the [above code snippet](https://github.com/spinnaker/fiat/blob/v1.16.0/fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourcePrefixPermissionSource.java#L70) in Fiat should be changed so case is ignored when using `String.startsWith()`, instead of having a `toUpperCase()` on just the prefix?

Or maybe I haven't configured the prefix permissions correctly?

I haven't tested it with Spinnaker 1.27.0 (Fiat version 1.28.4), because it doesn't work with the helm chart (for example these issues: https://github.com/spinnaker/spinnaker/issues/6655 , https://github.com/spinnaker/spinnaker/issues/6700 , also there are issues with the readiness probes), but I see Fiat v1.28.4 still has the same toUpperCase() code: https://github.com/spinnaker/fiat/blob/v1.28.4/fiat-roles/src/main/java/com/netflix/spinnaker/fiat/providers/ResourcePrefixPermissionSource.java#L71

### Steps to Reproduce:
Deploy Spinnaker in Kubernetes using the helm chart (https://github.com/OpsMx/spinnaker-helm). And use the above permission settings and test Kubernetes deployments (between the test cases delete the Kubernetes deployment before creating the new one to avoid leftover ReplicaSets with the old moniker application name - this adds additional issues). I'm not sure if SAML authentication/authorization is relevant.
