### ISSUE TITLE
Spinnaker not populating azureTenantId environment variable

### ISSUE THREAD

**Issue by ashleykleynhans** [spinnaker/spinnaker#6715]
### Issue Summary:

Spinnaker not populating azureTenantId environment variable.

### Cloud Provider(s):

N/A (oAuth2 issue).

### Environment:

* Halyard v1.50.
* Ubuntu 22.04 LTS VM.
* Spinnaker v1.28.1.
* Azure oAuth2 Authentication.

### Feature Area:

Halyard/Gate.
Security/Authentication/oAuth 2.0/Azure.

#### Expected Behaviour
When following the [Azue oAuth2 Authenfication Documentation](https://spinnaker.io/docs/setup/other_config/security/authentication/oauth/azure/), the `azureTenantId` environment variable specified in `~/.hal/default/service-settings/gate.yml`, the `azureTenantId` environment variable specified in `~/.hal/default/service-settings/gate.yml` is populated in the Gate service, and the Azure oAuth2 authentication is successful.

#### Actual Behaviour
When following the [Azue oAuth2 Authenfication Documentation](https://spinnaker.io/docs/setup/other_config/security/authentication/oauth/azure/), the `azureTenantId` environment variable specified in `~/.hal/default/service-settings/gate.yml` is not populated in the Gate service, causing the Azure oAuth2 authentication to fail with the following error message:
```
AADSTS900023: Specified tenant identifier '${azuretenantid}' is neither a valid DNS name, nor a valid external domain.
```

### Steps to Reproduce:

1. Configure Azure oAuth2 provider using Halyard:
```
sudo hal config security authn oauth2 edit \
  --client-id "<AZURE-CLIENT-ID>" \
  --client-secret "<AZURE-SECRET>" \
  --scope profile \
  --client-authentication-scheme query \
  --user-info-mapping-username userPrincipalName \
  --user-info-mapping-email email \
  --user-info-mapping-first-name givenName \
  --user-info-mapping-last-name surname \
  --provider azure
  ```
2. Enable Azure oAuth2 provider using Halyard:
```
hal config security authn oauth2 enable
```
3.  Configure the `azureTenantId` variable for Gate:
```
tee -a ~/.hal/default/service-settings/gate.yml >/dev/null <<EOF
env:
  azureTenantId: <AZURE_TENANT_ID>
EOF
```
4. Apply configuration:
```
hal deploy apply
```

### Additional Details:

The following 3 work-arounds are available for this issue:

1. Remove `provider` from the `oauth2` section in `~/.hal/config`.
2. Override the URLs in `~/.hal/default/profiles/gate-local.yml`:
```
tee ~/.hal/default/profiles/gate-local.yml >/dev/null <<EOF
security:
  oauth2:
    client:
      accessTokenUri: https://login.microsoftonline.com/<azureTenantIdhere>/oauth2/token
      userAuthorizationUri: https://login.microsoftonline.com/<azureTenantIdhere>/oauth2/authorize?resource=https://graph.windows.net/
EOF
```
3. Populate the `azureTenantId` in `/etc/default/spinnaker`:
```
echo "azureTenantId=12345678" | tee -a /etc/default/spinnaker
```

(3) feels the cleanest in my personal opinion.
