### ISSUE TITLE
Halyard fails to write config file after updating Halyard version to v1.50

### ISSUE THREAD

**Issue by Akash3221** [spinnaker/spinnaker#6716]
### Issue Summary:
I am trying to follow the given instructions for running halyard
https://spinnaker.io/docs/setup/install/halyard/#install-on-debianubuntu
The Halyard version is 1.50

### Cloud Provider(s):
AWS

### Environment:
Ubuntu

### Description:
When I try to upgrade Halyard to version 1.50 from 1.44, I am facing issue that says "Failure writing your halconfig to path /home/spinnaker/.hal/config"

```
ubuntu@ip-172-31-5-76:~$ hal config provider kubernetes enable
+ Get current deployment
  Success
- Edit the kubernetes provider
  Failure
Validation in Global:
! ERROR Failure writing your halconfig to path
  "/home/spinnaker/.hal/config": /tmp/2194816c-5220-4d9e-b0b6-9ff37af33bd8 ->
  /home/spinnaker/.hal/config

- Failed to enable kubernetes
```

### Steps to Reproduce:
Steps to Reproduce are provided in the given link provided below
https://spinnaker.io/docs/setup/install/providers/kubernetes-v2/aws-eks/

**Comment by ashleykleynhans** [comment]
Were you using a different user for halyard than the `spinnaker` user previously?

You should be able to fix this as follows:

```bash
SPINAKER_USER=$(cat /opt/spinnaker/config/halyard-user)
sudo useradd spinnaker --create-home -c "Spinnaker"
sudo mkdir -p /home/spinnaker/.hal
sudo chown spinnaker:spinnaker  /home/spinnaker/.hal
sudo cp /home/${SPINAKER_USER}/.hal/config /home/spinnaker/.hal/config
hal config provider kubernetes enable
```

**Comment by Akash3221** [comment]
Thanks @ashleykleynhans, it worked for me.

**Comment by Akash3221** [comment]
@ashleykleynhans  This is the error that I am getting after running the command "hal deploy apply".
```

ubuntu@ip-172-31-2-204:~$ hal deploy apply
+ Get current deployment
  Success
+ Prep deployment
  Success
Validation in default.stats:
- INFO Stats are currently ENABLED. Usage statistics are being
  collected. Thank you! These stats inform improvements to the product, and that
  helps the community. To disable, run `hal config stats disable`. To learn more
  about what and how stats data is used, please see
  https://spinnaker.io/docs/community/stay-informed/stats.

Validation in default.security:
- WARNING Your UI or API domain does not have override base URLs
  set even though your Spinnaker deployment is a Distributed deployment on a
  remote cloud provider. As a result, you will need to open SSH tunnels against
  that deployment to access Spinnaker.
? We recommend that you instead configure an authentication
  mechanism (OAuth2, SAML2, or x509) to make it easier to access Spinnaker
  securely, and then register the intended Domain and IP addresses that your
  publicly facing services will be using.

+ Preparation complete... deploying Spinnaker
+ Get current deployment
  Success
- Apply deployment
  Failure
Validation in Global:
! ERROR Failed to backup user file: /home/ubuntu/.kube/config

- Failed to deploy Spinnaker.
```

**Comment by ashleykleynhans** [comment]
@Akash3221 can you paste the contents of your /home/spinnaker/.hal/config file and redact any sensitive or confidential information please?

I will try to assist with this issue, but I am not experienced with using the k8s provider, so you may also want to consider joining the Spinnaker community Slack at spinnakerteam.slack.com if you haven't already done so and ask your question there.

Since you're using k8s, you may want to consider using the [Spinnaker Operator for Kubernetes](https://github.com/armory/spinnaker-operator) instead of Halyard, since its the preferred method of deploying Spinnaker anyway.

**Comment by Akash3221** [comment]
@ashleykleynhans please find the contents of my /home/spinnaker/.hal/config file.

```
currentDeployment: default
deploymentConfigurations:
- name: default
  version: 1.28.1
  providers:
    appengine:
      enabled: false
      accounts: []
    aws:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
      defaultKeyPairTemplate: '{{name}}-keypair'
      defaultRegions:
      - name: us-west-2
      defaults:
        iamRole: BaseIAMRole
    ecs:
      enabled: false
      accounts: []
    azure:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: azure-linux.json
        baseImages: []
    dcos:
      enabled: false
      accounts: []
      clusters: []
    dockerRegistry:
      enabled: false
      accounts: []
    google:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: gce.json
        baseImages: []
        zone: us-central1-f
        network: default
        useInternalIp: false
    huaweicloud:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
    kubernetes:
      enabled: true
      accounts:
      - name: test-spinnaker
        requiredGroupMembership: []
        permissions: {}
        dockerRegistries: []
        providerVersion: V2
        context: management
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: []
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /home/ubuntu/.kube/config
        rawResourcesEndpointConfig:
          kindExpressions: []
          omitKindExpressions: []
        oAuthScopes: []
        onlySpinnakerManaged: false
      primaryAccount: test-spinnaker
    tencentcloud:
      enabled: false
      accounts: []
      bakeryDefaults:
        baseImages: []
    oracle:
      enabled: false
      accounts: []
      bakeryDefaults:
        templateFile: oci.json
        baseImages: []
    cloudfoundry:
      enabled: false
      accounts: []
  deploymentEnvironment:
    size: SMALL
    type: Distributed
    accountName: test-spinnaker
    imageVariant: SLIM
    updateVersions: true
    consul:
      enabled: false
    vault:
      enabled: false
    customSizing: {}
    sidecars: {}
    initContainers: {}
    hostAliases: {}
    affinity: {}
    tolerations: {}
    nodeSelectors: {}
    gitConfig:
      upstreamUser: spinnaker
    livenessProbeConfig:
      enabled: false
    haServices:
      clouddriver:
        enabled: false
        disableClouddriverRoDeck: false
      echo:
        enabled: false
  persistentStorage:
    persistentStoreType: s3
    azs: {}
    gcs:
      rootFolder: front50
      bucketLocation: ''
    redis: {}
    s3:
      bucket: 
      rootFolder: front50
      region: us-east-2
      pathStyleAccess: false
    oracle: {}
  features:
    chaos: false
  metricStores:
    datadog:
      enabled: false
      tags: []
    prometheus:
      enabled: false
      add_source_metalabels: true
    stackdriver:
      enabled: false
    newrelic:
      enabled: false
      tags: []
    period: 30
    enabled: false
  notifications:
    slack:
      enabled: false
    twilio:
      enabled: false
      baseUrl: https://api.twilio.com/
    github-status:
      enabled: false
  timezone: America/Los_Angeles
  ci:
    jenkins:
      enabled: true
      masters:
      - name: my-jenkins-master
        permissions: {}
        address: 
        username: 
        password: 
        csrf: true
    travis:
      enabled: false
      masters: []
    wercker:
      enabled: false
      masters: []
    concourse:
      enabled: false
      masters: []
    gcb:
      enabled: false
      accounts: []
    codebuild:
      enabled: false
      accounts: []
  repository:
    artifactory:
      enabled: false
      searches: []
    nexus:
      enabled: false
      searches: []
  security:
    apiSecurity:
      ssl:
        enabled: false
    uiSecurity:
      ssl:
        enabled: false
    authn:
      oauth2:
        enabled: false
        client: {}
        resource: {}
        userInfoMapping: {}
      saml:
        enabled: false
        userAttributeMapping: {}
      ldap:
        enabled: false
      x509:
        enabled: false
      iap:
        enabled: false
      enabled: false
    authz:
      groupMembership:
        service: EXTERNAL
        google:
          roleProviderType: GOOGLE
        github:
          roleProviderType: GITHUB
        file:
          roleProviderType: FILE
        ldap:
          roleProviderType: LDAP
      enabled: false
  artifacts:
    bitbucket:
      enabled: false
      accounts: []
    gcs:
      enabled: false
      accounts: []
    oracle:
      enabled: false
      accounts: []
    github:
      enabled: false
      accounts: []
    gitlab:
      enabled: false
      accounts: []
    gitrepo:
      enabled: false
      accounts: []
    http:
      enabled: false
      accounts: []
    helm:
      enabled: true
      accounts:
      - name: artifactory-cloud
        repository: 
        username: 
        password: 
    s3:
      enabled: false
      accounts: []
    maven:
      enabled: false
      accounts: []
    templates: []
  pubsub:
    enabled: false
    google:
      enabled: false
      pubsubType: GOOGLE
      subscriptions: []
      publishers: []
  canary:
    enabled: false
    serviceIntegrations:
    - name: google
      enabled: false
      accounts: []
      gcsEnabled: false
      stackdriverEnabled: false
    - name: prometheus
      enabled: false
      accounts: []
    - name: datadog
      enabled: false
      accounts: []
    - name: signalfx
      enabled: false
      accounts: []
    - name: aws
      enabled: false
      accounts: []
      s3Enabled: false
    - name: newrelic
      enabled: false
      accounts: []
    reduxLoggerEnabled: true
    defaultJudge: NetflixACAJudge-v1.0
    stagesEnabled: true
    templatesEnabled: true
    showAllConfigsEnabled: true
  spinnaker:
    extensibility:
      plugins: {}
      repositories: {}
  webhook:
    trust:
      enabled: false
  stats:
    enabled: true
    endpoint: https://stats.spinnaker.io
    instanceId: 
    deploymentMethod: {}
    connectionTimeoutMillis: 3000
    readTimeoutMillis: 5000

```
