### ISSUE TITLE
Spinnaker custom notifications to a slack don't support tagging user groups

### ISSUE THREAD

**Issue by s-gusev** [spinnaker/spinnaker#6718]
### Issue Summary: 
spinnaker notifications to a slack don't support tagging user groups, while they support tagging individual users

### Feature Area: 
Notifications, Custom Notifications, Slack integration

### Description:
When setting up custom notifications via slack, it doesn't transform the user group tag into a valid message, while the individual user tag is transformed correctly 

### Steps to Reproduce:

```
message:
      pipeline.failed:
        text: "cc <@S03LJTXXXEJ>, <@U026C9ZXXXK>"
    type: "slack"
```

where `@S03LJTXXXEJ` is a user group tag, and `@U026C9ZXXXK` is an individual user
