### ISSUE TITLE
Cannot override authn props for GitHub Enterprise

### ISSUE THREAD

**Issue by boonware** [spinnaker/spinnaker#6766]
### Issue Summary:
* Using Halyard to configure the authentication provider `github` does not allow you to override the URLs for GitHub Enterprise. URLs are ignored and attempts to log in will direct you to https://github.com and not your custom GitHub Enterprise server. Manually editing the Halyard config file `~/.hal/config` does not solve the problem.
* This also means that attempts to lock access to a specific GitHub organization using the undocumented feature `--user-info-requirements: organization=someOrg` does not work as this bean is [only activated](https://github.com/spinnaker/gate/blob/master/gate-oauth2/src/main/groovy/com/netflix/spinnaker/gate/security/oauth2/provider/GithubProviderTokenServices.groovy#L33) when provider type is `github`, meaning this feature is not available to GitHub Enterprise users. In order to provide the overrides for GitHub Enterprise, users must select `other` as the auth provider type.

### Cloud Provider(s):
* Kubernetes

### Environment:
* Spinnaker version 1.29.0

### Feature Area:
Authentication

### Steps to Reproduce:
1. Configure auth as below.
```
hal config security authn oauth2 edit \
            --client-id ${GITHUB_OAUTH_CLIENT_ID} \
            --client-secret ${GITHUB_OAUTH_CLIENT_SECRET} \
            --provider github \
            --access-token-uri https://github.acme.com/login/oauth/access_token \
            --user-authorization-uri https://github.acme.com/login/oauth/authorize \
            --user-info-uri https://github.acme.com/api/v3/user \
            --user-info-mapping-email email \
            --scope read:org,user:email \
            --user-info-requirements organization=${GITHUB_ORG_NAME}
```
2. Activate and deploy configuration.
3. Attempt to log in. You will be directed to public GitHub.

**Comment by jasonmcintosh** [comment]
Halyard is not quite active.  And many of these settings FYI can be done via "profiles" vs. "halyard".  Halyard translates halyard config into "profiles".  SO by setting DIRECTLY in profiles you may be able to work around these.  Examples:
~/.hal/default/profiles/gate.yml
```yaml
security:
  oauth2:
    provider-requirements:
      type: github  
    resource:
      userInfoUri: REPLACEME
    client:
      accessTokenUri: REPLACEME
      clientId: REPLACEME
      clientSecret: REPLACEME
      scope: REPLACEME
      userAuthorizationUri: REPLACEME
```
