### ISSUE TITLE
Support Namespace selector for halyard kubernetes custom-service-settings

### ISSUE THREAD

**Issue by psimms-r7** [spinnaker/spinnaker#6773]
### Issue Summary:
Allow support for Namespace selector as part of the halyard kubernetes custom-service-settings

topologySpreadConstraints details
https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#namespace-selector

halyard kubernetes custom-service-settings
https://spinnaker.io/docs/reference/halyard/custom/#kubernetes

### Additional Details:

```
  deploymentEnvironment:
    size: SMALL         
    type: Distributed   
    accountName: default
    imageVariant: SLIM  
    updateVersions: true
    consul:            
      enabled: false   
    vault:             
      enabled: false                            
    location: spintest3
    customSizing: {}   
    sidecars: {}        
    initContainers: {}                                   
    hostAliases: {}  
    affinity:
      spin-clouddriver:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - clouddriver
              topologyKey: kubernetes.io/hostname
              namespaceSelector:
                matchLabels:
                  app: spinnaker
```

```
bash-5.0$ hal deploy apply
- Get current deployment
  Failure
Validation in Global:
! ERROR Could not translate your halconfig: Unrecognized field
  "namespaceSelector" (class
  com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig$PodAffinityTerm),
  not marked as ignorable (3 known properties: "namespaces", "labelSelector",
  "topologyKey"])
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain:
  com.netflix.spinnaker.halyard.config.model.v1.node.Halconfig["deploymentConfigurations"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentConfiguration["deploymentEnvironment"]->com.netflix.spinnaker.halyard.config.model.v1.node.DeploymentEnvironment["affinity"]->java.util.LinkedHashMap["spin-clouddriver"]->com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig["podAntiAffinity"]->com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig$PodAffinity["requiredDuringSchedulingIgnoredDuringExecution"]->java.util.ArrayList[0]->com.netflix.spinnaker.halyard.config.model.v1.node.AffinityConfig$PodAffinityTerm["namespaceSelector"])

- I have just picked up a fault in the AE-35 unit.
- Failed to get deployment name.
```

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

* An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 
* Before you open an issue, please [check if a similar issue already exists](https://github.com/spinnaker/spinnaker/issues) or has been closed before.
* Make sure you have read through the [Spinnaker FAQ](https://www.spinnaker.io/community/faqs/) and [Halyard FAQ](https://www.spinnaker.io/setup/quickstart/faq/) to provide as much information as possible.

Descriptions:

* Issue Summary: A brief description of what you're seeing.
* Cloud Provider: AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc.
* Environment: As much information about your Spinnaker environment and configuration that might be relevant to the issue. For example: "I am running Spinnaker using the Amazon images to deploy into AWS and GCP."
* Feature Area: Notifications, Pipelines, UI, Jenkins, etc.
* Description: The behavior you expect to see, and the actual behavior.
* Steps to reproduce: Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.
* Additional Details: Additional information such as screenshots and exception logs.
