### ISSUE TITLE
Echo Spring Cloud Config Server support not working - possibly missing dependencies

### ISSUE THREAD

**Issue by samirtahir91** [spinnaker/spinnaker#6780]
### Issue Summary:
I have configured spring.cloud.config.server in spinnakerconfig.yml
This is picked up by Igor and Clouddriver services fine on startup, I can see the correct log messsages, i.e. for Igor
`Located property source: [BootstrapPropertySource {name='bootstrapProperties-vault:igor'}`

But same config for Echo is ignored.

I can see support was added for Spring Cloud Config Server in Echo here - https://github.com/spinnaker/echo/pull/636/files

I can also see that dependencies were added as a fix for Igor here - https://github.com/spinnaker/igor/pull/865/files

I think dependencies are missing for Echo service, as I can't see the Spring Cloud Config JAR in the pod in `/opt/echo/lib` or in https://github.com/spinnaker/echo/blob/master/echo-web/echo-web.gradle

Please can you add the dependencies for Echo service if so?

Thanks

### Cloud Provider:
GCP

### Environment:
Deployed via halyard, migrated config to external Vault for Igor and Echo

### Feature Area:
Echo
Trigggers
Pub Sub
External Configuration

### Steps to Reproduce:

spinnakerconfig.yml:
```
spring:
  profiles:
    include: vault
  cloud:
    config:
      server:
        vault:
          host: <ommitted>
          port: <ommitted>
          scheme: https
          skipSslValidation: true
          backend: <ommitted>
          kvVersion: 2
          token: <ommitted>
          namespace: <ommitted>
```

echo-local.yml:
```
spring:
  cloud:
    config:
      server:
        vault:
          defaultKey: echo
```

igor.yml:
```
spring:
  cloud:
    config:
      server:
        vault:
          defaultKey: igor
```

### Additional Details:
No logs indicated spring cloud config is being picked up for Echo 

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

* An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 
* Before you open an issue, please [check if a similar issue already exists](https://github.com/spinnaker/spinnaker/issues) or has been closed before.
* Make sure you have read through the [Spinnaker FAQ](https://www.spinnaker.io/community/faqs/) and [Halyard FAQ](https://www.spinnaker.io/setup/quickstart/faq/) to provide as much information as possible.

Descriptions:

* Issue Summary: A brief description of what you're seeing.
* Cloud Provider: AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc.
* Environment: As much information about your Spinnaker environment and configuration that might be relevant to the issue. For example: "I am running Spinnaker using the Amazon images to deploy into AWS and GCP."
* Feature Area: Notifications, Pipelines, UI, Jenkins, etc.
* Description: The behavior you expect to see, and the actual behavior.
* Steps to reproduce: Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.
* Additional Details: Additional information such as screenshots and exception logs.
