### ISSUE TITLE
K8s provider v1beta1 API PodSecurityPolicy removed in K8s version 1.25 above

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [spinnaker/spinnaker#6880]
### Issue Summary:
K8s provider v1beta1 PodSecurityPolicy API removed 

### Cloud Provider(s):
GCP

### Environment:
Prod

### Description:
K8s has deprecated [PodSecurityPolicy](https://kubernetes.io/docs/concepts/security/pod-security-policy/) in verions 1.21 and removed that in 1.25.

We are facing issue when trying to automatically upgrade our GKE cluster to 1.25, because our Spinnaker service deployed in GKE is somehow still making API call to `policy/v1beta1/podsecuritypolicies`. Further narrowing down from GCP log shows that the call are initiated from [Spinnaker K8s service account](https://docs.armory.io/continuous-deployment/armory-admin/manual-service-account/#create-the-kubernetes-service-account) using kubectl agent. The call is being made more than once per minute. So we suspect it is Clouddriver trying to list PodSecurityPolicy from behind the scene

We tried to add `PodSecurityPolicy` to `omitKinds` specified in the [provider documentation](https://docs.armory.io/continuous-deployment/installation/armory-operator/op-manifest-reference/providers/#account-parameters-8) but no luck

It might be related to K8s module in clouddriver is actually using V1Beta1CustomerResourceDefintiona module instead of V1. See [link](https://github.com/spinnaker/clouddriver/blob/50d9f54fefd7c65c6a877ac54822b17c2cce4488/clouddriver-kubernetes/src/main/java/com/netflix/spinnaker/clouddriver/kubernetes/description/manifest/KubernetesKind.java#L25C4-L25C4)

**Comment by dbyron-sf** [comment]
Hmmm...I'd expect using omitKinds to work.  Can you share the k8s account config?

**Comment by CharmanderJieniJieni** [comment]
@dbyron-sf please see below, I basically put all potential combination but no luck

```yaml
- name: gke-foo
        requiredGroupMembership: []
        permissions: {}
        dockerRegistries: []
        providerVersion: V2
        context: gke_foo_us-central1_gke_foo
        configureImagePullSecrets: true
        cacheThreads: 1
        namespaces: []
        omitNamespaces: []
        kinds: []
        omitKinds: ["PodSecurityPolicy", "podSecurityPolicy", "POD_SECURITY_POLICY"]
        customResources: []
        cachingPolicies: []
        kubeconfigFile: /opt/spinnaker/credentials/kube-config
        rawResourcesEndpointConfig:
          kindExpressions: []
          omitKindExpressions: []
        oAuthScopes: []
        onlySpinnakerManaged: false
```
