### ISSUE TITLE
get dependencies redis docker image tag

### ISSUE THREAD

**Issue by willzhang** [spinnaker/spinnaker#6903]
### Issue Summary:

How can i get dependencies redis docker image tag?

### Cloud Provider(s):

kubernetes

### Environment:

halyard v1.62.2
spinnaker v1.32.2

### Feature Area:

halyard

### Description:

How can i get dependencies redis docker image tag?

The bom file `dependencies.redis.version` not redis image tag.
```
root@ubuntu:~# cat /home/spinnaker/.hal/.boms/bom/1.32.2.yml 
artifactSources:
  debianRepository: https://us-apt.pkg.dev/projects/spinnaker-community
  dockerRegistry: registry.cn-shenzhen.aliyuncs.com/cnmirror
  gitPrefix: https://github.com/spinnaker
  googleImageProject: marketplace-spinnaker-release
dependencies:
  consul:
    version: 0.7.5
  redis:
    version: 2:2.8.4-2
  vault:
    version: 0.7.0
services:
  clouddriver:
    commit: 98204860175e00f8b1e01b43f8fa06670cc4cd2e
    version: local:5.82.0
  deck:
    commit: 4bc0ae68f578f94fb5473a90d2db18d4c580944a
    version: local:3.15.1
  echo:
    commit: c24b570673fc0f441a65fb69f6936027905c686d
    version: local:2.39.0
  fiat:
    commit: 37a686b46d1bfe5569fff487151d6b8e84295169
    version: local:1.42.0
  front50:
    commit: f8d4d344e3858d9c3d45534d34a10e51181ece8e
    version: local:2.30.1
  gate:
    commit: 431b73f62d5d2caec4619e64ca7084c0d61f7b9e
    version: local:6.60.1
  igor:
    commit: 95c19bd7f49d5fd831104c8a0a92195a6eded154
    version: local:4.13.3
  kayenta:
    commit: 137036d870f9f4834eccd60d7895b212a42b9080
    version: local:2.38.0
  monitoring-daemon:
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
    version: local:1.4.0
  monitoring-third-party:
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
    version: local:1.4.0
  orca:
    commit: cb269b64cf2883317cd169cc7d82b75093ad6754
    version: local:8.36.0
  rosco:
    commit: a035e26d7fadeb258cb3c4206e386203c6ab1ac3
    version: local:1.18.0
timestamp: '2023-09-20 20:55:47'
version: 1.32.2
```
spinnaker use redis:6.2 image tag ,but i want know how can i get this image tag for offline install.
```
root@node40:~# kubectl -n spinnaker get deploy spin-redis  -o yaml |grep image:
        image: docker.io/library/redis:6.2
```

Is this is the only way find it in halyard code

![image](https://github.com/spinnaker/spinnaker/assets/33590311/1ebde9b6-e7f0-4383-9416-082a9abf6362)

if i can get it in dependencies will better.

```
dependencies:
  consul:
    version: 0.7.5
  redis:
    version: 2:2.8.4-2
    image_tag: 6.2
  vault:
    version: 0.7.0
```

### Additional Details:

Here have one issue for how to change redis docker image registry, and the latest redis image tag have been change: https://github.com/spinnaker/spinnaker/issues/3967
