### ISSUE TITLE
Orca: AWS Lambda Documentation / Installation instructions are incorrect

### ISSUE THREAD

**Issue by snorlaX-sleeps** [spinnaker/spinnaker#6938]
### Issue Summary:
The configuration instructions for the AWS Lambda plugin are incorrect for Spinnaker v1.33.0

### Cloud Provider(s):
AWS Lambda

### Environment:
Spinnaker: v1.33
Halyard: 1.63.0

AWS Lambda Plugin: 1.2.0

Kubernetes: v1.29
Deployed in AWS EKS using Helm

### Feature Area:
Orca and the Lambda plugin

### Description:
This PR moved the Orca section of the AWS Lambda plugin into Orca itself: https://github.com/spinnaker/orca/pull/4449
However the [documentation](https://github.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/blob/master/README.md#plugin-deployment-guide) for the Orca configuration of this still lists that the plugin repository should be set, which is no longer true.
The official [documentation](https://spinnaker.io/docs/setup/install/providers/aws/) also lists this information.

Specifically the documentation / instructions should be changed to the following as of Spinnaker v1.33:
```
  spinnaker:
    extensibility:
      plugins:
        Aws.LambdaDeploymentPlugin:
          enabled: true
          version: <<VERSION_NUMBER>> 
          extensions:
            Aws.LambdaDeploymentStage:
              enabled: true
```

The gate configuration seems to still need to reference the plugin.

### Steps to Reproduce:
Upgrade to Spinnaker v1.33 from a previous version with the AWS lambda plugin already installed / configured.
Orca will fail as it cannot startup due to a missing `LambdaCloudDriverUtils` Spring Bean.
