### ISSUE TITLE
LDAP integration not working with Windows 11 AD LDS

### ISSUE THREAD

**Issue by SledgeHammer01** [spinnaker/spinnaker#6966]
### Issue Summary:
Windows 11 Pro x64
Active Directory Lightweight Directory Services
version: 1.34.3

Upon trying to sign in to the UI, I get the following error:

`[LDAP: error code 32 - 0000208D: NameErr: DSID-03100223, problem 2001 (NO_OBJECT), data 0, best match of: '' ]; nested exception is javax.naming.NameNotFoundException: [LDAP: error code 32 - 0000208D: NameErr: DSID-03100223, problem 2001 (NO_OBJECT), data 0, best match of: '' ]; remaining name '/'
`

### Cloud Provider(s):
Docker Kubernetes

### Additional Details:

I'm using Active Directory Lightweight Directory Services for a local POC. Should that be supported?

```
DC=xxxsoftware.com,DC=com
  CN=Service Accounts
    CN=spinnaker-svc
  CN=Users
    CN=myuser
```
config file:

      ldap:
        enabled: true
        url: ldap://host.docker.internal:389
        userSearchFilter: (&(objectClass=user)(userPrincipalName={0}))
        managerDn: CN=spinnaker-svc,CN=Service Accounts,DC=xxxsoftware,DC=com
        managerPassword: xxx

gate-local:

```
ldap:
  enabled: true
  url: ldap://host.docker.internal:389
  userSearchFilter: (&(objectClass=user)(userPrincipalName={0}))
  managerDn: CN=spinnaker-svc,CN=Service Accounts,DC=xxxsoftware,DC=com
  managerPassword: xxx

```

AD LDS seems to use `userPrincipalName` instead of `sAMAccountName`.

Using ADSI Edit, I am able to connect to LDAP with `spinnaker-svc@xxxsoftware.com` and the password (using `simple bind authentication` if that makes a difference vs real AD), but the above managerDn is copy & pasted from ADSI Edit's dn for the user.
