### ISSUE TITLE
Google Container Registry -> Artifact Registry

### ISSUE THREAD

**Issue by lmanowski-esky** [spinnaker/spinnaker#7006]
As you probably already know, [Google has decided to phase out GCR in favour of Docker Artifact Registry](https://cloud.google.com/container-registry/docs/pushing-and-pulling#pushing_to_the_registry)

Google provided an automatic migration tool to transition Container Registry repositories to gcr.io repositories hosted on Artifact Registry. After the migration is complete, all traffic to *gcr.io is redirected to Artifact Registry.

![Image](https://github.com/user-attachments/assets/d9a57bec-5261-42c7-890b-ff57708cdb99)

While the GCR API is enabled, all images and tags in the repository remain visible in Spinnaker. However, disabling the GCR API causes Clouddriver to stop recognizing the migrated repositores. 
This issue appears only in Spinnaker, as Docker can still pull images without any problems. It seems like Spinnaker has some hardcoded reference to the Google Container Registry API, which causes the issue described above.

When the path europe-docker.pkg.dev is used, and a new user is added, the images become visible. Unfortunately, this forces a transition to new image paths.. To avoid this, we’d like the option to keep using the old paths with Artifact registry in Spinnaker.

spinnaker version: 1.28.1
hal: 1.51.0

It works after migrating to Artifact Registry, but only if `containerregistry.googleapis.com` is *enabled*:
```yaml
       dockerRegistry:
            enabled: true
            accounts:
                - name: gcr-account
                  requiredGroupMembership: []
                  permissions: {}
                  address: https://eu.gcr.io
                  username: _json_key
                  email: fake.email@spinnaker.io
                  cacheIntervalSeconds: 60
                  clientTimeoutMillis: 60000
                  cacheThreads: 1
                  paginateSize: 100
                  sortTagsByDate: true
                  trackDigests: false
                  insecureRegistry: false
                  repositories: []
                  passwordFile: <passwordFile>
```

Access to eu.gcr.io should work even after disabling the GCR API.
