### ISSUE TITLE
Clouddriver: Intermitent DockerRegistryImageCachingAgent Could not load tags for private ECR

### ISSUE THREAD

**Issue by joariasl** [spinnaker/spinnaker#7015]
The latest version of clouddriver coudl't load the ECR image tags and returns the error

```
WARN 1 --- [ecutionAction-3] .d.r.p.a.DockerRegistryImageCachingAgent : Could not load tags for <IMAGE_NAME> in https://<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com, reason: Status: 404, Method: GET, URL: https://<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/v2/<REPOSITORY>/tags/list%3Flast=..., Message: Not Found
```

I'm using the Docker Registry command configuration (ignore `<>` format values)

```yaml
...
dockerRegistry:
      enabled: true
      accounts:
      - name: <name>
        requiredGroupMembership: []
        permissions: {}
        address: https://<AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com
        username: AWS
        passwordCommand: aws --region us-east-1 ecr get-authorization-token --output
          text --query 'authorizationData[].authorizationToken' | base64 -d | sed
          's/^AWS://'
        email: <FAKE_EMAIL>
        cacheIntervalSeconds: 30
        clientTimeoutMillis: 60000
        cacheThreads: 2
        paginateSize: 1000
        sortTagsByDate: false
        trackDigests: false
        insecureRegistry: false
        repositories: []
      primaryAccount: <name>
```

cacheThreads is not relevant, I've tried with 1.

The `AmazonEC2ContainerRegistryReadOnly` policy attachment is working properly. All the registry repositories are configured equals, all of those are private and all of those contain tags.

I've tried start with a cleaned Redis to avoid the serialization problems.

Spinnaker Version: `1.37.3`
