### ISSUE TITLE
Hal BOM for 2025.0.1 hasn't been updated

### ISSUE THREAD

**Issue by anindyameister** [spinnaker/spinnaker#7076]
The service versions in the halconfig BOM for release 2025.0.1 haven't been updated in the public gcs bucket. 

```
$ kubectl exec -n spinnaker spinnaker-operator-66c6f5d5d4-gn47v -c halyard -- hal version bom 2025.0.1
+ Get BOM for 2025.0.1
  Success
version: 2025.0.1
timestamp: '2025-05-12T20:16:15.929+00:00'
services:
  echo:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  clouddriver:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  deck:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  fiat:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  front50:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  gate:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  igor:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  kayenta:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  orca:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  rosco:
    version: 2025.0.0
    commit: 5b14f932d4569e5871d9f6076104fe1031bcc81b
  defaultArtifact: {}
  monitoring-third-party:
    version: 1.4.0
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
  monitoring-daemon:
    version: 1.4.0
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
dependencies:
  redis:
    version: 2:2.8.4-2
  consul:
    version: 0.7.5
  vault:
    version: 0.7.0
artifactSources:
  debianRepository: https://us-apt.pkg.dev/projects/spinnaker-community
  dockerRegistry: us-docker.pkg.dev/spinnaker-community/docker
  googleImageProject: marketplace-spinnaker-release
  gitPrefix: https://github.com/spinnaker
```

**Comment by dbyron-sf** [comment]
Yes, I agree something doesn't look right with [versions.yml](https://console.cloud.google.com/storage/browser/_details/halconfig/versions.yml;tab=live_object?inv=1&invt=AbxnaA&project=spinnaker-community).  Before I released 2025.0.2, it contained:
```
illegalVersions:
  - reason: Broken apache config makes the UI unreachable
    version: 1.2.0
  - reason: UI does not load
    version: 1.4.0
latestHalyard: 1.70.0
latestSpinnaker: 2025.0.0
versions:
  - alias: v2025.0.0
    changelog: https://spinnaker.io/changelogs/2025.0.0-changelog/
    lastUpdate: 1745029707739
    minimumHalyardVersion: 2025.0.0
    version: 2025.0.0
  - alias: v1.38.0
    changelog: https://spinnaker.io/changelogs/1.38.0-changelog/
    lastUpdate: 1745007939913
    minimumHalyardVersion: "1.45"
    version: 1.38.0
  - alias: v1.37.11
    changelog: https://spinnaker.io/changelogs/1.37.11-changelog/
    lastUpdate: 1747079159834
    minimumHalyardVersion: "1.45"
    version: 1.37.11
  - alias: v2025.0.1
    changelog: https://spinnaker.io/changelogs/2025.0.1-changelog/
    lastUpdate: 1747080976365
    minimumHalyardVersion: 2025.0.1
    version: 2025.0.1
```
It looks like `latestSpinnaker` didn't get updated.  @jcavanagh can you take a look?

**Comment by dbyron-sf** [comment]
Let's see what happens when we release something after https://github.com/spinnaker/spinnaker/pull/7080 is in.

**Comment by dbyron-sf** [comment]
Looks like we also needed https://github.com/spinnaker/spinnaker/pull/7081 / https://github.com/spinnaker/spinnaker/pull/7083.  We regenerated the [2025.0.1 bom](https://console.cloud.google.com/storage/browser/_details/halconfig/bom/2025.0.1.yml;tab=live_object?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22,%22s%22:%5B(%22i%22:%22objectListDisplayFields%2FtimeCreated%22,%22s%22:%221%22),(%22i%22:%22displayName%22,%22s%22:%220%22)%5D))&inv=1&invt=Abx-ow&project=spinnaker-community) and now it contains:
```
artifactSources:
  debianRepository: https://us-apt.pkg.dev/projects/spinnaker-community
  dockerRegistry: us-docker.pkg.dev/spinnaker-community/docker
  gitPrefix: https://github.com/spinnaker
  googleImageProject: marketplace-spinnaker-release
dependencies:
  consul:
    version: 0.7.5
  redis:
    version: 2:2.8.4-2
  vault:
    version: 0.7.0
services:
  clouddriver:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  deck:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  echo:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  fiat:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  front50:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  gate:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  igor:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  kayenta:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  monitoring-daemon:
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
    version: 1.4.0
  monitoring-third-party:
    commit: 96d510cb22f65dcf788324ed8b68447c31de255a
    version: 1.4.0
  orca:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
  rosco:
    commit: 4f9ba539cd7aef1bfdee8922fc40aace3791fddd
    version: 2025.0.1
timestamp: 2025-05-21T08:17:33.834Z
version: 2025.0.1
```
We regenerated the [2025.0.2 bom](https://console.cloud.google.com/storage/browser/_details/halconfig/bom/2025.0.2.yml;tab=live_object?inv=1&invt=Abx-ow&project=spinnaker-community) as well.

Please take a look @anindyameister.
