### ISSUE TITLE
Multi-region AMI bake support

### ISSUE THREAD

**Issue by ervansetiawan** [spinnaker/spinnaker#825]
Cloud Provider : Amazon AWS

We have a Spinnaker instance running in us-west-1 region and would like to bake an AMI in another region, e.g. us-west-2. Currently, this is not possible. 

Rosco fails because Packer tries to launch a temporary instance in a non-existent VPC in us-west-2. It uses the VPC ID of the Spinnaker instance in the other region (us-west-1).

**Comment by lwander** [comment]
@duftler

**Comment by duftler** [comment]
@kalymero and @gardleopard have offered to share the solution they have working locally for this. They are going to put up a PR on rosco, and then we'll work together to make the companion changes to orca.

**Comment by medyagh** [comment]
any idea if this bug been fixed in the latest version ?

**Comment by moondev** [comment]
Does rosco support custom store types? If so we could create ebs-west.json ebs-east.json with the region specific vpc/subnet ids to do multi region baking. The pipeline would then have bake-east and bake-west stages that run in parallel.

**Comment by moondev** [comment]
Here is a workaround for anyone interested:

This shell script is at /usr/local/bin/packer
```
#!/bin/sh

REGION=$4
IFS='=' read -ra REG <<< "$REGION"
ARGS="$@"
NEWCONFIG="aws-ebs-${REG[1]}.json"
echo $NEWCONFIG
OLDCMD="packer $ARGS"
#real packer is in /opt
NEWCMD="/opt/${OLDCMD/aws-ebs.json/$NEWCONFIG}"
eval $NEWCMD
```

 
The real packer binary is at /opt/packer

The script looks for region in the params and then adds that to the end of aws-ebs.json and calls it with the real packer /opt/packer

So Rosco goes:
```
packer build -color=false -var aws_region=us-west-2 -var aws_ssh_username=ubuntu -var aws_instance_type=t2.micro -var aws_source_ami=ami-d732f0b7 -var aws_target_ami=nginx-all-20160721161956-ubuntu -var aws_associate_public_ip_address=true -var package_type=deb -var packages=nginx -var configDir=/opt/rosco/config/packer /opt/rosco/config/packer/aws-ebs.json
```
Fake packer intercepts it because it is on the PATH and then calls:
```
/opt/packer build -color=false -var aws_region=us-west-2 -var aws_ssh_username=ubuntu -var aws_instance_type=t2.micro -var aws_source_ami=ami-d732f0b7 -var aws_target_ami=nginx-all-20160721161956-ubuntu -var aws_associate_public_ip_address=true -var package_type=deb -var packages=nginx -var configDir=/opt/rosco/config/packer /opt/rosco/config/packer/aws-ebs-west-2.json
```
aws-ebs-west-2.json and aws-ebs-east-1.json have their specific vpc and subnet info.

**Comment by duftler** [comment]
Between the above workaround, the `copy_to` behavior added [here](https://github.com/spinnaker/rosco/pull/126) and the `var_file_name` support added [here](https://github.com/spinnaker/rosco/pull/131), calling this done.

**Comment by mmlac** [comment]
I don't think this issue is really solved. The [templateFile setting](https://github.com/spinnaker/rosco/commit/739d4f5c758815e9635b5162a5444e04fc0fe166) is probably the closest thing to a proper built-in fix for this use-case.

I'd argue it's not the template's job to specify the VPC / subnet, as they are variables that have nothing to do with the actual build process, so I suggest they are treated like i.e. the sshUserName.
Most templates will all look the same except with the VPC and subnet fields changed, and that defeats the purpose of having a template.

I think adding a vpc_id and subnet_id to the virtualizationSettings is much cleaner and should be simpler to support in the UI as well. If there is no setting for the region&type, it should not allow to save. If there is no setting for VPC and subnet even though spinnaker is running in a vpc in a different region, it should reject / warn in the UI.

Also building in a different subnet than where Spinnaker is running should not be such an uncommon scenario. Our Spinnaker i.e. runs in a private subnet w/o NAT and we might want to bake on an instance with access to the internet.


```
virtualizationSettings:
- region: us-east-1                      <<<---- We are on us-east-1, using current vpc/subnet,
        virtualizationType: hvm                      no additional config necessary.
        instanceType: t2.micro                       
        sourceAmi: ami-d4aed0bc                 
        sshUserName: ubuntu                      

- region: us-west-1                      <<<---- Not our vpc/subnet, need to specify one
        virtualizationType: hvm
        instanceType: t2.micro
        sourceAmi: ami-d4aed0bc
        sshUserName: ubuntu

        vpcId: 2nt3s423                 <-- pass to packer instead of using ENV variables of current VPC
        subnetId: 12345c5
       
```


A suggested UI would be:

Step: Bake

Regions: [X] us-east-1 [X] us-west-1  [[Select all]]    Bake process:  (*) parallel  ( ) copy_to
(copy to will highlight the baking region)

BaseOS: (*) ubuntu ...

Multiple accounts might need an even more elaborate solution, but it should be able to be designed in the same way, i.e.  define baseImages for each account or add a awsAccount setting.

Thoughts?
