### ISSUE TITLE
Using existing server groups as template in deploy stage is incomplete

### ISSUE THREAD

**Issue by leelasharma** [spinnaker/spinnaker#978]
When using an existing server group (that use docker images) as a a template in a different pipeline's deploy stage, the container definitions aren't being propagated. Volume sources, load balancers, settings, etc seem to be copied correctly.

I am running Spinnaker on kubernetes using docker images from quay to deploy to other kubernetes clusters.

Steps to Reproduce:
Create Pipleine A -> Add a docker image trigger -> Add Deploy stage -> Create a server group A with a docker container
Create Pipleine B -> Add deploy stage -> Add server group and copy configuration from server group A
This server group seems to be now missing the container configuration details.

**Comment by lwander** [comment]
Can you post a minimal version of your clouddriver-local.yml? Specifically the dockerRegistry and kubernetes account sections, since I'm having trouble reproducing this with my simple setup.

**Comment by leelasharma** [comment]
The cloud-driver.yml looks a bit like:
```
kubernetes:
  enabled: true
  accounts:
    - name: kubernetes-account-1
      namespaces:
        - default
      cluster: gke_test_europe-west1-d_test-cluster
      user: gke_test_europe-west1-d_test-cluster
      dockerRegistries:
        - accountName: docker-account-1
    - name: kubernetes-account-2
      namespaces:
        - default
        - namespace1
        - namespace2
        - namespace3
        - namespace4
      cluster: gke_prod_europe-west1-d_test-cluster
      user: gke_prod_europe-west1-d_test-cluster
      dockerRegistries:
        - accountName: docker-account-1
    - name: kubernetes-account-3
      namespaces:
        - namespace1
        - namespace2
        - namespace3
      cluster: gke_test_europe-west1-c_test-cluster
      user: gke_test_europe-west1-c_test-cluster
      dockerRegistries:
        - accountName: docker-account-2

dockerRegistry:
  enabled: true
  accounts:
    - name: docker-account-1
      address: https://docker-repo.test.com
      username: test
      password: test123
      email: test@test.com
      repositories:
        - repository-1
        - repository-2
        - repository-3
    - name: docker-account-2
      address: https://eu.gcr.io
      username: _json_key
      passwordFile: /docker-registry/registry-key.json
      email: spinnaker-test@test.com
      repositories:
        - test/repository-1
```
