### ISSUE TITLE
Use X-Forwarded headers by default

### ISSUE THREAD

**Issue by chongkong** [spinnaker/spinnaker#997]
Continued from [this](https://github.com/spinnaker/spinnaker/issues/996) issue, I had to setup several options to integrate SAML.

Original request looks like:

```
https://my.spinnaker.com/gate/auth/redirect?to=...
```

but when it arrives to application through proxy, it looks like :

```
http://localhost:8084/auth/redirect?to=...
```

It becomes problem because SAML handler uses the same request to resend after authentication is succceed. So we have to use `X-Forwarded-For` and `X-Forwarded-To` headers, and preserve its hostname (`my.spinnaker.com`)

I've added this to `/opt/spinnaker/config/spinnaker-local.yml`

``` yaml
server:
  tomcat:
    remoteIpHeader: X-Forwarded-For
    protocolHeader: X-Forwarded-Proto

// for latest tomcat version
server:
  tomcat:
    useForwardHeaders: true
```

and `ProxyPreserveHost` option to `/etc/apache2/sites-available/spinnaker.conf`

``` apache
<VirtualHost *:9000>
  DocumentRoot /opt/deck/html
  ProxyPreserveHost On

  ProxyPass "/gate" "http://localhost:8084" retry=0
  ProxyPassReverse "/gate" "http://localhost:8084"

  ProxyPass "/rosco" "http://localhost:8087" retry=0
  ProxyPassReverse "/rosco" "http://localhost:8087"

  ProxyPass "/auth/redirect" "http://localhost:8084/auth/redirect" retry=0

  <Directory "/opt/deck/html/">
    Require all granted
  </Directory>
</VirtualHost>
```

and I think these two options might be set by default. I think this is common case, but no document explains this, which took me 2 days to find a solution.
